[Search] Move breadcrumbs to React component
department-of-veterans-affairs/vets-website pull request #10003
Opened 2019-04-29 14:42 UTC by ncksllvn

Remove the `includeBreadcrumbs: true` line from `search.md` of `vagov-content` so that there aren't duplicate breadcrumbs. 

For faster startup and reloads, start locally using `npm run watch -- --entry=search,static-pages`.

---

[WIP]

## Description

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-04-29 18:10 UTC, ncksllvn commented on src/applications/search/reducers/index.js
> +        searchesPerformed,
I added this counter into the reducer so we could easily tell when it's the first results set and therefore not to set browser focus.

2019-04-29 18:10 UTC, ncksllvn commented on src/applications/search/containers/SearchApp.jsx
> +const SCREENREADER_FOCUS_CLASSNAME = 'sr-focus';
This class is applied to multiple elements. The helper `focusElement` will apply browser focus to the first one.

2019-04-29 18:10 UTC, ncksllvn commented on src/applications/search/containers/SearchApp.jsx
> +      }
This reads as -

1. If the app was previously loading (`prevProps.search.loading`) and is not loading now (`!this.props.search.loading`), then we have new results
2. If we have new results, and this is not the first search, then we should focus on the result set
3. Focus!

2019-05-01 18:01 UTC, 1Copenut requested changes
@ncksllvn @aubreyarcangel 
I took a look at this on `localhost` with VoiceOver as my screenreader proxy, and the results were excellent. Things were taking focus as expected, and announcing the changed result list.

I have two visual change requests, and I'm thumbs up:

1. Can we add a rule to the `styles.scss` file to defeat the yellow focus halo on the breadcrumb and H4 for suggested results?
  ```css
    nav[aria-label="Breadcrumb"],
    h4.sr-focus {
      outline: 0;
    }
  ```
2. I think we'll need to set the `includeBreadcrumbs: false` YAML in **search.md** on the vagov-content repo to eliminate a double breadcrumb now that we're using React.

I'll review with JAWS and NVDA when we're in staging, but I expect them to pass as well. Thank you both for working through this issue. It's been great watching the team collaborate to solve a unique challenge.

2019-05-01 19:36 UTC, ncksllvn commented
Thanks @1Copenut! Focus outline has been removed, and the Content PR to remove the breadcrumbs out of Markdown is here, https://github.com/department-of-veterans-affairs/vagov-content/pull/410.

@aubreyarcangel Can you take a look at this as well when you get the chance?

2019-05-02 17:05 UTC, ncksllvn commented
@1Copenut @aubreyarcangel I'd like to merge this today, along with the [content PR](https://github.com/department-of-veterans-affairs/vagov-content/pull/410). Do you mind taking a look again when you have time?

2019-05-02 19:11 UTC, 1Copenut approved these changes

2019-05-02 19:11 UTC, 1Copenut commented
@ncksllvn LGTM. I tested briefly on Chrome, Safari and Firefox on MacOS. Will test in Staging when ready.

2019-05-02 21:27 UTC, merged

2019-05-02 21:27 UTC, ncksllvn commented
Thanks @1Copenut!

2019-05-03 15:13 UTC, 1Copenut commented
@ncksllvn @aubreyarcangel I tested this in Staging with JAWS and NVDA. The results were very positive!

* **JAWS + IE11:** Announced top results header, number of results, breadcrumb change
* **JAWS + Chrome:** Announced top results header, search string change
* **NVDA + Firefox:** Announced top results header, partial search string change

How should we handle the open PR https://github.com/department-of-veterans-affairs/vets-website/pull/9743 ? Since we're handling the changes in React now, should that PR be closed without merging?

Thank you both for working through this on multiple iterations. I am thrilled to see how screen readers are behaving with search results now. I have some ideas for small results string readout improvements, and will put those in as an improvement ticket.

2019-05-03 16:11 UTC, ncksllvn commented
I think PR https://github.com/department-of-veterans-affairs/vets-website/pull/9743 provided us with some great insight into how to structure our components to handle browser focus naturally, but I think it can be closed now. Thanks @aubreyarcangel for your work on that!