add notification to user nav bar
department-of-veterans-affairs/vets-website pull request #10499
Opened 2019-07-30 18:38 UTC by accbjt

## Description
Add notification to user nav

User Flow:
- log in 
- click on user nav area
- 
## Testing done
local testing

## Screenshots

## Acceptance criteria
- [ ] Notification link should be in the user nav area
- [ ] Must be like design mockup [mockup](https:google.com)

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-07-30 18:47 UTC, 1Copenut requested changes
@accbjt I left a request to pluralize this text.

2019-07-30 18:47 UTC, 1Copenut commented on src/platform/site-wide/user-nav/components/PersonalizationDropdown.jsx
> +            Notification
Can we change this to Notifications, plural?

2019-07-30 18:58 UTC, accbjt commented
@1Copenut can you look at this one more time

2019-08-13 20:49 UTC, 1Copenut commented
@accbjt Can we close this PR? I think it's our example from the engineering demo.

2019-08-13 21:32 UTC, accbjt commented
Yes we can

On Tue, Aug 13, 2019 at 1:49 PM Trevor Pierce <notifications@github.com>
wrote:

> @accbjt <https://github.com/accbjt> Can we close this PR? I think it's
> our example from the engineering demo.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/department-of-veterans-affairs/vets-website/pull/10499?email_source=notifications&email_token=ABJA44BJOK5KUUCVB7TG3LLQEMM4VA5CNFSM4IH7FYJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4G6C3Q#issuecomment-521003374>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABJA44DPMMEE4WRVGTYQBRDQEMM4VANCNFSM4IH7FYJQ>
> .
>

2019-08-13 21:58 UTC, 1Copenut commented
Closing per conversation and demo code only.

2019-08-13 21:58 UTC, closed without merging