removal of blue bar from calculator.jsx
department-of-veterans-affairs/vets-website pull request #10521
Opened 2019-08-01 12:16 UTC by ksantiagomorgan6

## Description
As a developer i want to remove the unwanted blue bar in the Comparison Tool school profile page. 

## Testing done
Tested locally

## Screenshots
<img width="347" alt="Screen Shot 2019-08-01 at 8 02 09 AM" src="https://user-images.githubusercontent.com/50601724/62292430-5fcbc680-b434-11e9-8018-ca586551237d.png">

## Acceptance criteria
- [X] Removed blue bar from CT school profile page. 

## Definition of done
- [X] Events are logged appropriately
- [X] Documentation has been updated, if applicable
- [X] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-08-01 12:23 UTC, shawkey-daniel approved these changes
LGTM

2019-08-01 15:25 UTC, sonntag-adam approved these changes

2019-08-01 16:07 UTC, ksantiagomorgan6 commented
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

2019-08-02 17:50 UTC, rianfowler approved these changes

2019-08-05 17:56 UTC, shawkey-daniel requested changes
Looks like two environment imports

2019-08-05 17:58 UTC, shawkey-daniel approved these changes
LGTM

2019-08-06 12:15 UTC, sonntag-adam approved these changes

2019-08-06 12:21 UTC, ksantiagomorgan6 commented
@rianfowler can I get another review? I had to put the changes behind a production flag.

2019-08-06 20:29 UTC, rianfowler approved these changes
LGTM!

2019-08-06 21:55 UTC, merged