Add aria-label to option labels for accessibility
department-of-veterans-affairs/vets-website pull request #10536
Opened 2019-08-05 18:14 UTC by NateJohnson-BAH

## Description
Step 2 has Learn more links about each type of benefit. This text is repeated several times and doesn't provide a lot of context about what users will learn. I'd like to see if we can rewrite these links to be more clear calls to action or add an aria-label to each link. 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/768

## Testing done
confirmed in UI with screenreader utility

## Screenshots
*NO visual changes made

## Acceptance criteria
- [ ] As a screen reader user, I would like to hear a clear explanation like "Learn more about Post 9/11 benefits" when I focus a link on Step 2

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-08-05 18:33 UTC, shawkey-daniel requested changes
Make a constant for the label and repeat the constant instead of the text.

2019-08-05 20:06 UTC, shawkey-daniel approved these changes
LGTM

2019-08-06 20:10 UTC, rianfowler approved these changes

2019-08-07 14:58 UTC, NateJohnson-BAH commented
I didn't pay enough attention to what I was actually labelling. Thankfully our QA has caught it. I have gone back and updated the aria-label text for each 'learn more' option to be more precise and descriptive for each given option.

2019-08-07 15:35 UTC, shawkey-daniel approved these changes
LGTM

2019-08-07 15:36 UTC, delli-gatti-michael approved these changes
Approved by QA

2019-08-08 14:42 UTC, rianfowler approved these changes

2019-08-08 14:53 UTC, merged