Bah 19475
department-of-veterans-affairs/vets-website pull request #10577
Opened 2019-08-14 13:25 UTC by NateJohnson-BAH

## Description
As a developer, I need to reorder the questions on the Facility profile page so that the UX team can test the usability in the demo environment.

## Testing done
confirmed in local UI

## Screenshots
<img width="919" alt="Screen Shot 2019-08-14 at 9 24 25 AM" src="https://user-images.githubusercontent.com/52166695/63024511-58191280-be75-11e9-9fe4-b3d1f946bf07.png">

## Acceptance criteria
- [ ] After the "School Calendar" question the order of the questions in the "Calculator Fields" section is the following:
How do you want to take classes?
Where will you take the majority of your classes? (followed by conditional questions as applicable)
Will the majority of your classes be on the main campus?
Eligible for kicker bonus?

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-08-14 13:54 UTC, shawkey-daniel requested changes
For the online classes question, there is a OnlineClassesFilter.jsx component you can pull in so you don't duplicate the content. Look at the LandingPage.jsx container for example.

2019-08-14 15:37 UTC, sonntag-adam approved these changes

2019-08-14 18:02 UTC, zurbergram requested changes
Please use correct store object for OnlineClassesFilter and use eslint6 lambda to remove need to bind in the constructor

2019-08-14 18:02 UTC, zurbergram commented on src/applications/gi/components/profile/CalculatorForm.jsx
> +              {'Where will you take the majority of your classes?'} <br />(
Move the parentheses inside of button to be consistent with other places in CT

2019-08-21 16:31 UTC, zurbergram approved these changes
LGTM

2019-08-21 16:48 UTC, shawkey-daniel approved these changes
LGTM

2019-08-21 17:20 UTC, hughes-dustin commented
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

2019-08-21 17:45 UTC, rianfowler approved these changes

2019-08-21 17:46 UTC, merged