[Comparison Tool] Institutions profile school locations update
department-of-veterans-affairs/vets-website pull request #10628
Opened 2019-08-26 19:11 UTC by dmccurdybah

## Description

Update "view more" logic to display up to 15 locations without hiding additional locations behind "view more".  If there are more than 15 locations, only display the first 10 along with the "view more" ui.

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19539

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19560

## Testing done
Tested locally and QA reviewed

## Screenshots
![image](https://user-images.githubusercontent.com/41960449/63716246-84d50e80-c813-11e9-8b98-c4a9d62314c4.png)

## Acceptance criteria
- [x] If the number of related school locations (main, branch, extensions) is less than or equal to 15, all locations are displayed.
- [x] If the number of related school locations is greater than 15 then only 10 locations are displayed with a "View More" link that displays the remaining locations.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-08-26 20:14 UTC, zurbergram approved these changes
LGTM

2019-08-26 20:16 UTC, shawkey-daniel requested changes

2019-08-26 20:26 UTC, shawkey-daniel approved these changes
LGTM

2019-08-29 16:05 UTC, sonntag-adam approved these changes

2019-08-30 16:42 UTC, rianfowler approved these changes

2019-08-30 16:47 UTC, merged