Fix Vet Tec wrapping text
department-of-veterans-affairs/vets-website pull request #10674
Opened 2019-09-03 19:36 UTC by NateJohnson-BAH

## Description
On the VET TEC profile page, the "(25%)" after "Upon enrollment in program" and the one after "Upon completion of program" are wrapping to the next line. The percentage should be displayed in-line.

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19578

## Testing done
confirmed behavior in local UI at various scales

## Screenshots
Labels now appear inline at 100% scale, but change behavior based on reactive scale properties. 
<img width="490" alt="Screen Shot 2019-09-03 at 3 30 27 PM" src="https://user-images.githubusercontent.com/52166695/64202919-546b2100-ce60-11e9-86a1-401c3c71dbf3.png">

## Acceptance criteria
- [ ] The percentage should be displayed in-line.

## Definition of done
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-09-03 20:00 UTC, shawkey-daniel approved these changes
LGTM

2019-09-04 15:17 UTC, shawkey-daniel requested changes
Reviewers have preferred to use a ternary for production flags.

2019-09-04 15:17 UTC, shawkey-daniel commented on src/applications/gi/components/vet-tec/VetTecCalculator.jsx
> +import environment from '../../../../platform/utilities/environment';
You can use the alias for platform: 'platform/utilities/environment'

2019-09-04 17:21 UTC, shawkey-daniel approved these changes
LGTM

2019-09-11 18:18 UTC, delli-gatti-michael approved these changes
Approved by QA

2019-09-12 16:39 UTC, rianfowler approved these changes

2019-09-12 16:57 UTC, merged