1640 - GIBCT Screenreader bug - School Location table
department-of-veterans-affairs/vets-website pull request #10712
Opened 2019-09-10 16:00 UTC by NateJohnson-BAH

## Description
The school locations table doesn't announce itself properly to Safari + VoiceOver, and has some invalid HTML. It would be good to refactor this table for assistive device users. Screenshot and code sample below.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/1640

## Testing done
Confirmed locally in UI, via Chrome browser, Apple VoiceOver and Axe accessibility plugin. 

## Screenshots
Errors on page before fix:
<img width="1379" alt="Screen Shot 2019-09-10 at 11 50 23 AM" src="https://user-images.githubusercontent.com/52166695/64630048-4c603380-d3c2-11e9-9d38-4332c06cf3a4.png">

Screenreader and Axe util now approve:
<img width="1043" alt="Screen Shot 2019-09-10 at 11 51 14 AM" src="https://user-images.githubusercontent.com/52166695/64630072-571ac880-d3c2-11e9-817a-6c0c44184ad5.png">

## Acceptance criteria
- [ ] As a VoiceOver user, I want to hear the column header and cell announced properly.
- [ ] As a user, I do not want the visual layout to change when the HTML is refactored.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-09-10 16:15 UTC, zurbergram commented on src/applications/gi/components/profile/SchoolLocations.jsx
> +      <p className="main-campus-name">{name}</p>
this is too specific of a class name as this is being done in the generic `renderRow` function

If this is specific to the Main Campus row changes should either be made in `renderMainRow` or by using css class `${type}-row` which is used by the `<tr>`

```
.main-row {
    h6 {
      margin-bottom: 0em;
      margin-top: 0em;
    }
}
```

Is UI/UX ok with the switch to a `<p>` tag?

2019-09-10 16:15 UTC, zurbergram commented on src/applications/gi/sass/partials/_gi-profile-page.scss
> +      margin-top: 1.5em;
Is UI/UX ok with all of these changes?

2019-09-10 16:15 UTC, zurbergram commented on src/applications/gi/sass/partials/_gi-profile-page.scss
> +      clear: both;
Is UI/UX ok with all of these changes?

2019-09-10 16:15 UTC, zurbergram requested changes
See comments above

2019-09-10 18:42 UTC, zurbergram approved these changes
LGTM

2019-09-10 18:59 UTC, zurbergram approved these changes
LGTM

2019-09-13 19:17 UTC, delli-gatti-michael approved these changes
Approved by QA

2019-09-13 22:10 UTC, 1Copenut approved these changes
I reviewed with axe (Chrome) and VoiceOver (Safari). The table is working as expected with this browser. LMK when this branch is merged into Staging and I'll review with NVDA and JAWS. Should be no issues.

2019-09-16 16:05 UTC, rianfowler approved these changes

2019-09-16 18:01 UTC, merged