Add ability to change programs when viewing a vet tec profile
department-of-veterans-affairs/vets-website pull request #10856
Opened 2019-10-07 11:52 UTC by hughes-dustin

## Description
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19737

## Testing done

## Screenshots
<img width="1116" alt="Screen Shot 2019-10-07 at 7 51 13 AM" src="https://user-images.githubusercontent.com/48804654/66309307-46814380-e8d7-11e9-9fe7-12fe38883e96.png">

<img width="1116" alt="Screen Shot 2019-10-07 at 7 51 55 AM" src="https://user-images.githubusercontent.com/48804654/66309329-5b5dd700-e8d7-11e9-8067-2f839b510fc3.png">

## Acceptance criteria
- [ ] The "Approved programs" section table has 2 additional columns:
     - A selector column
     - A "Tuition & fees" column
- [ ] The selector column is pre-selected with the program that the user clicked on the search results page to view the profile page.
- [ ] The "Tuition & fees" column is populated with the Tuition & Fees dollar amount for the program.
- [ ] The "Length column rows has " hours" appended to the number of hours.
- [ ]  The "Tuition and fees for program" field in the "Estimate your benefits" section is populated with the tuition and fees amount of the selected program.
- [ ] The benefits estimator displays the selected program name.
- [ ] The benefits estimate displays the benefit calculations based on the selected program.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-10-07 20:11 UTC, shawkey-daniel requested changes

2019-10-08 12:15 UTC, delli-gatti-michael approved these changes

2019-10-08 12:47 UTC, hughes-dustin commented on src/applications/gi/tests/components/VetTecComponents.unit.spec.jsx
> +import createCommonStore from '../../../../platform/startup/store';
Okay!

2019-10-08 12:50 UTC, shawkey-daniel approved these changes
LGTM

2019-10-08 21:28 UTC, rianfowler approved these changes

2019-10-08 21:28 UTC, rianfowler commented on src/applications/gi/sass/gi.scss
> +    padding-left: 2.5em;
Recommend using the design system utilities to avoid adding duplicate css: 

https://design.va.gov/utilities/padding#padding-left

2019-10-08 21:28 UTC, rianfowler commented on src/applications/gi/sass/gi.scss
> +    width: 70%;
Might be able to use the fixed column utilities here: https://design.va.gov/layout/flexbox-grid#fixed-columns maybe with a 5:1:1 ratio for .name-col : hours-col : tuition-col?

2019-10-09 14:19 UTC, merged