Bah 2muchinfo107 2386
department-of-veterans-affairs/vets-website pull request #10933
Opened 2019-10-22 12:00 UTC by ksantiagomorgan6

## Description
The 508 office noticed an issue where IE11 + JAWS will read out a lot of extra information on the program detail views when users change a select menu in forms mode. I was able to recreate the issue, and it only occurred with IE11, not Chrome, using JAWS.

## Testing done
Local testing on Windows VM and JAWS

## Acceptance criteria
- [x] As a JAWS user, I don't want to hear extra information read aloud when I make a choice in FORMS mode from a select menu

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-10-22 13:11 UTC, shawkey-daniel requested changes

2019-10-22 13:16 UTC, ksantiagomorgan6 commented on src/applications/gi/components/profile/HeadingSummary.jsx
> +                isVisible={!!it.schoolClosing}
I went ahead and removed isVisible

2019-10-22 13:18 UTC, shawkey-daniel approved these changes
LGTM

2019-10-22 14:04 UTC, sonntag-adam approved these changes

2019-10-22 20:15 UTC, rianfowler approved these changes

2019-10-23 11:06 UTC, merged

2019-10-31 19:29 UTC, shawkey-daniel reviewed
~LGTM~ never mind, commented wrong thing