Colmery Sec 107 Analytics
department-of-veterans-affairs/vets-website pull request #10944
Opened 2019-10-23 14:34 UTC by ksantiagomorgan6

## Description
The Colmery Sec 107 update allows user to modify the housing allowance calculation based on where they will take classes. The default calculation for the location of the current page. User can also select extension campuses via a drop-down or enter a zip code into a text field to calculate housing for other locations.

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19642

## Testing done
Local testing done using browser console, navigate through targeted 107 analytics and checking datalayer in console. 

## Screenshots

![Screen Shot 2019-10-23 at 10 20 32 AM](https://user-images.githubusercontent.com/50601724/67403504-0630ef00-f580-11e9-9b1b-aa131c0c9a38.png)

## Acceptance criteria
- [x] Add gibctExtensionSearchZipCode analytics
- [x] Add gibctExtensionCampusDropdown analytics
- [x] Add gibctInternationalCheckbox analytics
- [x] Add gibctExtensionCampusSelection analytics

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-10-23 16:35 UTC, shawkey-daniel requested changes

2019-10-23 18:03 UTC, shawkey-daniel approved these changes
LGTM

2019-10-24 12:11 UTC, sonntag-adam approved these changes

2019-10-24 20:40 UTC, rianfowler approved these changes

2019-10-25 12:32 UTC, merged