SCO Anouncements
department-of-veterans-affairs/vets-website pull request #11068
Opened 2019-11-12 15:45 UTC by dmccurdybah

## Description

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-11-12 20:32 UTC, shawkey-daniel requested changes
Please make the 30 days default expiration a configurable item, so it can easily be changed in one place.

2019-11-13 19:31 UTC, sonntag-adam approved these changes

2019-11-13 19:51 UTC, shawkey-daniel approved these changes
LGTM

2019-11-13 20:16 UTC, rianfowler approved these changes

2019-11-13 20:18 UTC, merged