Fix for search results breadcrumb link
department-of-veterans-affairs/vets-website pull request #11096
Opened 2019-11-14 18:58 UTC by hughes-dustin

## Description
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19979

Conditionally change search results breadcrumb link to `program-search` when on vettec profile page. 

## Testing done
Dev tested.

## Screenshots

## Acceptance criteria
- [x] non-vettec profile page should have the `search` link.
- [x] vettec profile page should have the `program-search` link

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-11-14 19:08 UTC, delli-gatti-michael approved these changes

2019-11-14 19:48 UTC, devin-mccurdy approved these changes
LGTM

2019-11-14 19:49 UTC, shawkey-daniel requested changes
You need to verify the V is the second character. If it is any other, it would not be VET TEC.

2019-11-14 20:21 UTC, shawkey-daniel approved these changes
LGTM

2019-11-15 18:53 UTC, rianfowler approved these changes

2019-11-15 18:54 UTC, merged