2487 connect trd to api
department-of-veterans-affairs/vets-website pull request #11168
Opened 2019-11-21 18:02 UTC by cohnjesse

## Description
Original Ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/2487

As a Veteran using Rated Disabilities, I need to see the real data coming from within the VA to inform me of my status.

## Testing done 
unit tests already exist for these components

## Screenshots
NA

## Acceptance criteria
- [x] Change the redux code so it uses the number from FindRatingInfo
- [x] Update the endpoint the redux action is using and potentially update how errors are handled
- [x] Check unit test still passes
- [x] Data from the API is being displayed in the front end components

2019-11-21 23:24 UTC, micahchiang requested changes
One change is needed for correct error states to be displayed in the `TotalRatedDisabilities` component.

2019-11-21 23:24 UTC, micahchiang commented on src/applications/personalization/rated-disabilities/reducers/total-disabilities.js
> +          detail: action.response.errors.detail,
Errors that get returned by an API call come back as an array. These values need to be extracted.
<img width="640" alt="Screen Shot 2019-11-21 at 3 18 04 PM" src="https://user-images.githubusercontent.com/15097156/69385003-d6563380-0c72-11ea-8d2c-20525e4f6567.png">

2019-11-23 00:09 UTC, micahchiang approved these changes
LGTM

2019-11-23 00:09 UTC, micahchiang commented on src/applications/personalization/rated-disabilities/reducers/total-disabilities.js
> +        totalDisabilityRating: action.response.userPercentOfDisability,
Nice thing about finally getting this done is that we can use the same endpoint (hopefully) to check if a user is > 30% for the 686.

2019-11-26 12:48 UTC, U-DON approved these changes

2019-11-27 16:16 UTC, merged