Fix styling issue to before selector for checkbox label
department-of-veterans-affairs/vets-website pull request #11187
Opened 2019-11-25 13:22 UTC by hughes-dustin

## Description
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19962

This fixes the  GIDS checkboxes losing their labels' ::before selector's styling when you zoom out  in Safari. With this change, the checkbox will retain visibility when you zoom out to 75%. 

## Testing done 
\[Provide link to QA Test Plan ticket (issue-template coming soon) for the relevant product/feature.
List the new/update unit-test(s) & e2e-test\(s) that have been successfully run before open this PR.
Also, if UI-testable (i.e., testable manually on Staging by QA, either via the browser or REST API-client), provide link to QA test-request ticket \[issue-template coming soon].]

See [VSA QA Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/qa/vsa-qa-process.md) for more info on Engineering/QA collaboration/engagement.

## Screenshots

## Acceptance criteria
- [x] Checkboxes should remain despite zoom.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the Pre-Launch Checklist
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] A link has been provided to the VSA-QA Test Plan ticket \[use the VSA-QA Test Plan Issue Template to create the ticket within va.gov-team repo].
- [ ] A link has been provided to the VSA-QA Test-Request ticket \[issue-template coming soon].
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-11-25 13:32 UTC, sonntag-adam approved these changes

2019-11-26 16:38 UTC, devin-mccurdy approved these changes
LGTM

2019-11-26 18:26 UTC, bkjohnson requested changes
Screenshots showing the fix would be appreciated.  Also, I noticed this:

>  This is a global issue but we've decided to resolve it ourselves rather than punting to platform. 

If this _is_ a global issue, then fixing it in the gi application hasn't really fixed it.  I'm going to block this for now, since fixing it at the platform level might be preferable.

2019-11-26 18:48 UTC, bkjohnson approved these changes

2019-11-26 19:09 UTC, hughes-dustin commented
> Screenshots showing the fix would be appreciated. Also, I noticed this:
> 
> > This is a global issue but we've decided to resolve it ourselves rather than punting to platform.
> 
> If this _is_ a global issue, then fixing it in the gi application hasn't really fixed it. I'm going to block this for now, since fixing it at the platform level might be preferable.

Screenshots added. 

I just found an  issue in triage for platform dating back to August.  I'll leave a comment with how this can be resolved on that issue and we can hold off on this current PR.

 https://github.com/department-of-veterans-affairs/va.gov-team/issues/771

2019-11-26 19:32 UTC, merged