Update announcements.json
department-of-veterans-affairs/vets-website pull request #11247
Opened 2019-12-05 19:33 UTC by TamGIBill

Add two announcements for SAA and SCO Office Hours

## Description

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-12-05 19:45 UTC, shawkey-daniel requested changes

2019-12-05 19:45 UTC, shawkey-daniel commented on src/applications/static-pages/school-resources/constants/announcements.json
> +    "displayStartDate": "2019-12-05"
This line needs a comma at the end

2019-12-05 19:45 UTC, shawkey-daniel commented on src/applications/static-pages/school-resources/constants/announcements.json
> +    "displayStartDate": "2019-12-05"
This line also needs a comma at the end

2019-12-06 21:40 UTC, rianfowler approved these changes

2019-12-06 21:42 UTC, rianfowler approved these changes

2019-12-10 14:07 UTC, shawkey-daniel approved these changes
LGTM

2019-12-11 15:43 UTC, shawkey-daniel commented
Created #11288 to get changes in, since this one will not pass e2e tests in Jenkins.

2019-12-11 15:43 UTC, closed without merging