Adjusted schemas
department-of-veterans-affairs/vets-website pull request #11534
Opened 2020-01-21 19:19 UTC by cohnjesse

## Description
Original ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/4640

In order to get the form 686 work from the Rainbows team working on staging we need to fix the form's submitted data structure so that it both matches the shape of the JSON schema for the back end AND is valid for the VA form system.

## Testing done
Unit tests will be included in a separate branch

## Acceptance criteria
- [x] The shape of the form data on submission matches the shape of the JSON schema object for the back end
- [x] No schema invalidations errors get thrown when clicking the submit button

2020-01-21 19:39 UTC, micahchiang requested changes
Some questions about a couple of the properties, and also a comment to remove the console logs in `validation.js`.

2020-01-21 19:39 UTC, micahchiang commented on src/applications/disability-benefits/686/config/form.js
> +  genericLocation,
Should this be removed? I was under the assumption we were getting rid of it moving forward.

2020-01-21 19:39 UTC, micahchiang commented on src/applications/disability-benefits/686/config/form.js
>        'ui:required': isRequiredCallback,
Can this property be removed if we're always asking for city and state (or country) moving forward?

2020-01-21 19:39 UTC, micahchiang commented on src/applications/disability-benefits/686/config/form.js
> +      'ui:required': isRequiredCallback,
Can this property be removed if we're always asking for city and state (or country) moving forward?

2020-01-21 19:39 UTC, micahchiang commented on src/platform/forms-system/src/js/validation.js
> +
These console logs should be removed.

2020-01-24 17:11 UTC, micahchiang approved these changes
LGTM

2020-01-24 17:11 UTC, micahchiang commented on src/applications/disability-benefits/686/config/form.js
> +      'ui:title': 'State (or country if outside the USA',
I think this is missing an ending paren ')' after USA.

2020-01-28 20:30 UTC, cvalarida approved these changes

2020-01-28 20:31 UTC, merged