update modal text
department-of-veterans-affairs/vets-website pull request #11634
Opened 2020-02-05 18:55 UTC by annaswims

## Description

DS logon is regularly out for extended periods of time (~31 hours last week), and can be a [generally frustrating experience for veterans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/login/ds-logon/research/research_brief.md).

we could make it clear to veterans that they can log in with id.me or create a new id.me account and their "stuff" will still be there (presuming they have verified their identity).  
Before: 
<img width="360" alt="DS_logon_Banner" src="https://user-images.githubusercontent.com/19188/73770616-af27e200-474a-11ea-95f7-db8056ca1bb1.png">

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

I was testing by setting the [backend_statuses_controller action](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/backend_statuses_controller.rb#L9) to

````
    def index
     # statuses = ExternalServicesRedis::Status.new.fetch_or_cache
data = <<EOM
{"data":{"id":"","type":"pagerduty_external_services_responses","attributes":{"reported_at":"2020-02-05T18:26:38.000+00:00","statuses":[{"service":"DS Logon","service_id":"dslogon","status":"incident","last_incident_timestamp":"2020-02-05T17:45:26.000+00:00"}]}}}
EOM
      render json: data
    end
````

2020-02-05 18:56 UTC, annaswims commented
New text:

**You may have trouble signing in with DS Logon**
We’re sorry. We’re working to fix some problems with our DS Logon sign in process. You can sign in to VA.gov with an existing ID.me account or you can create an account and verify your identity through ID.me. 
[Learn how to create an account through ID.me](https://www.va.gov/sign-in-faq). 

If you continue to have trouble, please call the DS Logon help desk at (800) 538-9552.

2020-02-05 19:04 UTC, U-DON commented on src/platform/user/authentication/components/SignInModal.jsx
> +          "We’re sorry. We’re working to fix some problems with our DS Logon sign in process. You can sign in to VA.gov with an existing ID.me account or you can create an account and verify your ide
```suggestion
          <>
            <p>We’re sorry. We’re working to fix some problems with our DS Logon sign in process. You can sign in to VA.gov with an existing ID.me account or you can create an account and verify your identity through ID.me.</p>
            <p><a href="...">Learn how to create an account through ID.me.</a></p>
            <p>If you continue to have trouble, please call the DS Logon help desk at (800) 538-9552.</p>
          </>,
```

Not sure where the line break is or what URL you want to link to, but hopefully you can follow this as a guideline and get the rendered output you wanted.

2020-02-05 20:04 UTC, annaswims commented
we intend to validate by looking at the rate of id.me signups and logins during DS logon outages.

2020-02-05 21:21 UTC, U-DON commented on src/platform/user/authentication/components/SignInModal.jsx
> +            <p>If you continue to have trouble, please call the DS Logon help desk at <a href="tel:+18005389552">(800) 538-9552</a> .</p>
Should the space before the period be there?

2020-02-06 18:40 UTC, U-DON requested changes

2020-02-06 18:40 UTC, U-DON commented on src/platform/user/authentication/components/SignInModal.jsx
> +              desk at <a href="tel:+18005389552">(800) 538-9552</a> .
Sorry to be pedantic, but I think there's an extraneous space here. Everything looks great otherwise.

2020-02-07 15:32 UTC, U-DON approved these changes

2020-02-07 15:32 UTC, merged