Update announcements.json
department-of-veterans-affairs/vets-website pull request #11753
Opened 2020-02-24 15:22 UTC by TamGIBill

Added two webinars

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-02-24 17:41 UTC, shawkey-daniel requested changes

2020-02-24 17:41 UTC, shawkey-daniel commented on src/applications/static-pages/school-resources/constants/announcements.json
> +    "name": "Webinar on February 27 – Office Hours – For State Certifying Officials (SCOs)",
Should this be School Certifying Officials instead of State Certifying Officials? Otherwise, I think it is good to go.

2020-02-24 18:43 UTC, shawkey-daniel approved these changes
LGTM

2020-02-25 15:35 UTC, jhonny218 approved these changes
LGTM

2020-02-25 18:25 UTC, merged