Fixes:
department-of-veterans-affairs/vets-website pull request #11797
Opened 2020-03-02 23:37 UTC by brangi

-"Invalid date" Time Display on Facility Locator Hours
 -Small change to display of hours(spacing)

## Description

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-03-03 17:58 UTC, darkbushido requested changes

2020-03-03 17:58 UTC, darkbushido commented on src/applications/facility-locator/tests/helpers.unit.spec.js
> +    const operatingHours = '8:00am-Sunset';
You added spaces between 8:00 and am above but didnt here?

2020-03-05 16:08 UTC, darkbushido approved these changes

2020-03-05 16:10 UTC, jhonny218 approved these changes
LGTM

2020-03-05 16:52 UTC, merged