CT: Improve error messaging when there is a timeout#6662
department-of-veterans-affairs/vets-website pull request #11951
Opened 2020-03-20 02:44 UTC by ksantiagomorgan6

## Description
The GI Bill Comparison Tool currently handles an outage or timeout of the GIDS service by endlessly spinning, so this story seeks to provide those using the CT with an error message letting them know what they need to do.

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6662

## Testing done
Local testing completed

## Screenshots
Landing:
![Screen Shot 2020-03-18 at 11 48 26 PM](https://user-images.githubusercontent.com/50601724/77030746-05a55480-6976-11ea-9516-0f899e0807ce.png)
Search:
![Screen Shot 2020-03-18 at 11 47 35 PM](https://user-images.githubusercontent.com/50601724/77030762-1786f780-6976-11ea-91f9-fd42414261eb.png)

Profile:
![Screen Shot 2020-03-19 at 7 27 53 AM](https://user-images.githubusercontent.com/50601724/77062929-35bf1880-69b3-11ea-8145-42bfd189a8d5.png)

## Acceptance criteria
- [x] When the GI Bill Comparison Tool experiences an outage or timeout of the GIDS service, the following alert is displayed: We’re sorry. Something went wrong on our end. Please refresh this page or try again later.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-03-20 11:48 UTC, dmccurdybah commented on src/applications/gi/actions/index.js
> +          type: FETCH_PROFILE_FAILED,
Should this be `SEARCH_FAILED`?

2020-03-20 11:52 UTC, dmccurdybah commented on src/applications/gi/containers/SearchPage.jsx
> +import environment from '../../../platform/utilities/environment';
This can just  `platform/utilities/environment`

2020-03-20 11:53 UTC, ksantiagomorgan6 commented on src/applications/gi/actions/index.js
> +          type: FETCH_PROFILE_FAILED,
Yeah, updated

2020-03-20 13:14 UTC, devin-mccurdy approved these changes
LGTM

2020-03-20 13:19 UTC, shawkey-daniel requested changes

2020-03-20 13:19 UTC, shawkey-daniel commented on src/applications/gi/tests/reducers/constants.unit.spec.js
> +        payload: 'Service Unavailible',
spelling unavailable

2020-03-20 13:19 UTC, shawkey-daniel commented on src/applications/gi/tests/reducers/constants.unit.spec.js
> +    expect(state.error).to.eql('Service Unavailible');
spelling unavailable

2020-03-20 13:19 UTC, shawkey-daniel commented on src/applications/gi/tests/reducers/profile.unit.spec.js
> +        payload: 'Service Unavailible',
spelling unavailable

2020-03-20 13:19 UTC, shawkey-daniel commented on src/applications/gi/tests/reducers/profile.unit.spec.js
> +    expect(state.error).to.eql('Service Unavailible');
spelling unavailable

2020-03-20 13:19 UTC, shawkey-daniel commented on src/applications/gi/tests/reducers/search.unit.spec.js
> +        payload: 'Service Unavailible',
spelling unavailable

2020-03-20 13:19 UTC, shawkey-daniel commented on src/applications/gi/tests/reducers/search.unit.spec.js
> +    expect(state.error).to.eql('Service Unavailible');
spelling unavailable

2020-03-20 13:28 UTC, shawkey-daniel approved these changes
LGTM

2020-03-20 16:42 UTC, sonntag-adam approved these changes

2020-03-23 17:43 UTC, rianfowler approved these changes

2020-03-23 17:46 UTC, merged