Added estimate your benefits sec103 feature flag
department-of-veterans-affairs/vets-website pull request #12168
Opened 2020-04-09 14:44 UTC by ksantiagomorgan6

## Description
As a developer, I need to create a feature flag that can be used for the Estimate Your Benefits UI update effort.

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7773

## Testing done

## Screenshots

## Acceptance criteria
- [x] A feature flag exists for the new section 103 content.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-04-09 16:37 UTC, shawkey-daniel approved these changes
LGTM

2020-04-10 16:48 UTC, sonntag-adam approved these changes

2020-04-10 16:53 UTC, zurbergram approved these changes

2020-04-13 15:21 UTC, Clark-W-Griswold requested changes
Looks like there is an active conflict in `src/applications/gi/sass/partials/_gi-profile-page.scss`. 

Could we please resolve that before giving this an approval? :)

2020-04-13 16:41 UTC, Clark-W-Griswold approved these changes
👍

2020-04-13 17:37 UTC, merged