Add closed schools to search results caution flag filter
department-of-veterans-affairs/vets-website pull request #12344
Opened 2020-04-23 17:07 UTC by hughes-dustin

## Description
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8187

## Testing done
Dev tested

## Screenshots
![image](https://user-images.githubusercontent.com/48804654/80128046-265b5e00-8563-11ea-8c54-af7dd2e0d90b.png)
![image](https://user-images.githubusercontent.com/48804654/80128059-28bdb800-8563-11ea-94b9-1873e33ed12b.png)

## Acceptance criteria
-[x] The "Cautionary warnings" filter header is replaced with:
    > Warnings and school closings

-[x] The "Exclude institutions with warnings" filter text is replaced with:
    > Exclude results with warnings or closings

-[x] The filter Learn More modal content is the following:

    > **Cautionary warnings and school closings**
    > 
    > VA applies caution flags when we, or another federal agency, have increased regulatory or legal scrutiny of an educational program. We recommend students consider these warnings before enrolling in flagged programs.
    > 
    > When VA receives notice that a school or campus location will be closing, we add a school closing flag to that profile. Once the closing date passes, we remove the institution from the Comparison Tool during the next system update.
    > 
    > To learn more about caution flags, [visit the About this Tool page](https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#CF).

-[x] When the user selects the filter, institutions with either caution flags OR a school closing flag are excluded from the search results.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-04-23 19:48 UTC, zurbergram requested changes
Why not name it `excludeWarnings` instead of `excludeCautionAndSchoolClosureFlags` ?

2020-04-24 14:08 UTC, zurbergram approved these changes

2020-04-27 16:50 UTC, sonntag-adam approved these changes

2020-04-27 16:54 UTC, zurbergram approved these changes

2020-04-29 14:00 UTC, merged