Removed unnecessary aria-label and aria-live attributes
department-of-veterans-affairs/vets-website pull request #12362
Opened 2020-04-24 18:49 UTC by dmccurdybah

## Description
Removed unnecessary ARIA attributes to improve accessibility.

[ZenHub Issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8392)

## Testing done
Tested locally and QA reviewed

## Screenshots
N/A

## Acceptance criteria
- [x] Screen readers do not announce live region changes. Accordions should be able to be opened and closed, with screen readers announcing the button is "expanded" or "collapsed", but not start reading the elements inside them.
- [x] No axe violations appear
- [x] Semantic HTML validates a checker like the W3C HTML5 validator

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-04-24 18:52 UTC, shawkey-daniel approved these changes
LGTM

2020-04-28 18:14 UTC, 1Copenut requested changes
I pulled this branch to my local machine and tested with MacOS + Safari + VoiceOver. The accordions are no longer being read out when I expand/collapse them, which is a good thing.

Please remove the `aria-live` and `aria-atomic` attributes from the [CalculatorForm.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/238ef5f08d0a564ed6f05cc943783f29e97a4404/src/applications/gi/components/profile/CalculatorForm.jsx#L713) on lines 713 and 714. Then we should be good to test in staging after it's merged.

2020-04-29 11:52 UTC, sonntag-adam approved these changes

2020-04-29 13:52 UTC, 1Copenut approved these changes
Re-tested briefly in Safari (MacOS) with VoiceOver. The phantom live announcement is no longer being read out, and accordions are announcing themselves properly. I'll retest quickly with NVDA and JAWS in Staging, but I'm confident we're 💯

2020-04-29 13:53 UTC, merged