MDOT: Analytics
department-of-veterans-affairs/vets-website pull request #12679
Opened 2020-05-15 13:41 UTC by mr0sari0

## Description
This PR focuses on adding analytics to areas of interest in the form.

## Testing done

## Screenshots

## Acceptance criteria
- [ ]  Analytics should be sent on submission, successful submissions, failed submissions, and ineligibility orders

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-05-15 16:02 UTC, mr0sari0 commented on src/applications/disability-benefits/2346/config/form.js
> +      const randomNumber = Math.round(Math.random() * 10);
Adding a temporary way to simulate whether the call was successful or not.

2020-05-19 21:22 UTC, bradl3yC commented
Instead of pushing directly to the dataLayer, we need to leverage 
```
import recordEvent from 'platform/monitoring/record-event'
```

2020-05-19 21:24 UTC, bradl3yC commented on src/applications/disability-benefits/2346/config/form.js
> +  const onFailure = error =>
I would prefer to see a try catch used as opposed to .then/.catch

2020-05-19 22:22 UTC, bradl3yC requested changes
This is g2g as soon as you use the platform helper - swapping to async await in a try/catch isn't necessary as we're probably removing that code at some point

2020-05-20 00:01 UTC, mr0sari0 commented
> This is g2g as soon as you use the platform helper - swapping to async await in a try/catch isn't necessary as we're probably removing that code at some point

Of course I see this after I finish refactoring.  Anyway, I'm running into a bug where my request is getting its own value apart from what I'm returning.

2020-05-20 00:02 UTC, mr0sari0 commented
> Instead of pushing directly to the dataLayer, we need to leverage
> 
> ```
> import recordEvent from 'platform/monitoring/record-event'
> ```

Just updated.

2020-05-20 14:05 UTC, bradl3yC commented
Can you attach screens of the data later with the tags working?

2020-05-20 14:06 UTC, bradl3yC approved these changes

2020-05-20 15:42 UTC, merged