Modal Text Update
department-of-veterans-affairs/vets-website pull request #12896
Opened 2020-06-02 17:00 UTC by ksantiagomorgan6

## Description
The content of the cumulative post-9/11 service modal has been updated to reflect more accurate information so that Veterans and their beneficiaries have the most up to date information to support their estimation of benefits
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9522

Some of our modals have links that read "this page" after a descriptive sentence or two. It might be worth considering updating these links to be more descriptive.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9243

## Testing done
local testing
## Screenshots
![Screen Shot 2020-06-02 at 10 56 23 AM](https://user-images.githubusercontent.com/50601724/83547839-ceecce00-a4d0-11ea-8402-34f6e95e7865.png)
![Screen Shot 2020-06-02 at 10 56 38 AM](https://user-images.githubusercontent.com/50601724/83547841-d0b69180-a4d0-11ea-8194-e55274ef64e1.png)
![Screen Shot 2020-06-02 at 10 56 51 AM](https://user-images.githubusercontent.com/50601724/83547858-d44a1880-a4d0-11ea-8af0-d5a058ce0461.png)
![Screen Shot 2020-06-02 at 10 56 05 AM](https://user-images.githubusercontent.com/50601724/83547861-d57b4580-a4d0-11ea-9c12-1b2353e077c9.png)

## Acceptance criteria
- [x] The content of the Cumulative Post-9/11 service modal has been updated in all locations where it appears in the Comparison Tool
- [x] The content of the Cumulative Post-9/11 service modal displays the following content:

Cumulative Post-9/11 service
The Post-9/11 GI Bill education benefits you receive depend on how much active duty service you’ve completed since September 10, 2001. We calculate the amount based on the total (cumulative) time you’ve spent on active duty. If you’re a Purple Heart or Fry Scholarship recipient, or have a service-connected discharge, you’ll receive 100% of the benefits.
- [x] Link text is clear and offers enough information to users without needing to rely on the text around them
- [x] This work is completed behind a toggle so that it is only available in the staging environments and below.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-06-02 17:11 UTC, shawkey-daniel requested changes

2020-06-02 17:11 UTC, shawkey-daniel commented on src/applications/gi/containers/Modals.jsx
> +              </p>
Is this paragraph and the enclosing div needed for the PR, since only the next paragraph changes?

2020-06-02 17:11 UTC, shawkey-daniel commented on src/applications/gi/containers/Modals.jsx
> +            </p>
Is this paragraph and the enclosing div needed for the PR, since only the next paragraph changes?

2020-06-02 17:22 UTC, shawkey-daniel approved these changes
LGTM

2020-06-03 20:51 UTC, delli-gatti-michael approved these changes

2020-06-04 11:21 UTC, merged