added analytics to Stem 22-1995 form review screen
department-of-veterans-affairs/vets-website pull request #13098
Opened 2020-06-11 16:55 UTC by ksantiagomorgan6

## Description
Implement accordion expand / collapse tracking on Form 1995 Summary page
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7462
## Testing done
Local testing

## Screenshots
![Screen Shot 2020-06-11 at 12 50 41 PM](https://user-images.githubusercontent.com/50601724/84416684-888b2380-abe2-11ea-9416-1fbbf40fee4f.png)

## Acceptance criteria
- [x] Analytics are added to 1995 review accordions

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-06-11 17:05 UTC, shawkey-daniel approved these changes
LGTM

2020-06-12 11:57 UTC, sonntag-adam approved these changes

2020-06-15 13:22 UTC, f1337 approved these changes
LGTM (looks good to me!). One non blocking comment/suggestion.

2020-06-15 13:22 UTC, f1337 commented on src/platform/forms-system/src/js/review/ReviewChapters.jsx
> +      }
I'm new here and don't have a ton of context yet. Please pardon me if the following is not helpful. :)

Not a blocker, but a question & possible suggestion: Is this a pattern we expect to repeat elsewhere? If so, would it make future work faster, cleaner, and/or easier if we encapsulated this logic in a method that could be invoked like:

`this.props.recordFormEvent(formId, 'nav-accordion-collapse);`

2020-06-15 15:27 UTC, cvalarida requested changes

2020-06-15 15:27 UTC, cvalarida commented on src/platform/forms-system/src/js/review/ReviewChapters.jsx
> +      if (this.props.form.formId === '22-1995') {
Hard-coding logic for a specific form isn't an approach we can accept into the forms library. Please find another way to accomplish this. I recommend either looking into callbacks we can pass from the form config, or having a conversation with the analytics team to determine if this is useful information to gather for all forms.

2020-06-16 11:47 UTC, ksantiagomorgan6 commented
OBE

2020-06-16 11:47 UTC, closed without merging