22-10203 - Chapter 3
department-of-veterans-affairs/vets-website pull request #13252
Opened 2020-06-24 17:15 UTC by dmccurdybah

## Description

[ZenHub Issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/9874)

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-06-24 20:17 UTC, shawkey-daniel requested changes

2020-06-24 20:17 UTC, shawkey-daniel commented on src/applications/edu-benefits/10203/content/stemEligibility.jsx
> +    href="https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/"
Can this be a relative link?

2020-06-24 20:39 UTC, dmccurdybah commented on src/applications/edu-benefits/10203/content/stemEligibility.jsx
> +    href="https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/"
Can do

2020-06-25 11:52 UTC, shawkey-daniel approved these changes
LGTM

2020-06-25 16:37 UTC, bkjohnson approved these changes

2020-06-30 12:23 UTC, sonntag-adam approved these changes

2020-06-30 13:26 UTC, merged