Updated abbrevation in OJT for better understanding
department-of-veterans-affairs/vets-website pull request #13290
Opened 2020-06-26 17:17 UTC by ksantiagomorgan6

## Description
A few of the abbreviations on the on the job training are being read very literally by screen readers, and are not as clear as they could be. I'd like to consider updating

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10202

## Testing done
local testing using screen reader

## Screenshots

## Acceptance criteria
- [x] Screen readers announce text as natural language, not what is literally on the screen. Screenshots have the requested changes. Please disregard any that are not changed or cannot be changed.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-06-26 17:40 UTC, shawkey-daniel requested changes

2020-06-26 17:40 UTC, shawkey-daniel commented on src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
> +          { value: '2', label: '2 hours a week' },
Can we make this "hours per week"?

2020-06-26 17:42 UTC, ksantiagomorgan6 commented on src/applications/gi/components/profile/EstimateYourBenefitsForm.jsx
> +          { value: '2', label: '2 hours a week' },
Yeah, good catch

2020-06-29 23:10 UTC, 1Copenut approved these changes
LGTM. I pulled the feature branch and verified locally using VoiceOver. I'll spot check in Staging on NVDA and JAWS when ready.

2020-06-30 12:28 UTC, shawkey-daniel approved these changes
LGTM

2020-07-01 19:52 UTC, delli-gatti-michael approved these changes
~looks~ sounds good to me

2020-07-01 19:53 UTC, merged