Wizards: Add feature flag to 1995 wizard
department-of-veterans-affairs/vets-website pull request #13765
Opened 2020-08-07 14:26 UTC by mr0sari0

## Description
This sets up the wizard and feature flag on the 1995 wizard

## Testing done
UT and e2e updated

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-08-07 14:32 UTC, zurbergram requested changes
Please don't disable e2e tests, these changes do not appear to be behind an `environment.isProduction()` meaning all e2e tests should run and pass in the Jenkins build with changes

2020-08-07 14:32 UTC, zurbergram commented on src/applications/edu-benefits/1995/manifest.json
> +  "e2eTestsDisabled": "true"
Please don't disable e2e tests

2020-08-07 14:32 UTC, zurbergram commented on src/applications/edu-benefits/tests/1995/01-all-fields.e2e.spec.js
> +module.exports['@disabled'] =
Please don't disable e2e tests

2020-08-07 14:32 UTC, zurbergram commented on src/applications/edu-benefits/tests/1995/02-stem-all-fields.e2e.spec.js
> +module.exports['@disabled'] =
Please don't disable e2e tests

2020-08-07 16:57 UTC, mr0sari0 commented
> Please don't disable e2e tests, these changes do not appear to be behind an `environment.isProduction()` meaning all e2e tests should run and pass in the Jenkins build with changes

Hello, thanks for your feedback. I am not familiar with Nightwatch. Are you saying I can gate tests with an `environment.isProduction()` check?

2020-08-07 17:01 UTC, zurbergram commented
> > Please don't disable e2e tests, these changes do not appear to be behind an `environment.isProduction()` meaning all e2e tests should run and pass in the Jenkins build with changes
> 
> @zurbergram Thanks for your feedback. I am not familiar with Nightwatch. Are you saying I can gate tests with an `environment.isProduction()` check?

No, fix the e2e tests if your changes break them.

See https://github.com/department-of-veterans-affairs/vets-website/#end-to-end-e2e--browser-tests for how to run nightwatch e2e tests

2020-08-07 20:50 UTC, mr0sari0 commented
@zurbergram  I have updated the PR.

2020-08-10 14:16 UTC, zurbergram approved these changes

2020-08-10 20:35 UTC, bradl3yC commented on src/applications/edu-benefits/tests/1995/containers/IntroductionPage.unit.spec.jsx
> +      shouldEduBenefits1995WizardShow: false,
Pass this in via a provider as state and test the functionality from there

2020-08-19 13:58 UTC, bradl3yC approved these changes

2020-08-19 16:57 UTC, merged