Added stem sco email frontend feature flag
department-of-veterans-affairs/vets-website pull request #13883
Opened 2020-08-17 13:12 UTC by ksantiagomorgan6

## Description
As a developer, I need a way to toggle when the SCO email is sent from the staging environment so that SCOs are not being sent test data unnecessarily.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/12467

## Testing done
local testing 

## Screenshots
![Screen Shot 2020-08-17 at 9 05 33 AM](https://user-images.githubusercontent.com/50601724/90399672-575b2380-e069-11ea-9096-b21a2b41a6e9.png)

## Acceptance criteria
- [x] The STEM SCO Email feature flag is created and available in all environments.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-08-17 13:28 UTC, shawkey-daniel requested changes
This should follow the convention of snake case for the flag name in quotes as stated in the documentation.

2020-08-17 14:07 UTC, shawkey-daniel approved these changes
LGTM

2020-08-17 18:51 UTC, delli-gatti-michael approved these changes

2020-08-18 18:59 UTC, jhonny218 approved these changes

2020-08-18 19:49 UTC, merged