10201: EYB - iOS VoiceOver MUST read out the aria-label of the learn more buttons
department-of-veterans-affairs/vets-website pull request #14152
Opened 2020-09-09 17:14 UTC by elder-joseph

## Description
Modify Dropdown component to be 508 compliant for 'Learn More' buttons

[Originating Issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10201)

## Testing done
Testing passes locally

## Screenshots
N/A

## Acceptance criteria
- [x] iOS Safari reads out the full aria-label correctly

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-09-09 17:19 UTC, zurbergram requested changes

2020-09-09 17:19 UTC, zurbergram commented on src/applications/gi/components/Dropdown.jsx
> +        {this.props.learnMore ? (
Do a check on the type of `this.props.label` 
if the type is string use `<label htmlFor={this.props.name}>{this.props.label}</label>` 
else just render the provided element without label wrapping

2020-09-09 17:20 UTC, zurbergram commented on src/applications/gi/components/Dropdown.jsx
> +        {this.props.learnMore ? (
Do the check outside the return statement

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/gi/utils/render.jsx#L82 should be used for all "Learn More" labels to ensure consistency

2020-09-09 18:49 UTC, zurbergram approved these changes

2020-09-10 18:40 UTC, sonntag-adam approved these changes

2020-09-11 01:41 UTC, merged