Content alignments with JTF (Part 12of 2)
department-of-veterans-affairs/vets-website pull request #14357
Opened 2020-09-24 14:59 UTC by batemapf

## Description
See department-of-veterans-affairs/va.gov-team#13900. Addresses three of the four items listed in department-of-veterans-affairs/va.gov-team#13900 (comment):

- [x] Re-order health history so "Compromised immune system" is after "Cancer"
- [x] Add "Carpool or vanpool" to work transportation options
- [x] Add "Non-binary" to gender options

## Testing done
- Updated unit tests, pass locally
- Manually submitted form with updated options

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-09-24 16:00 UTC, DanielleThierryUSDSVA approved these changes

2020-09-25 16:20 UTC, cvalarida requested changes

2020-09-25 16:20 UTC, cvalarida commented on package.json
> +    "vets-json-schema": "https://github.com/department-of-veterans-affairs/vets-json-schema",
We need to pin the dependency to a specific commit hash to make sure any breaking changes introduced in a new `vets-json-schema` version are resolved in the same PR that upgrades the version. You can update the commit hash to the latest `master` commit with the `yarn update:schema` command from inside `vets-website`.

2020-09-25 16:33 UTC, cvalarida approved these changes
Looks great. Thanks! :raised_hands: :shipit:

2020-09-25 17:12 UTC, merged