move functions from HCA helpers to platform
department-of-veterans-affairs/vets-website pull request #14571
Opened 2020-10-14 14:31 UTC by erikphansen

## Description

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-10-14 15:04 UTC, sanlouise approved these changes
Looks good, it seems we also still need to update the relative import paths in `src/applications/hca/config/form.js`to the helpers that are now in `platform`

2020-10-14 15:09 UTC, erikphansen commented on src/applications/hca/helpers.jsx
> +export {
@sanlouise anything that was importing the functions from this file will still work because of these lines.

2020-10-14 15:59 UTC, sanlouise approved these changes

2020-10-14 15:59 UTC, erikphansen commented on src/applications/hca/helpers.jsx
> +export {
I actually don't know if this is a good approach or not. If reviewers object, I can find all the places that import the helpers from this file and update those imports.

2020-10-15 12:55 UTC, rianfowler requested changes
I think this PR should have a codeowners update, too. I don't think VSP FE should be the codeowner of these helpers- we don't have enough context to maintain them.

2020-10-15 14:06 UTC, erikphansen commented
@rianfowler Who should own them? They are going to be used by the HCA and Auth Exp. The ability to easily look up a medical facility's name from its ID feels like a foundational/platform-y thing to me. 🤷‍♂️

2020-10-15 17:03 UTC, rianfowler approved these changes

2020-10-15 18:37 UTC, merged