14639: Update casing for 1995 fields to be up to date with DEPO standards
department-of-veterans-affairs/vets-website pull request #14607
Opened 2020-10-15 20:31 UTC by elder-joseph

## Description
As a developer, I need to update the 1995 so that it is up to date with the current DEPO patterns and practices.

[Originating Issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14639)

## Testing done

## Screenshots
<img width="172" alt="Screen Shot 2020-10-15 at 3 53 37 PM" src="https://user-images.githubusercontent.com/48804834/96181094-74915e80-0f01-11eb-97e0-637d98243b69.png">
<img width="363" alt="Screen Shot 2020-10-15 at 3 54 56 PM" src="https://user-images.githubusercontent.com/48804834/96181097-75c28b80-0f01-11eb-9b38-8bbc935a4286.png">

## Acceptance criteria
- [x] In chapter 3, the "Add Another Service Period" button is replaced with "Add another service period"
- [x] In chapter 5, the "Do you have a parent who is dependent on your financial support?" question is replaced with "Do you have a parent who depends on you for financial support?"

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-10-16 13:11 UTC, zurbergram approved these changes
What other forms does this affect?

2020-10-16 14:01 UTC, elder-joseph commented
The platform specific casing change will affect the following edu-benefits forms:
- 1995
- 1990
- 1990E
- 1990N
- 5490
- 5495

2020-10-16 15:56 UTC, sonntag-adam approved these changes

2020-10-16 18:23 UTC, rianfowler requested changes
I think there was a decision related to this kind of change. @department-of-veterans-affairs/vsp-design-system-fe would know more.

2020-10-16 18:23 UTC, rianfowler commented on src/platform/forms-system/test/js/review/ArrayField.unit.spec.jsx
> +      'Add another Item name',
"Item" is capitalized mid-sentence.

2020-10-19 16:48 UTC, bkjohnson reviewed
I think this is fine, it follows the relevant practices/patterns:

- https://design.va.gov/content-style-guide/capitalization

However, I will try to find more info about that decision that Rian mentioned, because I also remember something along those lines.

2020-10-19 16:53 UTC, rianfowler approved these changes

2020-10-19 17:42 UTC, bkjohnson approved these changes
This issue captures the decision, along with a PR that was working towards removing the "Add Another" casing pattern:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/13684

The original PR that made the shift to sentence case for the "Add Another" pattern, while still allowing teams the option of opting out: https://github.com/department-of-veterans-affairs/vets-website/pull/14061

---

This more global approach is fine for now (it satisfies the first Acceptance Criteria in the issue), and if we decide that we want to meet those second and third AC, that is something that the design system team will do.

2020-10-19 17:49 UTC, merged

2020-10-19 17:49 UTC, elder-joseph commented
@bkjohnson Thank you for providing the context for this issue and the decision made around it.