VACMS-3256: Remove duplicate resources crumb.
department-of-veterans-affairs/vets-website pull request #14750
Opened 2020-10-28 13:49 UTC by ethanteague

## Description
Removes duplicate crumb being added by drupal page title.

## Testing done
Visual

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/97444591-b5767380-1902-11eb-90ea-fb65de3673c2.png)

## Acceptance criteria
- [ ] Visit preview page for `resources/what-if-im-having-trouble-opening-a-pdf/` and visually verify that breadcrumb looks like screenshot.

2020-10-29 21:44 UTC, ncksllvn approved these changes

2020-10-29 21:45 UTC, kelsonic commented on src/site/filters/liquid.js
> +    breadcrumbs.forEach(crumb => {
I think you could change the filter code bit to this if you want 🙂 doesn't matter though as i know this is high priority
```js
const filteredCrumbs = breadcrumbs.filter(crumb => crumb.url.path !== '/resources');
```

2020-10-29 21:46 UTC, kelsonic approved these changes
lgtm! 🎉 thanks!

2020-10-30 14:05 UTC, mpelzsherman requested changes
I'd really like to see @kelsonic 's suggestion implemted.

Also, if time permits, can we please add a unit test in `src/site/filters/liquid.unit.spec.js`?

2020-10-30 14:34 UTC, mpelzsherman approved these changes

2020-10-30 16:03 UTC, U-DON approved these changes

2020-10-30 16:15 UTC, merged