Mc chp31 orientation
department-of-veterans-affairs/vets-website pull request #14761
Opened 2020-10-28 20:53 UTC by micahchiang

## Description
This pull request adds a chapter 31 orientation step to the Chapter 31 application, as required by the stakeholder. 

## Testing done
- local

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-11-24 17:16 UTC, Mottie requested changes

2020-11-24 17:16 UTC, Mottie commented on src/applications/vre/28-1900/orientation/StepComponent.jsx
> +      <p className="vads-u-font-size--h4">
Would it be better to make this an `h4` since it's the size?

2020-11-24 17:16 UTC, Mottie commented on src/applications/vre/28-1900/orientation/StepComponent.jsx
> +      />
Will need our accessibility gurus to review this markup. If we embed a video, we'd need to include a transcript.

2020-11-24 17:16 UTC, Mottie commented on src/applications/vre/28-1900/orientation/utils.js
> +];
Nice!

2020-11-24 17:59 UTC, cohnjesse approved these changes
This looks great, a lot of work but a really great implementation

2020-11-24 17:59 UTC, cohnjesse commented on src/applications/vre/28-1900/orientation/utils.js
> +export const orientationSteps = [
This is really slick

2020-11-24 18:04 UTC, jenstrickland commented
@jason-gcio — Can we please meet to review this? We'll need to collaborate on providing videos in a Section 508 compliant and accessible way.

2020-12-01 14:43 UTC, jenstrickland commented
@micahchiang This is fine to be merged for now, as long as it's behind a feature flag. It allows us to share more broadly, collaborate, and iterate. Please keep me looped in so I can provide the code samples for discussion, as well, and add me and @joshkimux as reviewers going forward.

Additionally, I'd like to collect this work as a recommendation to present to the design system council, so let's figure out how we document all the things, @sporeboy. 😅

2020-12-01 14:46 UTC, Mottie approved these changes
LGTM! Thanks!

2020-12-01 17:44 UTC, closed without merging