only trust keepalive response if session-alive is present
department-of-veterans-affairs/vets-website pull request #14806
Opened 2020-11-02 23:06 UTC by ericbuckley

In some cases, the response returned to us from the `/keepalive` endpoint
won't have valid response headers.  One such case is when the browser
fails to submit a "Origin" request header.  When that happens, the
"session-alive" response header will be absent, so we shouldn't assume
that the user is logged out.  When missing we should assert that we can't
determine a user's SSOe status and therefore shouldn't try to keep it "in
sync" with their www.va.gov session.

fixes https://github.com/department-of-veterans-affairs/va.gov-team/issues/15709

[test cases coming...]

2020-11-03 18:26 UTC, rianfowler requested changes

2020-11-03 18:26 UTC, rianfowler commented on src/platform/utilities/tests/sso.unit.spec.js
> +    /* eslint-disable prettier/prettier */
Please disable the specific rule instead of all of prettier.

2020-11-03 18:30 UTC, ericbuckley commented on src/platform/utilities/tests/sso.unit.spec.js
> +    /* eslint-disable prettier/prettier */
@rianfowler I tried doing that with [quote-props](https://eslint.org/docs/rules/quote-props) but it didn't work.  Do you know what linting rule is suggesting I remove the quotes around the props?

For some background, I did try removing the quotes, but then eslint complained that the properties weren't in camel case.  For this particular test I need the headers to be snake case as they are set by https://eauth.va.gov/.

2020-11-03 20:27 UTC, bramleyjl reviewed
Syntax and purpose of change make sense to me, though I can't comment on the linting issue.

2021-07-01 16:13 UTC, joeniquette commented
this has been implemented in another ticket and is no longer required.
Other ticket: https://github.com/department-of-veterans-affairs/vets-website/pull/14920

2021-07-01 16:13 UTC, closed without merging