[Development] Increase BDD/CST file upload size
department-of-veterans-affairs/vets-website pull request #15187
Opened 2020-12-03 22:38 UTC by Mottie

## Description

File upload size has been increased to 150MB for all files uploaded to EVSS. They will in turn split the file into smaller 50MB files. This PR updates the file size validation and content visible to the Veteran

Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/16003 (FE)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/16004 (BE)
- https://github.com/department-of-veterans-affairs/devops/pull/7990

## Testing done

N/A

## Screenshots

N/A

## Acceptance criteria
- [x] BDD/CST file upload size increased to 150MB

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-12-04 16:03 UTC, ndsprinkle approved these changes

2020-12-29 23:06 UTC, edmangimelli requested changes
I think this has already been noted elsewhere, but the 150mb limit is for PDFs only, so I _think_ this PR will need a little tweak. Slack me if I'm mistaken!

2020-12-29 23:10 UTC, Mottie commented
You are correct. We should probably just close this PR since the "little tweak" would require a revamp of the platform upload file code.

2020-12-30 13:38 UTC, edmangimelli commented
@Mottie oh, was the idea to bump it to 150mb for everything on the FE, and let the BE send an error if a non-pdf goes over 50mb? That probably is a good first step (until we get platform involved).
Sorry I'm out of the loop on this one --it just came up in grooming.

2021-01-14 20:44 UTC, Mottie commented
> was the idea to bump it to 150mb for everything on the FE, and let the BE send an error if a non-pdf goes over 50mb? That probably is a good first step (until we get platform involved).

I've just updated this PR to only allow 150MB uploads for PDF files (behind a feature flag) and 50MB for everything else.

2021-01-15 14:37 UTC, edmangimelli approved these changes
thanks for the update, @mottie !

2021-01-15 14:41 UTC, ndsprinkle approved these changes

2021-01-15 14:56 UTC, merged