Remove remaining enzyme tests
department-of-veterans-affairs/vets-website pull request #15364
Opened 2020-12-14 22:54 UTC by vbahinwillit

## Description
Remove remaining enzyme tests

## Testing done
Unit testing and code coverage

## Screenshots
N/A

## Acceptance criteria
- [ ] All test should pass

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-12-16 14:42 UTC, jbalboni approved these changes

2020-12-16 14:42 UTC, jbalboni commented on src/applications/vaos/tests/components/VAOSApp/index.unit.spec.jsx
> +    screen.debug();
Missed removing this, looks like

2020-12-16 16:00 UTC, vbahinwillit commented on src/applications/vaos/tests/components/VAOSApp/index.unit.spec.jsx
> +    screen.debug();
Thought I got them all!!!

2020-12-16 16:45 UTC, jbalboni commented
@vbahinwillit It looks like FormButtons from the list in the ticket wasn't removed

2020-12-16 16:46 UTC, jbalboni commented
@vbahinwillit Also, while it wasn't in the list in the ticket, did we cover FacilityDirectionsLink in the FacilityAddress ticket? If so, we could remove that one as well.

2020-12-17 19:21 UTC, timwright12 approved these changes

2020-12-17 19:31 UTC, jbalboni requested changes

2020-12-17 19:31 UTC, jbalboni commented on yarn.lock
> +  version "18.4.0"
We definitely don't want to check in this change, it bumps the schema version which other forms depend on

2020-12-17 21:51 UTC, jbalboni approved these changes

2020-12-17 22:17 UTC, merged