EDU Form: Update misc content#17619
department-of-veterans-affairs/vets-website pull request #15453
Opened 2020-12-21 19:47 UTC by ksantiagomorgan6

## Description
As a developer, I need to update the content of various forms so that it the user experience is consistent across forms.
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/17619

## Testing done
local testing

## Screenshots
![Screen Shot 2020-12-21 at 2 43 50 PM](https://user-images.githubusercontent.com/50601724/102815904-27b38380-439b-11eb-8389-4a6f860b797d.png)
![Screen Shot 2020-12-21 at 2 45 11 PM](https://user-images.githubusercontent.com/50601724/102815909-297d4700-439b-11eb-9ea5-18c645e6cc9f.png)
![Screen Shot 2020-12-21 at 2 44 59 PM](https://user-images.githubusercontent.com/50601724/102815912-2a15dd80-439b-11eb-91a5-429b06d410d9.png)

## Acceptance criteria
- [x] In form 1990e:
a. In chapter 3, Sponsor's Branch of Service is sentence case (Sponsor's branch of service)
b. In chapter 3, Sponsor's VA number is replaced with Sponsor's VA file number
- [x] In form 0994:
a. When the “Continue to VA Form 22-1990” button appears, the text is displayed on a single line

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2020-12-21 19:54 UTC, shawkey-daniel requested changes

2020-12-21 19:54 UTC, shawkey-daniel commented on src/applications/edu-benefits/1990e/config/form.js
> +              'ui:title': "Sponsor's branch of Service",
You missed the big S in service

2020-12-21 19:57 UTC, ksantiagomorgan6 commented on src/applications/edu-benefits/1990e/config/form.js
> +              'ui:title': "Sponsor's branch of Service",
Updated

2020-12-21 20:44 UTC, shawkey-daniel approved these changes
LGTM

2020-12-23 11:32 UTC, delli-gatti-michael approved these changes

2020-12-23 14:24 UTC, merged