[526/BDD]: Skip Inflection Header for SIP
department-of-veterans-affairs/vets-website pull request #15517
Opened 2021-01-04 16:26 UTC by ndsprinkle

## Description
Due to a significant issue with disability names that have special characters, we need to not pass the inflection camel header for the 526/BDD forms. This PR adds the ability to skip the header for specific form IDs.

## Acceptance criteria
- [ ] Inflection header not provided for 526/BDD forms

2021-01-04 16:48 UTC, Mottie approved these changes
After looking at the code, I think I would agree that using the form ID is a simpler method (versus passing a parameter down through multiple components)

2021-01-04 17:49 UTC, edmangimelli requested changes
blocking this until the [back-end PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5582) is merged

2021-01-04 17:56 UTC, cvalarida approved these changes

2021-01-14 14:38 UTC, edmangimelli approved these changes
[The Back End PR](https://github.com/department-of-veterans-affairs/vets-api/pull/5582) has been merged, but not deployed, _but_ [it looks like the Back End deploys before the Front End](https://dsva.slack.com/archives/G016CG5FT6Z/p1610632987002500) (thanks @annaswims) --so it looks like this is ready to deploy today 👍

2021-01-14 15:26 UTC, merged