Review page - put all custom review data into DLs
department-of-veterans-affairs/vets-website pull request #15614
Opened 2021-01-12 17:28 UTC by stephenBarrs

## Description
This PR changes the outer div tag on all custom review fields to dl tags since the inner elements are dt and dd. 
Related issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/18223

Only Radio Buttons, YesNo widgets, DOB Widget and Select Groups are using the custom review field. Other fields may require changes to the VAFS codebase. 

## Testing done
I am not sure how to do the a11y testing to confirm this fixes the issue

## Screenshots
![image](https://user-images.githubusercontent.com/2481110/104349579-1a3c7580-54d1-11eb-92a8-1a8e209e9dc1.png)

## Acceptance criteria
- [ ] Related Axe violation is resolved

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-01-14 16:37 UTC, 1Copenut requested changes

2021-01-14 16:37 UTC, 1Copenut commented on src/applications/coronavirus-research/containers/CustomReviewDOBField.jsx
> +    <dl className="review-row">
Let's change these DLs back to `div[class="review-row"]`. Axe allows for one level of DIVs for nesting, but might throw an error for nested DLs. While experimenting this morning on localhost, I found an extra nesting div was appearing in CustomReviewField.

2021-01-14 16:37 UTC, 1Copenut commented on src/applications/coronavirus-research/containers/CustomReviewField.jsx
> -    <div>
If we remove the extra unclassed DIV and just return the `div[class="review-row"]` and the child elements, we can clear out the axe error without having to adjust any other elements.

```html
<!-- CustomReviewField.jsx#36 -->
<div className="review-row">
  <dt>{selectQuestionTitle}:</dt>
  <dd>{uiSchema['ui:title']}</dd>
</div>
```

2021-01-14 18:39 UTC, 1Copenut approved these changes
👍 LGTM!

2021-01-22 16:28 UTC, batemapf approved these changes

2021-01-25 19:56 UTC, merged