21203: STEM AD: Update content to be more plain language
department-of-veterans-affairs/vets-website pull request #16328
Opened 2021-03-11 16:49 UTC by elder-joseph

## Description
As a developer, I need to update the content of the STEM automated denial in the claims and appeals tool so that it is more plain language and easier for the user to understand.

[Originating Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21203)

## Testing done
Testing passes locally 

## Screenshots

### Updated Card Content:
<img width="664" alt="Screen Shot 2021-03-11 at 11 00 41 AM" src="https://user-images.githubusercontent.com/48804834/110816558-71549180-8259-11eb-8644-952933780069.png">

### Updated Details Content (full page)
![screencapture-localhost-3001-track-claims-your-stem-claims-2-status-2021-03-11-11_04_07](https://user-images.githubusercontent.com/48804834/110818298-20de3380-825b-11eb-9fa5-7bfb8e65fdc2.png)

### Updated Details Content (conditional sections not shown in full page)
<img width="708" alt="Screen Shot 2021-03-11 at 11 10 26 AM" src="https://user-images.githubusercontent.com/48804834/110817936-c93fc800-825a-11eb-957f-d9f036df9ad3.png">
<img width="693" alt="Screen Shot 2021-03-11 at 11 09 31 AM" src="https://user-images.githubusercontent.com/48804834/110817952-cd6be580-825a-11eb-8b69-b651fc60cb05.png">

## Acceptance criteria
- [x] The contents of the STEM automated denial card page match supporting artifact 1.
- [x] The contents of the STEM automated denial details page match supporting artifact 1.

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-03-11 17:43 UTC, shawkey-daniel requested changes

2021-03-11 17:43 UTC, shawkey-daniel commented on src/applications/claims-status/components/StemDeniedDetails.jsx
> +          )}
We still don't want this as a reason for denial. There is a possibility they could answer both questions no and still be eligible due to another criteria to be added later. The conditional for the affirmative is ok.

2021-03-11 17:43 UTC, shawkey-daniel commented on src/applications/claims-status/components/StemDeniedDetails.jsx
> +        {remainingEntitlement > 180 && (
Conditional is not needed here. This will always be the reason for denial for now.

2021-03-11 17:43 UTC, shawkey-daniel commented on src/applications/claims-status/components/StemDeniedDetails.jsx
> +        {remainingEntitlement && (
Conditional is not needed here. This will always be affirmative.

2021-03-11 17:43 UTC, shawkey-daniel commented on src/applications/claims-status/components/StemDeniedDetails.jsx
> +        )}
This is not needed because it is not possible when the only reason for denial is > 180.

2021-03-11 19:17 UTC, shawkey-daniel approved these changes
LGTM

2021-03-12 15:54 UTC, sonntag-adam approved these changes

2021-03-12 16:21 UTC, Mottie approved these changes

2021-03-12 16:54 UTC, merged