20703: Content updates to 0994
department-of-veterans-affairs/vets-website pull request #16445
Opened 2021-03-19 19:12 UTC by elder-joseph

## Description
As a developer, I need to remove the prod flag for the service history chapter updates so that they are available in the production environment.

[Originating Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20703)

## Testing done
Testing passes locally

## Screenshots
<img width="735" alt="Screen Shot 2021-03-19 at 3 04 28 PM" src="https://user-images.githubusercontent.com/48804834/111831074-3db2e080-88c5-11eb-87e6-3a759b3672c5.png">

## Acceptance criteria
- [x] The work completed in #20197 is available in the production environment.
Once merged, the `edu_form_omb_and_expiration` feature flag must be flipped to display this updated content. 
- [x] The content in the "Prepare" section of the 0994 introduction page is:

```
1. Prepare
To fill out this application, you’ll need your:

Direct deposit information
Highest level of education
Previous high-tech industry experience, if applicable
Information about the training provider or program you want to attend (optional)
To be eligible for VET TEC, you need to be

A Veteran with at least one day of unexpired education benefits, or
A service member with 180 days of less left on active duty
You can complete the VET TEC application to see if you’re eligible for the program, even if you haven’t yet selected the training program you'd like to attend. Learn more about the programs covered under VET TEC.

What if I need help filling out my application? An accredited representative, like a Veterans Service Officer (VSO), can help you fill out your application. Get help filing your claim.
```

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-03-22 13:21 UTC, shawkey-daniel requested changes

2021-03-22 13:21 UTC, shawkey-daniel commented on src/applications/edu-benefits/0994/containers/IntroductionPage.jsx
> +                      A service member with 180 days of less left on active duty
I think "of" should be "or". It is correct based on the story, but the story is wrong.

2021-03-22 14:40 UTC, shawkey-daniel approved these changes
LGTM

2021-03-23 15:05 UTC, delli-gatti-michael approved these changes

2021-03-24 13:41 UTC, merged