Add analytics events for ProgressBar, LoadingIndicator, Breadcrumbs
department-of-veterans-affairs/vets-website pull request #16684
Opened 2021-04-06 23:02 UTC by bsmartin-ep

## Description

Components updated:

- ProgressBar - https://github.com/department-of-veterans-affairs/va.gov-team/issues/19455
- SegmentedProgressBar - https://github.com/department-of-veterans-affairs/va.gov-team/issues/19455
- LoadingIndicator - https://github.com/department-of-veterans-affairs/va.gov-team/issues/19456
- Breadcrumbs - https://github.com/department-of-veterans-affairs/va.gov-team/issues/14490

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-04-07 13:14 UTC, LinnJS approved these changes

2021-04-07 21:11 UTC, jonwehausen requested changes
@bsmartin-ep Do you think we could take a look back at the [loading indicator](https://github.com/department-of-veterans-affairs/component-library/blob/5bccac3430ec4e76e41cc4f2dbf0fcdcedcfb7fd/src/components/LoadingIndicator/LoadingIndicator.jsx) and consider passing in `message`? Thank you sir

2021-04-13 11:56 UTC, jonwehausen approved these changes

2021-04-13 12:06 UTC, jonwehausen approved these changes

2021-04-13 12:06 UTC, jonwehausen approved these changes

2021-04-13 12:06 UTC, jonwehausen approved these changes

2021-04-13 12:57 UTC, jhonnyoddball approved these changes

2021-04-20 12:15 UTC, timwright12 approved these changes

2021-04-20 12:29 UTC, LeKeve approved these changes

2021-04-21 15:26 UTC, ncksllvn approved these changes

2021-04-22 22:04 UTC, merged

2021-04-28 00:21 UTC, jonwehausen reviewed
Review complete