Reset dataLayer properties to avoid bleed over
department-of-veterans-affairs/vets-website pull request #16738
Opened 2021-04-10 05:49 UTC by bsmartin-ep

## Description

For: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22412

> Today, with www.va.gov being a single page app, there are cases where a data layer variable may persist to a subsequent event where its context/meaning/definition is not necessarily needed.
> 
> With our design system standardization, it would be great time to do some discovery around the best method to clear data layer variables immediately following their usage within an event.
> 

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-04-12 13:19 UTC, jhonnyoddball approved these changes
LGTM

2021-04-13 14:26 UTC, jonwehausen requested changes
LGTM - Just having issues using the test instance

2021-04-13 21:08 UTC, jonwehausen approved these changes

2021-04-20 16:09 UTC, jonwehausen approved these changes

2021-04-20 16:12 UTC, merged