Possible fix for sentry error "Cannot call method addEventListener of null"
department-of-veterans-affairs/vets-website pull request #16979
Opened 2021-04-28 14:39 UTC by mpelzsherman

The Facilities team has been tracking this [Sentry error,](http://sentry.vfs.va.gov/organizations/vsp/issues/29941/) which has occurred over 5,000 times in production in the last 90 days.

Our best guess is that this is happening when the `bindModalTriggers` function is called to set up the signin/signup modal button before the button has rendered. We haven't been able to reproduce the error yet, but we are hoping this change will fix it.

See Slack [thread](https://dsva.slack.com/archives/CQH357ZTP/p1619204082170400).

2021-04-28 14:42 UTC, kelsonic approved these changes

2021-04-28 15:40 UTC, k80bowman commented
My concern with this PR is that it will get rid of the Sentry error, but if the button does not load before `componentDidMount` gets called, we will end up with a button with no listener attached, so that it does not work and essentially is failing silently, which I think is worse than having the Sentry error. Are we sure that this is not going to happen?

2021-04-28 15:49 UTC, mpelzsherman commented
As I explained in Slack:

The PR should a) fix the Sentry error, which is probably breaking _all Javascript on the page_, and b) will not introduce any new errors.

If this race condition occurs and the button isn’t rendered when `componentDidMount` gets called, clicking the button will just not do anything. Fixing that problem is a much bigger can of worms.

2021-04-28 16:05 UTC, k80bowman commented
If we merge this commit and it does resolve the Sentry errors, how quickly do you think we could dig into this can of worms in order to get the problem fixed?

2021-04-28 16:31 UTC, mpelzsherman commented
Unless/until we start getting a flood of bug reports from Veterans or stakeholders, I doubt this will get much traction.

2021-04-28 16:59 UTC, k80bowman requested changes
Ok. At this point, I am not comfortable with this solution. I think it fixes the Sentry errors, but leaves us with an invisible problem that is dependent on our users to make noise about. Feels like a slippery slope. I would recommend getting more input on this before merging. It might also be helpful to add some tests around this, maybe that is a way we can reproduce the error.

2021-05-04 17:38 UTC, U-DON commented
My suggestion would be to wrap it in a try/catch, where the catch block would add more context before forwarding the exception to Sentry. It might be worth including attributes like the link class or id and text, so we can better identify what link it is on the page. Presumably, the report would include the page URL too.

2022-01-19 14:04 UTC, closed without merging