Bah 10203 updates
department-of-veterans-affairs/vets-website pull request #17461
Opened 2021-06-02 20:24 UTC by ksantiagoBAH

## Description

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-06-03 16:43 UTC, shawkey-daniel requested changes

2021-06-03 16:43 UTC, shawkey-daniel commented on src/applications/edu-benefits/10203/pages/stemEligibility.js
> +// prod flags 24612
Please move comment next to flag

2021-06-03 16:51 UTC, ksantiagoBAH commented on src/applications/edu-benefits/10203/containers/IntroductionPage.jsx
> +  // prod flags 24612
moved

2021-06-03 19:28 UTC, shawkey-daniel approved these changes
LGTM

2021-06-04 16:06 UTC, sonntag-adam approved these changes

2021-06-08 11:49 UTC, merged