25559: Update search results card content and layout
department-of-veterans-affairs/vets-website pull request #17552
Opened 2021-06-09 20:49 UTC by elder-joseph

## Description
As a developer, I need to update the search results cards format and content to match the latest designs so that they can be usability tested in the sandbox.

Originating Issue: [25559](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25559)

## Testing done
Testing passes locally

## Screenshots
<img width="535" alt="Screen Shot 2021-06-09 at 4 38 11 PM" src="https://user-images.githubusercontent.com/48804834/121426697-dd6e9080-c941-11eb-9543-0ec7ff29f5dc.png">
<img width="255" alt="Screen Shot 2021-06-09 at 4 39 02 PM" src="https://user-images.githubusercontent.com/48804834/121426699-de9fbd80-c941-11eb-8db4-b84ed3c91cc5.png">
<img width="258" alt="Screen Shot 2021-06-09 at 4 39 12 PM" src="https://user-images.githubusercontent.com/48804834/121426703-df385400-c941-11eb-923e-9dcfd5a4df36.png">
<img width="270" alt="Screen Shot 2021-06-09 at 4 39 42 PM" src="https://user-images.githubusercontent.com/48804834/121426705-dfd0ea80-c941-11eb-9545-b2574a86de75.png">
<img width="252" alt="Screen Shot 2021-06-09 at 4 42 00 PM" src="https://user-images.githubusercontent.com/48804834/121426706-dfd0ea80-c941-11eb-9fa5-148b271fdefe.png">

## Acceptance criteria
- [x] Each card has the following 4 or 5 sections:
a. Type Header
b. Name / Location / Ratings (if available)
c. Caution Flags (if available)
d. Tuition and Housing Benefit
e. Institution Details (Accreditation, GI Bill Students, Approved programs, Program length)
f. Compare

- [x] The Type Header identifies the type of institution:
a. School
b. Employer
c. VET TEC

- [x] If an institution has a special mission, the special mission is displayed in the Type Header. Special missions include:
a. Single-gender school (Men-only, Women-only)
b. Religious affiliation (Religious)
c. Historically Black College or University (HBCU)

- [x] The name of the institution is a link to the institution profile page.

- [x] The format of the ratings information is: [star visual] (X.X of 5) by XX Veterans

- [x] VET TEC institution types display the preferred provider indicator below the ratings information.

- [x] The Caution Flag display:
a. Is only displayed when an institution has a caution flag
b. Initially displays the number of caution flags the institution has
c. The user can view the specific type of caution flags at the institution.

- [x] The "Housing benefit" for Employer institution types has helper content

- [x] Housing rate and the amount of entitlement used decrease every 6 months as employer pay increases
There is a new "Institution Details" section between the "Tuition and fees" section and the "Compare" section

- [x] The "Institution Details" section displays the following information based on institution type:
a. School: Accreditation, GI Bill students
b. Employer: Accreditation, GI Bill students
c. VET TEC: Approved programs, Program length

- [x] When an institution has no GI Bill students, 0 is displayed.

- [x] The view link is not displayed in the "Compare" section

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-06-10 00:24 UTC, zurbergram requested changes

2021-06-10 00:24 UTC, zurbergram commented on src/applications/gi-sandbox/components/search/SearchResultCard.jsx
> +import React, { useState } from 'react';
Please provide screenshots of how this looks on the Location search tab

2021-06-10 13:57 UTC, zurbergram approved these changes
LGTM

2021-06-11 18:27 UTC, sonntag-adam approved these changes

2021-06-14 13:11 UTC, merged