Remove feature flags
department-of-veterans-affairs/vets-website pull request #17587
Opened 2021-06-14 13:44 UTC by ashagross

[25828](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25828)

## Description
Remove 526 Feature flags that are no longer needed.

## Testing done
visual/manual

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [X ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [X ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-06-14 14:27 UTC, micahchiang reviewed
I think [this page](https://github.com/department-of-veterans-affairs/vets-website/blob/3e790c92fd8bc94df7562155fea045d8d1a7d330/src/applications/static-pages/wizard/index.js#L7) uses the 526 selector that is being removed here? Not sure though.

2021-06-14 14:35 UTC, Mottie commented
Yeah we need to remove the flag from the wizard. Nice catch Micah!

2021-06-14 14:41 UTC, mdewey approved these changes
LGTM! Thanks for the clean up :-)

2021-06-14 15:15 UTC, jbalboni approved these changes

2021-06-14 15:21 UTC, U-DON approved these changes

2021-06-14 15:32 UTC, micahchiang approved these changes

2021-06-14 17:13 UTC, dat-gcio approved these changes

2021-06-14 18:32 UTC, Mottie requested changes

2021-06-14 18:32 UTC, Mottie commented on src/applications/disability-benefits/all-claims/config/form.js
> -          }),
we still need `dob` & `servicePeriods`

2021-06-14 18:48 UTC, ashagross commented on src/applications/disability-benefits/all-claims/config/form.js
> -          }),
Got that added back!

2021-06-14 21:41 UTC, Mottie commented on src/applications/static-pages/wizard/index.js
> +export default connect(Wizard);
We can remove the `connect`.

2021-06-16 16:17 UTC, Mottie approved these changes
<img alt="ghe-emoji" title=":_tuzki_happiness:" src="https://cloud.githubusercontent.com/assets/136959/13203599/6830f01c-d881-11e5-83bc-54a8e3d65d4c.gif">

2021-06-16 16:28 UTC, merged