Emergency mashup UI
department-of-veterans-affairs/vets-website pull request #17683
Opened 2021-06-24 16:51 UTC by brangi

## Description

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-06-29 20:21 UTC, mpelzsherman requested changes
I think we need to add `LocationType.EMERGENCY_CARE` to [this array](https://github.com/department-of-veterans-affairs/vets-website/blob/be3d2bbd6f76e12126681eae9d8a21470304cff4/src/applications/facility-locator/components/PaginationWrapper.jsx).

2021-06-29 20:29 UTC, mpelzsherman commented on src/applications/facility-locator/api/MockLocatorApi.js
> +            }
Can this block be moved into a separate function? LIke the linter warning says, this function is getting too long/complex.

2021-06-29 20:36 UTC, mpelzsherman commented on src/applications/facility-locator/components/search-results-items/EmergencyCareResult.jsx
> +                recordEvent({ event: 'cta-primary-button-click' });
Please check w/analytics about the event name here. They probably want something more specific.

2021-06-29 20:41 UTC, mpelzsherman commented
Great job overall! The only required change is the pagination issue - the rest are just suggestions.

2021-06-29 21:06 UTC, gescobardev commented
Great work @brangi !

2021-06-29 23:02 UTC, brangi commented
Clicks on the link to the emergency care benefit page are tracked (event: cta-emergency-benefit-button-click)
 Environment check is in place to hold changes in staging until validated by team and accessibility specialists

2021-06-29 23:12 UTC, mpelzsherman approved these changes

2021-06-30 13:45 UTC, gescobardev approved these changes

2021-06-30 14:30 UTC, merged