DRAFT: Dashboard 2 cleanup
department-of-veterans-affairs/vets-website pull request #17940
Opened 2021-07-20 19:41 UTC by tmitchellgcio

## Description

## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-07-28 17:01 UTC, erikphansen requested changes

2021-07-29 19:10 UTC, tmitchellgcio commented on src/platform/site-wide/mega-menu/containers/Main.jsx
> +  if (loggedIn) {
Should we not so a check for logged in though? I assumed this had a purpose outside of the dashboard2

2021-07-29 21:21 UTC, erikphansen commented on src/platform/site-wide/mega-menu/containers/Main.jsx
> +  if (loggedIn) {
I think @kelsonic or someone on his team would know better (and I think his team has to approve this change anyway), but the idea was that, with the launch of My VA 2.0 to all users, we will always show the My VA link on the main nav, whether you are signed in or not.

2021-07-29 22:37 UTC, kelsonic commented on src/platform/site-wide/mega-menu/containers/Main.jsx
> +  if (loggedIn) {
Yupp! That's correct, you can omit the `if (loggedIn) {` bit assuming we want the My VA link to always show regardless of auth 🙂 Thanks @erikphansen!

2021-07-30 19:11 UTC, tmitchellgcio commented on src/platform/site-wide/mega-menu/containers/Main.jsx
> +  if (loggedIn) {
removed

2021-07-30 20:28 UTC, erikphansen approved these changes
Looks good. I also pulled this down locally and made sure the post-Dashboard-2 world looked good. This PR is mostly moving existing files and then updating some imports. I'm confident enough in the existing test coverage that nothing broken in this reorg. Nice job!

2021-07-30 20:51 UTC, kelsonic approved these changes

2021-07-30 21:20 UTC, alexandec approved these changes

2021-07-30 21:40 UTC, erikphansen commented
@tmitchellgcio I can't make sense of the Cypress failures on Jenkins :-/ I ran all of the Dashboard Cypress tests locally and it's fine. Running the entire suite locally and it fails and exits early. Can you maybe try merging in `master` yet again to see if that fixes things?

2021-08-02 21:55 UTC, micahchiang approved these changes

2021-08-03 20:15 UTC, tmitchellgcio commented
@department-of-veterans-affairs/chatbot-admin could I get a review?

2021-08-04 18:05 UTC, jgacek approved these changes

2021-08-04 18:08 UTC, merged