Kelsonic 25001 safari button outline
department-of-veterans-affairs/vets-website pull request #18065
Opened 2021-07-29 20:43 UTC by kelsonic

## Description
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/25001

This PR removes the transition property from the back to top button.

## Testing done
https://github.com/department-of-veterans-affairs/va.gov-team/issues/25001#issuecomment-889413479

## Screenshots
https://github.com/department-of-veterans-affairs/va.gov-team/issues/25001#issuecomment-889413479

## Acceptance criteria
- [x] Back to top button should show outline when focused on Safari

## Definition of done
- [x] Changes have been tested in vets-website
- [x] Changes have been tested in IE11, if applicable
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-07-29 20:50 UTC, Rleahy22 approved these changes

2021-07-29 22:42 UTC, alexandec approved these changes

2021-07-29 22:42 UTC, alexandec commented
PR seems fine, but the new formation version doesn't seem to exist (yet?)

2021-07-29 22:45 UTC, kelsonic commented
@alexandec Correct 🙂 Related PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/649

2021-07-29 22:53 UTC, bkjohnson requested changes, later dismissed
I'd like to block this for now until we have a better understanding of why the `gi-sandbox` BTT button has deviated from the design system.

2021-07-30 00:32 UTC, bkjohnson reviewed
My goal here isn't actually to prevent this PR from being merged - I just wanted to jump in and ask a question _before_ this gets merged and nobody ever looks at it again :upside_down_face: . Since I don't want to block things from happening if someone approves this before I'm awake tomorrow, I'm dismissing the change request.

However, I would still like to understand what prompted the BTT copy + modification to happen rather than contributing any fixes/enhancements to the design system. I remember some discussion around this and [thought the change might be limited to `z-index`](https://dsva.slack.com/archives/C0NGDDXME/p1626721673280100?thread_ts=1626701433.264600&cid=C0NGDDXME), but I did a diff between appropriate files and it looks more complicated than that. #17930 also doesn't really explain the Back to Top changes.


When you approve, please let us know so that the design system team can address the problem that interfered with a system contribution.

2021-07-30 11:54 UTC, shawkey-daniel approved these changes
LGTM

2021-07-30 13:30 UTC, zurbergram commented
@bkjohnson For https://github.com/department-of-veterans-affairs/vets-website/pull/17930 I attempted to use the code provided at https://design.va.gov/components/back-to-top and it did not work out of the box within the CT Sandbox application.  See discussion in https://dsva.slack.com/archives/C0NGDDXME/p1626701433264600 

There were several issues that made it not work as needed:
- There are 2 sticky/floating components within the Sandbox; the compare drawer and "Back to top".  See https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/31005740 and scroll down past header/jump links
- The compare drawer changes heights when expanded vs collapsed so need to account for "Back to top" placement because of this
- The "Back top" was not floating right correctly within the page, it was either not going right or too far to the right. The hack in https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/gi-sandbox/components/BackToTop.jsx is too grab the parent element's x coordinate and since the margin on both sides is the same use that to determine the value for the css `right` property of the button

Since the changes made to the CT Sandbox "Back to top" were not pure css changes I did not request the changes be incorporated into the design system.  

The [CT Sandbox](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/gi-sandbox) and [CT Classic](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/applications/gi) have several components and elements that are based on the design system but modified to work with the CT application.

2021-07-30 13:32 UTC, zurbergram requested changes
Please go to http://localhost:3001/gi-bill-comparison-tool-sandbox/profile/31005740 on this branch locally and provide screenshots that the "Back to top" button is correctly positioned on bottom right of screen above the compare drawer in both expanded and collapsed state

See https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/31005740 for current functionality.

2021-07-30 16:02 UTC, kelsonic commented
Sorry not sure what all the comments are referring to, this PR has to be merged first to remove the transition: all for buttons on safari due to an a11y error: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/649 `"@department-of-veterans-affairs/formation": "6.16.3"` is not currently published until the related PR is merged + deployed to NPM, apologies for any confusion! 🙂

2021-07-30 16:50 UTC, zacharymorel approved these changes
Weird that transitions prevent focus on element in safari. But we got to do what we got to do for a11y.

2021-08-03 17:37 UTC, zurbergram approved these changes

2021-08-05 14:48 UTC, kelsonic commented
@bkjohnson @cvalarida May I have a review?

2021-08-09 14:32 UTC, kelsonic commented
@bkjohnson @cvalarida May I have a review? Any success deploying the latest version of formation?

2021-08-09 16:36 UTC, bkjohnson reviewed
I just published the latest version of formation.

Also, since this is app code, there's nothing for us to review.

2021-08-09 16:38 UTC, kelsonic commented
@bkjohnson Thanks 🙂

2021-08-09 17:16 UTC, bkjohnson commented
Thank you for that! We will make an effort to follow up elsewhere now that we have some information, but app code isn't our responsibility.

2021-08-09 18:28 UTC, merged