Fetch clinic detail when using v2 endpoints
department-of-veterans-affairs/vets-website pull request #18106
Opened 2021-08-03 15:45 UTC by jbalboni

## Description
This PR
- Adds a fetch to the vaos service clinics endpoint
- Sets clinic name from the fetched clinic data, since we don't have that on appointments from vaos service
- Adds tests for both scenarios, where we successfully and unsuccessfully fetch clinic details

## Original issue(s)
department-of-veterans-affairs/va.gov-team#27642

## Testing done
Unit and local testing

## Acceptance criteria
- [ ] Clinic is fetched

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-08-03 15:46 UTC, jbalboni commented on src/applications/vaos/services/patient/index.js
> + * @param {boolean} [params.useV2=false] Use the v2 apis when making eligibility calls
I forgot to fix these before merging my other PR this morning

2021-08-04 13:44 UTC, LeKeve requested changes

2021-08-04 13:44 UTC, LeKeve commented on src/applications/vaos/services/mocks/index.js
> +    if (req.params.clinic_ids) {
These should be `req.query.clinic_ids`.

2021-08-04 13:44 UTC, LeKeve commented on src/applications/vaos/services/healthcare-service/index.js
> +    return transformClinicsV2(results)[0];
Is the `[0]` necessary? The v2 endpoint should only return a single clinic if `clinicIds` is passed a single id array.

2021-08-04 13:46 UTC, LeKeve commented on src/applications/vaos/services/healthcare-service/index.js
> +    return transformClinicsV2(results)[0];
Disregard this. I misread as `results[0]` and thought we were passing the first clinic we got in the response. This is actually grabbing the only clinic in the transformed array. Looks good.

2021-08-04 15:00 UTC, LeKeve approved these changes

2021-08-04 18:21 UTC, merged