Features/edu benefits application instructions
department-of-veterans-affairs/vets-website pull request #18146
Opened 2021-08-05 20:52 UTC by FernandoBoza

## Description

Welcome Page for instructions on how to apply for education benefits, changed button theme and copy edits.
## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [x] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-08-05 21:09 UTC, FernandoBoza reviewed
fixed es lint issues where I added eslint-disable for some imports like address from platform

2021-08-06 15:28 UTC, nathanielbuck commented on src/applications/my-education-benefits/components/EmailViewField.jsx
> +  if (!formData) return 'not working';
This should be returning an empty string or simply returning if a string isn't required.

2021-08-06 18:49 UTC, cesaresantiago requested changes
@FernandoBoza , you seem to have merge conflicts. Please revise.

2021-08-09 14:57 UTC, cesaresantiago approved these changes

2021-08-09 15:33 UTC, merged