29337: Update focus for sandbox elements
department-of-veterans-affairs/vets-website pull request #18425
Opened 2021-08-27 18:58 UTC by elder-joseph

## Description
Focus is not managed when I search for schools, or when I press Compare Institutions and navigate to the Comparison page.

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29337

## Testing done
Testing passes locally with mac screenreader.

## Screenshots
N/A

## Acceptance criteria
- [x] Search Result count is in focus on search
- [x] Institution comparison text is in focus on load

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-08-27 19:09 UTC, shawkey-daniel approved these changes
LGTM

2021-09-07 15:49 UTC, delli-gatti-michael approved these changes

2021-09-07 15:54 UTC, zurbergram requested changes
This only sets focus for Name Search.  
[Location search should also be updated to gain focus on results](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/gi-sandbox/containers/search/LocationSearchResults.jsx#L497)

2021-09-07 16:51 UTC, zurbergram approved these changes

2021-09-07 19:45 UTC, merged