CT Sandbox - caution flags accessibility
department-of-veterans-affairs/vets-website pull request #18551
Opened 2021-09-03 18:47 UTC by dmccurdybah

## Description

## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-09-03 18:56 UTC, timwright12 requested changes

2021-09-03 18:56 UTC, timwright12 commented on src/applications/gi-sandbox/components/CautionFlagAdditionalInfo.jsx
> +              <i
Icon needs `aria-hidden="true"` so it doesn't announce the glyph to screen readers

2021-09-03 18:59 UTC, shawkey-daniel approved these changes
LGTM

2021-09-03 19:34 UTC, timwright12 approved these changes

2021-09-09 14:53 UTC, delli-gatti-michael approved these changes

2021-09-09 14:56 UTC, merged