Updated Facility Locator Feature Flag Values
department-of-veterans-affairs/vets-website pull request #18669
Opened 2021-09-10 19:21 UTC by timwright12

## Description
Right now the frontend isn't consistently using snake_case or camelCase so we're having to return every key twice. This PR syncs up the facilities flags to use snake_case

## Original issue(s)
department-of-veterans-affairs/va.gov-team#12251

2021-09-10 19:53 UTC, alexandec approved these changes

2021-09-10 21:03 UTC, kelsonic approved these changes

2021-09-13 13:55 UTC, mpelzsherman approved these changes

2021-09-13 14:09 UTC, mpelzsherman requested changes
Testing in CI is indicating there might be a problem. I'll pull down the branch and see if I can figure out what's wrong.

2021-09-13 14:50 UTC, mpelzsherman approved these changes
My bad - was flipping the wrong feature! All good here.

2021-09-13 15:10 UTC, merged