added alert role for afghan banner
department-of-veterans-affairs/vets-website pull request #19155
Opened 2021-10-21 20:51 UTC by tmac9494

## Description
added 'alert' role to afghanistan banner

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/31556

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-10-21 21:01 UTC, kelsonic commented on src/platform/site-wide/announcements/components/AfghanistanPromoBanner.jsx
> +    role="alert"
I don't think we need this if the default role prop is `"alert"` if you want to omit it 🙂

2021-10-21 21:01 UTC, kelsonic commented on src/platform/site-wide/announcements/components/AfghanistanPromoBanner.jsx
> +    role="alert"
We will need to bump the package.json version here for the component-library for our PromoBanners to get the new role prop functionality 💯

2021-10-22 12:38 UTC, timwright12 approved these changes

2021-10-22 14:50 UTC, joshkimux requested changes

2022-03-24 00:12 UTC, closed without merging