Copy ContactInformationField to platform
department-of-veterans-affairs/vets-website pull request #19183
Opened 2021-10-22 21:40 UTC by Mottie

## Description

This PR moves `src/applications/personalization/profile/components/personal-information/ContactInformationField.jsx` to the `vap-svc` platform folder. Doing this will allow forms to _inline_-edit contact info (phone, email and address) using standardized code.

## Original issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/31318
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/31700

## Testing done

- Moved and updated the ContactInformationField unit test.
- Manual testing within a form (locally)
    Code used:
    
    ```jsx
    
    import InitializeVAPServiceID from '@@vap-svc/containers/InitializeVAPServiceID';
    import ContactInformationField from '@@vap-svc/components/ContactInformationField';
    import { FIELD_NAMES } from '@@vap-svc/constants';
    
    // ...
    
    <InitializeVAPServiceID>
      <h3>Mobile phone number</h3>
      <ContactInformationField
        fieldName={FIELD_NAMES.MOBILE_PHONE}
        isDeleteDisabled
      />
      <h3>Email address</h3>
      <ContactInformationField
        fieldName={FIELD_NAMES.EMAIL}
        isDeleteDisabled
      />
      <h3>Mailing address</h3>
      <ContactInformationField
        fieldName={FIELD_NAMES.MAILING_ADDRESS}
        isDeleteDisabled
      />
    </InitializeVAPServiceID>
    ```

## Screenshots

<details><summary>Test within our Notice of Disagreement form</summary>

![Screen Shot 2021-10-22 at 4 17 55 PM](https://user-images.githubusercontent.com/136959/138525553-9e3d3bae-8f3b-49dc-aff1-6ce8a5f1d873.png)</details>

## Acceptance criteria
- [x] Centralize field component to allow inline editing of contact information within forms
- [x] All test passing

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-10-23 01:19 UTC, erikphansen commented
Rather than _copy_ the existing files, can you _move_ them? I don't want to have multiple copies of this code floating around, even for, like, a day :-D

2021-10-25 13:26 UTC, timwright12 approved these changes

2021-10-25 14:50 UTC, timwright12 approved these changes

2021-10-25 20:11 UTC, erikphansen requested changes

2021-10-25 21:43 UTC, erikphansen requested changes

2021-10-26 14:35 UTC, erikphansen approved these changes

2021-10-26 14:54 UTC, merged