Rebalance Cypress parallelization on GitHub Actions
department-of-veterans-affairs/vets-website pull request #19348
Opened 2021-11-09 18:02 UTC by ddzz

## Description
This PR 

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32647

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-11-09 19:14 UTC, timwright12 approved these changes

2021-11-09 21:49 UTC, CBonade requested changes
There's a few steps in the `cypress-test-prep` that can also be removed if NUM_CONTAINERS and CI_NODE_INDEX are no longer going to be used. Lines 340-341 and 378-384 I think.

2021-11-09 21:50 UTC, ddzz commented
> There's a few steps in the `cypress-test-prep` that can also be removed if NUM_CONTAINERS and CI_NODE_INDEX are no longer going to be used. Lines 340-341 and 378-384 I think.

Good catch, thanks for reviewing. I'll update this.

2021-11-09 21:56 UTC, holdenhinkle approved these changes
LGTM, once those lines that Curt noted are removed.

2021-11-09 21:58 UTC, CBonade approved these changes

2021-11-10 14:45 UTC, holdenhinkle commented
This looks good.

NIT: If the number of 'containers' is changed from 8 to something else, you'll have to remember to change it in a few places in `.github/workflows/continuous-integration.yml` and once in `script/github-actions/select-cypress-tests.js`. It might be best if you set that number once and reference it everywhere else.

2021-11-10 14:57 UTC, merged