add instructions for phone appointment
department-of-veterans-affairs/vets-website pull request #19449
Opened 2021-11-17 19:08 UTC by jenniemc

## Description
Update the details page for booked phone appointments with phone instructions.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#32580

## Testing done
unit and local test

## Screenshots
![image](https://user-images.githubusercontent.com/54327023/142265791-3bcf5241-9672-47a8-9bd8-0c8eac8a6498.png)

## Acceptance criteria
- [ ] Display phone instructions when it is a phone appointment
- [ ] Bold the the facility name if it is a phone appointment
- [ ] page design matches the design spec [desktop](https://www.sketch.com/s/ccd66412-dd7c-41ba-9528-88892a33af63/a/jgQeA2m)

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-11-17 19:14 UTC, jenniemc commented on src/applications/vaos/appointment-list/redux/actions.js
> +          appointment.location.clinicName = clinic?.serviceName;
While editing this file has no connection to updating phone instructions on the details page, it does eliminate the error message concerning `serviceName` when clicking on a VA clinic appointment.

2021-11-17 19:39 UTC, vbahinwillit approved these changes
LGTM!

2021-11-17 22:01 UTC, vbahinwillit requested changes

2021-11-17 22:01 UTC, vbahinwillit commented on src/applications/vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/PhoneInstructions.jsx
> +  if (!isPhone || isCanceled) {
Good catch! A unit test for this might be a good idea.

2021-11-18 20:30 UTC, vbahinwillit approved these changes
LGTM!

2021-11-18 20:58 UTC, merged

2021-11-19 16:51 UTC, vbahinwillit requested changes
One small comment. There is a change under the 'Page content' section that's missing.

'Choose where you’d like to get your vaccine. (*Required)'