Fetch Claim Status
department-of-veterans-affairs/vets-website pull request #19529
Opened 2021-11-29 18:14 UTC by nathanielbuck

## Description
This adds a repeating call to get claim status. Ultimately it will poll every 5 seconds until a result is given. For testing purposes, it will poll every second for 5 seconds and then return a success message.

2021-11-29 19:14 UTC, timwright12 requested changes

2021-11-29 19:14 UTC, timwright12 commented on src/applications/my-education-benefits/actions/index.js
> +  window.console.log('Start poll...');
@nathanielbuck can we remove console logs?

2021-11-29 19:14 UTC, timwright12 commented on src/applications/my-education-benefits/actions/index.js
> +    window.console.log('- poll');
Same for this console log, we don't want them in production

2021-11-29 19:14 UTC, timwright12 commented on src/applications/my-education-benefits/actions/index.js
> +      window.console.log('Return resolve');
Same for this console log

2021-11-29 19:14 UTC, timwright12 commented on src/applications/my-education-benefits/actions/index.js
> +      window.console.log('pretend success');
Same for this console log

2021-11-29 19:14 UTC, timwright12 commented on src/applications/my-education-benefits/actions/index.js
> +      // window.console.log('Return reject');
Same for this console log even though it's a comment

2021-11-29 19:14 UTC, timwright12 commented on src/applications/my-education-benefits/actions/index.js
> +      window.console.log('Set timeout');
Same for this console log

2021-11-29 19:14 UTC, timwright12 commented on src/applications/my-education-benefits/actions/index.js
> +      window.console.log('dispatch success');
Same for this console log

2021-11-29 19:14 UTC, timwright12 commented on src/applications/my-education-benefits/actions/index.js
> +      window.console.log('dispatch failure');
Same for this console log

2021-11-29 19:14 UTC, timwright12 commented on src/applications/my-education-benefits/containers/ConfirmationPage.jsx
> +// import scrollToTop from 'platform/utilities/ui/scrollToTop';
Can we remove these comments if they're not being used?

2021-11-29 19:14 UTC, timwright12 commented on src/applications/my-education-benefits/containers/ConfirmationPage.jsx
> +  // componentDidMount(() => {
Same for this comment block

2021-11-29 19:14 UTC, timwright12 commented on src/applications/my-education-benefits/containers/ConfirmationPage.jsx
> +                    {moment(response.timestamp).format('MMM D, YYYY')}
Is it possible to use https://date-fns.org/ for this? We're trying to get moment out of the system because it's a deprecated library

2021-11-29 20:40 UTC, timwright12 approved these changes

2021-12-01 15:20 UTC, cesaresantiago approved these changes

2021-12-01 15:20 UTC, merged