#29367 fix: update caution flags layout when none are present
department-of-veterans-affairs/vets-website pull request #19681
Opened 2021-12-14 17:15 UTC by nbarthelemy

## Description

- A change to the comparison tool layout was required to comply with design standards when a school does not have any cautionary warnings

## Original issue(s)
department-of-veterans-affairs/va.gov-team#29367

## Testing done

- Verified locally

## Screenshots

![Screen Shot 2021-12-14 at 11 07 08 AM](https://user-images.githubusercontent.com/3201/146046792-e129cb99-3d1e-435c-b79a-890a3146f927.png)

## Acceptance criteria
- [ ] the display matches the ticket

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2021-12-14 18:20 UTC, timwright12 requested changes

2021-12-14 18:20 UTC, timwright12 commented on src/applications/gi-sandbox/containers/CompareLayout.jsx
> +                      <i className={`fa fa-exclamation-triangle`} />
```suggestion
                      <i aria-hidden="true" className={`fa fa-exclamation-triangle`} />
```

2021-12-14 19:15 UTC, timwright12 commented on src/applications/gi-sandbox/containers/CompareLayout.jsx
> +                      <i className={`fa fa-exclamation-triangle`} />
Hiding the glyph announcement from screenreaders

2021-12-15 16:06 UTC, nbarthelemy commented on src/applications/gi-sandbox/containers/CompareLayout.jsx
> +                      <i className={`fa fa-exclamation-triangle`} />
Done. Good catch. Thank you.

2021-12-15 16:11 UTC, nbarthelemy commented on src/applications/gi-sandbox/containers/CompareLayout.jsx
> +                      <i aria-hidden="true" className={`fa fa-exclamation-triangle`} />
Fixed

2021-12-15 17:29 UTC, timwright12 approved these changes

2021-12-16 20:03 UTC, merged