changing link to point to requested appts when a patient is over the …
department-of-veterans-affairs/vets-website pull request #19820
Opened 2022-01-06 15:02 UTC by ptouchton

…request limit

## Description
This PR is to address when the client has reached the request limit for a clinic. When the client clicks the link to view appointments they are sent to their requested appointments.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#30510

## Testing done
Manual

## Screenshots
![image](https://user-images.githubusercontent.com/3951775/148402428-ca7f3943-cada-4b17-88c8-a433a7c71574.png)
![image](https://user-images.githubusercontent.com/3951775/148402573-2d8959b9-49b3-4c1f-9a3f-f658dfbc105c.png)

-After clicking links

![image](https://user-images.githubusercontent.com/3951775/148403045-9b0215df-236b-4d87-ba7a-6985fe081d92.png)

## Acceptance criteria
- [ ] Given user has reached the request limit
When user clicks "your appointment request" in the request limit alert modal
Then load the appointment request list (/health-care/schedule-view-va-appointments/appointments/requested)

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-01-06 20:14 UTC, jenniemc commented on src/applications/vaos/new-appointment/components/ClinicChoicePage/RequestEligibilityMessage.jsx
> +                Go to <Link to="/requested">your appointment list</Link>
needs a space after the word "list"

2022-01-06 21:22 UTC, jenniemc requested changes
Terrific job! We could use a unit test here to test out the hyperlink.
I think we could expand on an already existing unit test [index.eligibility.unit.spec.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/tests/new-appointment/components/VAFacilityPage/index.eligibility.unit.spec.jsx#L573) to ensure that the hyperlink goes to the request page.

2022-01-06 22:48 UTC, jenniemc commented
@ptouchton  We slowly started using [Gherkin best practice for our unit test](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/testing/fe_testing_guidance.md#gherkin-style-for-unit-test). An excellent example can be found on the [clinic choice unit test page](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/tests/new-appointment/components/ClinicChoicePage.unit.spec.jsx#L184). Give it a try for your test by adding the Given/When/Then comments.

2022-01-07 15:09 UTC, ptouchton commented
@jenniemc  - Thanks for the unit test guidance. That was a great example!

2022-01-07 15:38 UTC, jenniemc approved these changes
Great job!

2022-01-07 15:41 UTC, merged