36190 no debt info
department-of-veterans-affairs/vets-website pull request #20220
Opened 2022-02-14 15:25 UTC by tmitchellgcio

## Description
If there is no debt balance this PR adds text to show their debt balance is $0 and if they have no debt this adds a link for users to click on to learn about VA debt

## Testing done
Added new unit tests and manual testing was done

## Acceptance criteria
- [x] Changes above have been made per mockups
- [x] A PR has been submitted for review

2022-02-14 17:25 UTC, cohnjesse requested changes
@tmitchellgcio can you add a description to this ticket of what it is for and some background on why the changes are needed? Please add this to all tickets moving forward as well.

2022-02-14 17:46 UTC, tmitchellgcio commented
> @tmitchellgcio can you add a description to this ticket of what it is for and some background on why the changes are needed? Please add this to all tickets moving forward as well.

Usually I attach the ticket, which I forgot to do this time. Literally the first time I've forgotten in months, but are you saying to add a description even if it's in the ticket? The ticket should explain all of that and I've rarely needed to add descriptions to the tickets.

2022-02-14 20:24 UTC, cohnjesse commented
@tmitchellgcio No worries, yes even if you attach the ticket please add all of the details in the template that gets created when you create a ticket ( a description,  the testing that was done, screenshots if applicable, acceptance criteria ). Having the original ticket attached is great, and you should do that, however tickets are often lacking in details and we should strive to make each PR so that an engineer can just look at the PR and get all of the information they need.

2022-02-14 20:38 UTC, tmitchellgcio commented
@cohnjesse no problem. Updated and will do this more in the future

2022-02-15 15:54 UTC, adamwhitlock1 approved these changes
LGTM overall. 

There are a couple linting warning for prop validation and an inline arrow function that you may want to clean up as time permits, but certainly not blocking.

2022-02-15 20:40 UTC, tmitchellgcio commented
I'm going to fix some of this linting stuff before I merge this. I also can't merge without @cohnjesse for his requested changes.

2022-02-15 21:04 UTC, hdjustice commented
Hi @cohnjesse Is there anything else we need on this one?  Thanks!

2022-02-15 22:06 UTC, cohnjesse commented
@hdjustice @tmitchellgcio I would love to see the original ticket linked on this as well as acceptance criteria there is for the PR. I also think you can get rid of the definition of done portion in the ticket. For future reference [here](https://github.com/department-of-veterans-affairs/vets-website/pull/19538) is a good reference of the level of detail/ what to put into each PR description at a minimum.

2022-02-15 22:25 UTC, tmitchellgcio commented
@cohnjesse The ticket is linked and has been since yesterday

2022-02-15 22:27 UTC, tmitchellgcio commented
@cohnjesse you don't need to put the ticket in the description. You can connect your ticket with the connect issue button. That's how it's connected here.

2022-02-15 22:33 UTC, tmitchellgcio commented
@cohnjesse completed. Anything else you need before you look at the PR?

2022-02-16 17:59 UTC, cohnjesse approved these changes
LGTM

2022-02-16 18:19 UTC, tlei123 approved these changes
Other than the issues flagged by the linter and me [for the code-comments], LGTM.

2022-02-16 18:19 UTC, tlei123 commented on src/applications/personalization/dashboard/tests/e2e/benefit-payments-and-debt.cypress.spec.js
> +        // make sure that the Payment and Debt section is shown
Looks like the code-comment here should say "is not shown". The subsequent assertions are 'not.exist'.

2022-02-16 18:23 UTC, tmitchellgcio commented on src/applications/personalization/dashboard/tests/e2e/benefit-payments-and-debt.cypress.spec.js
> +        // make sure that the Payment and Debt section is shown
I'd rather it be done right. I will change that sorry I should have paid attention there

2022-02-16 19:10 UTC, merged