Unused CSS Removal v4
department-of-veterans-affairs/vets-website pull request #20242
Opened 2022-02-15 21:10 UTC by jhonnyoddball

## Description
Removing unused CSS classes based on [audit](https://docs.google.com/document/d/1WfMzLFpIZwe35hrmhXl2-ii2DjWaik352vHWfp3RJ7Q/edit#) 

## Original issue(s)
department-of-veterans-affairs/va.gov-team#35384

## Testing done

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-03-03 16:08 UTC, ndsprinkle approved these changes

2022-03-03 16:40 UTC, timwright12 commented
@jhonnyoddball where are the test results? Can you drop something in the description?

2022-03-03 16:45 UTC, timwright12 requested changes
need test result data

2022-03-04 14:46 UTC, jhonnyoddball commented
@timwright12 Documentation was added. Please review

2022-03-04 21:49 UTC, timwright12 approved these changes

2022-03-07 16:24 UTC, merged