handle utc date conversion correctly
department-of-veterans-affairs/vets-website pull request #20297
Opened 2022-02-22 17:11 UTC by ptouchton

## Description

## Original issue(s)
department-of-veterans-affairs/va.gov-team#36488

## Testing done
Manual and unit

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-02-22 20:22 UTC, vbahinwillit requested changes
The following unit test is failing consistently for me:

      AssertionError: expected body to contain 'Thu, February 24, 2022 in the afternoon', but the text was 'HomeHealth careSchedule and manage health appointmentsVA online schedulingRequest detailPending primary care appointmentThe time and date of this appointment are still to be determined.VA appointmentCheyenne VA Medical Center2360 East Pershing BoulevardCheyenne, WyomingWY 82001-5356DirectionsMain phone: 307-778-7550TTY: 711Preferred type of appointmentOffice visitPreferred date and timeFri, February 25, 2022 in the afternoonSat, February 26, 2022 in the afternoonYou shared these details about your concernNew issue: A message from the patientYour contact detailsEmail: veteranemailtest@va.govPhone number: 212-555-12122 1 2. 5 5 5. 1 2 1 2.Call morningCancel Request'
      + expected - actual

      -HomeHealth careSchedule and manage health appointmentsVA online schedulingRequest detailPending primary care appointmentThe time and date of this appointment are still to be determined.VA appointmentCheyenne VA Medical Center2360 East Pershing BoulevardCheyenne, WyomingWY 82001-5356DirectionsMain phone: 307-778-7550TTY: 711Preferred type of appointmentOffice visitPreferred date and timeFri, February 25, 2022 in the afternoonSat, February 26, 2022 in the afternoonYou shared these details about your concernNew issue: A message from the patientYour contact detailsEmail: veteranemailtest@va.govPhone number: 212-555-12122 1 2. 5 5 5. 1 2 1 2.Call morningCancel Request
      +Thu, February 24, 2022 in the afternoon
      
      at _callee10$ (src/applications/vaos/tests/appointment-list/components/RequestedAppointmentDetailsPage.unit.spec.jsx:726:43)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:119:21)
      at asyncGeneratorStep (src/applications/vaos/tests/appointment-list/components/RequestedAppointmentDetailsPage.unit.spec.jsx:39:103)
      at _next (src/applications/vaos/tests/appointment-list/components/RequestedAppointmentDetailsPage.unit.spec.jsx:41:194)

2022-02-23 14:52 UTC, ptouchton commented
@vbahinwillit - That test that is failing for you is one I didn't touch. Would you mind running it in the master branch and see if you get the same result?

2022-02-25 14:00 UTC, jenniemc approved these changes
LGTM!

2022-03-01 20:27 UTC, vbahinwillit commented
Got the following error when running the unit test:

```
 -HomeHealth careSchedule and manage health appointmentsVA online schedulingRequest detailPending primary care appointmentThe time and date of this appointment are still to be determined.VA appointmentCheyenne VA Medical Center2360 East Pershing BoulevardCheyenne, WyomingWY 82001-5356DirectionsMain phone: 307-778-7550TTY: 711Preferred type of appointmentOffice visitPreferred date and timeFri, March 4, 2022 in the afternoonSat, March 5, 2022 in the afternoonYou shared these details about your concernNew issue: A message from the patientYour contact detailsEmail: veteranemailtest@va.govPhone number: 212-555-12122 1 2. 5 5 5. 1 2 1 2.Call morningCancel Request
      +Thu, March 3, 2022 in the afternoon
      
      at _callee10$ (src/applications/vaos/tests/appointment-list/components/RequestedAppointmentDetailsPage.unit.spec.jsx:726:43)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:119:21)
      at asyncGeneratorStep (src/applications/vaos/tests/appointment-list/components/RequestedAppointmentDetailsPage.unit.spec.jsx:39:103)
      at _next (src/applications/vaos/tests/appointment-list/components/RequestedAppointmentDetailsPage.unit.spec.jsx:41:194)
```

2022-03-03 20:24 UTC, vbahinwillit approved these changes

2022-03-04 14:57 UTC, ptouchton commented on src/applications/vaos/tests/appointment-list/components/RequestedAppointmentDetailsPage.unit.spec.jsx
> +      ).format('ddd, MMMM D, YYYY')} in the afternoon`,
Tony, I'm thinking there are still some issues with the version of code you have locally. In the latest commit these are the lines for that span


![image](https://user-images.githubusercontent.com/3951775/156786121-ce6a698a-580c-4bea-87db-d05e0b986c80.png)

2022-03-04 14:57 UTC, merged