VACMS-7878: Offices - Search filter input
department-of-veterans-affairs/vets-website pull request #20491
Opened 2022-03-10 22:07 UTC by allisonlu

## Description
- Created a SearchFilter component (a text input field that acts as a filter as user is typing their keyword). 
- Created an OfficeList component so it's separate from the main App file
- Added Back to Top component

## Original issue(s)
department-of-veterans-affairs/va.gov-team#7878

## Testing done
Local testing done, see demo below:
https://www.loom.com/share/7aeb9313d85d41888aa65b3228478dcd

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-03-10 23:45 UTC, ryguyk approved these changes
I left just a couple comments.  I wonder if  `<h1>` is the right element for "No results", but I think we'll iron out this type of concern before we launch.

2022-03-10 23:45 UTC, ryguyk commented on src/applications/office-directory/components/OfficeList.jsx
> +  return <h1>No results found!</h1>;
Should this be `<h1>`?

2022-03-10 23:45 UTC, ryguyk commented on src/applications/office-directory/containers/App.jsx
> +      {/* <input
This commented code can be removed. I hope to never see this code of mine back in here!

2022-03-11 00:25 UTC, allisonlu commented on src/applications/office-directory/components/OfficeList.jsx
> +  return <h1>No results found!</h1>;
Oof, thanks for catching that!

2022-03-11 00:41 UTC, theodur approved these changes

2022-03-11 13:13 UTC, timwright12 requested changes

2022-03-11 13:13 UTC, timwright12 commented on src/applications/office-directory/components/SearchFilter.jsx
> +        <input
Missing ID `query` to pair with the `htmlFor` attribute in the label

2022-03-11 18:32 UTC, timwright12 approved these changes

2022-03-11 21:59 UTC, merged