Feature/education inbox update UI
department-of-veterans-affairs/vets-website pull request #20697
Opened 2022-03-30 20:28 UTC by FernandoBoza

## Description

**Updates the Education Inbox to now Education Letters app name and path.**

**Updates for education/education-letters**
If user is visitor or logged in. If not logged in remain in page, else redirect to education/education-letters/preview

**Updates for education/education-letters/preview**
The user letters status page where users can either have a letter OR no letter. 
If a user can download a letter, they'll have the choice to download via a download button.

## Original issue(s)
[20229](https://github.com/department-of-veterans-affairs/vets-website/pull/20229)

## Testing done
- [ ] In progress

## Definition of done
- [X] Logged in users can see status of letters via a download  page or no letters page.
- [X] Non logged in users  text and copy for intro page has been updated

2022-03-30 20:52 UTC, timwright12 requested changes, later dismissed

2022-03-30 20:52 UTC, timwright12 commented on src/applications/education-letters/containers/App.jsx
> +        <div style={{ marginTop: '3rem', marginBottom: '6.4rem' }}>
Can we use the design system utilities for this? https://design.va.gov/utilities/margins

2022-03-30 20:52 UTC, timwright12 commented on src/applications/education-letters/containers/InboxPage.jsx
> +        <h3 style={{ marginTop: '1rem' }}>Education decision letter</h3>
Can we use design system utilities for this? https://design.va.gov/utilities/margins

2022-03-30 20:52 UTC, timwright12 commented on src/applications/education-letters/containers/InboxPage.jsx
> +            <i className="fa fa-download vads-u-display--inline-block vads-u-margin-right--1" />
```suggestion
            <i className="fa fa-download vads-u-display--inline-block vads-u-margin-right--1" aria-hidden="true" />
```

2022-03-31 15:32 UTC, nathanielbuck approved these changes

2022-03-31 18:50 UTC, theodur reviewed
I would also recommend updating the [changed-apps-build](https://github.com/department-of-veterans-affairs/vets-website/blob/master/config/changed-apps-build.json#L21) config to use the new entry name

2022-03-31 19:50 UTC, theodur approved these changes

2022-04-13 18:07 UTC, zeki-yaren commented
Testing is still in progress

2022-04-15 15:10 UTC, merged