updated the Modal web component in the vaos Application
department-of-veterans-affairs/vets-website pull request #20775
Opened 2022-04-12 05:54 UTC by simiadebowale

## Description
Platform Design System team built a Modal web component. This PR replaces the existing Modal component with the updated Modal web component.

## Original issue(s)
[department-of-veterans-affairs/va.gov-team#38608](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/38608)

## Testing done
updated unit tests

## Screenshots

## Acceptance criteria
- Modal component is updated across vaos application and functioning as expected.

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-04-12 15:55 UTC, vbahinwillit commented on src/applications/vaos/appointment-list/components/cancel/CancelCOVIDVaccineModal.jsx
> +      modalTitle="You need to call your VA medical center to cancel this appointment"
Add role.

2022-04-12 16:06 UTC, vbahinwillit commented
LGTM. Just a couple of general items. I would add the role to all of the modals and fix the 'quickfix' eslint errors. We've been fixing all eslint errors whenever we touch files since the platform turned on additional rules.

2022-04-12 17:12 UTC, jenniemc commented on src/applications/vaos/appointment-list/components/cancel/CancelAppointmentFailedModal.jsx
>  }
You can add propTypes to get rid of the linting warnings just like you would find in `CancelAppointmentConfirmationModal.jsx`

2022-04-12 18:25 UTC, jenniemc requested changes
Hi Simi, looks pretty good. Added some suggestions to fix linting warnings and adding attributes to the VAModal component.

2022-04-18 14:26 UTC, jenniemc approved these changes
LGTM!

2022-04-18 18:36 UTC, merged