38606 Redirect to static landing page 3
department-of-veterans-affairs/vets-website pull request #20815
Opened 2022-04-18 17:49 UTC by vbahinwillit

add redirect flag
add default route to VAOS static page

## Description
This PR redirects the user to the VAOS home on initial login, direct entry to /health-care/schedule-view-va-appointments/appointments/, and direct entry to /health-care/schedule-view-va-appointments/appointments/ for other pages.

**NOTE**: The login use case can only be tested from the development instance or staging. I am not sure how to test direct entry from other pages since I don't know if any other pages access the VAOS application directly. So, I am trusting that the changes to the manifest.json file will suffice.

## Original issue(s)
department-of-veterans-affairs/va.gov-team#38606

## Testing done
Unit and e2e testing

## Screenshots
N/A

## Acceptance criteria
- [ ] All test should pass

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-04-20 17:22 UTC, alexandec approved these changes

2022-04-20 20:30 UTC, jenniemc requested changes
Looks good but with one odd behavior. 
When using the review instance to append `appointments` to the end of the new rootURL in the browser address bar, it gets stuck in an endless loop just as we saw in the demo. But if a slash is added `appointments/` then it works as expected.

2022-04-21 12:47 UTC, vbahinwillit commented
> 

Yes. I did look into this behavior and I not sure if it has something to do with the review instance or not.

2022-04-21 13:31 UTC, jenniemc approved these changes
Hopefully it's just the review instance.

2022-04-21 15:41 UTC, merged