VAVFA-8986: Add facility expandable alert component.
department-of-veterans-affairs/vets-website pull request #21037
Opened 2022-05-11 01:27 UTC by ethanteague

## Description
Adds expandable alert for facility covid status usage

## Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8986

## Testing done
Visaul / eslint

## Screenshots
![image](https://user-images.githubusercontent.com/2404547/167750435-05140de0-f02a-42bf-be10-6199d94b449d.png)

![image](https://user-images.githubusercontent.com/2404547/167750457-09cff345-b8c3-44ba-9ee7-155074e37469.png)

## Acceptance criteria
- [ ] TBD

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-05-11 03:51 UTC, bkjohnson requested changes
I think we should hold off on this - [`<va-alert-expandable>`](https://design.va.gov/storybook/?path=/docs/components-va-alert-expandable--default)  will be published in the next few days.

2022-05-11 15:26 UTC, ethanteague commented
> I think we should hold off on this - [`<va-alert-expandable>`](https://design.va.gov/storybook/?path=/docs/components-va-alert-expandable--default) will be published in the next few days.
Not sure that we can, @bkjohnson - we need to release VAMC covid status alerts this week. Kind of a 911 situation. Looping in @kevwalsh @swirtSJW @maxx1128 @davidconlon @mmiddaugh @cjterdi for situational awareness.

2022-05-11 15:27 UTC, it-harrison approved these changes

2022-05-11 15:56 UTC, swirtSJW commented
This was just put on hold for a week due to people ops reasons.    Also converting this to draft because it will break things since the field is not on prod.

2022-05-11 22:12 UTC, swirtSJW requested changes, later dismissed
Mainly stuff we talked about on the call... and a little bit more pondering on naming. to make it either about supplemental status OR better yet alert expandable (generic)

2022-05-11 22:12 UTC, swirtSJW commented on src/applications/static-pages/facilities/buildVamcOperatingStatusProps.js
> +    case 'limited':
Should map to cases of the field_status_id to the values identified in the storybook component.   That way it is not specific to operating statuses which are not related.

2022-05-11 22:12 UTC, swirtSJW commented on src/applications/static-pages/facilities/buildVamcOperatingStatusProps.js
> +export const buildVamcOperatingStatusProps = attrs => {
Naming on this is confusing.  It is not VamcOperatingstatus.     If anything it is supplemental status. ... but going even bigger it is alert expandable

2022-05-11 22:12 UTC, swirtSJW commented on src/applications/static-pages/facilities/ExpandableVamcOperatingStatus.jsx
> +import React, { useState } from 'react';
filename and location seems misnamed.    THis is supplemental status not operating status and going one level up it is really the pattern for alert expandabile.

2022-05-11 22:12 UTC, swirtSJW commented on src/applications/static-pages/facilities/ExpandableVamcOperatingStatus.jsx
> +    <div className="expandable-vamc-operating-status">
Can we go more genateric? alert expandible   from storybook?

2022-05-11 22:12 UTC, swirtSJW commented on src/applications/static-pages/facilities/ExpandableVamcOperatingStatus.jsx
> +        className={`collapsible ${props.operatingStatusFacility}`}
supplemental status or more generic as alert expandable?

2022-05-11 22:12 UTC, swirtSJW commented on src/applications/static-pages/facilities/ExpandableVamcOperatingStatus.jsx
> +        className={`content ${props.operatingStatusFacility} ${
Can we make it less facility and status specific?

2022-05-11 22:12 UTC, swirtSJW commented on src/applications/static-pages/facilities/ExpandableVamcOperatingStatus.jsx
> +ExpandableVamcOperatingStatus.propTypes = {
supplemental status or alert expandable?

2022-05-11 22:12 UTC, swirtSJW commented on src/applications/static-pages/facilities/ExpandableVamcOperatingStatus.jsx
> +export default ExpandableVamcOperatingStatus;
naming?

2022-05-11 22:12 UTC, swirtSJW commented on src/applications/static-pages/facilities/buildVamcOperatingStatusProps.js
> +    operatingStatusFacility: opStatus,
less specific more like heading and body?

2022-05-11 22:12 UTC, swirtSJW commented on src/applications/static-pages/facilities/createExpandableVamcOperatingStatus.jsx
> +import { buildVamcOperatingStatusProps } from './buildVamcOperatingStatusProps';
Same questions about generizizing the names used.

2022-05-12 13:56 UTC, swirtSJW commented
> I think we should hold off on this - [`<va-alert-expandable>`](https://design.va.gov/storybook/?path=/docs/components-va-alert-expandable--default) will be published in the next few days.

Thanks for raising this.   We are under a tight deadline for the getting this out to coincide with a VAMC  operations rollout timing that goes well beyond the website..    @ethanteague  and @maxx1128  are going to rework this to become that component.   Yes the implementation may happen before the design component is official, but we can rework this if needed to align with the official design when it happens.   Any guidance you can give along the way is much appreciated, but for timing the rework of this that is inbound within hours, needs to go out preferably today 5/12 or at the latests tomorrow.


This component is going to be moved to src/platform/site-wide/alerts/components and renamed.

2022-05-12 23:14 UTC, bkjohnson approved these changes
I'm not seeing the option to dismiss my review, but I'm approving so that I'm not blocking whatever feature flag changes need to happen.

2022-05-17 14:53 UTC, maxx1128 commented on src/applications/facility-locator/components/search-results-items/common/LocationCovidStatus.jsx
> +/* eslint-disable jsx-a11y/no-noninteractive-tabindex */
Like `LocationOperationStatus.jsx`, this is disabled so the label can have a `tabIndex` value and be more accessible to keyboard users.

2022-05-17 18:42 UTC, swirtSJW approved these changes
Code and screencaps look good.

2022-05-17 20:52 UTC, merged