8870 added health connect number to facility locator search results. …
department-of-veterans-affairs/vets-website pull request #21212
Opened 2022-05-27 19:39 UTC by jtmst

…removed hard coded data

## Description

## Original issue(s)
department-of-veterans-affairs/va.gov-team#8870

## Testing done
Tested with mocked api response, not yet tested with sandbox data

## Screenshots
![image](https://user-images.githubusercontent.com/61624970/170778446-92b6f887-a7c7-4074-a040-ce93d7f58682.png)

## Acceptance criteria
- [ ] Front end will add logic to display value for VA health connect when populated
- [ ] Front end to remove hard coded values for VISN 8, 2 and 17

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-05-27 21:18 UTC, kind-claudio requested changes

2022-05-27 21:18 UTC, kind-claudio commented on src/applications/facility-locator/components/ResultsList.jsx
> +      return final;
This early return isn't doing much - the return on line 62 has to be there, so I'd suggest just leaning on that one & avoid the extra line of code here.

2022-06-01 15:52 UTC, maxx1128 requested changes
I found a couple small things, otherwise this checks out for me.

2022-06-03 13:15 UTC, maxx1128 approved these changes

2022-06-06 17:09 UTC, kind-claudio approved these changes

2022-06-07 18:06 UTC, swirtSJW approved these changes
Confirmed that this works on the deployed test environment

![image](https://user-images.githubusercontent.com/5752113/172452012-58957c65-7784-4ba8-b7e8-5077a5578465.png)


In the process we confirmed that facility locator in PR environment is indeed using sandbox.api.va.gov AND its data is out of date.   Status changes show immediately.   Health connect phone numbers are delayed up to 24 hrs after push from CMS.

2022-06-07 18:06 UTC, merged