Benefit selection page
department-of-veterans-affairs/vets-website pull request #21394
Opened 2022-06-17 13:17 UTC by s-caso

## Description
Initial UI for FRY/DEA benefit selection page

## Original issue(s)
department-of-veterans-affairs/va.gov-team#0000

## Testing done

## Screenshots
<img width="355" alt="Screen Shot 2022-06-17 at 9 16 35 AM" src="https://user-images.githubusercontent.com/94458706/174305741-53704332-d3a2-4909-ba7b-52739b2f2fea.png">

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-06-17 14:32 UTC, nathanielbuck requested changes

2022-06-17 14:33 UTC, nathanielbuck commented
Sebastian and I discussed this PR. Form validation and the display/functionality on the Review page need to be taken into consideration with this implementation, so more changes are needed.

2022-06-17 19:10 UTC, nathanielbuck commented on src/applications/fry-dea/sass/fry-dea.scss
> +// Benefit Selection Page
For anyone else looking As the author of the changes below, I'm not thrilled about having to do this, but it's a lot simper than having to implement the Input Message component (https://design.va.gov/components/form/input-message) by ourselves at the moment.

2022-06-21 16:25 UTC, alexandec approved these changes

2022-06-21 17:48 UTC, nathanielbuck approved these changes

2022-06-21 17:51 UTC, merged