47728 VA Request Flow - Best Times to Contact (Acheron)
department-of-veterans-affairs/vets-website pull request #22434
Opened 2022-10-17 22:21 UTC by vbahinwillit

## Description
This PR hides best time to call information when acheron is on

## Original issue(s)
fixes department-of-veterans-affairs/va.gov-team#47728

## Testing done
Unit testing

## Screenshots

## Acceptance criteria
- [ ] All test past

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-10-19 15:47 UTC, jenniemc requested changes
Are we suppose to remove the Best Time to Call question from the VA Request flow and Community Care request flow? The AC is for VA Request but the enhancement is also removing the question from the Community Care flow. 

Looks like the review page shows best time to call info even though none is entered.

2022-10-19 22:30 UTC, vbahinwillit commented
> 

Verified with Peter that changes should be for VA appointment requests only.

2022-10-19 22:35 UTC, vbahinwillit commented on src/applications/vaos/new-appointment/components/ReviewPage/ReviewDirectScheduleInfo.jsx
> -      <ContactDetailSection data={data} flowType={FLOW_TYPES.DIRECT} />
Removed 'flowType' prop to match other calls to the component that don't pass 'flowType'. The information can be retrieved via useSelector hook.

2022-10-19 22:41 UTC, vbahinwillit commented on src/applications/vaos/new-appointment/components/ContactInfoPage.jsx
> +        },
Hide best time to call checkboxes for both direct and request flows when acheron flag is true.

2022-10-20 18:49 UTC, jenniemc approved these changes
LGTM! And I was able to see the changes in the review instance!

2022-10-21 14:06 UTC, merged