Feature/meb update help section
department-of-veterans-affairs/vets-website pull request #22504
Opened 2022-10-26 16:38 UTC by FernandoBoza

## Description
Wired in Redux to fetch MEB4.0 feature flag and updated GetHelp component logic and text with va telephone components.

## Testing done
- [ ] Done

2022-10-26 17:09 UTC, bradbergeron-us approved these changes

2022-10-26 17:10 UTC, bradbergeron-us commented
Are we sure we want to merge this into Main though and not feature/meb-4.0?

2022-10-27 14:30 UTC, nathanielbuck commented
@FernandoBoza, this PR should be against the MEB 4.0 branch.

2022-10-27 18:40 UTC, nathanielbuck approved these changes

2022-10-28 19:11 UTC, nathanielbuck approved these changes

2022-10-28 19:13 UTC, nathanielbuck requested changes

2022-10-28 19:13 UTC, nathanielbuck commented on src/applications/my-education-benefits/components/GetFormHelp.jsx
> +          <va-telephone contact="8006982411" extension="711" />. We're here
Hey, I'm pretty sure that this doesn't work the way you're expecting. 711 will be dialed after the initial phone number.

2022-10-28 19:19 UTC, nathanielbuck approved these changes

2022-10-28 20:14 UTC, merged