Add back to todays appointments and tests
department-of-veterans-affairs/vets-website pull request #22544
Opened 2022-10-31 15:08 UTC by wullaski

## Description

Re adds the back to appointments button and associate tests. The button should only show up when there are more than one appointments for the day. Modifies e2e tests to test both scenarios.

## Original issue(s)
[department-of-veterans-affairs/va.gov-team#47443](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47443)

## Testing done

Visual 
E2E

## Acceptance criteria
- [ ] Link shows up with correct wording
- [ ] Link doesn't show up with only one appointment

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-10-31 15:45 UTC, wullaski commented
I'm ignoring linting warnings until there is a fix for the commit hook that is preventing the recommended change.

2022-10-31 20:15 UTC, brianseek commented on src/applications/check-in/day-of/pages/Confirmation/CheckInConfirmation.jsx
> +          <BackToAppointments appointments={appointments} />
we are passing an appointments prop here but not doing anything with it or acknowledging it at all in the BackToAppointments component. We should be able to remove the prop here.

2022-10-31 20:16 UTC, brianseek requested changes
This is looking good! One small change.

2022-11-02 21:26 UTC, brianseek approved these changes
Looks good, I added some comments, mostly nitpicks. Also there are some linting flags around including axeChecks in the cypress tests. It would be good just to go ahead and add them even though these things are getting axeChecked elsewhere

2022-11-02 21:26 UTC, brianseek commented on src/applications/check-in/locales/es/translation.json
> +  "back-to-todays-appointments": "Ir a otra cita",
I would make sure that this gets into the translation doc, since it won't come up in the empty keys audit.

2022-11-02 21:26 UTC, brianseek commented on src/applications/check-in/day-of/tests/e2e/confirmation-display/confirmation.display.cypress.spec.js
> +      { startTime: '2021-08-19T03:30:00' },
The only thing a little confusing about this is the startTime, are these times getting overwritten in the createAppointment function? I don't see them getting passed into the function. It is kind of weird to define these appointments in the past If it is just to define the number of appointments. Maybe doing something like { eligibility: 'ELIGIBLE' } would make more sense when reading it.

2022-11-02 21:57 UTC, brianseek commented on src/applications/check-in/day-of/tests/e2e/confirmation-display/confirmation.display.cypress.spec.js
> +      { startTime: '2021-08-19T03:30:00' },
Ah, I see that the Object.assign gives precedent to the source. So this makes it so each appointment doesn't have the same startTime. Still kind of weird, but maybe out of the scope of this ticket to fix.

2022-11-03 15:24 UTC, merged