[DLD] Use descriptionType for letter subtext
department-of-veterans-affairs/vets-website pull request #22638
Opened 2022-11-09 18:51 UTC by jerekshoe

## Description
* Using the `descriptionType` attribute to display letter subtext
* Also implemented a few accessibility fixes, namely:
    * Use `ol` and `li` tags for ordered list
    * Headings should be `h2`'s styled as `h4`'s, instead of `h4`'s

## Original issue(s)
department-of-veterans-affairs/va.gov-team#49359

## Screenshots

## Acceptance criteria
- [ ] Letter subtext uses `descriptionType` instead of `subject`

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-11-09 19:09 UTC, Mottie approved these changes

2022-11-09 20:32 UTC, jaredcunha commented on src/applications/claims-status/components/ClaimLetterList.jsx
> +  <ol className="vads-u-margin--0 vads-u-padding--0">
Minor suggestion here…
- Add "usa-unstyled-list" to the className.
- Remove `vads-u-display--block` from [this line](https://github.com/department-of-veterans-affairs/vets-website/pull/22638/files#diff-b58c5b99ec670a67b0a3fbe23d63937a6264379c9a864a7a91088eefac3252d6R17)
- Add `role="list"`. ESLint will complain about redundant roles, so you might need to ignore it. Basically, this is a bug with VoiceOver+Safari where list semantics get ignored with either `list-style: none` or changing display properties of list items, though some might say feature, that list semantics get ignored. 

Adding the `role` attribute will fix a bug that definitely exists in Safari. Updating the class names makes their design intent a little easier to grok.

2022-11-10 17:45 UTC, jaredcunha requested changes
`role="list"` should go on the `<ol>`, not the `<li>`.

2022-11-10 18:33 UTC, jaredcunha approved these changes

2022-11-10 18:43 UTC, merged