47132 vaos va link/confirmed appointment detail page
department-of-veterans-affairs/vets-website pull request #22775
Opened 2022-11-28 16:16 UTC by ryanshaw

## Description
This is one of several PRs that replace the react-router `Link` component in VAOS with the newer `va-link` web component.

[va-link](https://design.va.gov/components/link/)
[va-link storybook](https://design.va.gov/storybook/?path=/docs/components-va-link--default)

This was broken up into multiple PR's to allow for easier code review as this change impacts nearly every file and every test within VAOS.

## Original issue(s)
[department-of-veterans-affairs/va.gov-team/issues/47132](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47132)

## Related to these other PR's:
- [requested appointments](https://github.com/department-of-veterans-affairs/vets-website/pull/22776)
- [breadcrumbs](https://github.com/department-of-veterans-affairs/vets-website/pull/22779)
- [covid flow](https://github.com/department-of-veterans-affairs/vets-website/pull/22818)
- [new appointment](https://github.com/department-of-veterans-affairs/vets-website/pull/23125)
- [appointment list](https://github.com/department-of-veterans-affairs/vets-website/pull/23128)

## Testing done
- Unit testing
- e2e testing

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2022-12-06 15:44 UTC, jenniemc commented on src/applications/vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/StatusAlert.jsx
> +            href="/"
This link is going to the wrong path. I think "/" was enrolled in a special routes file. @vbahinwillit may have the background on it.

2022-12-06 15:46 UTC, jenniemc commented on src/applications/vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/StatusAlert.jsx
> +            href="/new-appointment"
This link is going to the wrong path. "/new-appointment" was enrolled in a special routes file. I don't know how it works but @vbahinwillit may have the background on it.

2022-12-07 14:09 UTC, jenniemc requested changes
Looks like the links on the status alert page are also experiencing the same wrong path.

2022-12-07 16:05 UTC, vbahinwillit approved these changes
LGTM!

2023-01-12 03:46 UTC, ryanshaw commented
> Looks like the links on the status alert page are also experiencing the same wrong path.

@jenniemc I changed this to use the va-link component with the React bindings to handle the onclick event.

2023-01-13 17:40 UTC, closed without merging