Vbahinwillit/issue45823-v2
department-of-veterans-affairs/vets-website pull request #23083
Opened 2023-01-09 03:04 UTC by vbahinwillit

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- *(Summarize the changes that have been made to the platform)*
- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution)*
- *(Which team do you work for, does your team own the maintainence of this component?)*
- *(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)*

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#0000
- *Link to ticket created in va.gov-team repo*
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected*
- *Describe the tests completed and the results*

## Screenshots
_Note: This field is mandatory for component work and UI changes (non-component work should NOT have screenshots)._

| | Before | After |
| --- | --- | --- |
| Mobile | | |
| Desktop | | |

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-01-11 23:41 UTC, jenniemc requested changes
For this iteration, I only reviewed the files supporting `UpcomingAppointmentLayout` component. So far it's looking real good in the desktop and mobile small-screen version. I included some suggestions for accessibility.

You may want to check out the text alignment on the print version.
<img width="561" alt="Screenshot 2023-01-11 at 3 08 13 PM" src="https://user-images.githubusercontent.com/54327023/211941250-179edcd4-e50d-48e5-903f-1396ed96c2f2.png">

2023-01-26 15:30 UTC, rmessina1010 approved these changes
LGTM

2023-02-08 00:07 UTC, vbahinwillit commented on src/applications/vaos/appointment-list/models/AppointmentModel.js
> +  getAppointmentDetails() {
Thanks for the suggestiong. Changed to 'getAppointmentLocality'.

2023-02-08 17:42 UTC, vbahinwillit commented on src/applications/vaos/appointment-list/components/AppointmentsPageV2/AppointmentColumnLayout.jsx
> +              <span className="sr-only"> {model.getTimeZoneAbbr()}</span>
Thanks for the suggestion. I will look into what Voice Over announces when we start 508 testing. The announcement of timezone was in the original code though.

2023-02-14 15:51 UTC, jenniemc approved these changes
LGTM!!

2023-02-14 17:41 UTC, merged