51570 remove v0 eligibility call for v2
department-of-veterans-affairs/vets-website pull request #23104
Opened 2023-01-11 17:36 UTC by simiadebowale

This PR removes the errant v0 cc eligibility call we were seeing in v2 and replaces that call with the required v2 cc eligibility check.

2023-01-17 21:38 UTC, vbahinwillit approved these changes

2023-01-17 23:53 UTC, jenniemc requested changes
Using nacier.y.stowe@id.me who is ineligible for community care, the review instance shows the page "Choose where you want to receive your care" where user can choose between VA Facility or Community Care for Audiology care.

In staging the same test user is routed to "Choose a VA location"  and not given the option for community care.

Here is the [sqa website](https://wiki.mobilehealth.va.gov/pages/viewpage.action?pageId=89728236#VAOSAWSSTAGING(SQA)TESTDATASETUP-TESTPATIENTSLOGINSANDCCELIGIBILITY) that shows test users and their eligibility status.

2023-01-18 16:26 UTC, simiadebowale commented
@jenniemc - Hey, I tested with that user (nacier.y.stowe@id.me). I'm getting the same behavior for this user in staging and in the RI

2023-01-18 17:41 UTC, jenniemc commented
> @jenniemc - Hey, I tested with that user ([nacier.y.stowe@id.me](mailto:nacier.y.stowe@id.me)). I'm getting the same behavior for this user in staging and in the RI

@simiadebowale Are you selecting a speciality care? I was using Audiology. Other speciality cares to use are: optometry, foodAndNutrition. Just don't use Podiatry for this test.

2023-01-18 18:05 UTC, closed without merging