updates retryOn fn + adds unit tests
department-of-veterans-affairs/vets-website pull request #23263
Opened 2023-01-31 19:44 UTC by asg5704

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- *(Summarize the changes that have been made to the platform)*
- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution)*
- *(Which team do you work for, does your team own the maintenance of this component?)*
- *(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)*

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#0000
- *Link to ticket created in va.gov-team repo*
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected*
- *Describe the tests completed and the results*
- *Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)*

## Screenshots
_Note: This field is mandatory for component work and UI changes (non-component work should NOT have screenshots)._

| | Before | After |
| --- | --- | --- |
| Mobile | | |
| Desktop | | |

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature
- [ ]  [Accessibility foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-02-02 18:56 UTC, jerekshoe commented on src/platform/utilities/api/index.js
> +      const errorResponse = isJson
You might have caught this already, but shouldn't this be `isJson(response)`?

2023-02-02 19:14 UTC, jerekshoe commented on src/platform/utilities/api/index.js
> +        : response.text();
You might need to clone this as well, I'm seeing an issue with the stream having already been read if not

2023-02-02 22:05 UTC, jerekshoe approved these changes
Works for the letters app

2023-02-02 22:27 UTC, rmessina1010 approved these changes
LGTM

2023-02-10 21:05 UTC, jerekshoe commented
Re-tested with the letters app and this works great!

2023-02-13 17:41 UTC, acrollet requested changes
I'm seeing an API request fail for us on the review environment for this PR that works correctly on staging. Digging into why, but leaving this here to prevent merge in the meantime. Thanks!

2023-02-13 17:49 UTC, asg5704 commented
> I'm seeing an API request fail for us on the review environment for this PR that works correctly on staging. Digging into why, but leaving this here to prevent merge in the meantime. Thanks!

Perfect thank you @acrollet, I wasn't going to roll this out until more VFS teams had time to test.

2023-02-13 19:01 UTC, acrollet approved these changes
Turns out the error was on my side earlier, the issue was with using Safari with review environments. Re-tested with Chrome and our check-in and pre-check-in workflows are working correctly.

2023-02-15 19:47 UTC, merged