MBMS-38246 Added conditional render for PreNeed footer function so it…
department-of-veterans-affairs/vets-website pull request #23585
Opened 2023-03-13 18:39 UTC by ConnorJeff

## Summary

 508 bug - Respondent burden displays on each screen within the Pre-Need digital form.  
### [Jira Link](https://vajira.max.gov/browse/MBMS-38246)
#### Steps to reproduce: 
- Start the Pre-Need application signed in OR signed out - https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction 

- On Step 1 of 7: Applicant Information scroll down
    - Note: The Respondent Burden displays

- Continue through the form flow 
    - Note: on each screen at the bottom, just above the Need Help? section the Respondent Burden displays

## Testing done

- Local Testing
    - Before respondent burden appeared on the introduction to the preneed form and every page of the application.
    - Now the respondent burden ONLY appears on the bottom of the form introduciton right above the ```Need Help?``` section. Does not apear on any other page of the application.

## What areas of the site does it impact?
pre-need eligibility determination form

## Acceptance criteria

- [x] Tasks Completed

2023-03-14 15:16 UTC, ksantiagoBAH approved these changes

2023-03-14 15:29 UTC, DouglasGilbert1 approved these changes

2023-03-14 16:19 UTC, ksantiagoBAH requested changes, later dismissed
Throw this behind a production flag please.

2023-03-15 16:59 UTC, sonntag-adam approved these changes

2023-03-16 14:29 UTC, ksantiagoBAH approved these changes

2023-03-17 14:33 UTC, rmessina1010 approved these changes
LGTM

2023-03-17 14:57 UTC, merged