MBMS-38527: Preparer Information foreign country update
department-of-veterans-affairs/vets-website pull request #23597
Opened 2023-03-14 13:39 UTC by DouglasGilbert1

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- update preparer information to not require state when foreign country is selected
- navigate to preparer information > select foreign country and attempt to go to next screen
- remove state requirement when foreign country is selected
- memorials self service

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#0000
- *Link to ticket created in va.gov-team repo*
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- when filling out preparer informatiion if foreign country was selected could not proceed to next screen because state was required but not shown on form
-  navigate to preparer information and select foreign country and attempt to move forward
- local testing

## What areas of the site does it impact?
pre need form

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature
- [ ]  [Accessibility foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-03-14 13:52 UTC, ksantiagoBAH approved these changes

2023-03-14 14:35 UTC, AlexanderSherrow approved these changes

2023-03-14 15:29 UTC, sonntag-adam approved these changes

2023-03-14 16:22 UTC, ksantiagoBAH requested changes
Can you put this behind a production flag please.

2023-03-15 15:45 UTC, ksantiagoBAH approved these changes

2023-03-15 20:33 UTC, sonntag-adam approved these changes

2023-03-17 20:28 UTC, rmessina1010 approved these changes
LGTM

2023-03-20 13:29 UTC, merged