MBMS-39017 fixed Grammar issues on preneed introduction page
department-of-veterans-affairs/vets-website pull request #23635
Opened 2023-03-16 17:59 UTC by ConnorJeff

# [MBMS-39017](https://vajira.max.gov/browse/MBMS-39017)
#### (Click Link Above to see Jira Bug)

## Summary

- Issue: Incorrect grammar on introduction page
- Feature Flag Status: Does not impact 
- Steps to reproduce: Navigate to the form's introduction and scroll to Step 1 for prepare and you will see the incorrect grammar noted above.
- Expected results: Remove period at the end of link and change to "Military Service number" (located under the 'Prepare' step of the subway pattern.)
- Actual Results: "Find a VA national cemetery" has a period after the word "cemetery" and "Military Service Number" is capitalized

## Testing done

- Local Testing

## Screenshots
_Note: This field is mandatory for component work and UI changes (non-component work should NOT have screenshots)._

#### Before:
![image](https://user-images.githubusercontent.com/122034971/225709509-2b4cd3bc-a51e-4644-a152-edaea28f96db.png)

#### After:
![image](https://user-images.githubusercontent.com/122034971/225710462-29262891-8ffc-44d7-8fa3-f28e15f5c4ac.png)

## Acceptance criteria

- [x]  Grammar issues have been corrected.

2023-03-20 11:36 UTC, ksantiagoBAH approved these changes

2023-03-20 14:50 UTC, DouglasGilbert1 approved these changes

2023-03-21 13:33 UTC, sonntag-adam requested changes
Needs a prod flag

2023-03-21 14:45 UTC, ConnorJeff reviewed
Added Prod flags

2023-03-21 17:37 UTC, sonntag-adam approved these changes

2023-03-23 14:14 UTC, rmessina1010 approved these changes
LGTM

2023-03-23 15:35 UTC, merged