Show an error message when GET /v0/user fails
department-of-veterans-affairs/vets-website pull request #23748
Opened 2023-03-27 21:48 UTC by dellerbie

## Summary

As part of the 2022 My VA Audit, we're making many UX improvements. After QA, under the My VA Health Care section, we discovered that if we cannot connect to MPI (i.e. the GET/user/ call fails) the entire My VA page will fail to load (showing an infinitely spinning loading indicator).  

This PR presents an error message to the user whenever calls to `GET /v0/user` fails.

## Related issue(s)
- Ticket: [https://github.com/department-of-veterans-affairs/va.gov-team/issues/49094](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49094)
- Epic: [https://github.com/department-of-veterans-affairs/va.gov-team/issues/41934](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41934)

## Testing done

- Blocked calls to `GET /v0/user` using Chrome developer tools
- Verified the error message is shown on the Dashboard when this happens
- Upated Platform unit spec for the `RequiredLoginView` component

## Screenshots

| Before | After |
| --- | --- |
| ![user-error-before](https://user-images.githubusercontent.com/534756/228074233-687f4f4a-dcef-422c-983f-f7c9a8e549f6.png)| ![user-error-after](https://user-images.githubusercontent.com/534756/228073150-d6293ce6-dfa3-4ad8-acf2-09fd7c15d4e3.png) |

## What areas of the site does it impact?

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  I added a screenshot of the developed feature
- [ ]  [Accessibility foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

2023-03-27 22:18 UTC, asg5704 commented
The changes are fine implementation wise, however none of them should live within authentication because they have nothing to do with authentication or session management.

2023-03-27 22:18 UTC, asg5704 commented on src/platform/user/authentication/actions/index.js
> +
Move to a more generalized action file

`user/profile/actions/index.js`

2023-03-27 22:19 UTC, asg5704 commented on src/platform/user/authentication/reducers/index.js
> +
Again move to a more generalized

`user/profile/reducers/index.js`

2023-03-27 22:19 UTC, asg5704 commented on src/platform/user/authentication/reducers/index.js
> +} from '../actions';
Move to a more generalized

`user/profile/reducers/index.js`

2023-03-27 22:21 UTC, asg5704 commented on src/platform/user/profile/actions/index.js
> +import { updateLoggedInStatus, userError } from '../../authentication/actions';
Again move to a more generalized actions

`user/profile/actions/index.js`

2023-03-27 22:27 UTC, asg5704 requested changes

2023-03-27 22:27 UTC, asg5704 commented on src/platform/user/authorization/components/RequiredLoginView.jsx
> +    if (user.login.error) {
We should probably put this under the `user` store so that it'll be `user.login`, `user.profile`, and `user.errors`

2023-03-28 00:36 UTC, allisonlu approved these changes
noting some eslint errors but those are out of scope of our ownership / sprint goals, so lgtm

2023-03-28 21:35 UTC, asg5704 approved these changes
LGTM. Approved.

2023-03-29 16:39 UTC, adamwhitlock1 approved these changes
lgtm

2023-03-29 19:06 UTC, asg5704 approved these changes

2023-03-29 22:45 UTC, rmessina1010 approved these changes
LGTM

2023-03-29 22:47 UTC, merged