Remove Legacy application Routing Link from Introduction Pages
department-of-veterans-affairs/vets-website pull request #23988
Opened 2023-04-19 20:06 UTC by bradbergeron-us

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- *(Summarize the changes that have been made to the platform)*
- *(If bug, how to reproduce)*
- *(What is the solution, why is this the solution)*
- *(Which team do you work for, does your team own the maintenance of this component?)*
- *(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)*

## Related issue(s)
- department-of-veterans-affairs/va.gov-team#0000
- *Link to ticket created in va.gov-team repo*
- *Link to previous change of the code/bug (if applicable)*
- *Link to epic if not included in ticket*

## Testing done

- *Describe what the old behavior was prior to the change*
- *Describe the steps required to verify your changes are working as expected*
- *Describe the tests completed and the results*
- *Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)*

## Screenshots
_Note: This field is mandatory for component work and UI changes (non-component work should NOT have screenshots)._

| | Before | After |
| --- | --- | --- |
| Mobile | | |
| Desktop | | |

## What areas of the site does it impact?
*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

- [ ]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ]  No error nor warning in the console.
- [ ]  Events are being sent to the appropriate logging solution
- [ ]  Documentation has been updated (link to documentation)
- [ ]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ]  Feature/bug has a monitor built into Datadog or Grafana (if applicable)
- [ ]  If app impacted requires authentication, did you login to a local build and verify all authenticated routes work as expected
- [ ]  I added a screenshot of the developed feature
- [ ]  [Accessibility foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-04-20 19:08 UTC, nathanielbuck approved these changes

2023-04-20 21:08 UTC, btruongafs approved these changes

2023-04-20 21:10 UTC, btruongafs commented on src/applications/my-education-benefits/components/IntroductionLoginV1.jsx
> +              If you don’t want to sign in, you can apply using the paper form.
@bradbergeron-us this still has the hyperlink on the entire sentence

2023-04-20 21:13 UTC, btruongafs requested changes
doesnt look like the hyperlink got changed to just the 'paper form' copy only

2023-04-21 15:28 UTC, bradbergeron-us commented on src/applications/my-education-benefits/components/IntroductionLoginV1.jsx
I updated this file, but it is not currently being used. The Introduction page container only imports InroductionLoginV2.jsx so the V1 is not used. @btruongafs

2023-04-21 15:53 UTC, bradbergeron-us commented on src/applications/my-education-benefits/components/IntroductionLoginV2.jsx
> +              {showMebEnhancements ? (
@btruongafs, the essential part of the change occurs here in the IntroductionLoginV2.jsc component, which the Introduction Page Container renders. Lines 85-100 address changing the copy and conditionally rendering based on the showMebEnhancements feature flag being toggled on or off.

2023-04-21 17:46 UTC, btruongafs approved these changes

2023-04-21 19:11 UTC, merged