Optimize household declaration section of the HCA
department-of-veterans-affairs/vets-website pull request #24098
Opened 2023-05-02 16:32 UTC by longmd

## Description
Based on findings and results from a December 2022 research initiative, the 10-10 Health Apps team made the decision to update the Household declaration section of the 10-10EZ form. This PR contains content, design, form structure and testing changes to support the UX optimization of that section. This PR also contains a bug fix for the forms library that caused data to be omitted when two form pages (one active and one inactive) contained the same data keys.

## Related issue(s)
department-of-veterans-affairs/va.gov-team#52960

## Testing done
- [x] Unit testing of all new components and existing form config declaration files
- [x] e2e testing of the nine (9) possible combinations of pages through that section

## Resources
- [Sketch File](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/208CCE1E-DC03-457F-B2FA-1232663983CF/canvas)
- [Updated household wireflow](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/nR0pl7W)

## Acceptance criteria

- [ ] Flow through the section can be completed per the provided wireflow documentation.
- [ ] Browser console contains no warnings or errors related to anything in the section.
- [ ] Original household section flow maintains in tact when feature flag is disabled for this build.

2023-05-09 19:30 UTC, jadon1979 approved these changes

2023-05-10 21:45 UTC, JoshingYou1 approved these changes
LGTM! Great work on this Matt. A lot of work here 😄

2023-05-10 22:00 UTC, harshil1793 approved these changes

2023-05-11 13:13 UTC, acrollet requested changes
This branch needs to be updated from latest main, thanks!

2023-05-11 14:22 UTC, longmd commented
Closing in favor of a fresh branch.

2023-05-11 14:22 UTC, closed without merging