Add intellisense for schemas
department-of-veterans-affairs/vets-website pull request #24104
Opened 2023-05-02 21:28 UTC by rhasselle-oddball

## Summary

- This will allow for auto-complete when typing schemas, UI schemas and form config options. 
- To use this, add `/** @type {PageSchema} */ ` directly above a `const` or `default export` which is an object including `schema` and `uiSchema`
- Or add `/** @type {FormConfig} */ ` directly above a `const formConfig` defining your form.
- You can also trigger intellisense manually in VSCode by pressing the default key combo (ctrl/command+space or possibly ctrl/command+i depending on your setup)
- This will not enforce types, detect eslint errors, or produce errors in any way. It is simply an suggestion/auto-complete aid.

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team-forms#245

## Testing done

- Verified properties by looking at examples from every form, and also referencing the RJSF documentation in our node_modules.
- Tested on existing forms. Verified intellisense works in the editor. No changes to outputted form in the UI or in testing.

### Reliability
- The intellisense doesn't detect 100% of the time for some reason. I think because VSCode has to scan your editor to know where to find the type. But seems to work most of the time.

## Screenshots

![image](https://user-images.githubusercontent.com/123402053/235788596-59c8527f-a6c0-48b0-afbc-4e4e61a1b750.png)
![image](https://user-images.githubusercontent.com/123402053/235789496-fdf3a2df-e4c7-427d-87ae-2b222844d7f5.png)
![image](https://user-images.githubusercontent.com/123402053/235789636-c9d9cd6f-ca27-4dfb-8efb-0b2e23276849.png)

## What areas of the site does it impact?

Only local devs code editors

## Acceptance criteria

### Quality Assurance & Testing

- [x] Screenshot of the developed feature is added

### Error Handling

- [x] Browser console contains no warnings or errors.

2023-05-02 21:48 UTC, tlei123 approved these changes
LGTM

2023-05-03 21:14 UTC, Mottie requested changes

2023-05-03 21:14 UTC, Mottie commented on src/platform/forms-system/src/js/types.js
> + * }} SchemaOptions
Should this also include `[key: string]: SchemaOptions` for nested definitions?

2023-05-04 15:45 UTC, rhasselle-oddball commented on src/platform/forms-system/src/js/types.js
> + * }} UISchemaOptions
thanks for all the feedback. the last 2 relate to code on a prototype branch so I'll omit those for now. `ui:webComponentField` is a field we are introducing for working with web components in RJSF directly. can discuss more offline if interested.

2023-05-04 17:13 UTC, rhasselle-oddball commented on src/platform/forms-system/src/js/types.js
> + * @property {Array<Object>} additionalRoutes
Added new key recommendations, and refactored to this syntax.
This syntax allows for adding "- description". We can add these in future if we want.

2023-05-04 17:13 UTC, rhasselle-oddball commented on src/platform/forms-system/src/js/types.js
> + * @typedef {{
This syntax needs to be used when we have `[key:string]: Type`, or if you have colons in the key names . However this syntax does not allow for comments.

2023-05-04 17:15 UTC, rhasselle-oddball commented on src/platform/forms-system/src/js/types.js
> + * }} FormConfig
I didn't include 'intentToFileUrl' because I didn't see that it did anything in the code, but everything else should be there now.

2023-05-04 19:08 UTC, Mottie approved these changes
Ok, LGTM. Thanks for your hard work!

2023-05-04 20:50 UTC, merged