Vbahinwillit/issue53080
department-of-veterans-affairs/vets-website pull request #24136
Opened 2023-05-05 11:56 UTC by vbahinwillit

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#0000
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted and*if*code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.go header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL)_What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-05-15 21:38 UTC, vbahinwillit commented on src/applications/vaos/appointment-list/redux/actions.js
> +      const data = results[0]?.filter(appt => !appt.hasOwnProperty('meta'));
Modified to use 'hasOwnProperty' since checking for false when 'app.meta' is undefined does not work.

2023-05-15 21:39 UTC, vbahinwillit commented on src/applications/vaos/appointment-list/redux/actions.js
> +      );
Modified to use 'find' since 'backendServiceFailures' is expected to be an Object

2023-05-15 21:41 UTC, vbahinwillit commented on src/applications/vaos/appointment-list/redux/actions.js
> +      const results = await fetchAppointments({
No need to use Promise.all here since there is only one async api call.

2023-05-15 21:43 UTC, vbahinwillit commented on src/applications/vaos/services/appointment/index.js
> +      transformRequests.push({
Fixed the nested array issue

2023-05-15 21:46 UTC, vbahinwillit commented on src/applications/vaos/utils/appointment.js
> +
Currently use in the e2e tests

2023-05-16 22:53 UTC, vbahinwillit commented on src/applications/vaos/services/appointment/index.js
> +// const BAD_STAGING_SITES = new Set(['556', '612']);
Function not used

2023-05-18 18:49 UTC, ryanshaw requested changes

2023-05-18 19:26 UTC, vbahinwillit commented on src/applications/vaos/tests/appointment-list/components/ConfirmedAppointmentDetailsPage/index.unit.spec.jsx
> +describe.skip('VAOS <ConfirmedAppointmentDetailsPage>', () => {
Yes. I will move each of the v0 test to v2, remove duplicates, and stub the remaining test for implementation later.

2023-05-18 19:45 UTC, vbahinwillit commented on src/applications/vaos/services/appointment/index.js
> +        (!useV2VA && appt.kind !== 'cc') ||
done.

2023-05-18 20:55 UTC, ryanshaw commented on src/applications/vaos/tests/appointment-list/components/ConfirmedAppointmentDetailsPage/index.unit.spec.jsx
> +describe.skip('VAOS <ConfirmedAppointmentDetailsPage>', () => {
That was my plan too 🙂

2023-05-18 20:57 UTC, ryanshaw approved these changes
LGTM!

2023-05-18 23:22 UTC, merged