Notification Settings - add email channel toggle, utils hook, unit tests
department-of-veterans-affairs/vets-website pull request #24853
Opened 2023-07-13 18:34 UTC by adamwhitlock1

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#0000
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-07-13 19:55 UTC, adamwhitlock1 commented on src/applications/personalization/profile/constants.js
> +export const BLOCKED_MHV_NOTIFICATION_IDS = [
Changed name for clarity as to what types of notification are blocked.

2023-07-13 20:09 UTC, adamwhitlock1 commented on src/applications/personalization/profile/hooks/useNotificationSettingsUtils.js
This is the main section of functionality added in this PR.

The hook provides several pieces of functionality (returned at the end of the main hook function) which I will outline here:

**toggles**: the feature toggles strictly in relation to the notification settings feature set. This can be a good place to access all related toggles, and also they are used within some of the other functions in this hook.

**communicationPreferences**: the root state for notification settings. Mostly used internally in the hook, but returned in case needed in a component quickly

**channelsWithContactInfo**: an array of channels that have contact info for them on file in the profile.

**missingChannels**: basically the opposite of the above, but with additional `name` property added as well for use in upcoming components.

**useAvailableGroups**: provides an array of notification groups that are available according to some criteria.
 - the group must have some communication channels available in the notification items that the user has on file. So for example it would filter out any groups that only have email notifications in the group if the user doesn't have an email on file.
 - the group must also not belong to a group that is turned off by one of three feature toggles

**useUnavailableItems**: provides array of unavailable notification items from all groups and an array of plain language strings. This will be used to list out the notifications that _could_ be shown to a user if they add their missing contact info for those.

**useUnavailableItemsByGroup**: this was an idea that I had, where we could do something similar to the useUnavailableItems but split the items by group so they could get displayed in chunks with maybe a heading above each with the group name. This will be unused for the initial implementation, but I'm going to experiment with further.

**useFilteredItemsForMHVNotfications**: removes any MHV notifications from a set of itemIds if they are present and the feature toggle in not turned on.

2023-07-13 22:05 UTC, allisonlu commented on src/applications/personalization/profile/tests/hooks/useNotificationSettingsUtils/missingChannels.spec.jsx
just a heads up – unit tests aren't running, I think because the file extension here is `.spec.jsx` instead of `.unit.spec.jsx`

2023-07-13 22:13 UTC, allisonlu commented
^ Other than my one comment above, this lgtm! Looking forward to seeing it in action

2023-07-13 22:32 UTC, adamwhitlock1 commented on src/applications/personalization/profile/tests/hooks/useNotificationSettingsUtils/missingChannels.spec.jsx
I dont know how many times I am going to do this before I learn. Thanks for catching, I pushed an update for the file names.

2023-07-13 22:46 UTC, dellerbie requested changes

2023-07-14 00:04 UTC, adamwhitlock1 commented on src/applications/personalization/profile/tests/hooks/useNotificationSettingsUtils/missingChannels.unit.spec.jsx
> +  it('returns array with corrent channel id when missing email', () => {
im really on a roll with these typos today

2023-07-14 00:05 UTC, adamwhitlock1 commented on src/applications/personalization/profile/tests/hooks/useNotificationSettingsUtils/missingChannels.unit.spec.jsx
> +  it('returns array with corrent channel id when missing mobile phone', () => {
maybe a case of copy pasta from taking the last test and modifying for the other use case. Will correct to make sure its described correctly.

2023-07-14 00:06 UTC, adamwhitlock1 commented on src/applications/personalization/profile/tests/hooks/useNotificationSettingsUtils/useAvailableGroups.unit.spec.jsx
> +    expect(hookResults.length).to.equal(5);
Yea I think I can make the test a little more explicit, thanks Derrick!

2023-07-14 14:56 UTC, adamwhitlock1 commented on src/applications/personalization/profile/tests/hooks/useNotificationSettingsUtils/useAvailableGroups.unit.spec.jsx
> +    expect(hookResults.length).to.equal(5);
Updated with a check to make sure all 5 specific group names are present in result.

2023-07-14 14:57 UTC, adamwhitlock1 commented
Addressed concerns and feedback. Should be ready for re-review now @dellerbie and @allisonlu thank you!

2023-07-14 16:28 UTC, dellerbie approved these changes
lgtm Adam!

2023-07-14 17:21 UTC, rsmithadhoc approved these changes

2023-07-14 21:10 UTC, merged