Mhv 45263 compose form updates
department-of-veterans-affairs/vets-website pull request #24918
Opened 2023-07-19 15:48 UTC by KyleCardwell

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#0000
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-07-19 21:37 UTC, oleksii-morgun-va requested changes

2023-07-19 21:37 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/components/ComposeForm/ComposeForm.jsx
> +      setLastFocusableElement(e.target);
Perhaps worth validating that this focus lands properly with this change

2023-07-19 21:37 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/components/ComposeForm/ComposeForm.jsx
> +            &nbsp;Save draft
I am guessing you are trying to achieve some spacing with `&nbsp` here. Would a margin to an icon be more appropriate?

2023-07-19 21:37 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/components/ComposeForm/ReplyForm.jsx
> +                  &nbsp;Save draft
same as a comment above

2023-07-19 21:37 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/components/Draft/DeleteDraft.jsx
> +        <i className="fas fa-trash-alt" />
we are usually adding `aria-hidden` to icons

2023-07-19 21:37 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/components/ComposeForm/ReplyForm.jsx
> +                  <i className="fas fa-save" />
we are usually adding `aria-hidden` to icons

2023-07-19 21:37 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/components/ComposeForm/ComposeForm.jsx
> +            <i className="fas fa-save" />
we are usually adding `aria-hidden` to icons

2023-07-20 16:58 UTC, oleksii-morgun-va approved these changes

2023-07-20 17:56 UTC, vsaleem approved these changes

2023-07-24 18:05 UTC, merged