61692 Update the static landing page (Public Websites)
department-of-veterans-affairs/vets-website pull request #24928
Opened 2023-07-19 19:59 UTC by vbahinwillit

## Summary
This PR updates the static landing page.

## Related issue(s)

department-of-veterans-affairs/va.gov-team#61692

## Testing done
Unit testing

## Screenshots

## What areas of the site does it impact?
VAOS

## Acceptance criteria
All tests should pass.

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-07-20 12:07 UTC, vbahinwillit commented on src/applications/static-pages/health-care-manage-benefits/get-medical-records-page/components/AuthContent/index.unit.spec.js
> +    // expect(text).to.include('CernerCallToAction');
Commented out to due text no longer being included in the output. This is the result of CernerCallToAction:332 (needed to get feature flag state).

export default connect(mapStateToProps)(CernerCallToAction);

2023-07-20 21:56 UTC, jenniemc commented
@vbahinwillit, Followed the setup instructions changing the facility 'vha_442' attribute, 'fieldVamcEhrSystem' from 'vista' to 'cerner'.  I also changed the attribute 'is_cerner' from 'false' to 'true' for facilities '983' and '984' on the file 'src/applications/vaos/services/mocks/index.js'.

When I go to test locally "http://localhost:3001/health-care/schedule-view-va-appointments", I get this screen instead. What am I missing?
![Screenshot 2023-07-20 at 2 43 47 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/54327023/b5890ebe-fbb2-4d7b-b193-5568e5612f91)

2023-07-21 00:57 UTC, jenniemc approved these changes
Other than minor spacing and text repositioning, this looks terrific!

2023-07-21 00:57 UTC, jenniemc commented on src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.js
> +              <va-additional-info trigger="Having trouble opening My VA health? Try these steps:">
"Try these steps:" should be removed from the title and repositioned above the start of item lists.

2023-07-21 00:57 UTC, jenniemc commented on src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.js
> +                </a>
Could use more spacing between the bottom of the facilities list and "Go to My VA Health" link

2023-07-21 19:26 UTC, ryguyk requested changes
`<CernerCallToAction>` is used on five separate widgets. It looks like this change is going to have the effect of changing things on all five of them. I don't think that is desirable, given my understanding of the scope of work.

2023-07-24 16:03 UTC, vbahinwillit commented
> `<CernerCallToAction>` is used on five separate widgets. It looks like this change is going to have the effect of changing things on all five of them. I don't think that is desirable, given my understanding of the scope of work.

Thanks for the review. I will make the necessary changes.

2023-07-24 16:41 UTC, vbahinwillit commented
@ryguyk - These changes are behind a feature flag.

2023-08-04 15:45 UTC, simiadebowale approved these changes
LGTM

2023-08-04 22:22 UTC, jenniemc reviewed
Looks good. Just see two minor items for clarification.

2023-08-09 21:33 UTC, randimays commented
@vbahinwillit 

There's one more spot where we need to replace a selector with the new version. I didn't see this one last week... my apologies.

`selectIsCernerPatient` - src/applications/vaos/redux/selectors.js

This one needs to be using the selector by the same name in src/platform/user/cerner-dsot.

2023-08-10 14:18 UTC, vbahinwillit commented
@randimays - The changes to remove the deprecated Cerner references are currently in PR #25160 (both the old and new requested changes). PR #25160 will be deployed to Staging and Prod before this PR.

2023-08-10 15:29 UTC, randimays commented
Seeing this issue on the review instance using [vets.gov.user+1@gmail.com](https://tud.vfs.va.gov/?page=1)

Testing URL: http://80b4c591ece3c8714b70b8d511682939.review.vetsgov-internal/health-care/schedule-view-va-appointments/appointments/

<img width="1434" alt="Screenshot 2023-08-10 at 10 28 06 AM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/19175324/d39f22ba-e4f0-4d44-9199-9cee3dba1ff5">

2023-08-11 20:35 UTC, randimays approved these changes
LGTM

2023-08-14 16:33 UTC, ryguyk approved these changes
I'm approving so as to unblock (I previously requested changes). I am deferring to the review by @randimays, as she is now more informed than I am regarding this work.

2023-08-15 15:44 UTC, merged