[MHV-44568] Updated Navigation after sending a message
department-of-veterans-affairs/vets-website pull request #24991
Opened 2023-07-25 18:47 UTC by vsaleem

- User will be redirected to the original folder from where the message was sent from

## Summary

## Related issue(s)

## Testing done

## Screenshots

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-07-28 13:44 UTC, alex-morgun-1 requested changes

2023-08-03 16:51 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/tests/containers/FolderThreadListView.unit.spec.jsx
> +      expect(folderName).to.have.text(customFolder.name);
not critical, but 3 lines above can be optimized in 1 line like so
```suggestion
      expect(screen.getByText(customFolder.name, { selector: 'h1' })).to.exist;
```

2023-08-03 16:51 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/tests/containers/FolderThreadListView.unit.spec.jsx
> +      expect(folderDescription).to.have.text(DefaultFolders.CUSTOM_FOLDER.desc);
same suggestion as above

2023-08-03 16:52 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/tests/containers/FolderThreadListView.unit.spec.jsx
> +    expect(folderName).to.have.text(DefaultFolders.DELETED.header);
same suggestion as on lines 143-145

2023-08-03 16:53 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/tests/containers/FolderThreadListView.unit.spec.jsx
> +    expect(folderDescription).to.have.text(DefaultFolders.DELETED.desc);
same suggestion as on lines 143-145

2023-08-03 16:53 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/components/ManageFolderButtons.jsx
> +    if (threads.threadList.length > 0) {
we probably should cover this logic in a unit test as well. Please pardon if you already do, I may have missed

2023-08-03 16:56 UTC, oleksii-morgun-va commented
Great additions! I think we should strive to cover the scenarios with 'Delete Folder' scenarios in unit tests too. Particularly since this issue has stroke us back this time

2023-08-03 17:00 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/tests/containers/ThreadDetails.unit.spec.jsx
> +          },
We should have these objects in mocks in `/fixtures` that we can re-use here and in other tests too

2023-08-30 13:56 UTC, closed without merging