Removed prod flags
department-of-veterans-affairs/vets-website pull request #25274
Opened 2023-08-17 16:30 UTC by ConnorJeff

# [MBMS-46289](https://jira.devops.va.gov/browse/MBMS-46289)

This PR removes the prod flags from [MBMS-45417](https://github.com/department-of-veterans-affairs/vets-website/pull/25163/)

2023-08-17 18:14 UTC, adam-antonioli approved these changes, later dismissed

2023-08-17 18:36 UTC, adam-antonioli approved these changes

2023-08-18 13:06 UTC, sonntag-adam approved these changes

2023-08-18 14:37 UTC, rmessina1010 approved these changes
LGTM

2023-08-18 17:17 UTC, ksantiagoBAH requested changes
Looking into an issue on the contact page, when selecting someone else and back to the name of the applicant it prevents the user from moving forward.

2023-08-29 15:21 UTC, closed without merging

2023-08-29 15:23 UTC, ksantiagoBAH commented
Issue was resolved in https://github.com/department-of-veterans-affairs/vets-website/pull/25367