updated reply draft components if !cannotReply
department-of-veterans-affairs/vets-website pull request #25389
Opened 2023-08-25 17:29 UTC by KyleCardwell

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- Updates a Reply Draft that is older than 45 days to not be sendable or editable (view only)

## Related issue(s)

- https://jira.devops.va.gov/browse/MHV-45262

## Testing done

- Old Behavior: Reply Drafts older than 45 days could still be edited in the textarea, and the send/save buttons were visible
- New Behavior:  Reply Drafts older than 45 days cannot be edited or sent/saved

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |![Screenshot 2023-08-25 at 11 19 59 AM](https://github.com/department-of-veterans-affairs/vets-website/assets/79024398/8833c2dc-30a1-46fa-9725-a496d9768be2)|![Screenshot 2023-08-25 at 11 22 36 AM](https://github.com/department-of-veterans-affairs/vets-website/assets/79024398/b367053e-65fc-4139-a5c3-b3cd40db73cb)|

## What areas of the site does it impact?

va.gov - secure messaging

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-08-28 17:53 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/sass/folder-thread-list-view.scss
> +  padding-right: 3px;
based on the into earlier today, would you like to use the VA DST class for padding on an element itself instead?

2023-08-28 17:56 UTC, oleksii-morgun-va requested changes
Looks great. Design implementation is exactly as on mocks. I would definitely expand the unit test coverage here to capture this logic of an old draft. I would include assertions that a component renders a `section` instead of a `textarea` on an old conversation for a draft. And perhaps enhance an existing test to assert that there is a `textarea` if a thread is not old enough. I believe we already have tests for those components somewhere around that 45 day criteria. We could probably just expand them.

2023-08-28 19:37 UTC, oleksii-morgun-va approved these changes

2023-08-30 03:57 UTC, rmessina1010 approved these changes
LGTM

2023-08-30 15:46 UTC, merged