Ndbex 63627 burial review page
department-of-veterans-affairs/vets-website pull request #25407
Opened 2023-08-25 21:17 UTC by Midge-dev

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#0000
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-08-31 01:21 UTC, DLarson-Oddball requested changes
Pulled down and was able to review my answers to an in progress form

2023-08-31 01:21 UTC, DLarson-Oddball commented on src/applications/burials/components/NoFormPage.jsx
> +        'Claimant’s middle name': formData.claimantFullName?.middle ?? 'None',
The optional chaining guard on L72 isn't present on L69. Also, I love the use of nullish coalescing vs the ternary where the first path returns the same value compared in the conditional. Feels notably more succinct.

2023-08-31 01:21 UTC, DLarson-Oddball commented on src/applications/burials/components/NoFormPage.jsx
> +                <CreateSummarySections
What do you think about renaming this component `SummarySection`?

2023-08-31 01:21 UTC, DLarson-Oddball commented on src/applications/burials/components/NoFormPage.jsx
> +      ) : (
This feels like a lot of logic to wrap in a ternary. Could we break this up into a couple functions returning the proper content instead?

2023-08-31 01:21 UTC, DLarson-Oddball commented on src/applications/burials/reducers/itf.js
> +// import set from 'platform/utilities/data/set';
Do we still need this file?

2023-09-01 21:48 UTC, Midge-dev commented on src/applications/burials/components/NoFormPage.jsx
> +              <strong>XX/XX/XXXX</strong>. You have 12 months from that date to
Not at this time. API needs to give this to us

2023-09-05 15:06 UTC, Midge-dev commented on src/applications/burials/BurialsApp.jsx
> +  const showForm = false;
This was updated to use a flipper and has since been resolved. Thanks!

2023-09-05 16:43 UTC, DLarson-Oddball approved these changes

2023-09-06 16:11 UTC, Midge-dev commented
This is ready for review. Thanks!

@department-of-veterans-affairs/vsa-debt-frontend
vsa-debt-frontend
@department-of-veterans-affairs/benefits-team-1-frontend
benefits-team-1-frontend
@department-of-veterans-affairs/platform-design-system-fe
platform-design-system-fe
@department-of-veterans-affairs/platform-va-product-forms
platform-va-product-forms
@department-of-veterans-affairs/va-platform-cop-frontend
VA Platform CoP Frontend

2023-09-06 18:09 UTC, Andrew565 approved these changes

2023-09-06 23:18 UTC, Mottie approved these changes

2023-09-07 16:26 UTC, Midge-dev commented on src/applications/burials/BurialsApp.jsx
> +    window.location.href = '/whatever/the/how-to/page/is';
@Mottie thanks for that! Fixed and pushed

2023-09-07 19:49 UTC, merged