MHV-48120: Allergies error handling work done
department-of-veterans-affairs/vets-website pull request #25414
Opened 2023-08-28 16:13 UTC by mattwrightva

## Summary
MHV medical records allergies api error handling work has been done. 

## Related issue(s)
https://jira.devops.va.gov/browse/MHV-48120

## Testing done
No additional testing done. 

## Screenshots
<img width="948" alt="Screenshot 2023-08-28 at 10 12 11 AM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/107576133/640aa4ac-6a7c-434f-89c3-0a24b4296e1c">
<img width="969" alt="Screenshot 2023-08-28 at 10 12 03 AM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/107576133/15e132b0-2a62-442b-b678-a27aa8c66778">

## What areas of the site does it impact?
MHV medical records - allergies

## Acceptance criteria
AC1 All API calls for this domain handle errors gracefully

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

2023-08-28 22:34 UTC, mattwrightva commented on src/applications/mhv/medical-records/reducers/alerts.js
> +  // eslint-disable-next-line sonarjs/no-small-switch
I imagine we will have more alert actions/reducers so I made this a switch to follow convention for reducers.

2023-08-29 14:26 UTC, powellkerry approved these changes

2023-08-29 15:23 UTC, mmoyer-va requested changes
Implement the naming conventions we discussed in [this Slack thread](https://dsva.slack.com/archives/C04ER7MHX5E/p1693261576416279).

2023-08-29 16:31 UTC, mmoyer-va approved these changes

2023-08-29 16:36 UTC, merged