63931 travel content update second
department-of-veterans-affairs/vets-website pull request #25505
Opened 2023-09-01 20:52 UTC by lee-delarm6

## Summary

- Updates to text requested
- Adjusted prop type

## Screenshots
![Screenshot 2023-09-01 at 4 51 42 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/135059743/a290058c-6023-43eb-80de-e048b0c944bf)

2023-09-05 16:51 UTC, wullaski approved these changes
LGTM! just happen to notice the single quotes 🔍

2023-09-05 16:51 UTC, wullaski commented on src/applications/check-in/locales/en/translation.json
> +  "youre-traveling-for-treatment-of-a-service-connected-condition": "You're traveling for treatment of a service-connected condition, <0>or</0>",
```suggestion
  "youre-traveling-for-treatment-of-a-service-connected-condition": "You’re traveling for treatment of a service-connected condition, <0>or</0>",
```

2023-09-05 16:51 UTC, wullaski commented on src/applications/check-in/locales/en/translation.json
> +  "youre-traveling-for-one-of-these-reasons": "You're traveling for one of these reasons:",
```suggestion
  "youre-traveling-for-one-of-these-reasons": "You’re traveling for one of these reasons:",
```

2023-09-05 16:51 UTC, wullaski commented on src/applications/check-in/locales/en/translation.json
> +  "you-have-an-annual-income-below-the-maximum": "You have an annual income that's below the maximum annual VA pension rate, <0>or</0>",
```suggestion
  "you-have-an-annual-income-below-the-maximum": "You have an annual income that’s below the maximum annual VA pension rate, <0>or</0>",
```

2023-09-05 16:51 UTC, wullaski commented on src/applications/check-in/locales/en/translation.json
> +  "this-must-be-true-youre-traveling-for-care": "<0>This must be true:</0> You're traveling for care at a VA health facility or for VA-approved care at a non-VA health facility in your community. <0>
```suggestion
  "this-must-be-true-youre-traveling-for-care": "<0>This must be true:</0> You’re traveling for care at a VA health facility or for VA-approved care at a non-VA health facility in your community. <0>And at least one of these must also be true:</0>",
```

2023-09-05 16:51 UTC, wullaski commented on src/applications/check-in/locales/en/translation.json
> +  "you-cant-afford-to-pay-for-your-travel": "You can't afford to pay for your travel, as defined by our guidelines, <0>or</0>",
```suggestion
  "you-cant-afford-to-pay-for-your-travel": "You can’t afford to pay for your travel, as defined by our guidelines, <0>or</0>",
```

2023-09-05 16:57 UTC, wullaski requested changes

2023-09-05 16:57 UTC, wullaski commented on src/applications/check-in/day-of/pages/TravelQuestion.jsx
> +          <p>
You could add a margin bottom of zero here to get rid of the extra space after the paragraph `vads-u-margin-bottom--0` I think

2023-09-05 16:57 UTC, wullaski commented on src/applications/check-in/day-of/pages/TravelQuestion.jsx
> +          <p>
Sorry one last nitpick I noticed after I approved the first time

2023-09-05 19:17 UTC, lee-delarm6 commented
![Screenshot 2023-09-05 at 3 16 33 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/135059743/04aaaec0-196a-4f9a-9ecc-70870ea9c3f8)
@wullaski Updated the spacing!

2023-09-06 12:57 UTC, wullaski approved these changes
LGTM! 🚢

2023-09-06 12:57 UTC, merged