Updated translations
department-of-veterans-affairs/vets-website pull request #25617
Opened 2023-09-11 17:50 UTC by lee-delarm6

Updated translations

## Summary

- Added translations for spanish and tagalog

## Testing done

- Made sure app still built, no translations in use

2023-09-11 18:22 UTC, brianseek requested changes
These should be alphabetized along with the corresponding english keys if not already alphabetized there.

2023-09-12 00:27 UTC, lee-delarm6 commented
> These should be alphabetized along with the corresponding english keys if not already alphabetized there.

Gotcha, alphabetizing also moved a couple others around, but I assume it's no worry

2023-09-12 16:27 UTC, lee-delarm6 commented on src/applications/check-in/locales/en/translation.json
> +  "zip-code-is-required": "Zip code is required"
Oh shoot, I didn't take into account other new translations. Good catch!

2023-09-12 16:28 UTC, brianseek requested changes
One change to the english file and I think this will be good to go.

2023-09-13 13:06 UTC, lee-delarm6 commented
Re-added those translations to the bottom as requested @brianseek

2023-09-13 18:38 UTC, brianseek approved these changes
Looks good!

2023-09-13 20:01 UTC, merged