[MHV-47590] Update DeleteDraft Navigation
department-of-veterans-affairs/vets-website pull request #25631
Opened 2023-09-12 14:46 UTC by vsaleem

- User is redirected to previous folder user was in after a unsaved compose/reply draft message is deleted

## Summary

- _When a user clicks the 'Delete Draft' button on Start a new message or Reply screens, an unsaved message will remain unsaved/deleted and the user is redirected to the previous location where the user started the new message._
- _When a user clicks the 'Delete Draft' button on Start a new message or Reply screens, a partially composed message will present user with 'We can't save this message yet' modal, and then the user can continue editing the message or continue deleting the message. When a user confirms the message to be deleted, they are redirected to the previous location where the user started the new message._
- _When a user clicks the 'Delete Draft' button on Start a new message or Reply screens, a saved message will present user with a Delete Draft Modal.  User is given a warning that deleting messages is permanent can confirm_
- _Va.gov - Secure Messaging_

## Related issue(s)

_https://jira.devops.va.gov/browse/MHV-47590_

## Testing done
Updated cypress tests: After deleting a message, the user is redirected to the initiating screen where the user began the message.

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*Va.gov - Secure Messaging*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-10-25 15:51 UTC, oleksii-morgun-va requested changes
Vic, great work. Overall looks good. Can you look if we can add unit test coverage on modified areas of code and see if test engineers can assist with that test to avoid skipping it

2023-10-25 15:51 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/components/ComposeForm/ComposeForm.jsx
> +        }
we may want to cover this logic in a unit test

2023-10-25 15:51 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/components/Draft/DeleteDraft.jsx
> +            );
we may be missing test coverage for this block

2023-10-25 15:51 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/tests/e2e/secure-messaging-navigate-away-from-replying-message.cypress.spec.js
> +  it.skip('navigate away by click on the inside link', () => {
are we able to have this resolved with test engineers prior to merging to avoid skipping?

2023-10-25 19:09 UTC, KyleCardwell approved these changes
Great job Vic, looks good!

2023-11-03 15:34 UTC, vsaleem commented
> Vic, great work. Overall looks good. Can you look if we can add unit test coverage on modified areas of code and see if test engineers can assist with that test to avoid skipping it

@oleksii-morgun-va can you take another look at this review?  I'm going to handle the unit tests for this ticket in a separate story --> https://jira.devops.va.gov/browse/MHV-51084

2023-11-06 15:15 UTC, oleksii-morgun-va approved these changes

2023-11-06 15:17 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/util/constants.js
> +    DELETE_NEW_DRAFT_TITLE: 'Draft this draft?',
```suggestion
    DELETE_NEW_DRAFT_TITLE: 'Delete this draft?',
```

2023-11-06 17:30 UTC, rmessina1010 approved these changes
LGTM

2023-11-06 20:47 UTC, merged