updated routes for va-request flow
department-of-veterans-affairs/vets-website pull request #25780
Opened 2023-09-20 19:07 UTC by simiadebowale

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#0000
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-09-21 19:32 UTC, vbahinwillit commented on src/applications/vaos/new-appointment/newAppointmentFlow.js
Should be able to use relative paths as opposed to absolute. So no need to prefix paths with 'schedule'. I chose to use relative paths thinking it would be better for future updates.

2023-09-21 19:36 UTC, vbahinwillit requested changes
Refreshing the browser with the following link doesn't work. http://localhost:3001/my-health/appointments/pending

![Screenshot 2023-09-21 at 2 37 46 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/3587066/599a6b18-1d7c-410d-b31d-54a4a315d8af)

2023-09-21 23:03 UTC, simiadebowale commented
@vbahinwillit - This issue was happening in the local env because of the url changes. The reverse proxy we set up fixed the issue in staging but we're still seeing this behavior in the local env. If you switch to `main`, you should still see this error

2023-09-21 23:22 UTC, simiadebowale commented on src/applications/vaos/new-appointment/newAppointmentFlow.js
@vbahinwillit - when I used relative paths I was having issues with using the back button & then hitting continue. I'm seeing this specifically when navigating from `/schedule/va-request`  to `/schedule/va-request/reason`

2023-09-22 19:01 UTC, vbahinwillit commented on src/applications/vaos/new-appointment/newAppointmentFlow.js
@simiadebowale - I had the same issue. Adding a trailing '/' to the path resolved the issue for me.

2023-09-22 20:31 UTC, simiadebowale commented on src/applications/vaos/new-appointment/newAppointmentFlow.js
@vbahinwillit - I tried changing to `/reason` and it caused routing issues, it wasn't appending the the `/schedule/va-request/` I also tried `/va-request/reason` and it wasn't appending `/schedule`. `va-request/reason` works but when it navigate forward and back, I get routing issues.

2023-09-26 06:20 UTC, jenniemc commented on src/applications/vaos/new-appointment/newAppointmentFlow.js
Direct schedule flow and request flow share many of the same components. These include `ReasonForAppointmentPage`, `ReviewPage`, `ContactInfoPage`
When adding absolute path to `/schedule/va-request/reason` the request flow works as expected but will break direct schedule path. For example, in DS flow at the "Choose a reason for this appointment" page when using the back button, it serves up “Choose an appointment day and time” (http://localhost:3001/my-health/appointments/schedule/va-request/date-time) when it should be Choose a date and time (http://localhost:3001/my-health/appointments/schedule/date-time)

Is there any particular reason why the acceptance criteria for request flow must have:

- Choose an appointment date and time page, then URL will display https://va.gov/my-health/appointments/schedule/va-request
-  Choose a reason for this appointment, then URL will display https://va.gov/my-health/appointments/schedule/va-request/reason
-  Choose a type of appointment, then URL will display https://va.gov/my-health/appointments/schedule/va-request/preferred-method
-  Confirm your contact information page, then URL will display https://va.gov/my-health/appointments/schedule/va-request/contact-information
-  Review your appointment details page, then URL will display https://va.gov/my-health/appointments/schedule/va-request/review


If there is no particular reason, can we exclude appending `va-request` so the URL will display as follows? 
- https://va.gov/my-health/appointments/schedule/request-date
- https://va.gov/my-health/appointments/schedule/reason
- https://va.gov/my-health/appointments/schedule/preferred-method
- https://va.gov/my-health/appointments/schedule/contact-information
- https://va.gov/my-health/appointments/schedule/review

That way we can use relative path as Tony suggests and solves the routing issue since there is no `/va-request` appended to the `<Route path={`${match.url}~~/va-request~~/xxxx`}>` for request flow.

2023-09-27 03:47 UTC, closed without merging