MHV-48175 Handle Vaccines API errors
department-of-veterans-affairs/vets-website pull request #26110
Opened 2023-10-10 16:03 UTC by tynyttie

## Summary
Implemented frontend error handling for API errors on the Vaccines page.

## Related issue(s)

[MHV-48175](https://jira.devops.va.gov/browse/MHV-48175)

## Testing done

## What areas of the site does it impact?
The modification affects the Vaccine section of the Medical Records page.

## Acceptance criteria

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

2023-10-16 15:43 UTC, mattwrightva reviewed
Hey Ty, check out tests/actions/allergies.unit.spec.js for examples of how to cover the lines you added here. Compare with tests/actions/vaccines.unit.spec.js and you'll see what needs to be added.

2023-10-16 15:59 UTC, mmoyer-va requested changes
In addition to dispatching an alert when something goes wrong, we will need to display that alert in the Vaccines list and details pages. We are using `AccessTroubleAlertBox` to print the alert, but it is currently specific to allergies. It would need modifications if we want to use it for other domains.

2023-10-17 13:56 UTC, mmoyer-va requested changes
A few changes:
- The alert box for Vaccines says "Allergies". That component will need a type prop or something.
- There is an error in the vaccines reducer (see comment)
- Please include a screenshot with your PR, as this involves frontend changes.
- Your PR should quote the Jira ticket, per our recent guidelines

2023-10-17 13:56 UTC, mmoyer-va commented on src/applications/mhv/medical-records/api/MrApi.js
>  };
I am in favor making the Vaccine APIs use real data, but were you and Matt able to access vaccine data from the backend? I just tried it locally and it prints your error. I want to make sure it works before we push this change to staging.

I looked into it and the error I'm seeing is in the vaccines reducer. It's not checking if the response is empty before trying to grab records.
```
ERROR! TypeError: Cannot read properties of undefined (reading 'map')
    at vaccineReducer (vaccines.js:58:12)
```

2023-10-19 19:25 UTC, mmoyer3 approved these changes
Looks good!

2023-10-19 19:40 UTC, mattwrightva approved these changes
Awesome!

2023-10-19 21:08 UTC, mmoyer-va approved these changes

2023-10-19 21:09 UTC, merged