[MHV-50168] Message Details and Reply Draft UI Updates
department-of-veterans-affairs/vets-website pull request #26462
Opened 2023-10-31 13:05 UTC by vsaleem

## Summary

- Major changes to Message Details and Reply Draft UI
- Refactored accordion display by adding most recent message to accordion plane and scenario for which data appears
- The most recent message displayed in accordion will remain open by default
- Updated styling with Design Library foundation and removed custom css (see sketch styling recs.)
- Removed 'message you are replying to' section from Reply Form, this section located inside the accordion
- UNIT TESTS ARE PENDING (MUST UPDATE MessageThreads unit test BEFORE MERGE)
- CY TESTS NEED REVIEW (Experiencing major conflicts)

## Related issue(s)

- 

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2023-10-31 13:26 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/components/MessageThread/MessageThreadMeta.jsx
> +                  !fromMe || (!fromMe && replyToName)
@vsaleem This may be worth addressing

2023-10-31 14:26 UTC, oleksii-morgun-va requested changes
Vic, this is huge work. Looks great. I left couple notes to confirm before approving this

2023-10-31 14:26 UTC, oleksii-morgun-va commented on src/applications/mhv/secure-messaging/tests/containers/ThreadDetails.unit.spec.jsx
> +
commented code above. I think you meant to delete it

2023-10-31 20:36 UTC, oleksii-morgun-va approved these changes

2023-11-01 18:26 UTC, KyleCardwell approved these changes

2023-11-01 18:49 UTC, rmessina1010 approved these changes
LGTM

2023-11-01 18:51 UTC, merged