first commit for re-styled results info-pane
department-of-veterans-affairs/vets-website pull request #26567
Opened 2023-11-03 20:03 UTC by Wyzardsleeves

## Summary

- Updated the styling on the info panels of the results in Labs and Tests.
- Is not a bug.
- Used HTML/JSX and our proprietary va-tags.
- MHV Medical Records.

## Related issue(s)
### [MHV-45449](https://jira.devops.va.gov/browse/MHV-45449) - Need help understanding your results - Styling Updates needed ###

MR to VA.gov: Need help understanding your results - Styling Updates needed on Chem/hem (one page)

Note: Final Design TBD
>
>
>Screen shots:
>
>User Story: As a Medical Records User, I want to get help to be able to understand results of my MR data.
>
>Acceptance Criteria:
>AC1 Results section has been restyled
>AC2
>AC3
>AC4
>AC5
>
>Links to UCD:
>Sketch Link:
>User Flow:
>Mobile:
>Desktop:
>Other Design Notes:
>
>Architectural Notes: Always check for the latest designs in Sketch!

## Testing done

- No test because of no new functionality. Test passed locally. 

## Screenshots

Chem/hem
<img width="704" alt="Screenshot 2023-11-03 at 3 03 22 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/9909777/fc1107e1-2f6d-42e0-bf9b-ea5fe8793f59">

All other Labs and Tests
<img width="704" alt="Screenshot 2023-11-03 at 3 01 08 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/9909777/51536844-2007-4929-82aa-3820d8217aa3">

## What areas of the site does it impact?
MHV Medical Records

2023-11-05 17:45 UTC, rmessina1010 submitted a review, later dismissed
LGTM

2023-11-06 13:27 UTC, mmoyer-va requested changes
Added some specific comments, plus here are some general comments:

1. I think three of these dropdowns are identical. If that's the case, can we create a shared component instead of repeating the code three times?
2. Are the `<br/>` tags needed? We're not using them in most other places. Try taking them out and see if the result looks the same.
3. Use the SM link I mention in the specific comments. Also, I would factor this link out into a SecureMessageEmailLink component in "shared." We can use it in other places too.

2023-11-06 13:27 UTC, mmoyer-va commented on src/applications/mhv/medical-records/components/LabsAndTests/ChemHemDetails.jsx
> +            questions.
1. In other "Note:" sections, "if" is capitalized. Should it be the same here?
2. "oredered" is misspelled.

2023-11-06 13:27 UTC, mmoyer-va commented on src/applications/mhv/medical-records/components/LabsAndTests/ChemHemDetails.jsx
> +            "low". But this doesn’t automatically mean you have a health
Typically, a period will be inside the quotation marks, e.g. "low."

2023-11-06 13:27 UTC, mmoyer-va commented on src/applications/mhv/medical-records/components/LabsAndTests/ChemHemDetails.jsx
>                Compose a message.
For consistency with the Landing Page, this link should be:
```
                <a
                  href={mhvUrl(
                    isAuthenticatedWithSSOe(fullState),
                    'compose-message',
                  )}
                >
                  Compose a message on the My HealtheVet website
                </a>
```

2023-11-06 13:27 UTC, mmoyer-va commented on src/applications/mhv/medical-records/components/LabsAndTests/MicroDetails.jsx
>              </a>
Same as previous comment -- use this link:
```
                <a
                  href={mhvUrl(
                    isAuthenticatedWithSSOe(fullState),
                    'compose-message',
                  )}
                >
                  Compose a message on the My HealtheVet website
                </a>
```

2023-11-06 13:27 UTC, mmoyer-va commented on src/applications/mhv/medical-records/components/LabsAndTests/PathologyDetails.jsx
>              </a>
Again, same comment about the link.

2023-11-08 13:13 UTC, mmoyer-va requested changes

2023-11-08 13:13 UTC, mmoyer-va commented on src/applications/mhv/medical-records/components/shared/InfoAlert.jsx
> +        </a>
I think messagingURL is the same for all four places this is used. I would just use it put here, rather than pass it in as a prop.

2023-11-08 13:13 UTC, mmoyer-va commented on src/applications/mhv/medical-records/components/shared/InfoAlert.jsx
> +const InfoAlert = ({ highLowResults, messagingURL }) => (
Add props validation for these to get rid of the linter warning.

2023-11-16 18:35 UTC, mattwrightva approved these changes, later dismissed
Looks good!

2023-11-16 19:36 UTC, mmoyer-va approved these changes, later dismissed

2023-12-12 17:46 UTC, mmoyer-va approved these changes

2023-12-12 19:59 UTC, merged