68917 update vets-json-schema for ec/nok
department-of-veterans-affairs/vets-website pull request #26605
Opened 2023-11-07 17:14 UTC by jadon1979

## Summary

- Update the vets-json-schema for the EC/NOK implementation 
- 
## Related issue(s)

- (https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/68917)[https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/68917]

## Testing done

- Verified that the schema version is correct

2023-11-07 19:30 UTC, JoshingYou1 requested changes
There's just one small change that needs to be made. Otherwise, LGTM!

2023-11-07 19:30 UTC, JoshingYou1 commented on yarn.lock
> +"vets-json-schema@https://github.com/department-of-veterans-affairs/vets-json-schema.git":
I think this needs to be updated to reflect the new commit hash as well.

2023-11-07 20:50 UTC, longmd approved these changes

2023-11-07 23:22 UTC, rmessina1010 approved these changes
LGTM

2023-11-08 16:27 UTC, JoshingYou1 approved these changes

2023-11-08 22:48 UTC, merged