Removed clear-session
department-of-veterans-affairs/vets-website pull request #26757
Opened 2023-11-17 02:04 UTC by ianmagenta

## Summary
Remove the `clear-session` from the Cerner deep linking URL.
Note: I opted to leave in the `useSingleLogoutPaths` path, despite being redundant. This function is called in several places and I figured it would be best to maintain the function's interface (in case it changes again in the future).

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/70106

## What areas of the site does it impact?
This primarily impacts the following components which all call `getCernerURL`:
- `CernerWidgets`
- `CernerAlert`
- `ScheduleCernerPage`
- `FacilitiesRadioWidget`

## Acceptance criteria
- [x] Remove the `clear-session` from the Cerner utilities file in `vets-website`
- [x] Update unit tests if required

2023-11-17 16:13 UTC, powellkerry approved these changes

2023-11-17 16:32 UTC, joeniquette commented
@ianmagenta can you please check the deeplinks to see what they list for each one, both va.gov and mhv, staging and prod. Once documented then lets make a call as to if its really safe to remove clear session.

2023-11-27 17:25 UTC, asg5704 commented on src/applications/vaos/tests/new-appointment/components/VAFacilityPage/index.unit.spec.jsx
> +      ).to.contain('pages/scheduling/upcoming');
Revert this

2023-11-27 17:25 UTC, asg5704 commented on src/applications/vaos/tests/new-appointment/components/ScheduleCernerPage.unit.spec.jsx
> +      ).to.contain('pages/scheduling/upcoming');
Revert this

2023-11-27 17:26 UTC, asg5704 commented on src/platform/utilities/cerner/index.js
> +  return `${host}${path}?authenticated=true`;
Can you wrap this in an `encodeURIComponent`

2023-11-27 17:26 UTC, asg5704 requested changes
Can you make the requested changes and I can approve. Because running the unit test locally => 110 failed tests.

2023-11-27 18:11 UTC, ianmagenta commented
@asg5704 - Good to go!

2023-11-27 18:27 UTC, asg5704 approved these changes
Thank you

2023-11-30 20:35 UTC, merged