Add pension email
department-of-veterans-affairs/vets-website pull request #26897
Opened 2023-11-28 20:17 UTC by TaiWilkin

## Summary
On the Pension Benefits application(21P-527EZ), moves the email/phone and mailing address sections to separate pages in Chapter 1 - Applicant Information, and updates the included fields for the 'Email address and phone numbers' page to match current designs. 

## How to run in local environment
1. Check out this branch locally
2. In your local environment, set the `pension_form_enabled` flipper to 'enabled' at http://localhost:3000/flipper/features/pension_form_enabled
3. Run `vets-website` and `vets-api`

## How to verify
1. Go to `http://localhost:3001/pension/application/527EZ` in your browser
2. Select 'Start your application without signing in'
3. Verify the page 'Mailing address' is in the correct location, per the designs (the fields will be updated in [#70329](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70329)
4. Verify the page 'Email address and phone numbers' includes the fields email, phone number, mobile number, and international number. Email and mobile number should be required.

## Related issue(s)
[Ticket in Github](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70330)
[Epic in Github](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63349)

## Testing done
- [x] Existing unit tests updated
- [x] New unit tests added

## Screenshots

### Desktop
| Before | After (Mailing address) | After (Phone and email) |  
| ------ | ------ | ------ | 
|<img width="349" alt="before" src="https://github.com/department-of-veterans-affairs/vets-website/assets/21046714/e180135c-168f-4766-bdce-2de4508a21df"> | <img width="431" alt="mailing" src="https://github.com/department-of-veterans-affairs/vets-website/assets/21046714/36f1a043-f999-4285-a339-029a2291749d"> | <img width="521" alt="email-phone" src="https://github.com/department-of-veterans-affairs/vets-website/assets/21046714/b70b09f9-1674-4f53-9675-067b39470283"> |

## What areas of the site does it impact?
Pension Benefits Application

## Acceptance criteria
[Ticket in Github](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70330)

### Quality Assurance & Testing
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

2023-11-29 19:47 UTC, mjknight50 commented
@mayacoforma A design comment..  it seems akward/weird to have Mailing Address listed twice.  Maybe there is some accessibility reason?

![Screenshot 2023-11-29 at 2 45 42 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/3513353/019a2298-8128-43fa-8750-07dfc01e1178)

Otherwise, looks good.

2023-11-29 19:47 UTC, mjknight50 approved these changes

2023-11-29 20:16 UTC, TaiWilkin commented
@mjknight50 That's an unfortunate side effect of the component being used - I replace it in [#26913](https://github.com/department-of-veterans-affairs/vets-website/pull/26913), which is built off of this branch, so it will be corrected as soon as that's it. We could merge that into this before proceeding with this PR, if you would prefer.

2023-11-30 19:46 UTC, mjknight50 commented on .github/CODEOWNERS
> +src/applications/pensions @department-of-veterans-affairs/pensions @department-of-veterans-affairs/va-platform-cop-frontend
Good... yes, let's make this the standard for all front-end.

2023-11-30 19:57 UTC, mjknight50 requested changes
Can the linting errors be addressed?

2023-11-30 19:57 UTC, mjknight50 commented on src/applications/pensions/config/form.js
>  import get from 'platform/utilities/data/get';
Importing from platform via platform/utilities is deprecated. Import from @department-of-veterans-affairs/platform-utilities

2023-11-30 19:57 UTC, mjknight50 commented on src/applications/pensions/config/form.js
>  import currentOrPastDateUI from 'platform/forms-system/src/js/definitions/currentOrPastDate';
There are a bunch of linting errors for deprecation of Importing from platform via platform/utilities

2023-12-01 15:45 UTC, ToddWebDev approved these changes
Nice work, Tai! I'm getting one failing unit test locally, but it seems to be passing in CI.

2023-12-01 16:39 UTC, mjknight50 approved these changes

2023-12-04 11:02 UTC, rmessina1010 approved these changes
LGTM

2023-12-04 19:55 UTC, merged