MHV-52607: Care summaries and notes content updates complete
department-of-veterans-affairs/vets-website pull request #27154
Opened 2023-12-14 23:24 UTC by mattwrightva

## Summary

- 

## Related issue(s)
### [MHV-52607](https://jira.devops.va.gov/browse/MHV-52607) - Care summaries and notes content updates ###

<img width="898" alt="Screenshot 2023-12-14 at 4 19 46 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/107576133/493ddbbd-f47b-4a3a-99d4-2e296b7b6621">
<img width="902" alt="Screenshot 2023-12-14 at 4 19 53 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/107576133/a3a2a40e-b0ef-4f45-a38c-6e2f3c5ed57d">

## Testing done

- No new unit tests or test updates needed

## Screenshots
List view:

Dischare summary:
===
Details:

## What areas of the site does it impact?
MHV Medical Records

## Acceptance criteria
AC1 Content updates completed as listed

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

2023-12-20 18:33 UTC, mmoyer-va requested changes

2023-12-20 18:33 UTC, mmoyer-va commented on src/applications/mhv/medical-records/reducers/careSummariesAndNotes.js
> +    coSignedBy: extractAuthor(record) || EMPTY_FIELD,
Double check this. I think the mapping is:
- signedBy: DocumentReference.author.reference (from NoteTO.author)
- cosignedBy: DocumentReference.authenticator.reference (from NoteTO. approvedBy)

Here is the logic in existing MHV:
![image](https://github.com/department-of-veterans-affairs/vets-website/assets/87040148/33fc5b7d-2e8b-4770-b994-29f1964efc03)

Here is [John's mapping](https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.note-mappings.html#mappings-for-via-to-mhv-fhir-phr-noteto).

2023-12-21 15:19 UTC, mmoyer-va approved these changes, later dismissed
Thanks!

2023-12-21 20:39 UTC, Asterix22 approved these changes

2023-12-22 22:12 UTC, ataker approved these changes

2023-12-22 23:11 UTC, merged