Added new verbiage
department-of-veterans-affairs/vets-website pull request #27193
Opened 2023-12-18 21:37 UTC by mkerns1

## Summary

- Updated expenses questions verbiage

## Related issue(s)

- department-of-veterans-affairs/va.gov-team#71795

## Acceptance criteria
-   Update verbiage for Dependent Expenses

2023-12-18 21:48 UTC, longmd requested changes

2023-12-18 21:48 UTC, longmd commented on src/applications/ezr/components/FormDescriptions/index.jsx
Can you please rename this file to match the name of the const and export similar to `ContactInfoDescription`? We need to also create a unit test to ensure rendering.

2023-12-18 21:48 UTC, longmd commented on src/applications/ezr/config/chapters/householdInformation/dependentEducationExpenses.js
> +import { DependentEducationExpensesDescription } from '../../../components/FormDescriptions';
Update this import upon completing the adjustment for the file naming and export convention above.

2023-12-18 22:00 UTC, longmd submitted a review, later dismissed

2023-12-18 22:00 UTC, longmd commented on src/applications/ezr/components/FormDescriptions/DependentEducationExpensesDescription.jsx
Can you add a unit test for this file to ensure we have test coverage for it? You can duplicate what was done for the contact info description.

2023-12-18 22:08 UTC, longmd approved these changes, later dismissed
LGTM. Thank you for the updates.

2023-12-20 15:17 UTC, ataker submitted a review, later dismissed

2024-05-05 00:17 UTC, closed without merging