Fixed Maintenance Banner
department-of-veterans-affairs/vets-website pull request #27509
Opened 2024-01-16 19:46 UTC by ianmagenta

## Summary
Updated the `DowntimeBanner` component so that it displays when it's unable to get an OK response from the `/backend_statuses` endpoint.

## Related issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/73465

## What areas of the site does it impact?
This impacts the `DowntimeBanner` component which is displayed on both the sign-in modal and the sign-in page.

## Acceptance criteria
- [x] Investigate which maintenance banner the identity team uses
- [x] Update vets-website so that a 400/500 or other error codes returned from `/backend_statuses` displays the maintenance banner
- [x] Update unit tests as needed

2024-01-16 19:49 UTC, ianmagenta commented
@asg5704 - All of the `DowntimeBanner` tests are currently set to be skipped, so I didn't include any new ones for this change. If you want me to add one though, happy to do so!

2024-01-16 22:19 UTC, asg5704 requested changes
Also see the Slack messages for more context

2024-01-16 22:19 UTC, asg5704 commented on src/platform/user/authentication/components/DowntimeBanner.js
> +      : [{ service: 'ssoe', serviceId: 'ssoe', status: 'down' }];
Change this to `mvi` one in the constants

2024-01-17 19:55 UTC, asg5704 approved these changes
Looks good Ian. Thank you!

2024-01-18 19:14 UTC, rsmithadhoc approved these changes

2024-01-19 20:11 UTC, merged