74878/hya vet stat image dynamic sizing
department-of-veterans-affairs/vets-website pull request #27741
Opened 2024-01-30 17:49 UTC by hasahmed2

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

https://app.zenhub.com/workspaces/veteran-status-6526f98f141b6f0ed1e059c4/issues/gh/department-of-veterans-affairs/va.gov-team/74878

https://app.zenhub.com/workspaces/veteran-status-6526f98f141b6f0ed1e059c4/issues/gh/department-of-veterans-affairs/va.gov-team/72419

https://app.zenhub.com/workspaces/veteran-status-6526f98f141b6f0ed1e059c4/issues/gh/department-of-veterans-affairs/va.gov-team/68863

## Testing done

- _Describe what the old behavior was prior to the change_
  - The image would size according to a fixed rem value
- _Describe the steps required to verify your changes are working as expected_
  - Resize the screen and verify desktop view and mobile view match these mocks: https://www.figma.com/file/UwSvhj9Yn5trM5L5W3UgH0/VA-Status---Wireframes?type=design&node-id=86-446&mode=design&t=AnmewemLpP0ggAwt-0
- _Describe the tests completed and the results_
  - Performed manual testing to verify correct looks locally as well as running all unit tests

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  ||
<img width="387" alt="image" src="https://github.com/department-of-veterans-affairs/vets-website/assets/148818278/44eef4fe-abfb-4c83-917e-1dcbf959644d">
|
| Desktop |
<img width="1635" alt="image" src="https://github.com/department-of-veterans-affairs/vets-website/assets/148818278/5d96e558-f7d9-4d60-adb3-c8b512639813">
|
<img width="1635" alt="image" src="https://github.com/department-of-veterans-affairs/vets-website/assets/148818278/c1599c34-ab3d-4126-9712-58cb885b81ef">
|

## What areas of the site does it impact?

Proof Of Veteran Status in Military Information Page

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-01-30 21:34 UTC, liztownd requested changes
One comment regarding margin spacing, otherwise looks good!

2024-01-30 21:34 UTC, liztownd commented on src/applications/personalization/profile/components/proof-of-veteran-status/ProofOfVeteranStatus.jsx
> +          <div className="vads-l-grid-container vads-u-padding-y--2 vads-u-padding-l--0">
It was driving me crazy why there was such a large margin at the left of the image. If we swap the `vads-l-grid-container` class out for `vads-l-grid-container--full` that fixes it. Then we can remove the `vads-u-padding-l--0` (which wasn't doing anything anyway)

2024-01-31 19:49 UTC, adamwhitlock1 approved these changes
tests look to be passing, and everything lgtm. @liztownd did you still have changes that still needed to be made on this?

2024-02-01 13:10 UTC, liztownd approved these changes

2024-02-01 15:26 UTC, merged