Rename va-featured-content to va-summary-box
department-of-veterans-affairs/vets-website pull request #27945
Opened 2024-02-12 21:07 UTC by ataker

## Summary
Design system is renaming the component va-featured-content to va-summary-box. This PR is to update current instances to the new name. No functional changes have been made.

## Related issue(s)

-[Update naming to Summary Box #2336](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2336)

## Testing done

- Tested updates locally in chrome

## Screenshots

<img width="662" alt="Screenshot 2024-02-10 at 19 37 20" src="https://github.com/department-of-veterans-affairs/vets-website/assets/1413938/ce2e6c57-236d-4d05-b460-f624af3fce25">
<img width="445" alt="Screenshot 2024-02-10 at 19 34 28" src="https://github.com/department-of-veterans-affairs/vets-website/assets/1413938/5fd6ddd7-01a5-4e0f-b060-117d9f95ea3d">
<img width="660" alt="Screenshot 2024-02-10 at 19 25 02" src="https://github.com/department-of-veterans-affairs/vets-website/assets/1413938/197b99a0-2add-48e5-b58a-7d4835d93e38">
<img width="670" alt="Screenshot 2024-02-10 at 19 24 48" src="https://github.com/department-of-veterans-affairs/vets-website/assets/1413938/04183973-e37c-4718-a24e-60143f1bfa93">

## What areas of the site does it impact?

None outside of these files

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

2024-02-13 20:52 UTC, micahchiang requested changes
Looks good, but I think your registry needs to be reset to yarn from verdaccio.

2024-02-13 20:52 UTC, micahchiang commented on yarn.lock
> +  resolved "http://localhost:4873/@department-of-veterans-affairs%2fcomponent-library/-/component-library-37.0.0.tgz#b36cce43dc1d53b0f0fd55c496b5ddded5035e69"
This needs to be reset to the registry.yarnpkg.com

2024-02-13 20:52 UTC, micahchiang commented on yarn.lock
> +  resolved "http://localhost:4873/@department-of-veterans-affairs%2freact-components/-/react-components-28.0.0.tgz#8ff7bbc1303a68e7ad2806e743a8ee72416aa284"
This needs to be reset to the registry.yarnpkg.com

2024-02-13 20:52 UTC, micahchiang commented on yarn.lock
> +  resolved "http://localhost:4873/@department-of-veterans-affairs%2fweb-components/-/web-components-5.0.0.tgz#81628780cef1e647dfd3f87d1473058b8cee481d"
This needs to be reset to the registry.yarnpkg.com

2024-02-14 19:34 UTC, micahchiang submitted a review, later dismissed

2024-02-15 06:27 UTC, adamwhitlock1 approved these changes, later dismissed
lgtm for authenticate experience! thanks 🚀

2024-02-15 15:02 UTC, Andrew565 submitted a review, later dismissed

2024-02-16 18:55 UTC, micahchiang commented
@ataker - just FYI, there's a PR out that includes a `va-featured-content` component. If it gets merged, please be on the look for it when you merge `main` into this branch. https://github.com/department-of-veterans-affairs/vets-website/pull/28007

2024-02-16 19:27 UTC, Mottie submitted a review, later dismissed

2024-02-20 21:41 UTC, Mottie approved these changes, later dismissed

2024-02-22 17:40 UTC, mchae-nava approved these changes
LGTM

2024-02-22 17:41 UTC, micahchiang approved these changes

2024-02-22 19:38 UTC, adamwhitlock1 approved these changes

2024-02-23 19:14 UTC, Mottie approved these changes

2024-02-23 21:53 UTC, micahchiang commented
Someday, we'll get this thing merged :rage1:

2024-02-24 00:46 UTC, merged