Update va breadcrumbs to uswds v3
department-of-veterans-affairs/vets-website pull request #27975
Opened 2024-02-14 04:18 UTC by jenniemc

## Summary

This PR updates the VaBreadcrumbs to set `uswds` to true

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#75308

## Testing done

unit test

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

Desktop
---
![Screenshot 2024-02-13 at 10 16 58 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/54327023/3a370003-b2ad-4c9f-a188-949c4ea25ad8)

![Screenshot 2024-02-13 at 9 49 28 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/54327023/4f97bfec-a166-4054-ba48-738c08076017)

![Screenshot 2024-02-13 at 9 49 51 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/54327023/997d8c0c-63e0-47fb-8c4f-625a403d8e16)

Tablet (notice the text wrap)
---
![Screenshot 2024-02-13 at 9 52 34 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/54327023/af06b86d-a421-477b-892e-d494bc16a2f2)

Covid flow desktop
---
![Screenshot 2024-02-13 at 9 57 54 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/54327023/a8595105-22ec-4cde-bc26-1309c3cdaabf)

## What areas of the site does it impact?

breadcrumb

## Acceptance criteria

- [ ] Update to `<VaBreadcrumbs>` and set `uswds` prop to true
- [ ]  Ensure the last crumb matches the page title

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-02-14 19:54 UTC, micahchiang submitted a review, later dismissed

2024-02-14 20:18 UTC, vbahinwillit requested changes

2024-02-15 19:44 UTC, vbahinwillit reviewed
Still need to remove BREADCRUMB_LISTS from constants.js. Other, than that, LGTM.

2024-02-15 19:47 UTC, vbahinwillit approved these changes, later dismissed

2024-02-21 22:05 UTC, vbahinwillit approved these changes

2024-02-21 22:13 UTC, micahchiang approved these changes

2024-02-21 22:46 UTC, merged