[View Payments] Upgrade web components to their V3 versions
department-of-veterans-affairs/vets-website pull request #28025
Opened 2024-02-16 17:31 UTC by jerekshoe

## Summary
Upgrading all of the web components in the View Payments application to use their V3 versions. Also removing `uswds="false"` on web components that don't have a V3 version currently

## Related issue(s)
- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#76127

## Screenshots

### `va-alert`
|         | Before | After |
| ------- | ------ | ----- |
| Desktop |        |       |

### `va-table` / `va-pagination`
|         | Before | After |
| ------- | ------ | ----- |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-02-16 20:19 UTC, pmclaren19 commented on src/applications/disability-benefits/view-payments/components/view-payments-lists/ViewPaymentsLists.jsx
> +      );
Line 128 also has a va-alert so we should update that as well!

2024-02-16 21:43 UTC, micahchiang approved these changes, later dismissed

2024-02-16 21:48 UTC, pmclaren19 approved these changes
Thanks for updating! LGTM :)

2024-02-19 20:17 UTC, pmclaren19 requested changes
@jerekshoe I think we actually can remove this prop entirely? https://dsva.slack.com/archives/C055573C508/p1708110642607439 And by default it will be set to true.

2024-02-20 18:08 UTC, pmclaren19 commented
> @jerekshoe I think we actually can remove this prop entirely? https://dsva.slack.com/archives/C055573C508/p1708110642607439 And by default it will be set to true.

Talked with the Team this morning in stand up and this ticket is fine to merge, @jerekshoe will just want to create another ticket for the work to remove the `uswds=true` when [this](https://github.com/department-of-veterans-affairs/component-library/pull/1043) pr is merged.

2024-02-20 18:08 UTC, pmclaren19 approved these changes

2024-02-20 18:09 UTC, merged