Add refill page and feature flag to medications
department-of-veterans-affairs/vets-website pull request #28169
Opened 2024-02-23 22:15 UTC by agravell047

## Summary

- Added refill page to MHV medications app
- Added unit tests for new page
- Added feature flag to hide this until ready for prod
- Added API requests for retrieving refillable list, refilling multiple rx's
- Added custom back button to replace breadcrumbs and match mocks
- Added pagination for renewable prescriptions only

## Related issue(s)

https://jira.devops.va.gov/browse/MHV-55039
>AC1: Breadcrumb style matches mocks, it is styled this way because it is not in the navigation flow but is instead a sub-task flow
AC2: You have # prescriptions ready to refill should reflect the number of all meds that are currently able to be filled or refilled. If there is only one the content should change to "You have 1 prescription ready to refill" (singular)
AC3: Medications should be sorted alphabetically A-Z in the checklist and should not be paginated
AC4: Request refills button should show as "Request refill" when only one prescription is available to be refilled
AC5: Clicking select all button will check all the boxes in the list. 
AC6: Learn how to renew prescriptions link should take users to the "More ways to manage.." section on the About medications page with the accordion open. 
AC7: Go to your medications list should take users back to main list page
AC8: In the prescriptions you may need to renew sections, the showing # should reflect all recently expired, discontinued, and meds that ran out of refills for the last 6 months
AC9: If there is only one available the content should be singular
AC10: Medications should be sorted alphabetically A-Z
AC11: This section should be paginated if the list is over 20 medications. When navigating from one page to the next, the checkboxes should not be affected. If this is not possible let UCD team know

## Testing done

- Tested locally
- Ran unit tests locally
- Added unit tests

## Screenshots

![Screenshot 2024-02-23 at 4 12 13 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/146013972/696772e4-ad76-49ff-9921-8313c6a40830)
![Screenshot 2024-02-23 at 3 45 52 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/146013972/0d8e9a53-8167-4caf-b76c-8869e5a0efd2)

## What areas of the site does it impact?

MHV Medications app

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-02-23 23:02 UTC, robertbylight requested changes

2024-02-23 23:07 UTC, agravell047 commented on src/applications/mhv/medications/tests/containers/RefillPrescriptions.unit.spec.jsx
> +    const link = await screen.findByTestId('medications-page-link');
I changed the other one to back-to-medications-page-link, if you do a pull it should pass now

2024-02-26 17:15 UTC, robertbylight approved these changes
Good job! Breaking down the refill Container was a good choice!

2024-02-26 20:09 UTC, micahchiang approved these changes
In the future, I'd encourage your team to submit PRs in a more piecemeal manner. Big PRs like this are difficult for reviewers to consume.

2024-02-26 20:09 UTC, micahchiang commented on src/applications/mhv/medications/components/RefillPrescriptions/RenewablePrescriptions.jsx
> +        <strong>Note:</strong> If your prescriptions isn’t in this list, find it
Should `prescriptions` be singular here?

2024-02-26 20:09 UTC, micahchiang commented on src/applications/mhv/medications/components/RefillPrescriptions/RenewablePrescriptions.jsx
> +        {renewablePrescriptionsList.length !== 1 ? 's' : ''} you may need to
Would there ever be a situation where `renewablePrescriptionsList` is `null` or `undefined`?

2024-02-26 20:18 UTC, merged