removes burials-poc-v6
department-of-veterans-affairs/vets-website pull request #28186
Opened 2024-02-26 18:34 UTC by CaitHawk

Removes the `burials-poc-v6` application folder including components & unit tests and any references to it.

[Zenhub Ticket](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/77051)

2024-02-26 18:49 UTC, asg5704 requested changes
I pulled down your branch and it looks mostly good. Can you also remove the `burial-poc-v6` from the following files:

**vets-website**
- `.github/CODEOWNERS`
- `.github/workflows/continuous-integration.yml`
- `jsconfig-example.json`

**content-build**
- Remove `burial-poc-v6` app in the `registry.json`?

2024-02-26 19:33 UTC, Midge-dev approved these changes, later dismissed
@CaitHawk This was on my list so thank you! Approved

2024-02-26 19:44 UTC, asg5704 approved these changes, later dismissed

2024-02-26 19:44 UTC, asg5704 commented
Thank you @CaitHawk for removing this application that hasn't been worked on in almost 2 years. 🚀

2024-02-27 20:44 UTC, micahchiang requested changes
Hi there - I'm going to request changes on this for the time being. I believe
there's a VFS forms team that plans on using some of the things referenced in here, though I'll let @humancompanion-usds weigh in on that. @jeana-adhoc and/or @rhasselle-oddball may also have more insight into that. 

If that isn't the case, then I'll circle back and approve this PR once things have been confirmed.

2024-03-07 19:11 UTC, asg5704 commented
> Hi there - I'm going to request changes on this for the time being. I believe there's a VFS forms team that plans on using some of the things referenced in here, though I'll let @humancompanion-usds weigh in on that. @jeana-adhoc and/or @rhasselle-oddball may also have more insight into that.
> 
> If that isn't the case, then I'll circle back and approve this PR once things have been confirmed.

@micahchiang Are we still waiting for people/teams to take a look at this?

2024-03-07 19:28 UTC, asg5704 approved these changes

2024-03-07 21:32 UTC, humancompanion-usds commented
Yes, the Veteran-facing Forms team will be implementing the Review page from this prototype in the Forms Library. Please do not remove this until they have it. Thanks! 

@ndsprinkle and @jeana-adhoc - Can gather what you need from this prototype and let us know when it is okay to remove? Thanks.

2024-07-08 16:43 UTC, closed without merging