Use vets json schema fixtures for pension cypress tests
department-of-veterans-affairs/vets-website pull request #28228
Opened 2024-02-28 14:57 UTC by scottsdevelopment

## Summary

- Point cypress test data to the new vets json schema examples from the package.

## Related issue(s)

- department-of-veterans-affairs/va.gov-team#75946

## Testing done

- All cypress tests pass

2024-02-28 16:17 UTC, mjknight50 commented on package.json
> +    "vets-json-schema": "https://github.com/department-of-veterans-affairs/vets-json-schema.git#a07ab99bc6d6f5896f7315ad21de5507737e1401"
Would it make sense to move away from git commit toward version number?

2024-02-28 17:09 UTC, danlim715 approved these changes, later dismissed

2024-03-01 14:54 UTC, Andrew565 commented
PR has failing required tests, opting not to review at this time. - Tier 2/FE COP

2024-03-05 20:43 UTC, wayne-weibel requested changes
Am seeing the below error when running locally
`yarn cy:run --spec src/applications/pensions/tests/e2e/pensions.cypress.spec.js`

![image](https://github.com/department-of-veterans-affairs/vets-website/assets/5315216/0b789d3e-a757-4061-8437-75d3581f13ba)

2024-03-06 17:01 UTC, mjknight50 approved these changes, later dismissed
I ran some tests and it looked good.

2024-03-06 20:22 UTC, wayne-weibel approved these changes
If all other cypress tests are still passing this will work for now

2024-03-07 20:41 UTC, wayne-weibel commented
@Andrew565 all of the required tests (should) be passing now.

2024-03-08 21:03 UTC, Andrew565 approved these changes

2024-03-08 21:04 UTC, merged