[VA-17071] Update Facility Locator with components
department-of-veterans-affairs/vets-website pull request #28433
Opened 2024-03-07 22:15 UTC by maxx1128

## Summary

This is a series of component updates to what's being used in the facility locator. Some are being updated from v1 to v3, some v1 components are being brought in, and some v3 components are being brought in. All the specifics are in [ticket #17071.](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17071)

## Related issue(s)

- _Link to ticket created in va.gov-cms repo_
[department-of-veterans-affairs/va.gov-cms#17071](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17071)

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-03-14 19:28 UTC, maxx1128 commented
The final tests blocking this ticket are `src/applications/facility-locator/tests/e2e/accessibility.cypress.spec.js`, but I haven't been able to find a workaround since the `cypress-plugin-tabs` currently doesn't let you tab into elements in the shadow DOM. Pausing this for now.

2024-03-19 00:22 UTC, jilladams commented
@maxx1128 what was outcome of checking with @laflannery re: the shadow DOM and whether this PR should go ahead as is or pivot?

2024-03-26 23:56 UTC, eselkin submitted a review, later dismissed
LGTM

2024-03-26 23:56 UTC, eselkin commented on src/applications/facility-locator/components/search-results-items/Covid19Result.jsx
> +              target="_blank"
I'm not sure it respects the target and rel props.

2024-03-28 20:32 UTC, laflannery commented
@maxx1128 I am using this to test: http://3bd545180a26dd67af1e3d182b997884.review.vetsgov-internal/find-locations

Updates needed:
1. The breadcrumb component is present but empty:
![Screenshot 2024-03-28 at 2 56 37 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/b80c7df2-897b-4140-8451-6e8b0ca4e9e2)

2. When you select Community provider's - the facility type field is no longer aligned with the Service type field
![Screenshot 2024-03-28 at 3 55 53 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/cb5b7ae9-93d1-48f0-8295-987a3ba97c17)

3. The service type field is also not acting conditionally correctly as it should be. It should not be active for Vet Centers, Cemeteries or Community Pharmacies but it currently is - it just happens to be empty
![Screenshot 2024-03-28 at 3 58 56 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/c98696c0-b9f9-4426-8ef7-98d7d96c0e71

4. There is a lot of space between the 2 lines of filters now - are you able to change the `margin-top` to 0 on the "Facility type" label or is this not possible because it's within the shadow root? or could you maybe do this another way to get the space indicated in the screenshot smaller?
![Screenshot 2024-03-28 at 3 44 52 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/791318b7-3ca5-4a88-910d-b1e82631452b)
5. Can you please unbold the input text for the City state field? Because this field is not a component it doesn't match the v3s
![Screenshot 2024-03-28 at 3 49 59 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/25053f00-183c-4636-ad77-a8cf45331075)

6. The Alerts used for the operating statutes should be using the "slim" version, meaning we need to add the `slim` prop to these.
![Screenshot 2024-03-28 at 3 27 50 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/66668759-e139-493c-9a15-b4ece79a8001)

7. Can you update the "Try using our other tools to search" link to use `<va-link>` component?
![Screenshot 2024-03-28 at 4 25 24 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/953716a1-c126-423e-b145-4bc4520cb671)

8. Can you update the search button to be a v3 `<va-button>` component?
![Screenshot 2024-03-28 at 4 26 42 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/66126d39-305f-4920-bfb1-90ef3f694cfb)

9. Also, and I hate to do this - but I completely did not realize there was an alert being used when the Facility locator doesn't work. I saw it on the ngrok today when we were trying to test. This is a v1 component and should be updated to v3. Are we able to do this? I understand if not and if we should open a new ticket for this.
![Screenshot 2024-03-28 at 2 25 01 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/4d04f4dc-e4cb-4705-9f9b-9c802907ec86)

2024-03-29 20:51 UTC, jilladams submitted a review, later dismissed
Adding a review to capture that Laura's review feedback is merge-blocking: https://github.com/department-of-veterans-affairs/vets-website/pull/28433#issuecomment-2026064419

2024-04-01 17:32 UTC, maxx1128 commented
@laflannery I made updates based on your feedback except for the below points:

8. The submit button didn't work as a `<va-button>` component since it broke the related functionality.
9. This specific alert isn't even using a v1 component and is some entirely custom markup. Moving that to a v3 component from that would be a separate ticket.

2024-04-01 19:28 UTC, jilladams commented
@maxx1128 in this case, the current ticket for this PR includes componentizing custom code that isn't yet in a component. I left it that way, since we were already in PR. Can you speak to effort to adopt that component? We can def break out into a separate ticket since it's not on a deadline now, but if it's small to do and we can kill it here, let me know how that would affect your sprint?

2024-04-01 19:40 UTC, maxx1128 commented
> @maxx1128 in this case, the current ticket for this PR includes componentizing custom code that isn't yet in a component. I left it that way, since we were already in PR. Can you speak to effort to adopt that component? We can def break out into a separate ticket since it's not on a deadline now, but if it's small to do and we can kill it here, let me know how that would affect your sprint?

From what I saw, it didn't look like it would be easy to copy and paste it into the new component. I wasn't able to replicate that view locally, however. I'll look at it again and see if it could be knocked out relatively quickly.

2024-04-02 13:29 UTC, laflannery commented
@maxx1128 3 more comments. 2 I think I missed during my first review which I apologize for and 1 is new:
1. The service type field should not be required. I confirmed on the current Prod Facility Locator
2.  The service type field doesn't have a border anymore on first load, Vet Centers, Cemeteries or Community Pharmacies:
![Screenshot 2024-04-02 at 9 25 40 AM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/f11e0c72-8ded-415d-9579-9681336d9399)
3. When the Facility type field has an error, it's getting duplicate styles because the component has styles and the custom styles have also been retained:
![Screenshot 2024-04-02 at 9 19 50 AM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/33a74ada-aaac-486c-8d26-33f920962bd2)
   - We should remove the custom error styles and only use the component styles:
      - Remove class `usa-input-error` from the wrapping div
      - Remove the `va-select` element from the CSS `padding:0` declaration
      - Remove the `bor-rad` class from the `<va-select>` this will make the red line lok nicer when it appears.
![Screenshot 2024-04-02 at 9 27 41 AM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/8568a86e-f3b1-4701-bf81-82230c782337)
![Screenshot 2024-04-02 at 9 29 03 AM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/89d82207-fdfe-4113-aa79-5b695f891c89)

2024-04-02 22:14 UTC, maxx1128 commented
@laflannery I addressed the second round of feedback as well. For point 2, that state without a border (`inert`) is the closest thing the v3 component has to a disabled state - I got around it by lowering the opacity and removing pointer events, which keeps users from clicking on it but doesn't remove keyboard events. If that doesn't work, we may need to stick with `inert` for now and make a ticket for the design system team to include the border styling in that state.

<img width="1045" alt="Screen Shot 2024-04-02 at 6 03 04 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/10790736/978c1ff6-cf8e-4bfc-abeb-999535d38684">

I also made the changes you listed for point 3 and took a screenshot so you can more quickly check the changes.

<img width="1056" alt="Screen Shot 2024-04-02 at 6 08 00 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/10790736/8890c9da-5c2f-481e-b8c7-6e93e21abb11">

2024-04-03 02:12 UTC, eselkin requested changes
minor tweak, otherwise looks great. Breadcrumbs work. Search works.

2024-04-04 16:52 UTC, laflannery commented
@maxx1128 I also tried many things to get the component to work for our use case but unfortunately it just doesn't. The best thing we can do right now is to go back to the custom implementation we had because that is functional, accessible and visually correct. Which I know isn't great because you worked hard but it's the best option for what we are working with. That being said, can you:
1. Put the custom implementation of the Service Type field back with 2 small adjustments:
   - Remove `class="bor-rad" style="font-weight: bold;"` form the `<select>` element because this will align the styles with the other fields
![Screenshot 2024-04-04 at 12 48 54 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/1118a8ee-b455-4833-8f7b-c964b78d4369)
2. The error state for the Facility Type field is still not quite correct:
![Screenshot 2024-04-04 at 12 51 01 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/82def947-ffce-4b32-9cc9-f86ccfd71ec9)
   - You need to remove the VADS padding that has been added to the component and then this should fix it:
![Screenshot 2024-04-04 at 12 51 57 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/139bf090-9c4e-452b-b41d-592c9ca5bc1d)
![Screenshot 2024-04-04 at 12 52 26 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/3e63e661-9997-4c44-801a-f4c448f24c69)

2024-04-09 18:12 UTC, eselkin approved these changes
LGTM

2024-04-09 20:57 UTC, laflannery approved these changes
LGTM!

2024-04-10 15:19 UTC, merged