DR | Update Max and Min filesize error content
department-of-veterans-affairs/vets-website pull request #28525
Opened 2024-03-12 22:04 UTC by rocio-desantiago

## Summary

- _(Summarize the changes that have been made to the platform)_
   > remove `enableShortWorkflow` from errorMessages updated in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/28402). No reason for error messages to be different locally vs staging/prod.

   > remove `enableShortWorkflow` from buttons so that the same buttons show up in both local and staging/production environments. No reason for buttons to show up different locally vs staging/prod.

- _(If bug, how to reproduce)_
   > Not a bug

- _(What is the solution, why is this the solution)_
   > Remove `enableShortWorkflow` from code where error messages related to this ticket are called.

- _(Which team do you work for, does your team own the maintenance of this component?)_
   > Benefits Team 1 - Decision Reviews

- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_
   > n/a

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#76161
- _Previous PR_
  > [PR #28402](https://github.com/department-of-veterans-affairs/vets-website/pull/28402) 
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/va.gov-team#74457

## Testing done

- _Describe what the old behavior was prior to the change_
    > No behavior change
- _Describe the steps required to verify your changes are working as expected_
    > -  Locally, upload a large file that exceeds 100MB
           - You should see the following error: `We couldn’t upload your file because it’s too large. File size must to be less than 100 MB` plus the `Upload a new file` and `Cancel` button pair as shown in staging.
    > -  Upload a small file less than 1KB 
            - You should see the following error: `We couldn’t upload your file because it’s too small. Please delete this file. Try uploading a file that’s 1KB or more.` plus the `Upload a new file` and `Cancel` button pair as shown in staging.

## Screenshots

| File Size | Before | After | 
| ------- | ------- | ------- | 
| Small PDF Error | <img width="600" alt="tinyPDF-file_error_locally" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/77473afb-d851-4ea2-acdf-8e05a859831b"> | <img width="600" alt="tinyPDF-file_error" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/13f93795-3646-4b72-a647-31d04f698715"> |
Large PDF Error | <img width="600" alt="largePDF-file_error_locally" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/37f3d432-ddec-411b-80b5-9ca03c1b1e4d"> | <img width="600" alt="largePDF-file_error" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/37054305/db9f70dc-b1e1-46bb-964c-038deaecc7d7"> |

## What areas of the site does it impact?
- Decision Reviews 
- File Upload for too large or too small files

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_
**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

2024-03-13 14:47 UTC, powellkerry approved these changes, later dismissed

2024-03-13 20:15 UTC, Mottie requested changes

2024-03-13 21:51 UTC, rocio-desantiago commented on src/platform/forms-system/src/js/actions.js
> -      const fileTooBigErrorMessage = enableShortWorkflow
removed

2024-03-13 21:51 UTC, rocio-desantiago commented on src/platform/forms-system/src/js/fields/FileField.jsx
> +                          uswds={uswds}
done

2024-03-14 14:51 UTC, powellkerry approved these changes

2024-03-14 15:29 UTC, Mottie approved these changes

2024-03-14 15:51 UTC, merged