Update direct deposit content and flow.
department-of-veterans-affairs/vets-website pull request #28620
Opened 2024-03-18 19:18 UTC by scottsdevelopment

## Summary

- Updated the direct deposit information workflow and content on various pages.

## Related issue(s)

- department-of-veterans-affairs/va.gov-team#77021

## Testing done

- Manual testing
- Cypress testing

## Screenshots

![Screenshot 2024-03-18 at 3 03 54 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/51915366/08f15a7c-6be4-48df-b513-626ee58e4e1b)
![Screenshot 2024-03-18 at 3 04 13 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/51915366/a80ae9ae-e83e-422d-a244-98db22168432)
![Screenshot 2024-03-18 at 3 04 02 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/51915366/34b79638-e676-49e1-9c14-05645f1e560a)
![Screenshot 2024-03-18 at 3 03 17 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/51915366/73ce618e-97b7-40a1-9035-e204e371fe1e)

## What areas of the site does it impact?

- Pension form

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.

## Requested Feedback

- Addressing certain spacing concerns, required fields, getting tests to pass etc.

2024-03-20 01:40 UTC, ToddWebDev requested changes
I have a few suggested changes.

2024-03-20 15:36 UTC, ToddWebDev submitted a review, later dismissed

2024-03-21 14:18 UTC, ToddWebDev commented on src/applications/pensions/config/form.js
>              },
This view field is actually unnecessary. We don't need to organize or save the title and description to the redux store.

```suggestion
        ...titleUI(
              'Account information for direct deposit',
              AccountInformationAlert,
            ),
```

2024-03-21 14:18 UTC, ToddWebDev commented on src/applications/pensions/config/form.js
>                },
We can remove it from the schema too.

```suggestion

```

2024-03-21 14:45 UTC, ToddWebDev approved these changes, later dismissed

2024-03-25 15:09 UTC, ToddWebDev approved these changes, later dismissed

2024-03-25 18:44 UTC, jamigibbs approved these changes

2024-03-25 19:20 UTC, ToddWebDev approved these changes

2024-03-25 19:45 UTC, merged