[MHV-56098, MHV-55648, MHV-56084] V3 Component Fixes - SM
department-of-veterans-affairs/vets-website pull request #28789
Opened 2024-03-26 16:11 UTC by vsaleem

- Removed ALT text from 'unread message' icon
- Adjusted pagination length to 7 on MessageList pages
- Fixed text wrapping on Attachment Name when adding new files for attachments

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#0000
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-04-03 12:56 UTC, oleksii-morgun commented on src/applications/mhv/secure-messaging/components/ThreadList/ThreadListItem.jsx
> +                alt=""
Should we consider just removing this attribute if it is not used?

2024-04-03 12:57 UTC, oleksii-morgun approved these changes, later dismissed
Looks great 👍🏻 Just one comment re: the `alt` prop, but I will leave it up to you to determine. Otherwise, approved ✅

2024-04-03 13:52 UTC, KyleCardwell approved these changes, later dismissed
Looks good!  (Same question about the empty alt attribute)

2024-04-03 18:16 UTC, rmessina1010 submitted a review, later dismissed
LGTM

2024-04-03 18:24 UTC, vsaleem commented
The `alt` tag was removed - got confirmation from a11y that `alt` is not needed since we are using aria-hidden in this component. @oleksii-morgun @KyleCardwell

2024-04-04 19:50 UTC, oleksii-morgun requested changes
since the new `src/applications/mhv-secure-messaging` directory is up, let's migrate this code over to the new directory

2024-04-08 15:30 UTC, KyleCardwell approved these changes, later dismissed
Looks good!

2024-04-08 19:09 UTC, oleksii-morgun commented on src/applications/mhv/secure-messaging/components/AttachmentsList.jsx
> +                    <span className="attachment-name-text">{file.name}</span>(
I would suggest not to include these old dir changes whatsoever. They may break cypress tests (as tests are not updated in the old dir) and cause more confusion

2024-04-08 19:09 UTC, oleksii-morgun commented on src/applications/mhv/secure-messaging/components/ThreadList/ThreadsList.jsx
> +          </div>
same here as above

2024-04-08 22:44 UTC, oleksii-morgun approved these changes
Looks good 👍🏻

2024-04-09 20:04 UTC, merged