VACMS-16910: DUW Branch, Year, Month logic
department-of-veterans-affairs/vets-website pull request #28838
Opened 2024-03-27 23:56 UTC by chriskim2311

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#0000
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-03-29 17:22 UTC, chriskim2311 commented
@laflannery @thejordanwood  This PR is ready for your review!
http://ac9f0484a44ca55b0120d613e59dc10b.review.vetsgov-internal/discharge-upgrade-instructions/introduction

2024-04-01 13:07 UTC, laflannery commented
@chriskim2311 I'm getting a 502 error, can you take a look when you get a min?

2024-04-04 17:41 UTC, chriskim2311 commented
@randimays I have 3 commented out unit tests wondering if you can run one of them locally and see if you can figure out why they are not working properly.

2024-04-04 18:12 UTC, laflannery commented
@chriskim2311 A few comments:
1. I already mentioned this in slack - can you add an `href` to the Get started link on the introduction page?
2. The 2 select box questions (year and month discharged) we need to format like we do the Zip code screen in Income limits so they would look like the screenshot and then we would be able to force focus to the H1 like we are doing on the radio button question:
![Screenshot 2024-04-04 at 2 05 49 PM 1](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/5432a45c-6105-4d57-940c-02f021061891)
3. The middle part of the `<title>` currently says "PACT Act", can you update this to say "Discharge Upgrade"?
4. We need to update the focus management when an error occurs (currently we have an existing backlog ticket to this in PACT ACT) but the current behavior is that when you press Continue without making any selections, the error message is announced but keyboard focus remains on the Continue button. What should happen is that when there's a validation error when a user presses Continue, focus moves back to the containing element of the field with the error with tabindex="-1". This will make it so that, your first tab stop will now be the input where you can correct the error.

2024-04-04 20:12 UTC, randimays requested changes
Some observations:

1. I missed this in your previous PR:

<img width="701" alt="Screenshot 2024-04-04 at 1 40 10 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/19175324/99c48051-4df7-4614-804d-8373995a7368">

There's a typo in the word "Department" 4 lines from the bottom.

2. Anywhere that we're using `uswds="true"` or `uswds`, we can remove this. If the component has a v3 version, it's default now and we don't need to add the prop. Double-check that styling/functionality are the same though, please.

3. The spacing between the question and options here is quite large. I know we are using web components, but is it possible to tighten up the spacing here?

<img width="582" alt="Screenshot 2024-04-04 at 1 52 03 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/19175324/f1df48b3-9504-4fb1-83d7-325c0637eb47">

4. This may be fixed by the formatting adjustment Laura suggested to mirror Income Limits, but I'm noticing a big size discrepancy between the questions on mobile

<img width="402" alt="Screenshot 2024-04-04 at 1 56 05 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/19175324/de2b961a-249e-4b13-bed3-5f726d364413">
<img width="402" alt="Screenshot 2024-04-04 at 1 56 00 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/19175324/f5f7fbc1-f921-4c46-a987-ff9fee0ab4f4">

5. This first page should have a back button

<img width="1046" alt="Screenshot 2024-04-04 at 1 58 55 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/19175324/9e19b900-af34-48d8-b8bb-4a7ea886eabb">

6. Make sure you address whatever `Github Actions / Linting` warnings come up, if possible. We can always ignore the "something something platform import is deprecated" ones, but the others are usually helpful.

2024-04-04 20:12 UTC, randimays commented on src/applications/discharge-wizard/tests/v2/DischargeMonth.unit.spec.js
> +//       duwform: {
This should be updated wherever you use it - it's `duwForm`. These syntax errors cause that not helpful generic test failure :(

2024-04-04 20:12 UTC, randimays commented on src/applications/discharge-wizard/tests/v2/DischargeMonth.unit.spec.js
> +//   setServicePeriod: () => {},
This should be `setDischargeMonth`

2024-04-04 20:12 UTC, randimays commented on src/applications/discharge-wizard/tests/v2/DischargeYear.unit.spec.js
> +//   setServicePeriod: () => {},
This should be `setDischargeYear`

2024-04-04 20:12 UTC, randimays commented on src/applications/discharge-wizard/tests/v2/DischargeYear.unit.spec.js
> +//       duwform: {
Update to `duwForm`

2024-04-04 20:12 UTC, randimays commented on src/applications/discharge-wizard/tests/v2/DischargeYear.unit.spec.js
> +//       duwform: {
Update to `duwForm`

2024-04-04 20:12 UTC, randimays commented on src/applications/discharge-wizard/components/v2/questions/DischargeYear.jsx
> +DischargeYear.propTypes = {
Update PropTypes here, same as DischargeMonth

2024-04-04 20:12 UTC, randimays commented on src/applications/discharge-wizard/tests/v2/ServiceBranch.unit.spec.js
> +//       duwform: {
Update to `duwForm`

2024-04-04 20:12 UTC, randimays commented on src/applications/discharge-wizard/tests/v2/ServiceBranch.unit.spec.js
> +//       duwform: {
Update to `duwForm`

2024-04-04 20:21 UTC, chriskim2311 commented on src/applications/discharge-wizard/actions/index.js
> +  DW_UPDATE_FIELD,
This is the previous v1 action. Added a comment to distinguish

2024-04-04 20:29 UTC, chriskim2311 commented on src/applications/discharge-wizard/routes.jsx
> +      { path: 'introduction1', component: HomePage },
For some weird reason I get a loading spinner for /introduction. This was for testing but will remove

2024-04-04 20:31 UTC, randimays commented on src/applications/discharge-wizard/routes.jsx
> +      { path: 'introduction1', component: HomePage },
Do you have `yarn watch` or `yarn watch --env entry=discharge-wizard` running? For some reason, when I try to run it from the app folder, it never resolves 🤔 Not sure what causes that though.

2024-04-04 20:37 UTC, chriskim2311 commented on src/applications/discharge-wizard/routes.jsx
> +      { path: 'introduction1', component: HomePage },
Using yarn watch. Not sure why either but the route works in staging and in previous review instances

2024-04-04 21:26 UTC, randimays requested changes

2024-04-04 21:26 UTC, randimays commented on src/applications/discharge-wizard/components/v2/questions/DischargeYear.jsx
> +import { pageSetup } from '../../../../pact-act/utilities/page-setup';
This import should be udpated

2024-04-04 21:26 UTC, randimays commented on src/applications/discharge-wizard/components/v2/questions/DischargeYear.jsx
> +  setDischargeYear: PropTypes.func.isRequired,
Check out the lint warning here 👀

2024-04-04 21:26 UTC, randimays commented on src/applications/discharge-wizard/components/v2/questions/shared/Dropdown.jsx
> +Dropdown.propTypes = {
Several lint warnings here 👀

2024-04-05 13:51 UTC, laflannery commented
From my previous comment, 1-3 look good and 5 we discussed and we don't need because it's only 1 question/page, However, the focus management still needs some work:
- One the 2 select box fields, the `tabindex="-1" is staying on the component which means that if I need to go back to the field for any reason I can't, because it's need removed from the tab order. Here's [an example of a test form](https://staging.va.gov/mock-form-patterns/mailing-address) where this is being done that is a good example
- Also, the first radio button question we need to have this same focus behavior on, [The first step of the mock form](https://staging.va.gov/mock-form-patterns/relationship-to-veteran) has a radio group as an example

2024-04-05 16:17 UTC, thejordanwood commented
@chriskim2311 I agree with all of the spacing notes that Randi gave here. 

@laflannery There's a year box in the [past income limits flow](https://www.va.gov/health-care/income-limits/year). Should the year/month discharge questions look like this too?

![Screenshot 2024-04-05 at 11 16 10 AM](https://github.com/department-of-veterans-affairs/vets-website/assets/104526584/175e4ddc-8102-43c9-8ec0-cdb70ac2b7e3)

2024-04-05 16:21 UTC, laflannery commented
@thejordanwood Yes, this is correct. Chris changed both of these on his latest updates to match what you showed  - the only difference is that we don't need the visual "Required" indicator since this is the only question on the screen (technically we don't need it on Income limits either)
![Screenshot 2024-04-05 at 12 20 17 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/106678594/83530a46-ef66-4d2b-97ce-a5d0ad4218dc)

2024-04-05 16:32 UTC, thejordanwood commented
@chriskim2311 I see you just updated the screenshots–thank you!

1. I think the spacing between the header and the fields is still a bit too large. For income limits, it's about 32px of space so we should stay consistent with that. 
2. If we're staying consistent with income limits, the spacing between the fields and the back/continue buttons should be 16px. 
3. Looks like @laflannery answered my question about the year/month fields. No need to include the "Required" indicator. Can we change the field box to say "Select a year" or "Select a month" instead of "-Select-"?
4. About the error messages: What you have here is correct, but they all need periods at the end. Also we may need to say "Select a branch of service." instead of just branch. 

Apologies for the delayed review on my part!

2024-04-05 17:08 UTC, thejordanwood commented
@chriskim2311 In that case, then we can move forward with the spacing as is.

2024-04-05 18:55 UTC, randimays approved these changes
From my earlier comments:

1. ✅ 
2. ✅ 
3. I realized this weird spacing is the same on PACT Act. Nothing we can do here ✅
4. ✅ 
5. ✅ 
6. ✅ 

LGTM, great work! 💥

2024-04-05 20:32 UTC, merged