Add margin when this area is not expanded as well
department-of-veterans-affairs/vets-website pull request #28997
Opened 2024-04-04 22:46 UTC by lee-delarm6

## Summary

- Added 16px more margin when additional info section is not opened to expand ease of clicking these options, and space between additional info and buttons when near bottom

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/79719

## Testing done

- Visual testing

## Screenshots

![Screenshot 2024-04-04 at 6 40 18 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/135059743/24f2683d-0998-4293-8537-cc632baee7bd)
![Screenshot 2024-04-04 at 6 40 15 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/135059743/2120e02c-ef4e-4a1e-a576-6d97363083b2)
![Screenshot 2024-04-04 at 6 40 04 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/135059743/d03338a2-1d72-4272-8870-37aa73aa2243)
![Screenshot 2024-04-04 at 6 39 22 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/135059743/9d0bd61e-9435-458f-ba79-9bc671ae06ee)
![Screenshot 2024-04-04 at 6 39 15 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/135059743/04332284-cf40-4314-8999-6993d97f0550)
![Screenshot 2024-04-04 at 6 39 02 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/135059743/3794b6e5-3bc9-4ce6-a3ed-3ebcc732ce99)
![Screenshot 2024-04-04 at 6 38 57 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/135059743/2ad25a0b-e6fd-482a-807c-7dcc40a1b1cd)

## What areas of the site does it impact?

- Spacing below additional info on TravelPages

2024-04-05 14:47 UTC, wullaski requested changes

2024-04-05 14:47 UTC, wullaski commented on src/applications/check-in/components/pages/TravelPage/index.jsx
> +              <React.Fragment key={index}>
Since we need a wrapper for margin now we can remove the React.Fragment

2024-04-08 14:41 UTC, powellkerry approved these changes

2024-04-08 15:28 UTC, brianseek approved these changes
LGTM!

2024-04-10 13:35 UTC, wullaski approved these changes
🚢

2024-04-10 13:39 UTC, merged