MHV-55434 the txt file download revision for blue button - hotfix
department-of-veterans-affairs/vets-website pull request #29092
Opened 2024-04-09 20:38 UTC by Wyzardsleeves

## Hotfix for [MHV-55434](https://github.com/department-of-veterans-affairs/vets-website/pull/28871)

## Summary

- Updated content/data for consolidated reports.
- Is not a bug.
- Updated existing content and added new lines of code.
- MHV Medical Records.

## Related issue(s)
### [MHV-MHV-55434](https://jira.devops.va.gov/browse/MHV-55434) - Back Button focus issue all domains ###

![Screenshot 2024-03-28 at 3 28 16 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/9909777/f09c3cd2-1490-44d4-bba8-87a918b08520)

![Screenshot 2024-03-28 at 3 28 48 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/9909777/f00b0e58-2888-4007-be42-b6872a25e8a3)

## Testing done

-  Manual testing

## What areas of the site does it impact?
MHV Medical Records

2024-04-09 20:42 UTC, powellkerry approved these changes, later dismissed

2024-04-09 20:50 UTC, mmoyer-va requested changes

2024-04-09 20:50 UTC, mmoyer-va commented on src/applications/mhv/medical-records/util/txtHelpers/downloadRecords.js
> +            record.type === '11506-3'
You should use constants here. We show the first set of fields if the `record.type` is one of:
- `loincCodes.PHYSICIAN_PROCEDURE_NOTE`
- `loincCodes.CONSULT_RESULT`

2024-04-10 19:25 UTC, mmoyer-va requested changes

2024-04-11 13:57 UTC, mmoyer-va approved these changes

2024-04-11 14:13 UTC, merged