79244 footer placeholder
department-of-veterans-affairs/vets-website pull request #29171
Opened 2024-04-12 20:03 UTC by emily-gullo

## Summary

- Creating static footer placeholder utilizing the same file format structure as the new `header` for consistency
- Note that links are not yet available for the first column.

## Related issue(s)

- [Ticket #79244](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/79244)

## Testing done

- I ran content-build locally with the new footer to confirm it matches design's mockups
- Further confirmed it is matching the current double-footer state that header is experiencing

## Screenshots

<img width="1490" alt="Screenshot 2024-04-08 at 15 15 38" src="https://github.com/department-of-veterans-affairs/content-build/assets/148817676/0e4b6e69-e255-4a3a-bb3b-df07cbcc309e">

<img width="544" alt="Screenshot 2024-04-12 at 13 02 25" src="https://github.com/department-of-veterans-affairs/vets-website/assets/148817676/ce28ffb4-1167-4c50-8f4b-052d6fcd9143">

## What areas of the site does it impact?
Accredited Representative Portal

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria
- [ ] Footer is displaying
- [ ] Footer matches [mocks](https://www.figma.com/file/C3sdnDf8anVqXVdmiCWwq8/%F0%9F%9A%A7-Accredited-Rep-Facing?type=design&node-id=437-34556&mode=design&t=ddYVRQXLxcAZPnWN-0)

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

2024-04-15 19:02 UTC, cohnjesse submitted a review, later dismissed
LGTM, obviously we will need to do a subsequent ticket to remove the content-build footer so we don't have the duplicate. Looks great!

2024-04-17 16:04 UTC, williamphelps13 requested changes
Did a first run through! Were you able to run this past design/research to get feedback on this implementation?

2024-04-17 18:00 UTC, emily-gullo commented on src/applications/accredited-representative-portal/components/common/Footer/MobileFooter/MobileFooter.jsx
> +                    <a href="https://va.gov">VA forms</a>
I think that'd be ideal for the tickets expanding on this placeholder for sure!

2024-04-22 17:45 UTC, powellkerry approved these changes, later dismissed

2024-04-23 15:18 UTC, williamphelps13 requested changes

2024-04-24 16:54 UTC, williamphelps13 approved these changes
Changes to comments look good. We can address this comment in the next Footer issue: https://github.com/department-of-veterans-affairs/vets-website/pull/29171#discussion_r1576409607

2024-04-24 20:01 UTC, merged