Added test case for expend all messages and focus them by pressing nav
department-of-veterans-affairs/vets-website pull request #29196
Opened 2024-04-16 13:53 UTC by haniasma

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#0000
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-04-16 13:57 UTC, alex-morgun-1 requested changes
Let's take it as a regular practice to keep PR descriptions updated to reflect the scope of work captured in PR. Also, it will be helpful to keep PR title in the following format:
`MHV-[TICKET_NUMMBER] SM - [PR Title]`

2024-04-16 14:19 UTC, oleksii-morgun commented on src/applications/mhv-secure-messaging/main/tests/e2e/keyboard-nav-test/secure-messaging-keyboard-nav-to-message-details.cypress.spec.js
> +    }
I think I understand the goal this loop is trying to reach, which is tab to "Expand All +" button. I am concerned that an arbitrary number of iterations here may not be reliable. is there a way to do a `while` loop with a condition when a specific button reaches focus?

2024-04-16 14:20 UTC, oleksii-morgun commented on src/applications/mhv-secure-messaging/main/tests/e2e/pages/PatientMessageDetailsPage.js
> +  verifyClickAndExpendAllMessagesHasFocus = () => {
```suggestion
  verifyClickAndExpandAllMessagesHasFocus = () => {
```

2024-04-17 14:40 UTC, powellkerry approved these changes, later dismissed

2024-04-17 16:47 UTC, Asterix22 approved these changes

2024-04-18 13:20 UTC, oleksii-morgun approved these changes
👍🏻

2024-04-18 15:35 UTC, fazilqa approved these changes
resolved

2024-04-18 17:05 UTC, merged