Update confirmation page
department-of-veterans-affairs/vets-website pull request #29245
Opened 2024-04-17 19:18 UTC by ToddWebDev

## Summary
Update the confirmation page of the Pension Benefits form (21p-527EZ)

## Description
Includes bank account information when a submitted form opts in for direct deposit.

## Acceptance criteria
[Issue in Github](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80313)

## How to run in local environment
1. Check out this branch locally
2. In your local environment, set the `pension_form_enabled` flipper to 'enabled' at http://localhost:3000/flipper/features/pension_form_enabled
3. Run `vets-website` and `vets-api`
4. Go to `http://localhost:3001/pension/application/527EZ` in your browser

## How to verify
### Using direct deposit
1. Continue to the direct deposit page in the 'Additional information' chapter
2. Select 'Yes' on the 'Do you have a bank account to use for direct deposit?' question
3. Continue to the 'Account information for direct deposit' page
4. Enter bank account information
6. Submit the form
7. Verify that the 'Direct deposit account information' section is included on the confirmation page

### No direct deposit
1. Continue to the direct deposit page in the 'Additional information' chapter
2. Select 'No' on the 'Do you have a bank account to use for direct deposit?' question
6. Submit the form
7. Verify that the 'Direct deposit account information' section is NOT included on the confirmation page

## Related issue(s)
[Issue in Github](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80313)
[Epic in Github](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79749)

## Testing done
- [x] Existing unit tests updated
- [x] New unit tests added

## Screenshots
|  Direct deposit |  No direct deposit |
| ------ | ------ |
|![localhost_3001_pension_apply-for-veteran-pension-form-21p-527ez_confirmation](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/4a431031-926d-46e5-bbff-398179095d0e)|![localhost_3001_pension_apply-for-veteran-pension-form-21p-527ez_confirmation (1)](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/796cdc88-34f6-4439-9820-9c8cc019f228)

## What areas of the site does it impact?
Pension Benefits Application

### Quality Assurance & Testing
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

2024-04-18 13:39 UTC, TaiWilkin requested changes
The feature itself is working very well.
I think this is one of the new features which needs to be wrapped in a feature flag (see issue).

2024-04-18 19:33 UTC, ToddWebDev commented
@TaiWilkin The acceptance criteria has been updated so that this work does not need to be behind a feature flag anymore

2024-04-18 20:21 UTC, TaiWilkin approved these changes
LGTM

2024-04-18 20:44 UTC, TaiWilkin approved these changes

2024-04-19 14:43 UTC, powellkerry approved these changes

2024-04-19 15:51 UTC, merged