MHV-57141 sm update import patient keyword search page
department-of-veterans-affairs/vets-website pull request #29278
Opened 2024-04-18 22:01 UTC by fazilqa

## Summary

- E2E tests for Inbox page filter-sort by keyboard required
- This PR adds new spec with required tests, additional methods and parametrization
- VA.gov - Secure Messaging

## Related issue(s)

- https://jira.devops.va.gov/browse/MHV-57141

## Testing done

- Test run locally based on 200x pattern
- All specs run in headless mode with no fails

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-04-19 12:29 UTC, oleksii-morgun commented on src/applications/mhv-secure-messaging/main/tests/e2e/keyboard-nav-test/secure-messaging-keyboard-nav-inbox-filter-sort.cypress.spec.js
> +    landingPage.submitFilerByKeyboard(filteredData);
```suggestion
    landingPage.submitFilterByKeyboard(filteredData);
```

2024-04-19 13:02 UTC, oleksii-morgun commented on src/applications/mhv-secure-messaging/main/tests/e2e/pages/PatientInboxPage.js
> +  submitFilerByKeyboard = mockFilterResponse => {
same as above
```suggestion
  submitFilterByKeyboard = mockFilterResponse => {
```

2024-04-19 13:34 UTC, oleksii-morgun requested changes, later dismissed
Hey @fazilqa I will need to place this PR on a brief hold before we can proceed. This is related to another minor folder structure change upcoming. I will post more details in our engineering channel

2024-04-19 21:06 UTC, powellkerry approved these changes

2024-04-22 16:38 UTC, closed without merging

2024-04-22 16:45 UTC, fazilqa commented
closed