Added feature flag to front end
department-of-veterans-affairs/vets-website pull request #29502
Opened 2024-04-30 18:57 UTC by cohnjesse

## Summary

Now that we know we need a feature flag to only allow certain VSOs to use the ARF app and we have added the back end code for the feature flag, we need to add it to the front end as well. This PR adds that code to the front end.

## Related issue(s)

https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/80613

## What areas of the site does it impact?

only the ARF app

## Acceptance criteria

- [ ] The ARF app front end is now gated with the accreditedRepresentativePortalPilot feature flag

2024-05-01 01:24 UTC, gabezurita reviewed
You are looking good.

It seems like we still have some failing tests to fix!
https://github.com/department-of-veterans-affairs/vets-website/actions/runs/8900869681/job/24443871632?pr=29502
```
    Running:  accredited-representative-portal/tests/e2e/accredited-representative           (2 of 70)
            -portal.cypress.spec.js                                                                 


  Accredited Representative Portal
    Feature toggle not enabled
      ✓ does not allow navigation to the Portal when feature is not enabled
    Feature toggle enabled - Navigation from Landing Page to pages and back
      1) allows navigation from the Landing Page to unified sign-in page
      2) allows navigation from the Landing Page to the Dashboard Page and back
      3) allows navigation from the Landing Page to the Dashboard Page to the POA Requests Page and back
      4) allows navigation from the Landing Page to the Dashboard Page to the Permissions Page and back


  1 passing (54s)
  4 failing

  1) Accredited Representative Portal
       Feature toggle enabled - Navigation from Landing Page to pages and back
         allows navigation from the Landing Page to unified sign-in page:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid=landing-page-sign-in-link]`, but never found it.
      at Context.eval (http://localhost:3001/__cypress/tests?p=src/applications/accredited-representative-portal/tests/e2e/accredited-representative-portal.cypress.spec.js:34:10)

  2) Accredited Representative Portal
       Feature toggle enabled - Navigation from Landing Page to pages and back
         allows navigation from the Landing Page to the Dashboard Page and back:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid=landing-page-heading]`, but never found it.
      at Context.eval (http://localhost:3001/__cypress/tests?p=src/applications/accredited-representative-portal/tests/e2e/accredited-representative-portal.cypress.spec.js:39:52)

  3) Accredited Representative Portal
       Feature toggle enabled - Navigation from Landing Page to pages and back
         allows navigation from the Landing Page to the Dashboard Page to the POA Requests Page and back:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid=landing-page-heading]`, but never found it.
      at Context.eval (http://localhost:3001/__cypress/tests?p=src/applications/accredited-representative-portal/tests/e2e/accredited-representative-portal.cypress.spec.js:58:52)

  4) Accredited Representative Portal
       Feature toggle enabled - Navigation from Landing Page to pages and back
         allows navigation from the Landing Page to the Dashboard Page to the Permissions Page and back:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-testid=landing-page-heading]`, but never found it.
      at Context.eval (http://localhost:3001/__cypress/tests?p=src/applications/accredited-representative-portal/tests/e2e/accredited-representative-portal.cypress.spec.js:83:52)

```

2024-05-02 19:36 UTC, pjhill submitted a review, later dismissed

2024-05-06 22:38 UTC, gabezurita approved these changes, later dismissed
LGTM!

2024-05-08 19:03 UTC, williamphelps13 requested changes
Still working through my review, but wanted to note this key change as early as I could.

2024-05-10 16:00 UTC, closed without merging