MBMS-43487 | Self-Service: Pre-Need Integration: Applicant and Sponsor Information Other Comment Box
department-of-veterans-affairs/vets-website pull request #29601
Opened 2024-05-06 17:34 UTC by jordanBoardmanCodes

## Summary

As a Veteran and/or family member, I need the ability to enter my correct race if it is not listed so that I can provide the most accurate race and obtain a quick determination on possible eligibility.

## Related issue(s)

Jira Ticket: https://jira.devops.va.gov/browse/MBMS-43487

## Screenshots

https://github.com/department-of-veterans-affairs/vets-website/assets/155088633/51d85e08-ba0e-403f-abd4-a96dc951342f

https://github.com/department-of-veterans-affairs/vets-website/assets/155088633/e2eb5a94-4f06-40f5-85ce-c8cb7a8672b0

https://github.com/department-of-veterans-affairs/vets-website/assets/155088633/186c5591-6992-4dab-82c0-b2acfddb3a03

https://github.com/department-of-veterans-affairs/vets-website/assets/155088633/b46f44a4-5e90-448e-bdb9-763acfaa7c13

https://github.com/department-of-veterans-affairs/vets-website/assets/155088633/2e22cb38-bd26-48dd-9bfd-dc277318a36d

## What areas of the site does it impact?

Pre-Need Integration

## Acceptance criteria

<img width="893" alt="Screenshot 2024-05-09 at 11 12 00 AM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/155088633/3d0bb3d3-750d-4e37-8a64-b9b60798d093">

<img width="771" alt="Screenshot 2024-05-09 at 11 12 50 AM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/155088633/d225ad72-6531-488b-af11-0c81e28e9a1f">

### Quality Assurance & Testing

- [x] POR/UI/UX Review
- [x] Unit Tests Passing
- [ ] QA
- [x] Dev Approvals

2024-05-09 16:34 UTC, ksantiagoBAH requested changes

2024-05-09 17:14 UTC, jordanBoardmanCodes commented on src/applications/pre-need-integration/config/form.jsx
> +  // applicantDemographicsEthnicityTitle,
Done

2024-05-09 17:14 UTC, jordanBoardmanCodes commented on src/applications/pre-need-integration/config/form.jsx
> +  // applicantDemographicsPreparerRaceTitle,
Done

2024-05-09 17:16 UTC, jordanBoardmanCodes commented on src/applications/pre-need-integration/utils/helpers.js
> +      return form?.application?.veteran?.race?.isOther; // Only triggers the required if the user clicks Other and submits from there
Done

2024-05-09 17:16 UTC, jordanBoardmanCodes commented on src/applications/pre-need-integration/utils/helpers.js
> +      pattern: /^(?!\s+$)[\w\s.,'"!?()-]+$/, // Checks to make sure the user doesn't input only spaces or any unusual characters
Done

2024-05-09 17:16 UTC, jordanBoardmanCodes commented on src/applications/pre-need-integration/utils/helpers.js
> +        return !form?.application?.veteran?.race?.isOther; // Safely return the value of isOther
Done

2024-05-09 17:44 UTC, ksantiagoBAH commented on src/applications/pre-need-integration/config/form.jsx
> +  // applicantDemographicsPreparerRaceTitle,
They are still there it appears

2024-05-09 17:54 UTC, jordanBoardmanCodes commented on src/applications/pre-need-integration/config/form.jsx
> +  // applicantDemographicsPreparerRaceTitle,
Whoops yep I had a push issue - one sec

2024-05-09 19:21 UTC, ksantiagoBAH submitted a review, later dismissed

2024-05-10 14:13 UTC, ksantiagoBAH approved these changes, later dismissed

2024-05-10 14:41 UTC, ConnorJeff approved these changes, later dismissed

2024-05-14 14:07 UTC, delli-gatti-michael approved these changes

2024-05-14 14:47 UTC, delli-gatti-michael approved these changes

2024-05-14 14:51 UTC, ksantiagoBAH approved these changes

2024-05-14 14:57 UTC, merged