[MHV-57126] Update Font Awesome icons switch to USWDS icons.
department-of-veterans-affairs/vets-website pull request #29673
Opened 2024-05-08 20:00 UTC by Wyzardsleeves

## Summary

- Updated font-awesome icons to use uswds icons instead.
- Is not a bug.
- Updated existing content and added new lines of code.
- MHV Medical Records.

## Screenshot
![Screenshot 2024-05-08 at 2 41 47 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/9909777/c7a5bcfd-6d24-43e9-b982-85aeb46750a2)

## Related issue(s)
### [MHV-57126](https://jira.devops.va.gov/browse/MHV-57126) - Update Font Awesome icon to USWDS icons. ###

![Screenshot 2024-05-08 at 2 59 25 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/9909777/196695a7-7aca-492e-9a11-b9205b7f06e9)

## Testing done

-  Manual testing

## What areas of the site does it impact?
MHV Medical Records

2024-05-10 14:12 UTC, mmoyer-va requested changes
Looks good, but I found another one in `SectionGuideButton.jsx`. It is for the burger menu button for the navigation in mobile view.
<img width="305" alt="image" src="https://github.com/department-of-veterans-affairs/vets-website/assets/87040148/1d62b90e-8b14-4b21-97a2-414da1fa921b">

2024-05-13 18:24 UTC, Wyzardsleeves commented
![Screenshot 2024-05-13 at 1 24 02 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/9909777/65b6874b-c9fc-4732-9997-b7203cfb4261)

2024-05-13 18:37 UTC, mmoyer-va approved these changes, later dismissed

2024-05-14 04:48 UTC, adamwhitlock1 approved these changes
looks like some import orders just go changes in the profile tests, so approved for authed-exp team side

2024-05-14 17:12 UTC, mmoyer-va approved these changes

2024-05-14 18:39 UTC, merged