82555 review approved page
department-of-veterans-affairs/vets-website pull request #29716
Opened 2024-05-10 18:22 UTC by lee-delarm6

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Summary

- Get one of the new notification appointments pages styled and ready for data input (sample data on the page only)

## Related issue(s)

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82555

## Testing done

- Visual and build test only

## Screenshots

![Screenshot 2024-05-10 at 2 22 11 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/135059743/7a21f684-3cc6-415f-a7b0-fcf8f550a53b)

2024-05-20 19:35 UTC, lee-delarm6 commented
Adding feature flag so we can merge this and others into main

![Screenshot 2024-05-20 at 3 11 27 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/135059743/402d93d0-081f-4e0f-96f9-eb1fdcc3b157)

2024-05-20 21:21 UTC, simiadebowale submitted a review, later dismissed
LGTM

2024-05-22 15:55 UTC, simiadebowale requested changes

2024-05-22 15:55 UTC, simiadebowale commented on src/applications/vaos/appointment-list/components/AppointmentsPage/index.jsx
> +  const featureAppointmentDetailsRedesign = useSelector(state =>
Can we change the name `featureCCDirectScheduling`

2024-05-22 15:55 UTC, simiadebowale commented on src/applications/vaos/appointment-list/components/AppointmentsPage/index.jsx
> +  const featureAppointmentDetailsRedesign = useSelector(state =>
Also can we update the selector in src/applications/vaos/referral-appointments/components/ReferralAppLink.jsx to `selectFeatureCCDirectScheduling` .

2024-05-22 16:50 UTC, lee-delarm6 commented
@simiadebowale Resolved those notes you've got on there

2024-05-22 18:18 UTC, simiadebowale approved these changes

2024-05-22 18:30 UTC, merged