minor tweaks to align mocks and actual response
department-of-veterans-affairs/vets-website pull request #29751
Opened 2024-05-13 20:00 UTC by kjduensing

Now that the actual endpoint is deployed on the BTSSS API, resolve the differences between what we expected (mocks) and what is actually returned from the endpoint.

2024-05-13 22:15 UTC, athifw requested changes, later dismissed
Left a comment, valid linting comments as well.

2024-05-13 22:15 UTC, athifw commented on src/applications/travel-pay/components/TravelClaimCard.jsx
> -  SAVED: 'Saved',
it looks like we still need to translate the statuses from the data - for example, one of the statuses we get is `"InManualReview"`, which should be translated to `"In Manual Review"`

2024-05-13 22:30 UTC, athifw commented on src/applications/travel-pay/components/TravelClaimCard.jsx
> -  SAVED: 'Saved',
never mind - I see that this is done in the backend now

2024-05-14 16:40 UTC, athifw approved these changes

2024-05-15 13:30 UTC, harshil1793 approved these changes

2024-05-15 14:23 UTC, merged