removes return url for external csp
department-of-veterans-affairs/vets-website pull request #29959
Opened 2024-05-23 17:30 UTC by CaitHawk

[Zenhub Ticket](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/83522)

[Walkthrough of intended auth flow(https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/83522)

2024-05-29 18:07 UTC, asg5704 commented on src/platform/utilities/sso/index.js
> +    const isExternalCSP = sessionStorage
Change variable name to what it does.. something like `shouldRemoveAuthReturnUrl` or `shouldRemoveSessionStorage`

2024-05-29 18:09 UTC, asg5704 commented on src/platform/utilities/sso/index.js
> +      .includes('mhv' || 'myhealth' || 'ebenefits' || 'MAP');
Change to `?.includes` just in case the `authReturnUrl` is null and let's only do `mhv` for now as I think some TeamSites are being impacted.

2024-05-29 18:10 UTC, asg5704 requested changes
Minor changes

2024-05-30 16:01 UTC, asg5704 commented on src/platform/utilities/sso/index.js
> +      .includes('mhv');
`.includes('mhv')` => `?.includes('mhv')`

2024-05-30 17:04 UTC, CaitHawk commented on src/platform/utilities/sso/index.js
> +      .includes('mhv');
My bad. All done

2024-05-30 17:16 UTC, asg5704 approved these changes

2024-05-31 02:50 UTC, merged