84318 Cancel button appears on the details page for Phone Appointments
department-of-veterans-affairs/vets-website pull request #30136
Opened 2024-06-03 16:20 UTC by vbahinwillit

## Summary
This PR fixes the phone appointment layout to not display the cancel button.

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#84318

## Testing done
Unit and e2e

## Screenshots

## What areas of the site does it impact?
VAOS

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-06-04 00:20 UTC, jenniemc requested changes
From the [Figma design](https://www.figma.com/design/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?node-id=2266-81261&t=PxwalaY50q9tYkfN-0), it looks like Phone appointments can have a cancel appointment button. It looks to be determined by the `cancellable` property.  When the feature redesign flag is off, Judy Morrison's phone appointment on 7/22/2024 does not have a cancel button because the `cancellable` property is set to false. Whereas Royal Tester's phone appt on 11/5/2024 does have the cancel button visible because it has `cancellable` set to true.  
![Screenshot 2024-06-03 at 5 18 39 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/54327023/b372e591-7ec2-450c-b57e-c6fcd2733ec8)

2024-06-04 00:20 UTC, jenniemc commented on src/applications/vaos/components/layout/DetailPageLayout.jsx
> +    !isPhoneAppointment
```suggestion
    !isPastAppointment &&
    !isPhoneAppointment
```
```suggestion
    !isPastAppointment &&
   isCancellable,
```

2024-06-05 13:56 UTC, ataker commented
Waiting for a team review before reviewing for frontend CoP

2024-06-07 15:41 UTC, CBonade approved these changes

2024-06-25 15:51 UTC, closed without merging