arf. integrate sign-in functionality for ARP
department-of-veterans-affairs/vets-website pull request #30146
Opened 2024-06-03 20:24 UTC by gabezurita

Integrates Accredited Representative Portal (ARP) sign-in functionality using the React Router and Redux libraries. Key changes include:

- Implement an AuthRouterProvider proof of concept https://github.com/department-of-veterans-affairs/vets-website/pull/28355/files
- Update header user navigation component
  - Shows logged-in/out states with sign in/out links
  - Uses /v0/representative_user endpoint to populate client state
- Gate dashboard access based on signed-in status
- Use feature toggles to control functionality

The sign-in integration allows accredited representatives to authenticate and access the portal. The user's logged-in state is tracked in the Redux store. The header reflects the current auth state and provides sign-in/sign-out links.

## Related issue(s)

- [#80240 Integrate Sign-in into ARP](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/80240)

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_

## Screenshots

### Before - Mobile

### Before - Desktop

### After - Mobile

### After - Desktop

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

2024-06-04 01:15 UTC, gabezurita commented
@amprokop, @williamphelps13, and @nihil2501, a review on this would be appreciated!

2024-06-04 15:13 UTC, gabezurita commented
@department-of-veterans-affairs/octo-identity, would you like to review this front-end PR, too? More work must be done (see PR description), but it's a start.

2024-06-04 23:27 UTC, gabezurita commented on src/applications/accredited-representative-portal/actions/user.js
> +          // credentials: 'include', // TODOARF: Do we need this?
See commit uncommenting this out:
fcd8ed8d32

2024-06-05 15:20 UTC, gabezurita commented on src/applications/accredited-representative-portal/actions/user.js
> +          // credentials: 'include', // TODOARF: Do we need this?
I also made a [demo showing sign-in working with the ARP engine endpoint!](https://www.loom.com/share/1189bde814794a9997e75d5c2384fe66?sid=6a442864-9682-45ce-9f8c-8a4842411760) if you want to take a look 😄

2024-06-07 15:27 UTC, williamphelps13 requested changes
Appreciate the demo video as well!

2024-06-08 00:58 UTC, gabezurita reviewed
Addressed all feedback in the below commit:
https://github.com/department-of-veterans-affairs/vets-website/commit/f875e303a0cd04c45cea5972098cd5571ba4b463

Thanks for the thorough review! Agreed with all the style/nit/preference changes not part of the VA lint rules.

2024-06-08 00:58 UTC, gabezurita commented on src/applications/accredited-representative-portal/containers/App.jsx
> +  const isProduction = window.Cypress || environment.isProduction();
It's necessary for simulating production in e2e testing. Feel free to play with it!

2024-06-08 00:58 UTC, gabezurita commented on src/applications/accredited-representative-portal/containers/App.jsx
> +        <VaLoadingIndicator message="Loading user information (App)..." />
Done, see commit: f875e303a0

2024-06-08 00:58 UTC, gabezurita commented on src/applications/accredited-representative-portal/tests/components/common/Header/MobileHeader/MobileLogoRow.unit.spec.js
> +import { MobileLogoRow } from '../../../../../components/common/Header/MobileHeader/MobileLogoRow';
See commit: https://github.com/department-of-veterans-affairs/vets-website/commit/f875e303a0cd04c45cea5972098cd5571ba4b463

2024-06-08 00:58 UTC, gabezurita commented on src/applications/accredited-representative-portal/components/common/Header/Header.jsx
>  import React from 'react';
Yep, see commit: https://github.com/department-of-veterans-affairs/vets-website/commit/f875e303a0cd04c45cea5972098cd5571ba4b463

2024-06-08 00:58 UTC, gabezurita commented on src/applications/accredited-representative-portal/tests/components/common/Header/MobileHeader/MobileLogoRow.unit.spec.js
> +    expect(logo.alt).to.equal(
Yep, see commit: https://github.com/department-of-veterans-affairs/vets-website/commit/f875e303a0cd04c45cea5972098cd5571ba4b463

2024-06-08 00:58 UTC, gabezurita commented on src/applications/accredited-representative-portal/actions/user.js
> +export function fetchUser() {
Sure, why not update all the non-arrow functions in the app:
https://github.com/department-of-veterans-affairs/vets-website/commit/f875e303a0cd04c45cea5972098cd5571ba4b463

2024-06-08 00:58 UTC, gabezurita commented on src/applications/accredited-representative-portal/components/common/Header/common/UserNav.jsx
> +    .substr(2, 9)}`;
Yep, see commit: https://github.com/department-of-veterans-affairs/vets-website/commit/f875e303a0cd04c45cea5972098cd5571ba4b463

2024-06-10 14:59 UTC, CBonade approved these changes, later dismissed
Approved! Looks like there's a conflict that will need resolving before merge, though.

2024-06-10 18:38 UTC, gabezurita commented on src/applications/accredited-representative-portal/actions/user.js
> +      );
Had the change stashed! https://github.com/department-of-veterans-affairs/vets-website/pull/30146/commits/0c7cc4985fbdac5b6c7b4d5d37342c76f1229f89

2024-06-10 18:38 UTC, gabezurita commented on src/applications/accredited-representative-portal/tests/components/common/Header/MobileHeader/MobileLogoRow.unit.spec.js
> +import { MobileLogoRow } from '../../../../../components/common/Header/MobileHeader/MobileLogoRow';
Had the change stashed! https://github.com/department-of-veterans-affairs/vets-website/pull/30146/commits/0c7cc4985fbdac5b6c7b4d5d37342c76f1229f89

2024-06-10 18:38 UTC, gabezurita commented on src/applications/accredited-representative-portal/actions/user.js
> +    }
Had the change stashed! https://github.com/department-of-veterans-affairs/vets-website/pull/30146/commits/0c7cc4985fbdac5b6c7b4d5d37342c76f1229f89

2024-06-10 18:38 UTC, gabezurita commented on src/applications/accredited-representative-portal/components/LandingPageWelcome/LandingPageWelcome.jsx
> +};
Had the change stashed! https://github.com/department-of-veterans-affairs/vets-website/pull/30146/commits/0c7cc4985fbdac5b6c7b4d5d37342c76f1229f89

2024-06-10 23:17 UTC, williamphelps13 approved these changes
This is a huge step forward for ARP. Great job, Gabe!

2024-06-10 23:24 UTC, merged

2024-06-10 23:25 UTC, gabezurita commented
> This is a huge step forward for ARP. Great job, Gabe!

Thanks, @williamphelps13 for the thorough 🦅 👁️ review!