MHV-45437 Lab-Tests-Modify-To-Use-MHV-Endpoint
department-of-veterans-affairs/vets-website pull request #30229
Opened 2024-06-07 15:10 UTC by tynyttie

## Summary
Modified RadiologyImagesList to use the LabsAndTest MHV endpoint for live data.

## Related issue(s)

[MHV-45437](https://jira.devops.va.gov/browse/MHV-45437) - Lab/Tests - Modify to use MHV endpoint

MR to VA.gov: Lab/Test - Modify to use MHV endpoint

User Story: As a Medical Records team, we want to hit the live MHV endpoint for this domain

Acceptance Criteria:
AC1 Modify to use live MHV endpoint
AC2 All lab/test domains
AC3
AC4
AC5

Links to UCD:
Sketch Link:
User Flow:
Mobile:
Desktop:
Other Design Notes:

Architectural Notes: Always check for the latest designs in Sketch!

Test Coverage
No Tests were found testing the requirement.

## Testing done
Conducted UI testing to ensure the expected behavior. I updated existing unit test for new components.

## Screenshots

Due to the inability to distinguish between live data and mock data, no screenshot will be added.

## What areas of the site does it impact?

The modification affects the Lab and Test Details pages in Medical Records.

## Acceptance criteria
1. Lab and Test Details page receives live data. 

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

2024-06-07 15:57 UTC, rmessina1010 submitted a review, later dismissed
LGTM

2024-06-07 16:23 UTC, mmoyer-va requested changes
This ticket is actually to change the functions `getLabsAndTests` and `getLabOrTest` in MrApi.js to use the live endpoint instead of the mock data.

2024-06-07 19:44 UTC, mmoyer-va approved these changes, later dismissed

2024-06-13 15:24 UTC, mmoyer-va approved these changes, later dismissed

2024-06-13 15:53 UTC, mmoyer-va approved these changes

2024-06-13 16:17 UTC, merged