updated refill logic
department-of-veterans-affairs/vets-website pull request #30305
Opened 2024-06-12 16:07 UTC by robertbylight

## Summary

## Related issue(s)

## Testing done

## Screenshots
no ui changes

## What areas of the site does it impact?
mhv-medications

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-06-13 17:46 UTC, vmenshutin-bylight approved these changes, later dismissed

2024-06-14 13:00 UTC, CBonade requested changes
Just one requested change here to hopefully prevent errors in the future (and ensure there are none present now)

2024-06-14 13:04 UTC, RajiVenkatesh18 commented on src/applications/mhv-medications/tests/e2e/pages/MedicationsRefillPage.js
> +  clickPrescriptionRefillCheckboxForSuccessFulRequest = prescription => {
good point! Thank you! I will fix that now.

2024-06-14 13:32 UTC, vmenshutin-bylight approved these changes

2024-06-14 13:49 UTC, CBonade approved these changes

2024-06-14 14:00 UTC, merged