Add mocked response for GIBill Statement of Benefits
department-of-veterans-affairs/vets-website pull request #30377
Opened 2024-06-17 17:25 UTC by AdamKing0126

This PR is to add mocked responses for Post-911 Gi Bill Statement of benefits at 
`/education/gi-bill/post-9-11/ch-33-benefit/`

Use this mock like this:
`yarn mock-api --responses src/applications/post-911-gib-status/mocks/server.js`

This will mock out the responses to the statement of benefits tool.  Included is only a 200 response.  Inspect the [API Docs](https://developer.va.gov/explore/api/education-benefits/docs?version=current) for other responses

2024-06-18 21:21 UTC, nicksayre requested changes
Added one quick code sugestion

2024-06-18 21:21 UTC, nicksayre commented on src/applications/post-911-gib-status/mocks/server.js
> +const responses = {
```suggestion
const responses = {
  'GET /v0/backend_statuses/gibs': {
    data: {
      id: 'string',
      type: 'string',
      attributes: {
        isAvailable: true,
        name: 'gibs',
      },
    },
  },
```

2024-06-18 21:22 UTC, AdamKing0126 commented
> Added one quick code suggestion.

Thanks Nick!

2024-06-18 21:37 UTC, nicksayre approved these changes

2024-06-18 21:50 UTC, AdamKing0126 commented on src/applications/post-911-gib-status/mocks/server.js
> +/* eslint-disable camelcase */
Sorry, gotta keep it!

2024-06-20 13:52 UTC, CBonade approved these changes

2024-06-20 17:54 UTC, merged