[86014] FSR Feature Flag Removal (vets-website)
department-of-veterans-affairs/vets-website pull request #30383
Opened 2024-06-17 20:13 UTC by maxx1128

## Summary

Three feature flags have been set to `true` by default and there are no longer any in-progress forms that have them set to `false`. This means the flags are safe to remove, and this pull request removes them on the `vets-website` side.

## Related issue(s)

- [Main ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86012)
- [Initial ticket for the discovery](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81813)

## Testing done

N/A. As long as all the existing tests pass, this is good.

## Screenshots

N/A

## What areas of the site does it impact?

FSR Forms, specifically in-progress

## Acceptance criteria

- [x]  I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x]  No error nor warning in the console.
- [x]  Events are being sent to the appropriate logging solution
- [x]  No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2024-06-20 14:06 UTC, CBonade commented
Platform review delayed due to checks not yet completed.

2024-06-20 14:52 UTC, Dr-Pongo requested changes
Just one note on removing `combinedFinancialStatusReport` from `featureFlagNames.json`.

Edit:
Oh there's one more reference of combined in the following
`src/applications/mhv-secure-messaging/tests/e2e/fixtures/generalResponses/featureToggles.json`

2024-06-20 14:52 UTC, Dr-Pongo commented on src/platform/utilities/feature-toggles/featureFlagNames.json
>    "combinedFinancialStatusReport": "combined_financial_status_report",
Hey I think `combinedFinancialStatusReport` can be removed as well!

2024-06-20 17:21 UTC, maxx1128 commented
Removed the extra flag and rebased off of `main` to also hopefully pass the tests.

2024-06-21 16:11 UTC, Dr-Pongo approved these changes
LGTM! 🚀

2024-06-24 13:06 UTC, oleksii-morgun approved these changes

2024-06-24 13:39 UTC, rsmithadhoc approved these changes

2024-06-24 16:19 UTC, merged