Styles links to be 20px/1.25rem
department-of-veterans-affairs/vets-website pull request #30503
Opened 2024-06-25 14:44 UTC by radavis

## Summary

** Styles landing page links to be 20px/1.25rem**

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#85688

## Testing done

- localhost

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

### :warning: Team Sites (only applies to modifications made to the VA.gov header) :warning:

- [ ] The vets-website header does not contain any web-components
- [ ] I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#local-dev) to test the injected header scenario
- [ ] I reached out in the `#sitewide-public-websites` Slack channel for questions

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-06-25 16:50 UTC, radavis commented on src/applications/mhv-landing-page/components/HubLinks.jsx
> -        class="mhv-c-link"
Swapped the `<va-link />` web component for an anchor tag.

2024-06-25 17:29 UTC, fmccaf1 reviewed
I'm not clear if I should be seeing something different now that you swapped the anchor tag back in.... but looking at the links in the 6 cards, that looks good! Let me know if there is anything else I should be reviewing besides those card links

2024-06-26 13:38 UTC, carlosfelix2 requested changes
Looks like the subscribe to the newsletter portion is still 16px. Change to 20px

2024-06-26 14:19 UTC, radavis commented
@carlosfelix2 I didn't see that ask called out in the ACs. https://github.com/department-of-veterans-affairs/va.gov-team/issues/85688

2024-06-26 21:21 UTC, radavis commented on src/applications/mhv-landing-page/components/HubLinks.jsx
> -        class="mhv-c-link"
And then swapped it back :upside_down_face:

2024-06-27 13:27 UTC, carlosfelix2 approved these changes
Looks good. Some fonts are 16.96px, but unsure if that is something you can control. Sent message in Slack about it.

2024-06-27 14:18 UTC, fmccaf1 commented
This looks good! Looks like all the changes are in and everything is looking correctly sized.

2024-06-27 14:51 UTC, merged