Add pension module routes to use flipper flag.
department-of-veterans-affairs/vets-website pull request #30524
Opened 2024-06-25 20:02 UTC by scottsdevelopment

## Summary

- Use a Flipper flag to control the API endpoint of the pensions application

## Related issue(s)

- department-of-veterans-affairs/va.gov-team#86460

## Testing done

- Manual testing and cypress tests

## What areas of the site does it impact?

- Pension application

2024-06-28 15:39 UTC, wayne-weibel requested changes

2024-06-28 15:39 UTC, wayne-weibel commented on src/applications/pensions/PensionsApp.jsx
> +  );
can put this in submit.rb - eliminate the extra function argument and codeclimate issue.  or make it a helper function and include that in submit.rb

2024-07-03 17:59 UTC, ToddWebDev approved these changes

2024-07-09 16:45 UTC, wayne-weibel approved these changes

2024-07-09 16:49 UTC, ToddWebDev approved these changes

2024-07-09 18:02 UTC, IGallupSoCo approved these changes
LGTM

2024-07-11 15:58 UTC, merged