Payment History - Remove accordion on Debt Details page #86969
department-of-veterans-affairs/vets-website pull request #30841
Opened 2024-07-15 19:01 UTC by amponce

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)

## Summary

- Accordion removal from “How to Pay” & text updates on the Debt Details page
Add address to Pay by Mail section.

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#86969

## Testing done

- manual/visual

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Desktop |  ![localhost_3001_manage-va-debt_summary_debt-balances (1)](https://github.com/user-attachments/assets/cfe7e09c-0454-4b72-ae7b-6d28c6faf945) |    ![localhost_3001_manage-va-debt_summary_debt-balances_details_79612301871 (1)](https://github.com/user-attachments/assets/5d57ccdb-9611-4d71-bac1-0322c71acf37) |

## What areas of the site does it impact?

*Combined Debt Portal Summary*

## Acceptance criteria

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.

2024-07-16 16:54 UTC, josephrlee requested changes
Just one minor edit! Other than that, looks good!

2024-07-16 16:54 UTC, josephrlee commented on src/applications/combined-debt-portal/debt-letters/components/HowDoIPay.jsx
> +      <a className="vads-c-action-link--blue" href="https://www.pay.va.gov/">
Use the updated `<va-action-link>` component here: https://design.va.gov/storybook/?path=/docs/components-va-link-action--docs

2024-07-16 23:49 UTC, josephrlee approved these changes

2024-07-17 13:59 UTC, IGallupSoCo approved these changes
LGTM

2024-07-17 20:39 UTC, amponce commented
Closing this PR and opened a rebased version https://github.com/department-of-veterans-affairs/vets-website/pull/30841

2024-07-17 20:47 UTC, closed without merging