updated signinapp tests for coverage
department-of-veterans-affairs/vets-website pull request #30852
Opened 2024-07-16 15:57 UTC by acaruso-oddball

## Summary

Fixes code coverage for the SignInApp component so that all statements, branches, functions, lines are a minimum 90%.

## Related issue(s)
[Fix SignInApp code coverage](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/87767)

## Testing done

Run yarn test:unit <location-of-unit-test> --coverage --coverage-html
Open up the coverage/index.html file in a browser
Verify code coverage minimums and refactor as needed

## What areas of the site does it impact?

Testing around authentication components. 

## Acceptance criteria

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed

2024-07-22 16:20 UTC, micahchiang requested changes
From what I can tell, the package added to package.json and yarn.lock in this PR isn't necessary. Could you please revert? Thanks!

2024-07-22 21:29 UTC, acaruso-oddball commented
Hi folks, I've reverted the changes as I encountered the following warning during testing:

` Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating `

Although updating as suggested was a potential solution, I confirmed that it was not necessary to resolve the issue.

2024-07-23 20:19 UTC, acaruso-oddball commented on package.json
removed thx

2024-07-23 20:19 UTC, acaruso-oddball commented on yarn.lock
removed thx

2024-07-24 20:47 UTC, acald-creator approved these changes

2024-07-31 15:09 UTC, micahchiang approved these changes

2024-07-31 15:10 UTC, merged