Implement VerifyAndRegisterAlert and MhvBasicAccountAlert to MHV Landing page - version 2
department-of-veterans-affairs/vets-website pull request #31029
Opened 2024-07-25 23:59 UTC by jzucadi

import React, { useEffect } from 'react';
import { useSelector } from 'react-redux';
import PropTypes from 'prop-types';
import {
  renderMHVDowntime,
  MhvSecondaryNav,
} from '@department-of-veterans-affairs/mhv/exports';
import DowntimeNotification, {
  externalServices,
} from '~/platform/monitoring/DowntimeNotification';
import { signInServiceName } from '~/platform/user/authentication/selectors';
import { SERVICE_PROVIDERS } from '~/platform/user/authentication/constants';
// eslint-disable-next-line import/no-named-default
import { default as recordEventFn } from '~/platform/monitoring/record-event';

import CardLayout from './CardLayout';
import HeaderLayout from './HeaderLayout';
import HubLinks from './HubLinks';
import NewsletterSignup from './NewsletterSignup';
import HelpdeskInfo from './HelpdeskInfo';
import LandingPageAlerts from './LandingPageAlerts';
import {
  isLOA3,
  isVAPatient,
  personalizationEnabled,
  hasMhvAccount,
} from '../selectors';

const LandingPage = ({ data = {}, recordEvent = recordEventFn }) => {
  const { cards = [], hubs = [] } = data;
  const userVerified = useSelector(isLOA3);
  const vaPatient = useSelector(isVAPatient);
  const userRegistered = userVerified && vaPatient;
  const signInService = useSelector(signInServiceName);
  const userHasMhvAccount = useSelector(hasMhvAccount);
  const showWelcomeMessage = useSelector(personalizationEnabled);
  const serviceLabel = SERVICE_PROVIDERS[signInService]?.label;
  const unVerifiedHeadline = `Verify your identity to use your ${serviceLabel} account on My HealtheVet`;

  useEffect(
    () => {
      if (!userVerified) {
        recordEvent({
          event: 'nav-alert-box-load',
          action: 'load',
          'alert-box-headline': unVerifiedHeadline,
          'alert-box-status': 'continue',
        });
      }
    },
    [recordEvent, unVerifiedHeadline, userVerified],
  );

  return (
    <>
      {userRegistered && <MhvSecondaryNav />}
      <div
        className="vads-u-margin-y--3 medium-screen:vads-u-margin-y--5"
        data-testid="landing-page-container"
      >
        <div className="vads-l-grid-container large-screen:vads-u-padding-x--0">
          <DowntimeNotification
            dependencies={[externalServices.mhvPlatform]}
            render={renderMHVDowntime}
          />
          <HeaderLayout
            showWelcomeMessage={showWelcomeMessage}
            showLearnMore={userRegistered}
          />
          <LandingPageAlerts
            userVerified={userVerified}
            userRegistered={userRegistered}
            userHasMhvAccount={userHasMhvAccount}
            unVerifiedHeadline={unVerifiedHeadline}
            signInService={signInService}
          />
          {userRegistered && <CardLayout data={cards} />}
        </div>
        {userRegistered && (
          <div className="vads-l-grid-container large-screen:vads-u-padding-x--0">
            <div className="vads-l-row vads-u-margin-top--3">
              <div className="vads-l-col medium-screen:vads-l-col--8">
                <HelpdeskInfo />
              </div>
            </div>
          </div>
        )}
        {userRegistered && <HubLinks hubs={hubs} />}
        {userRegistered && <NewsletterSignup />}
      </div>
    </>
  );
};

LandingPage.propTypes = {
  data: PropTypes.object,
  recordEvent: PropTypes.func,
};

export default LandingPage;

2024-07-30 14:23 UTC, radavis reviewed
I like that our alerts are now wrapped up by a single component. 

We're getting into territory where we are showing multiple alerts to the user (e.g. - loa1 & mhv case yields UnregisteredUser and MhvBasicAccountAlert). I think we need to refactor the logic for showing these alerts before we can merge. Here's some guidance for showing the most relevant alert to the user.

2024-07-30 19:48 UTC, micahchiang submitted a review, later dismissed

2024-07-30 20:19 UTC, jzucadi commented
> I like that our alerts are now wrapped up by a single component.
> 
> We're getting into territory where we are showing multiple alerts to the user (e.g. - loa1 & mhv case yields UnregisteredUser and MhvBasicAccountAlerts). I think we need to refactor the logic for showing these alerts before we can merge. [Here's some guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/mhv-home-alerts.md#proposed-alert-flow) for showing the most relevant alert to the user.
> 
> ![Screenshot 2024-07-30 at 10-17-47 My HealtheVet Veterans Affairs](https://private-user-images.githubusercontent.com/1299034/353496776-d3872345-4ce5-4c85-8139-bd2bf25ed2b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNzA2NTgsIm5iZiI6MTcyMjM3MDM1OCwicGF0aCI6Ii8xMjk5MDM0LzM1MzQ5Njc3Ni1kMzg3MjM0NS00Y2U1LTRjODUtODEzOS1iZDJiZjI1ZWQyYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzBUMjAxMjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ2OTZjZTE1NzU2Nzk1NjhlZDQ3Y2YwOTRlOWVhYmY4MDY5MjNkY2FkNDNkMTE2NmE4MWJmMjBlN2U0MDllNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vPrHHxrhuO0G5VhNA5GhjTPHa4urCqu50LVheDKQ4gc)

Agreed!

2024-08-05 15:51 UTC, dcloud commented
@jzucadi I'm also seeing the three alerts per @radavis screenshot and agree that we probably want to show the single most relevant alert. Let's talk about this as a team and make sure UX is informed and on board

2024-08-05 16:17 UTC, sterkenburgsara reviewed
These two alerts shouldn't display at the same time. There is criteria in the ticket for the first alert in the stack that it should _only_ be for ID.me and Login.gov (have to remove MyHealtheVet sign-in credential from that logic). If a user signs in with a My HealtheVet basic (LOA1) credential they should see the second alert (yellow one) only.

2024-08-06 20:09 UTC, dcloud reviewed
I left 2 minor suggestions, but think this looks good. Seeing a merge conflict, which I think would negate a ✅ , so please ping me once that conflict has been resolved

2024-08-06 20:09 UTC, dcloud commented on src/applications/mhv-landing-page/components/LandingPageAlerts.jsx
> +  if (userHasMhvBasicAccount && !userVerified) {
```suggestion
  if (userHasMhvBasicAccount) {
```

2024-08-06 20:09 UTC, dcloud commented on src/applications/mhv-landing-page/components/LandingPageAlerts.jsx
> +    showsVerifyAndRegisterAlert
Doesn't `showsVerifyAndRegisterAlert` also check the sign in service is idme or logingov and is LOA3? I don't think we should need the first two conditional checks:

```suggestion
    showsVerifyAndRegisterAlert
```

2024-08-07 17:15 UTC, radavis requested changes, later dismissed
Looks good. You will need to remove the log statements from the e2e spec

2024-08-07 17:15 UTC, radavis commented on src/applications/mhv-landing-page/tests/e2e/alerts/unverified.cypress.spec.js
> +
This should be removed.

2024-08-07 18:25 UTC, jzucadi commented on src/applications/mhv-landing-page/tests/e2e/alerts/unverified.cypress.spec.js
> +
Sorry! I forgot to take this out.

2024-08-07 19:51 UTC, dcloud approved these changes
This looks good to me, thanks for leaving things nicer than you found them! 🚀

2024-08-08 16:02 UTC, merged