Form 10-10EZR keyboard only test
department-of-veterans-affairs/vets-website pull request #31079
Opened 2024-07-29 18:31 UTC by dellerbie

Keyboard only Cypress test for Form 10-10EZR

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [ ] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Related issue(s)

- department-of-veterans-affairs/va.gov-team#80252

## Testing done

Added a new Cypress E2E test for this

## What areas of the site does it impact?

Form 10-10EZR

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

2024-08-07 15:43 UTC, longmd commented on src/applications/ezr/tests/e2e/fixtures/data/maximal-test.json
> -      "gulfWarStartDate": "1990-09-XX",
The `-XX` is how the `va-memorable-date` formats the values when the format is month/day only. Id suggest reverting this to provide accurate data formatting for the component.

2024-08-07 15:45 UTC, longmd requested changes
Please revert the date formatting in the maximal test to accurately reflect how that gets formatted.

2024-08-07 20:55 UTC, longmd requested changes

2024-08-07 20:55 UTC, longmd commented on src/applications/ezr/tests/e2e/fixtures/data/maximal-test.json
> +    "view:toxicExposureDates": {
This data should match the same month/year format as the Gulf War dates. Let's replace the "day" values with `XX`.

2024-08-07 22:55 UTC, longmd approved these changes

2024-08-07 22:55 UTC, longmd commented on src/applications/ezr/tests/e2e/fixtures/data/maximal-test.json
> +      "toxicExposureEndDate": "1990-09-XX"
Good extra test of the same-as date selection! 👍🏼

2024-08-08 12:55 UTC, mkerns1 approved these changes
LGTM!

2024-08-08 20:30 UTC, merged