ARF-86187 update steps 3 & 4 to v3 designs
department-of-veterans-affairs/vets-website pull request #31088
Opened 2024-07-29 22:53 UTC by tjheffner

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [ ] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

If the folder you changed contains a `manifest.json`, search for its `entryName` in the content-build [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) (the `entryName` there will match).

If an entry for this folder exists in content-build and you are:
1. **Deleting a folder**: Delete the application entry in [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) and merge that PR **before** this one
- _Add the link to your merged content-build PR here_

2. **Renaming or moving a folder**: Update the entry in the [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json), but do not merge it until your vets-website changes here are merged. The content-build PR must be merged immediately after your vets-website change is merged in to avoid CI errors with content-build (and Tugboat).

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [ ] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#0000
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-07-30 05:31 UTC, williamphelps13 reviewed
Thanks for reaching out about this PR! I went through the PR in pretty good detail! Hopefully the notes are helpful and the solution for the conditional logic you reached out about is looking good! Happy to pair as well! I can run through this PR again when you move it out of draft!

2024-07-30 14:54 UTC, tjheffner commented on src/applications/accreditation/21a/pages/03-employment-information-chapter/employersPages.js
>  const arrayBuilderOptions = {
I called this out in my PR description, that we should be using the `formatReviewDate` you added in the [Steps 1 & 2 PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31019/files#diff-34c7bb72d1fddd213368717383f4d84945513334580e2fa823e91dd7ec4e8926), once it is merged

2024-07-30 14:56 UTC, tjheffner commented on src/applications/accreditation/21a/pages/03-employment-information-chapter/employersPages.js
> +const employmentActivitiesPage = {
Sure, I can break it out

2024-07-30 14:57 UTC, tjheffner commented on src/applications/accreditation/21a/pages/03-employment-information-chapter/employersPages.js
> +      labels: {
I had originally had them as their own object (and used `object.keys()` for the schema), but the checkbox group wasn't rendering properly, will give it another shot.

2024-07-30 15:41 UTC, tjheffner commented on src/applications/accreditation/21a/pages/04-education-history-chapter/educationalInstitutionsPages.js
> +  isItemIncomplete: item => !item?.name || !item.dateRange || !item.received,
LGTM, makes sense that any fields conditional required should also be part of a complete item when present :)

2024-07-31 14:36 UTC, williamphelps13 requested changes
I'll review this in detail this morning! Can you add the keys of the new fields to this file with mock data: src/applications/accreditation/21a/tests/fixtures/data/[test-data.json](https://github.com/department-of-veterans-affairs/vets-website/blob/a7f1721ae72c398183d8625837f3745f6630fe2e/src/applications/accreditation/21a/tests/fixtures/data/test-data.json). Then run `yarn cy:open` and ensure our 21a e2e submits?

2024-08-02 18:50 UTC, williamphelps13 requested changes
One more minor tweak then LGTM

2024-08-02 18:55 UTC, tjheffner commented on src/applications/accreditation/21a/pages/04-education-history-chapter/educationalInstitutionsPages.js
> +        formData?.educationalInstitutions?.[index]?.degreeReceived === true, // TODO: Required is not working correctly on edi
ugh yeah, it doesn't seem like required is being passed through the UI pattern properly. I do see the underlying `VaSelectField` has a required propType, so it shouldn't be a huge lift to wire that together correctly

2024-08-02 19:00 UTC, williamphelps13 approved these changes
Awesome job, Tanner!

2024-08-02 19:38 UTC, Andrew565 approved these changes

2024-08-02 19:40 UTC, merged