ARF 88511 Align Introduction Page with V3 Designs and Complete Post V3 Refinement
department-of-veterans-affairs/vets-website pull request #31329
Opened 2024-08-12 16:31 UTC by williamphelps13

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
- Summarize the changes that have been made to the platform
  - Introduction Page Changes:
    - Align with [V3 Designs](https://www.figma.com/design/2afIGOMII0uRI5ck1dWo1w/Form-21a---Apply-for-Accreditation-(CA-%26-Attorneys)?node-id=2000-54190&t=UFnVAKb8uMVhQfCh-4)
    - Remove `Start your application without signing in link`
    - Up `<a>` links to `<va-link/>`
  - Post V3 Refinement Changes:
    - Options
      - Migrate all radio, checkbox, and select options to an options file
      -  Add `Object.Freeze` all of them
      - Alphabetize keys where order does not matter (degree is ordered from least to most years required for degree, discharge is ordered as honorable types of discharge first then dishonorable types) 
    - Update frontend schema keys that are within list loops and include duplication of context (`serviceBranch` does not need the word `service` because it is nested within `militaryServiceExperiences` so service is implied)
- Accredited Representative Facing Team which owns the maintenance of this component

## Related issue(s)
- [Align Introduction Page with V3 Designs and Complete Post V3 Refinement #88511](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/88511)
- [[ARF] Digital Form 21a](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/83627)

## Testing done
- Describe the steps required to verify your changes are working as expected:
  - Go through each of the changes described above and ensure they are done accurately
  - For the removal of `Start your application without signing in link` can temporarily add `environment.isDev()` to test if it would then disappear in dev)

## Screenshots

### Before 
<img width="812" alt="Screenshot 2024-08-12 at 9 36 03 AM" src="https://github.com/user-attachments/assets/39d83b5b-2f03-4121-8909-553e9e175cfa">
<img width="794" alt="Screenshot 2024-08-12 at 9 36 13 AM" src="https://github.com/user-attachments/assets/c39a3eaf-1926-4479-9fbe-89dd7ec56e2a">
<img width="822" alt="Screenshot 2024-08-12 at 9 36 28 AM" src="https://github.com/user-attachments/assets/4cdc52ec-adb9-4690-8895-e1315a2874f1">

### After
<img width="818" alt="Screenshot 2024-08-12 at 9 34 06 AM" src="https://github.com/user-attachments/assets/ea8b203f-90fe-4533-9125-69d866344853">
<img width="815" alt="Screenshot 2024-08-12 at 9 34 16 AM" src="https://github.com/user-attachments/assets/67ee393c-6c5b-43d2-9a4a-d69b57f8bbe2">
<img width="813" alt="Screenshot 2024-08-12 at 9 34 26 AM" src="https://github.com/user-attachments/assets/3464352a-4cf8-44a9-b6b5-deee4920a2e2">
<img width="828" alt="Screenshot 2024-08-12 at 9 34 36 AM" src="https://github.com/user-attachments/assets/488ddee1-a75a-4fcd-8604-3f3b4b5af51d">

## Acceptance criteria

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

2024-08-12 18:31 UTC, jamigibbs submitted a review, later dismissed

2024-08-12 23:46 UTC, gabezurita requested changes
Looking good! Seems like we have one typo.

2024-08-12 23:46 UTC, gabezurita commented on src/applications/accreditation/21a/containers/IntroductionPage.jsx
> +            You will need to provide each jurisdiction your are currently a
Typo `you`

2024-08-14 22:08 UTC, gabezurita approved these changes
LGTM!

2024-08-16 21:21 UTC, jamigibbs approved these changes
The only possible issue I notice is that the screenshots show the v1 variation of `va-process-list` which has been removed as of the [latest component-library release](https://github.com/department-of-veterans-affairs/component-library/releases/tag/v45.0.0): 

- https://github.com/department-of-veterans-affairs/component-library/pull/1276

2024-08-16 21:41 UTC, merged