Arf/87799/arp 21a
department-of-veterans-affairs/vets-website pull request #31352
Opened 2024-08-13 12:48 UTC by nihil2501

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [ ] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

If the folder you changed contains a `manifest.json`, search for its `entryName` in the content-build [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) (the `entryName` there will match).

If an entry for this folder exists in content-build and you are:
1. **Deleting a folder**: Delete the application entry in [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) and merge that PR **before** this one
- _Add the link to your merged content-build PR here_

2. **Renaming or moving a folder**: Update the entry in the [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json), but do not merge it until your vets-website changes here are merged. The content-build PR must be merged immediately after your vets-website change is merged in to avoid CI errors with content-build (and Tugboat).

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [ ] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#0000
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-08-16 21:38 UTC, gabezurita reviewed
Looking good so far! I'll fuss test this on Monday!

Some good improvements!

2024-08-16 21:38 UTC, gabezurita commented on src/applications/accredited-representative-portal/actions/user.js
> +      const serviceName = user?.profile?.signIn?.serviceName;
Nice!

2024-08-16 21:38 UTC, gabezurita commented on src/applications/accredited-representative-portal/reducers/user.js
> +        loading: false,
Great improvement!

2024-08-19 22:16 UTC, gabezurita commented on src/applications/accredited-representative-portal/actions/user.js
> +      if (serviceName) {
If there's no `serviceName`, could we make error handling more explicit?
```js
export function fetchUser() {
  return async (dispatch) => {
    dispatch({ type: FETCH_USER });

    try {
      const path = '/accredited_representative_portal/v0/user';
      const user = await apiRequest(`${environment.API_URL}${path}`);

      if (!user?.profile?.signIn?.serviceName) {
        throw new Error('Service name is missing in the user profile.');
      }

      sessionStorage.setItem('serviceName', user.profile.signIn.serviceName);

      dispatch({
        type: FETCH_USER_SUCCESS,
        payload: user,
      });
    } catch (error) {
      const errorMessage = error.errors?.[0]?.detail || error.message || 'An unknown error occurred while fetching user data.';
      dispatch({
        type: FETCH_USER_FAILURE,
        error: errorMessage,
      });
    }
  };
}
```

2024-08-20 15:16 UTC, ndsprinkle approved these changes

2024-08-20 19:00 UTC, ndsprinkle requested changes
Removing approval since you indicated in slack that this is the old/no longer relevant solution?

2024-08-21 20:29 UTC, nihil2501 commented
> Removing approval since you indicated in slack that this is the old/no longer relevant solution?

@ndsprinkle I reverted the single commit that pertained to that long discussion in Slack you were referring to. The rest of this PR is changes purely within our application. Except for one addition to configure the SIP API URL for our form (our app has its own backend), and for this reason it looks like I still need an approval from forms team for this one line configuration change.

2024-08-23 21:20 UTC, tjheffner commented
Verified locally that save-in-progress is working for 21a! 🎉 

vets-website branch: `arf/87799/arp-21a`
vets-api branch: `arf_86023/in_progress_forms.poc`

Signed in via id.me with `vets.gov.user+0@gmail.com`

![Screenshot 2024-08-23 at 2 17 47 PM](https://github.com/user-attachments/assets/2cb826ec-fda0-46a1-94cf-6af6c3baa06c)


There are some failing CI checks here (tests need repaired based on some of the changes in the PR), but overall this is awesome work. Thank you @nihil2501 (& @athifw) !

2024-09-04 22:45 UTC, gabezurita commented
@nihil2501, I just finished merging `main` and resolving 18 merge conflicts. If/when I get CI green, I'll give this one last round of QA and then approve/merge it!
![image](https://github.com/user-attachments/assets/51b6c00a-f4ff-4d44-b687-610c0c1ce897)

2024-09-05 14:38 UTC, gabezurita approved these changes, later dismissed
LGTM!

2024-09-05 14:38 UTC, gabezurita commented on src/applications/accredited-representative-portal/reducers/user.js
> +function transformProfilePayload(payload) {
Thanks for adding this transform function

2024-09-05 14:38 UTC, gabezurita commented on src/applications/accredited-representative-portal/tests/e2e/accredited-representative-portal.cypress.spec.js
> +describe.skip('Accredited Representative Portal', () => {
This test has stale 21-22 code that needs to be cleaned up.

We'll fix this `.skip` as a part of the below code cleanup issue:
https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/92083

2024-09-05 14:41 UTC, gabezurita commented
@ndsprinkle, @platform-design-system-fe, @platform-va-product-forms, @department-of-veterans-affairs/va-platform-cop-frontend this is ready for your review!

2024-09-05 16:19 UTC, gabezurita commented
@ndsprinkle, @department-of-veterans-affairs/platform-design-system-fe , @department-of-veterans-affairs/platform-va-product-forms, @department-of-veterans-affairs/va-platform-cop-frontend this is ready for your review!

2024-09-06 22:55 UTC, gabezurita approved these changes
Re-approving post mainline merge

2024-09-09 21:57 UTC, rmessina1010 approved these changes
LGTM

2024-09-09 22:22 UTC, gabezurita commented
Hey @ndsprinkle, FYI, it seems we need approval from you

2024-09-10 14:09 UTC, ndsprinkle approved these changes
Hey @nihil2501 , looks great to me! Just one thing I wanted to call out, because I'm slightly confused as to what's happening with the manifest.json. Is one manifest being deleted and the app is updated to point to another already existing manifest? Just asking because content-build could break depending on how you did this change.

Here's the information:
```
## Are you removing, renaming or moving a folder in this PR?
- [ ] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

If the folder you changed contains a `manifest.json`, search for its `entryName` in the content-build [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) (the `entryName` there will match).

If an entry for this folder exists in content-build and you are:
1. **Deleting a folder**:
   1. First search `vets-website` for _all_ instances of the `entryName` in your `manifest.json` and remove them in a separate PR. Look particularly for references in `src/applications/static-pages/static-pages-entry.js` and `src/platform/forms/constants.js`. _**If you do not do this, other applications will break!**_
      - _Add the link to your merged vets-website PR here_
   2. Then, Delete the application entry in [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) and merge that PR **before** this one
      - _Add the link to your merged content-build PR here_

2. **Renaming or moving a folder**: Update the entry in the [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json), but do not merge it until your vets-website changes here are merged. The content-build PR must be merged immediately after your vets-website change is merged in to avoid CI errors with content-build (and Tugboat).
```

2024-09-10 17:19 UTC, raudabaugh commented
@ndsprinkle Good callout. The plan is to merge https://github.com/department-of-veterans-affairs/content-build/pull/2180 after this

2024-09-10 22:22 UTC, gabezurita commented
We'll first merge the below to be on the safe side:
[devops](https://github.com/department-of-veterans-affairs/devops/pull/14686)
[vsp-platform-revproxy](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/pull/622)
[content-build](https://github.com/department-of-veterans-affairs/content-build/pull/2269)

2024-09-11 17:17 UTC, merged