VACMS-16937: DUW Step 1 component
department-of-veterans-affairs/vets-website pull request #31398
Opened 2024-08-14 19:46 UTC by chriskim2311

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
PR adds subway map for Step 1 of DUW

## Related issue(s)

## Testing done
Tested locally 

## Screenshots

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-08-15 14:54 UTC, randimays requested changes, later dismissed
Just finished testing. I have some observations:

**Flow 1** under Screenshots in your PR description: I expected to see more text per the Mural since these two conditions aren't met

<details><summary>Flow 1 - A</summary>
<br/>
> If Question 1 = 1 or 2 AND IF Question 2= 2001-2009 only, SHOW:
> If Q1 = 8, SHOW:

<img width="459" alt="Screenshot 2024-08-15 at 8 51 31 AM" src="https://github.com/user-attachments/assets/55babbdf-ae4d-4206-9491-46bafa8379e9">

The "Download and fill out DoD Form 149" text is there, but the paragraph under it is missing.

</details>

<details><summary>Flow 1 - B</summary>
<br/>
I think this text should be there too:
<img width="659" alt="Screenshot 2024-08-15 at 8 55 46 AM" src="https://github.com/user-attachments/assets/305757b6-38c0-4f6c-a81a-8904d36b2c19">
</details>

<details><summary>Flow 1 - C</summary>
<br/>

This text is partially there; the "Item 8" text is missing. The "Item 10" text is there but it says "Item 17" instead of "Item 10."

<img width="594" alt="Screenshot 2024-08-15 at 8 58 12 AM" src="https://github.com/user-attachments/assets/4e428994-d2e3-4844-ab80-2038cbd1ad9a">

<img width="642" alt="Screenshot 2024-08-15 at 8 58 19 AM" src="https://github.com/user-attachments/assets/0ec593d9-9a77-4baf-ae6d-c671a5c5fe95">

</details>
<hr/>

**Flow 2** under Screenshots in your PR description: I noticed that even though you selected "Navy" as the branch of service, the board later referred to is "BCMR" instead of "BCNR." I can't reproduce this in my flow, but I thought I'd point it out in case something wonky is happening.

<details><summary>Flow 2 - A</summary>
<br/>

Given that this is all pieced-together dynamic text, I'm not sure if this is possible. But if we're able to add a line break here that'd be helpful for readability. 

<img width="690" alt="Screenshot 2024-08-15 at 9 05 16 AM" src="https://github.com/user-attachments/assets/8c4f3288-acd9-4814-bc10-e3ac1cc33865">

</details>
<details><summary>Flow 2 - B</summary>
<br/>

The text here differs a bit from the Mural.

<img width="568" alt="Screenshot 2024-08-15 at 9 07 15 AM" src="https://github.com/user-attachments/assets/8878dbde-5119-4212-9c38-5dccaa94d3ca">

<img width="574" alt="Screenshot 2024-08-15 at 9 07 19 AM" src="https://github.com/user-attachments/assets/730846d6-2179-4012-98b6-91a556bf3e9e">

This flow also has "Item 17" instead of "Item 10", similar to "Flow 1 - C" above.
</details>
<hr/>

**Flow 4** under Screenshots in your PR description:

<details><summary>Flow 4 - A</summary>
<br/>

Same text discrepancy as Flow 2 - B.

</details>

<details><summary>Flow 4 - B</summary>
<br/>

Some text differences between the Mural and the review instance:
<img width="600" alt="Screenshot 2024-08-15 at 9 37 20 AM" src="https://github.com/user-attachments/assets/a4aff6c8-e390-4b1e-8c28-a6861da12683">
<img width="600" alt="Screenshot 2024-08-15 at 9 36 58 AM" src="https://github.com/user-attachments/assets/1d8e3f8d-d21e-4829-9f80-04cc88bfc184">

</details>

<hr/>

There were a couple flows that were not in your PR description, so I wanted to make sure I covered them:

<details><summary>If Question 1 = 1 or 2 AND IF Question 2= 2001-2009 only</summary>
<br/>

<img width="527" alt="Screenshot 2024-08-15 at 9 42 11 AM" src="https://github.com/user-attachments/assets/e11ae0f0-1800-4486-9a3a-3bb2ba0e3411">

While trying to get to a flow that had it, I put in these answers:

<img width="700" alt="Screenshot 2024-08-15 at 9 41 44 AM" src="https://github.com/user-attachments/assets/4c60bf38-11f9-4db0-8cf9-102afca97628">

I think the prior service / honorable discharge question is missing for this flow (and possibly others?).

<img width="675" alt="Screenshot 2024-08-15 at 9 46 08 AM" src="https://github.com/user-attachments/assets/b6ce6c9a-769c-44df-8124-c3e4603778a4">

The very last link in this block ("Apply for a PBDR review (opens in a new tab)") goes to a page that 404s. I don't think that's necessarily our problem to solve, but we should double check that we have the right link, and if we do, point out to CAIA that it's broken.

I also noticed the same text discrepancies as Flow 2 - B and the "Item 10" vs. "Item 17" issue.

</details>

<details><summary>If DRB & 5b!=1</summary>
<br/>

I tried a flow to get this content to appear, but it didn't show up. Might've put in the wrong answers but I'm not sure.

<img width="600" alt="Screenshot 2024-08-15 at 9 53 28 AM" src="https://github.com/user-attachments/assets/36f411c8-e1b8-40b5-a21c-91f1e775a842">

<img width="700" alt="Screenshot 2024-08-15 at 9 52 26 AM" src="https://github.com/user-attachments/assets/249b7706-a379-476e-9e67-a38b645b253b">

</details>

2024-08-29 00:32 UTC, eselkin commented
I see this in the flow 1
<img width="747" alt="Screenshot 2024-08-28 at 5 29 44 PM" src="https://github.com/user-attachments/assets/837e32ac-5911-4d57-90dc-f0e3c1be28fe">
Is that expected? I didn't see it on the images

2024-08-29 00:37 UTC, chriskim2311 commented
@eselkin Yes that is expected. Some changes were merged from main and accounted for Randi's comments. Once the flow/functionality PR is merged I will update the screenshots in this PR

2024-09-10 16:50 UTC, randimays reviewed
Nice! One question in the comments and an observation:

The results screen looks too narrow on desktop
<img width="1000" alt="Screenshot 2024-09-10 at 11 08 31 AM" src="https://github.com/user-attachments/assets/91a46e01-60a2-4379-999e-b88bc8fbac59">

2024-09-10 16:50 UTC, randimays commented on src/applications/discharge-wizard/components/v2/resultsComponents/StepOne.jsx
> +  /* eslint-enable quote-props */
Curious; what was this added for?

2024-09-10 16:52 UTC, chriskim2311 commented on src/applications/discharge-wizard/components/v2/resultsComponents/StepOne.jsx
> +  /* eslint-enable quote-props */
Will remove thanks!

2024-09-10 20:49 UTC, laflannery commented
1. Heading structure:
   - On Flow 1, there is a blue alert. Can you update the H4 in the blue alert to be an H2? This will correct the current skipped heading error.
![image](https://github.com/user-attachments/assets/6d38b810-5522-41ec-a466-bb5202d85306)
   - However, on Flow 2 there is no blue alert and so the headings within the Process lists should be H2s. Is it possible to make the Process list headings conditional based on if that alert appears before or not?
![image](https://github.com/user-attachments/assets/28ca26ea-ca6f-4bba-84cf-7c90615ae9c4)
   - If the conditional is not possible, then all the Process list headings should be H2s
2. Download form link: I know this is how it probably is on Prod but would we be able to update the Download form link to have the Download link icon before it, to make this more consistent with the rest of VA?
3. Tagging @thejordanwood as this is Design related. On Flow 7 there are 2 alerts right next to each other. I'm not a huge fan of this but since they are already here and changing it is most likely out of scope, my only recommendation would be to add some space between the two: 
![image](https://github.com/user-attachments/assets/42f502c1-475f-42f3-bac6-9ff29827989a)

2024-09-10 21:20 UTC, chriskim2311 commented
@laflannery Thanks! I was able to get the heading changes in. In terms of the download link icon, which link were you referring to?

2024-09-10 22:00 UTC, thejordanwood commented
@chriskim2311 I agree with @laflannery, I think a bit of space between the alerts would be good. Let's do 16px. Here's a mockup of what that'll look like. 

<img width="474" alt="Screenshot 2024-09-10 at 4 59 38 PM" src="https://github.com/user-attachments/assets/2f8fa9d7-8853-4ecb-a1d3-636aec1707a8">

2024-09-11 12:59 UTC, laflannery commented
@chriskim2311 Headings look great, thanks! Regarding the Download icon, I was referring to these here:

![image](https://github.com/user-attachments/assets/a017c9b5-9cfb-47cb-9b73-45877bdd476c)
![image](https://github.com/user-attachments/assets/bb4ac903-1822-4497-86af-e24a92dabd9d)

And I was thinking we could add the icon before the links like this:
![image](https://github.com/user-attachments/assets/662657ad-b990-45e3-a37f-cbefb3e61705)

2024-09-11 19:29 UTC, chriskim2311 commented
@laflannery The RI is back up with the latest changes for the download icon. 
@randimays Can you take another look at this as well. Thanks!

2024-09-11 20:22 UTC, laflannery commented
Approved!

2024-09-11 20:38 UTC, thejordanwood commented
Looks good to me!

2024-09-11 21:46 UTC, randimays approved these changes

2024-09-11 23:15 UTC, merged