MHV-60548: Labs and tests content updates
department-of-veterans-affairs/vets-website pull request #31463
Opened 2024-08-19 16:33 UTC by mattwrightva

## Summary
- Content updates made to chem/hem, microbiology, pathology, and radiology
- Changes applied to list views, detail views, and pdf and text files

## Related issue(s)
https://jira.devops.va.gov/browse/MHV-60548

> ### Update the Microbiology UI
> Description
> Update the Microbiology UI
> 
> See FIGMA link for details on all items below.
> 
> 1-If nothing is populated in the lab test field, the link in the card will be “Microbiology” List page
> 
> 2- If we do have data in the lab test field, it will be populated as the link in the card. List page
> 
> 3-If nothing is populated in the lab test field, the h1 will be “Microbiology” Details page
> 
> 4-Don’t include the Lab type field if there is no data in the lab test field Details page
> 
> 5-If we do have data in the lab test field, it will be the h1. Details page
> 
> 6-If there is data in the lab test field, add the Lab type field here. Details page
> 
> 7-If nothing is populated in the lab test field, the h1 will include “Microbiology” PDF
> 
> 8-Don’t include the Lab type field if there is no data in the lab test field PDF
> 
> 9-If we do have data in the lab test field, it will be in the h1. PDF
> 
> 10- If there is data in the lab test field, add the Lab type field here PDF
> 
> Figma link:  https://www.figma.com/design/mGZRdLypKGaFsHo5xp2kaZ/Medical-Records?node-id=6582-44635&t=iLimUk0Mvl8152p8-4
> 
>  
> 
> User Story:   As a MR user, I want the microbiology UI updated to latest design, so I have the best user experience possible.

## Testing done
No new tests needed

## Screenshots
<img width="772" alt="Screenshot 2024-08-19 at 10 32 30 AM" src="https://github.com/user-attachments/assets/1d33d3a4-dc30-4e8a-a5a9-21454d62b269">
<img width="768" alt="Screenshot 2024-08-19 at 10 31 00 AM" src="https://github.com/user-attachments/assets/ff398fbd-aa8d-44d0-887b-61484f21a296">
<img width="766" alt="Screenshot 2024-08-19 at 10 30 52 AM" src="https://github.com/user-attachments/assets/ab6e997b-0f2b-4f93-b455-9ae42970511c">
<img width="789" alt="Screenshot 2024-08-19 at 10 30 39 AM" src="https://github.com/user-attachments/assets/d3eee3d5-a38f-44fd-ac73-6236174fad81">
<img width="756" alt="Screenshot 2024-08-19 at 10 30 25 AM" src="https://github.com/user-attachments/assets/d2698136-2673-4d3f-82e7-9efd420bcddc">
<img width="790" alt="Screenshot 2024-08-19 at 10 28 42 AM" src="https://github.com/user-attachments/assets/5e560c5f-b000-48d8-98ba-cdd956d38f01">

## What areas of the site does it impact?
MHV medical records labs and tests

## Acceptance criteria
AC1  Issues 1-10 listed above have been changed
AC2   UCD has verified the changes (Lexi)

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-08-19 16:41 UTC, Wyzardsleeves submitted a review, later dismissed
Looks good.

2024-08-23 19:34 UTC, mmoyer-va requested changes

2024-08-23 19:34 UTC, mmoyer-va commented on src/applications/mhv-medical-records/util/pdfHelpers/labsAndTests.js
> +          title: 'Interpretation',
Is this supposed to be Interpretation? UCD called this out in UAT.

2024-08-23 19:58 UTC, mmoyer-va approved these changes

2024-08-26 16:47 UTC, merged