adds feature flag for sign in page
department-of-veterans-affairs/vets-website pull request #31548
Opened 2024-08-22 18:44 UTC by CaitHawk

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

Adds feature flag for upcoming sign-in modal/USiP content changes regarding the deprecation of MHV and DL Logon credential service providers.

## Related issue(s)

[Jira Ticket](https://jira.devops.va.gov/browse/VI-379)

## What areas of the site does it impact?

```platform/utilities/feature-toggle/featureFlagNames.json```

## Acceptance criteria

Add feature toggles to the frontend (vets-website) and backend (vets-api) so that the new design is editable

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

2024-08-22 23:10 UTC, rmessina1010 submitted a review, later dismissed
LGTM

2024-08-23 00:32 UTC, asg5704 commented on src/platform/utilities/feature-toggles/featureFlagNames.json
> +  "signInModalv2": "sign_in_modal_v2",
Can you change that to capital `V` please

2024-08-23 00:33 UTC, asg5704 requested changes
Can you change to a capital `V` please

2024-08-23 15:45 UTC, asg5704 approved these changes

2024-08-29 22:49 UTC, rmessina1010 approved these changes
LGTM

2024-09-04 17:40 UTC, merged