90381 facility search
department-of-veterans-affairs/vets-website pull request #31724
Opened 2024-09-03 16:08 UTC by coope93

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- UI enhancements for the 1010CG Facility Search. We are not utilizing the va-search-input component. This required converting the page to a custom page.
- Added ability to see 5 more facilities at a time. 
- The facilities selection does not currently render on the confirmation page as a result of using the new custom page. We will have a subsequent ticket to address this. 
- The changes are behind a flipper toggle [`caregiver_use_facilities_API`]

## Related issue(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/90381

## Testing done

- Uses the va-search-input component to search and load facilities. 

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

10-10CG

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

2024-09-04 14:33 UTC, coope93 commented on src/applications/caregivers/actions/fetchFacilities.js
> +        errorMessage: 'There was an error fetching the health care facilities.',
We still need confirmation on what the wording for this generic error message should be when the facilities request returns an error.

2024-09-04 14:34 UTC, coope93 commented on src/applications/caregivers/components/FormFields/FacilityList.jsx
> -  useEffect(
This was causing the page to jump to the top of the list when the `load more facilities` was loading more facilities. Now we let the parent component handle when to focus on the results.

2024-09-04 14:54 UTC, mkerns1 approved these changes, later dismissed
LGTM!

2024-09-05 14:48 UTC, longmd commented on src/applications/caregivers/components/FormFields/FacilitySearch.jsx
> +          <a href="#" onClick={showMoreFacilities}>
We need to refactor this to a `button`. This is an a11y violation. I assume you want it to look like a link? If so, we have a class for that. Lets do this as:
```
<button type="button" className="va-button-link" onClick={showMoreFacilities}>
    Load more facilities
</button>
```

2024-09-05 14:55 UTC, longmd requested changes

2024-09-05 14:55 UTC, longmd commented on src/applications/caregivers/components/FormFields/FacilitySearch.jsx
> +          <a href="#" onClick={showMoreFacilities}>
We need to refactor this to a `button`--as this is an a11y violation. I assume you want it to look like a link? If so, we have a class for that. Lets do this as:
```
<button type="button" className="va-button-link" onClick={showMoreFacilities}>
    Load more facilities
</button>
```

2024-09-05 14:55 UTC, longmd commented on src/applications/caregivers/config/form.js
> +import FacilitySearch from '../components/FormFields/FacilitySearch';
Can we nest this with the appropriate "chapter" pages--so up around L29-30?

2024-09-05 18:00 UTC, longmd approved these changes
LGTM 🚀

2024-09-05 19:29 UTC, merged