Adds error checking for ModalCreateFolder
department-of-veterans-affairs/vets-website pull request #3175
Opened 2016-09-24 00:38 UTC by webinista

Closes department-of-veterans-affairs/messaging-fe#67

- Adds error check for:
    - Existing folder name.
    - Blank folder name field (including spaces-only folder names)
    - Disallowed characters.
- Disables submit button if there is an error.
- Adds maximum length config option, error messages for ModalCreateFolder.
- Changes top margin of va-modal-button-group. Refactoring va-modal SCSS.

2016-09-24 00:51 UTC, U-DON commented on src/js/messaging/reducers/folders.js
> +      return set('data.newFolderName', action.folderName, state);
This should probably live in the modal reducer under `createNewFolder`. It is related with folders, but this state is more closely related with the `createNewFolder` modal itself.

2016-09-24 00:52 UTC, U-DON commented on src/js/messaging/reducers/folders.js
> +    case SET_FOLDER_NAME:
This should probably live in the modal reducer under `createNewFolder`. It is related with folders, but this state is more closely related with the `createNewFolder` modal itself.

I would also move the action creator to the modal action module.

2016-09-24 00:52 UTC, U-DON requested changes

2016-09-24 00:58 UTC, U-DON commented on src/js/messaging/containers/Main.jsx
> +  setFolderName
Maybe call it `setNewFolderName`?

2016-09-24 01:01 UTC, U-DON commented on src/js/messaging/containers/Main.jsx
> +  handleOnFolderNameChange(field) {
I typically see `handle*` and `on*` as complementary for naming event handling, but not together. Maybe simplify these to just `handle*`. For this one in particular, `handleNewFolderNameChange` to match the suggested change of action name to `setNewFolderName`.

2016-09-24 01:04 UTC, U-DON commented on src/sass/modules/_m-modal.scss
> +    font-size: 2.5rem;
The font-weight is displaying as normal for me and should be bold.

2016-09-24 01:07 UTC, U-DON commented
Validation is working great. Only changes I'd like to see are name/namespace related.

2016-09-24 01:21 UTC, webinista commented on src/sass/modules/_m-modal.scss
> +    font-size: 2.5rem;
Punting this one over to Vanguard. It looks like every button with a `usa-button-` prefix needs to have a `span` inside in order for it to render as bold. Can fix in this project later, but this is a global issue that affects the entire site.

2016-09-26 17:09 UTC, U-DON commented on src/js/messaging/reducers/modals.js
> +      return set('createFolder.folderName', action.folderName, state);
Path also needs to be updated to `createFolder.newFolderName`. I guess also update `SET_FOLDER_NAME` -> `SET_NEW_FOLDER_NAME`.

2016-09-26 18:29 UTC, webinista commented
Blocks work on #68.

2016-09-26 18:48 UTC, webinista commented
Closing this. It's now a mess. Going to open a new one.

2016-09-26 18:48 UTC, closed without merging