adds v2 content to login modal
department-of-veterans-affairs/vets-website pull request #31848
Opened 2024-09-09 18:36 UTC by CaitHawk

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to Summary and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

## Related issue(s)

[Jira Ticket]()

## Testing done

- unit testing
- feature flag

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

- The Login Modal
- The Unified Sign In Page

## Acceptance criteria

### Quality Assurance & Testing

- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [x] Linting warnings have been addressed
- [x] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [x] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [x] Events are being sent to the appropriate logging solution
- [x] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

2024-09-09 19:49 UTC, asg5704 commented on src/platform/user/authentication/components/LoginNote.js
> +        experience. We'll remove the My HealtheVet option after
Ensure there is a space between both `after` words and the date.
<img width="624" alt="Screenshot 2024-09-09 at 3 48 58 PM" src="https://github.com/user-attachments/assets/16fdaf82-837a-42ee-ab45-8024a44fef5d">

2024-09-09 19:54 UTC, asg5704 commented on src/platform/user/authentication/components/LoginNote.js
> +      className="vads-u-padding-x--1"
Add the `target="_blank"` and an `aria-label="Creating a Login.gov or ID.me account. (Opens in a new window)"`

2024-09-09 19:56 UTC, asg5704 commented on src/platform/user/authentication/components/LoginActions.jsx
> +              </p>
I believe this should be a part of the `h3`. Probably best to add it as a `<span className="vads-u-display--block">` to get it to wrap appropriately.

2024-09-09 19:57 UTC, asg5704 commented on src/platform/user/authentication/components/LoginActions.jsx
> +                <br />
No `<br />` needed, let it get wrapped by the container.

2024-09-09 19:57 UTC, asg5704 commented on src/platform/user/authentication/components/LoginActions.jsx
> +              </p>
Same thing. This should be in the `h3` as a `span`.

2024-09-09 19:59 UTC, asg5704 commented on src/platform/user/authentication/components/LoginHeader.jsx
> +            {isSignInV2 ? 'Sign in or create an account' : 'Sign in'}
🚀

2024-09-09 20:26 UTC, asg5704 requested changes
Only minor changes required.

Also I think the `LoginButton` component will need to be updated.
- [x] Add `ariaDescribedBy` as a prop
- [x] The button needs the `aria-describedby={ariaDescribedBy}`
- [ ] Add a unique `id` to the `h3 > span` and pass that to the <LoginButton ariaDescribedBy="mhv" for example. (We can also sync if that's confusing 😅

2024-09-10 20:46 UTC, asg5704 approved these changes

2024-09-10 20:56 UTC, asg5704 approved these changes

2024-09-12 14:27 UTC, powellkerry approved these changes

2024-09-12 15:37 UTC, merged