MHV-53461 Add alert for virus attachments
department-of-veterans-affairs/vets-website pull request #32050
Opened 2024-09-23 16:08 UTC by KolbyVA

## Are you removing, renaming or moving a folder in this PR?
- [ ] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

If the folder you changed contains a `manifest.json`, search for its `entryName` in the content-build [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) (the `entryName` there will match).

If an entry for this folder exists in content-build and you are:
1. **Deleting a folder**:
   1. First search `vets-website` for _all_ instances of the `entryName` in your `manifest.json` and remove them in a separate PR. Look particularly for references in `src/applications/static-pages/static-pages-entry.js` and `src/platform/forms/constants.js`. _**If you do not do this, other applications will break!**_
      - _Add the link to your merged vets-website PR here_
   2. Then, Delete the application entry in [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) and merge that PR **before** this one
      - _Add the link to your merged content-build PR here_

2. **Renaming or moving a folder**: Update the entry in the [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json), but do not merge it until your vets-website changes here are merged. The content-build PR must be merged immediately after your vets-website change is merged in to avoid CI errors with content-build (and Tugboat).

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [ ] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
Adds logic and alert for attachments that fail virus scanning.

## Related issue(s)
https://jira.devops.va.gov/browse/MHV-53461
> Add error message for attachments that failed virus scan by the API (Start a new message page)
> 
> Note:  This does not apply to a multiple draft scenario. (0.1% of session on va.gov run into multiple drafts)
> 
> Attachments will be scanned for viruses by the backend.  The front end will need to let the user know that the attachment did not pass the scanning process and will not be attached to the message.

## Testing done
To test, download txt test file from https://www.eicar.org/download-anti-malware-testfile/#top. This appears to the api as a virus, but is NOT an actual virus. Attach it to a message and send it. The api should throw an error and the alert should appear. This may not work with the other test file types (such as pdf), but should work with the txt file.

Unit tests fixed, 1 added

## Screenshots
![Screen Shot 2024-09-23 at 11 08 17 AM](https://github.com/user-attachments/assets/4c7f0d2d-61da-4a5e-ad8a-8d54a5a53ccd)

## What areas of the site does it impact?
mhv secure messaging

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-09-23 19:20 UTC, powellkerry submitted a review, later dismissed

2024-09-25 14:01 UTC, oleksii-morgun requested changes
@KolbyVA this is good work. I left some comments below that will require attention. Couple other things: 
1. I see some prop validation warnings. Although they may have not been part of your PR, we may have missed them during past reviews. I would appreciate if those could be added. 
2. Unit testing can be enhanced. I only saw one scenario in coverage, and in that scenario we just passed a prop that is already set. There are multiple other scenarios that we can validate here. Including using mockFetch and validating how alerts render based on API response, scenarios with multiple attachments, validating `Attach` button etc. 
3. I was not able to reproduce `ReplyDraft` scenario. Although I dont see it in Jira ticket, (I inquired in a thread about), I see ti is in your code but it does not seem to render properly

2024-09-25 14:01 UTC, oleksii-morgun commented
I converted your PR to Draft so that others are not alerted until it is ready for review

2024-09-27 17:04 UTC, oleksii-morgun approved these changes

2024-09-27 17:32 UTC, merged