payment history table heading change
department-of-veterans-affairs/vets-website pull request #32954
Opened 2024-11-07 21:17 UTC by janechodance

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

Update payment history table heading update

## Related issue(s)

* [#95135](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95135) - original issue
* [#96758](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96758) - accessibility artifact

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |   
![Screenshot 2024-11-06 at 3 34 38 PM](https://github.com/user-attachments/assets/2ae27c1d-cb58-4fb9-b4e2-03230ff3b741)
     |    
![Screenshot 2024-11-07 at 4 15 47 PM](https://github.com/user-attachments/assets/962aebc9-4015-41b8-aee5-1bdf8b2e7ad5)
   |

## What areas of the site does it impact?

payment history page

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [x] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [x] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-11-07 23:12 UTC, 1Copenut requested changes
Thank you for the early ping @janechodance. I have one request for additional change, making the blue "We don't have a record of returned payments" information box also use the H3 instead of H2. This way both alert boxes will nest under the big idea H2 "Your VA Payments".

I'll add the accessibility artifact to your PR and finish it as soon as we have this update in place. Much appreciated!

```diff
! src/applications/disability-benefits/view-payments/components/view-payments-lists/ViewPaymentsLists.jsx#51

paymentsReturnedTable = (
  <va-alert status="info">
-   <h2 slot="headline" className="vads-u-font-size--h3">
+   <h3 slot="headline" className="vads-u-font-size--h3">
      We don’t have a record of returned payments
-   </h2>
+   </h3>
    <p className="vads-u-font-size--base">
      We can’t find any returned VA payments. If you think this is an
      error, or if you have questions about your payment history, please
      call <va-telephone contact={CONTACTS.VA_BENEFITS} />.
    </p>
  </va-alert>
);
```

![Screenshot 2024-11-07 171154](https://github.com/user-attachments/assets/d86c726f-260a-4406-b2a4-b14bf6a6b87a)

2024-11-12 17:33 UTC, 1Copenut approved these changes
👍 Changes look good and cover the accessibility checklist. Thanks @janechodance

2024-11-12 18:24 UTC, dysbo approved these changes

2024-11-15 17:01 UTC, harshil1793 approved these changes

2024-11-15 17:04 UTC, merged