ToU - pass along skip_mhv_account_creation parameter on accept
department-of-veterans-affairs/vets-website pull request #33008
Opened 2024-11-13 21:10 UTC by rileyanderson

## Summary

- Update ToU to pass along skip_mhv_account_creation parameter on accept

## Related issue(s)

- https://jira.devops.va.gov/browse/VI-740
- https://github.com/department-of-veterans-affairs/vets-api/pull/19450

## Testing
- Testing instructions here: https://github.com/department-of-veterans-affairs/vets-api/pull/19450
## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?
Terms Of Use

2024-11-13 22:02 UTC, asg5704 approved these changes

2024-11-14 15:22 UTC, harshil1793 approved these changes

2024-11-14 15:25 UTC, harshil1793 requested changes
Can we try rerunning the failed test, specifically "Continuous Integration / Testing Reports - Cypress E2E Tests (push)"?

2024-11-14 15:56 UTC, asg5704 commented
> Can we try rerunning the failed test, specifically "Continuous Integration / Testing Reports - Cypress E2E Tests (push)"?

Looks like its failing because its trying to parse JSON of artifacts that aren't downloaded (aka there aren't any changes)

2024-11-15 20:16 UTC, harshil1793 approved these changes

2024-11-15 20:26 UTC, merged