add org select requirement and show selection
department-of-veterans-affairs/vets-website pull request #33015
Opened 2024-11-14 13:59 UTC by jvcAdHoc

## Are you removing, renaming or moving a folder in this PR?
- [x] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

Did you change site-wide styles, platform utilities or other infrastructure?
- [x] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- This pr adds validation to organization selection to force users to select an option
- This pr adds the `checked` attribute to the radio buttons to show users their selection when navigating backwards

## Related issue(s)

- [96835](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96835)
- [96855](https://github.com/department-of-veterans-affairs/va.gov-team/issues/96855)

## Testing done

- Went through flow locally with all rep types options as well as through the review page to confirm expected behavior

## Screenshots
### Before
https://github.com/user-attachments/assets/dac1bcac-aa70-4f38-9b4a-976023dc1115
### After
https://github.com/user-attachments/assets/296f65c2-da8b-44f5-8fe5-39c702b224c8

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [x] Did you login to a local build and verify all authenticated routes work as expected with a test user

2024-11-14 14:50 UTC, holdenhinkle approved these changes, later dismissed

2024-11-14 15:19 UTC, harshil1793 requested changes
It looks like the new code at line 10 introduces a new linting warning. Can we please clean those up before we merge this?

2024-11-14 19:58 UTC, holdenhinkle approved these changes

2024-11-18 23:53 UTC, harshil1793 approved these changes

2024-11-19 12:14 UTC, merged