MHV-61930 connect to ccd api
department-of-veterans-affairs/vets-website pull request #33128
Opened 2024-11-20 15:50 UTC by KolbyVA

## Are you removing, renaming or moving a folder in this PR?
- [ ] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [ ] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary
Connected to the Vets-api backend to generate and download Continuity of Care documents.

## Related issue(s)
https://jira.devops.va.gov/browse/MHV-62802
> Create reducer and action for CCD (This may not be needed-Check with Mike)
https://jira.devops.va.gov/browse/MHV-61930
> Connect to backend to download Continuity of Care  (CCD) document
> We do not build this report–it is an XML report.  Matt is doing the backend work.
> Check w/ UCD to see how this will work. We have to request download from original source, and the download persists in MHV for 24 hours. UPDATE: Check Slack thread - this should be one button that does both calls.
> In MHV, as soon as the user lands on the page, the app makes the request automatically to download IF records are more than 24 hours old.

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots
![image](https://github.com/user-attachments/assets/e6038dd5-69b5-4ce8-937c-6479c1f94dbb)
https://github.com/user-attachments/assets/0b814a35-4708-4be7-991c-40712fddcd96

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-11-20 16:17 UTC, mattwrightva requested changes
Looks like you still need to write unit tests.

2024-12-05 18:47 UTC, mmoyer-va requested changes

2024-12-05 18:47 UTC, mmoyer-va commented on src/applications/mhv-medical-records/actions/downloads.js
> +        12 || 12}${timestampDate.getMinutes()}${timestampDate.getSeconds()}${
Is it possible to use a library like `date-fns` here? Will the method you're using pad out zeroes if the minutes or seconds are single digit?

2024-12-05 18:47 UTC, mmoyer-va commented on src/applications/mhv-medical-records/actions/downloads.js
> +        firstName !== null ? `${firstName}-` : ''
Can `firstName` ever be undefined? Rather than checking null, can you just check all truthy values? (e.g. `{firstname ? ...}`

2024-12-05 18:47 UTC, mmoyer-va commented on src/applications/mhv-medical-records/containers/DownloadReportPage.jsx
> +            <strong>Try again after 24 hours ({CCDRetryTimestamp} ET).</strong>
We shouldn't be setting this date to ET. It should appear in the user's time zone, unless UCD specified otherwise.

2024-12-05 19:24 UTC, mmoyer-va approved these changes, later dismissed
Thanks!

2024-12-05 19:33 UTC, mattwrightva approved these changes, later dismissed
Nice!

2024-12-06 14:02 UTC, mmoyer-va submitted a review, later dismissed

2024-12-06 16:22 UTC, timothy-steele-va approved these changes, later dismissed

2024-12-06 20:08 UTC, mmoyer-va submitted a review, later dismissed

2024-12-10 18:05 UTC, mattwrightva approved these changes
Nice!

2024-12-10 18:43 UTC, merged