isolating 21a sub app
department-of-veterans-affairs/vets-website pull request #33262
Opened 2024-11-27 18:49 UTC by chumpy

https://github.com/department-of-veterans-affairs/va.gov-team/issues/96895

Step 1 of react-router upgrade is to fully isolate the 21a app from any libraries upgraded in the `accredited-representative-portal` application found in a parent directory.

The approach is to copy components shared from the parent application into the 21a application so that we can preserve any functionality affected by the upgrade to the parent application. We also are creating a workspace with a localized `package.json` file that will ensure we stay on the current version of react-router when we upgrade the parent application.

2024-12-02 20:28 UTC, nihil2501 requested changes
Nice. But I think we still need to migrate down `createReduxStore` and then update the 21a [README.md](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/accredited-representative-portal/accreditation/21a/README.md) to explain the new situation regarding the section **WIP Status and Dependency on the `representative` Application**

2024-12-03 15:44 UTC, nihil2501 approved these changes
LGTM

2024-12-03 19:18 UTC, jquispe-oddball approved these changes

2024-12-04 15:09 UTC, rsmithadhoc approved these changes

2024-12-04 15:52 UTC, merged