97067 disability benefits nb workflow choice page skeleton
department-of-veterans-affairs/vets-website pull request #33655
Opened 2024-12-18 16:13 UTC by NB28VT

WORKING DRAFT NOT READY FOR REVIEW

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [ ] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

If the folder you changed contains a `manifest.json`, search for its `entryName` in the content-build [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) (the `entryName` there will match).

If an entry for this folder exists in content-build and you are:
1. **Deleting a folder**:
   1. First search `vets-website` for _all_ instances of the `entryName` in your `manifest.json` and remove them in a separate PR. Look particularly for references in `src/applications/static-pages/static-pages-entry.js` and `src/platform/forms/constants.js`. _**If you do not do this, other applications will break!**_
      - _Add the link to your merged vets-website PR here_
   2. Then, Delete the application entry in [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) and merge that PR **before** this one
      - _Add the link to your merged content-build PR here_

2. **Renaming or moving a folder**: Update the entry in the [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json), but do not merge it until your vets-website changes here are merged. The content-build PR must be merged immediately after your vets-website change is merged in to avoid CI errors with content-build (and Tugboat).

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [ ] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#0000
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-12-18 18:14 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/config/form0781/index.js
> +  mentalHealthSupportInfoPage: {
Potentially take out if Scott's merges first (https://github.com/department-of-veterans-affairs/va.gov-team/issues/97078)

2024-12-18 18:17 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/pages/form0781/workflowChoicePage.js
> +      pTSDWorkflowChoice: {
TODO: make this a "view" property

2024-12-18 18:21 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/pages/form0781/workflowChoicePage.js
> +      pTSDWorkflowChoice: {
Leave at higher level, or consider nesting in 0781, but probably leave at high level as a view property

2024-12-18 18:22 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/config/form0781/index.js
> +  mentalHealthSupportInfoPage: {
Because he will have this page actually implemented

2024-12-18 18:29 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/config/form0781/index.js
> +  mentalHealthSupportInfoPage: {
TODO: do unit tests for these: **showManualUpload0781Page(formData),**

2024-12-19 00:05 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/config/form0781/index.js
> +  },
This looks like it's referring to [[3.3], the Upload 0781 page](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9442-62961&t=OwUuVSYswnhT7tYQ-4), when I thought the corresponding page for [#97067](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97067) was [[3.2], the 0781 choice page](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9442-72041&t=OwUuVSYswnhT7tYQ-4).

2024-12-19 00:16 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/config/form0781/index.js
> +  },
Oh, never mind. I realize now that the `workflowChoicePage` is [[3.2], the 0781 choice page](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9442-72041&t=OwUuVSYswnhT7tYQ-4).

2024-12-19 00:28 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/pages/form0781/workflowChoicePage.js
> +    pTSDWorkflowChoice: radioUI({
Perhaps consider a different name as the respective question is related to mental health and not PTSD specifically.

2024-12-19 00:30 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/config/form0781/index.js
> +  showmentalHealthSupportInfoPage,
Capitalize 'mental' for consistency.

2024-12-21 00:31 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/content/form0781.jsx
> +};
I utilized this in https://github.com/department-of-veterans-affairs/vets-website/pull/33741

2025-01-09 19:02 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/pages/form0781/workflowChoicePage.js
> +    pTSDWorkflowChoice: radioUI({
Good suggestion, changed to `mentalHealthWorkflowChoice`

2025-01-09 19:03 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/config/form0781/index.js
> +  showmentalHealthSupportInfoPage,
These import names have changed since this comment was originally posted so I think we're good now

2025-01-09 19:06 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/config/form0781/index.js
> +    depends: formData => isCompletingForm0781(formData),
I think this page merged before `isCompletingForm0781` was a thing; regardless, this change fixed accidentally jumping to this page from one of the workflow choices, since we should only see this page if the user has opted into the 0781 flow

2025-01-09 19:08 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/content/form0781.jsx
> -export const form0781WorkflowChoices = {
Created a separate content file for the workflow choice page as we've been doing with the other pages.

2025-01-09 19:09 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/pages/form0781/workflowChoicePage.js
> +    'view:mentalHealthWorkflowChoice': radioUI({
Note this property is view only, since making this selection is used for page routing, it isn't submitted to the backend

2025-01-09 19:11 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/pages/form0781/workflowChoicePage.js
> +    'view:ptsdQuestionsPreview': {
This property is required to use the collapsable content component as displayed in the Figma wireframe:

<img width="400" alt="Screenshot 2025-01-09 at 2 10 02 PM" src="https://github.com/user-attachments/assets/dee10e1e-edad-46bb-8ab1-26825fce6529" />

2025-01-10 18:12 UTC, ajones446 commented on src/applications/disability-benefits/all-claims/config/form0781/index.js
> +    depends: formData => isCompletingForm0781(formData),
Yep, I updated that in [PR 33975](https://github.com/department-of-veterans-affairs/vets-website/pull/33975/files). It just got merged into main this morning.

2025-01-10 20:56 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/pages/form0781/manualUploadPage.js
You chose not to include a screenshot for this page?

2025-01-10 21:08 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +      You selected these mental health conditions: <b>PTSD, Depression</b>.
This should display selections from [2.1] 0781 screener, `formData.mentalHealth.conditions`.

2025-01-10 21:14 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +  <VaAdditionalInfo trigger="We'll ask you questions about these topics">
use [curly apostrophe](https://design.va.gov/content-style-guide/punctuation#apostrophes)

```suggestion
  <VaAdditionalInfo trigger='We’ll ask you questions about these topics'>
```

2025-01-10 21:22 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/tests/pages/form0781/workflowChoicePage.unit.spec.js
I would also suggest including a test that confirms the correct condition(s) selected on the screener page are rendered in the description.

2025-01-11 00:46 UTC, freeheeling requested changes
Please review comments.

2025-01-13 15:11 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/pages/form0781/manualUploadPage.js
Should we include it? It's just the placeholder text

2025-01-13 16:08 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/pages/form0781/manualUploadPage.js
Just bringing it up, in case it was something you did/didn't intend to include.

2025-01-17 18:49 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/pages/form0781/manualUploadPage.js
I did end up doing this when I posted the revised screenshots

2025-01-17 18:50 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +      You selected these mental health conditions: <b>PTSD, Depression</b>.
Implemented in https://github.com/department-of-veterans-affairs/vets-website/pull/33655/commits/d68a885d16f38a3446cd4a5d5236936ecd7f76bc and https://github.com/department-of-veterans-affairs/vets-website/pull/33655/commits/6fea11d8dac18237e2e89033841b83d7dc47ef7d per the [latest copy revisions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/101227)

2025-01-17 18:50 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +  <VaAdditionalInfo trigger="We'll ask you questions about these topics">
Fixed in all places, thanks for using the suggested change feature

2025-01-17 18:51 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/tests/pages/form0781/workflowChoicePage.unit.spec.js
This should be covered well enough, have a look

2025-01-17 19:05 UTC, NB28VT commented
TODO: tests should take care of this, but as pointed out in https://github.com/department-of-veterans-affairs/va.gov-team/issues/101227 we should make sure if the user goes back and changes their selection of new disabilities it is presented on the new page (and the page is not cached, the forms library should ideally take care of this)

2025-01-21 15:15 UTC, NB28VT commented
> TODO: tests should take care of this, but as pointed out in [department-of-veterans-affairs/va.gov-team#101227](https://github.com/department-of-veterans-affairs/va.gov-team/issues/101227) we should make sure if the user goes back and changes their selection of new disabilities it is presented on the new page (and the page is not cached, the forms library should ideally take care of this)

Confirmed this locally

2025-01-21 15:52 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +        <strong>{conditions.join(', ')}</strong>.
I know that design has comma separates conditions but, after viewing the screenshot provided in the PR description, I wonder if that choice should be reconsidered as there are conditions that also include commas and, when joined with other conditions, the differentiation may be confusing. Just mentioning for consideration.

2025-01-21 16:03 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +        <strong>{conditions.join(', ')}</strong>.
Yeah I noticed that as well meant to mention that in the PR, it's less confusing because there the conditions are capitalized but it's still confusing. I'm not how we get around that, unless we revise this and list the conditions in bullet points, I can ask Ruben about that

2025-01-21 16:19 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +        <strong>{conditions.join(', ')}</strong>.
Yes we will do bulleted list here

2025-01-21 18:21 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +        <strong>{conditions.join(', ')}</strong>.
Made the change for this [here](https://github.com/department-of-veterans-affairs/vets-website/pull/33655/commits/320f881724502c90482556dc04628e209e440c6e) and updated the screenshot in the PR description

2025-01-22 21:40 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +export const traumaticEventsExamples = (
This content is also in src/applications/disability-benefits/all-claims/content/form0781.jsx.

2025-01-22 21:48 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +  return <></>;
Shouldn't there always be at least 1 condition for this page to render?

2025-01-22 21:50 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/tests/pages/form0781/workflowChoicePage.unit.spec.js
> +  it('Displays a selection of choices on filling out 0781 and incplues examples', () => {
> and incplues examples

typo? "incplues" ➡ "includes"

2025-01-22 21:55 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/tests/pages/form0781/workflowChoicePage.unit.spec.js
> +  it('should prevent continuing if a selection is not made', () => {
Is an error message displayed if attempting to continue from this page without making a selection? Should the content of that error message be tested?

2025-01-22 21:58 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/utils/form0781.js
> +export function showManualUpload0781Page(formData) {
I didn't see a test for this function.

2025-01-23 15:37 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +  return <></>;
Yes, this is pretty defensive, noted this [here](https://github.com/department-of-veterans-affairs/vets-website/pull/33655/files/320f881724502c90482556dc04628e209e440c6e#diff-5485bdc8546bee34e56df206822fac64a4da9aff823504a10efc54a53f6c0323R97) in the test.

I would assume we would want this page to render with the other helpful information instead of blowing up if there is a bug that causes the conditions to be missing and still allow getting to this page. What do you think? Maybe we can ask Ruben and Lisa about this

2025-01-23 18:04 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +  return <></>;
I did notice your inclusion of that test, but was also wondering if the page shouldn't be rendered at all. Not sure what protocol is in this situation.

2025-01-23 18:52 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +  return <></>;
Yeah revisiting this and the [content that follows it ](https://github.com/department-of-veterans-affairs/vets-website/pull/33655/files#diff-069586937c2b741226c820e0f34bc68962a1ed01a5194b71bfde4d334bdfa2ccR39) I think the page copy would never make a whole lot of sense without the conditions and we would want it to blow up. 

So I think I am going to remove the guard and the associated test here

2025-01-23 20:16 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +export const traumaticEventsExamples = (
Not quite, this one differs slightly and reflects the latest content spec from Ruben for this specific page. Also I think we're removing the other cases in a separate ticket?

Regardless, I'd say this is fine here because it's specific to this page and imported as such

2025-01-23 20:27 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/utils/form0781.js
> +export function showManualUpload0781Page(formData) {
Yeah remember we discussed these utility functions and agreed anything relating to the page routing was best saved for e2e tests? This one ended up being a [real rabbit hole](https://dsva.slack.com/archives/C053U7BUT27/p1734729884214569) because of the need to do some stubbing our test library doesn't easily support. I spent a few days trying to get that to work and stopped because we discussed it and decided we could cover it later with e2e tests.

2025-01-23 21:23 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +export const traumaticEventsExamples = (
I stand corrected. Didn't look closely enough, obviously.

2025-01-24 19:48 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/content/form0781/workflowChoicePage.jsx
> +  return <></>;
Did this in https://github.com/department-of-veterans-affairs/vets-website/pull/33655/commits/9495de49b142380baff48cbff69e3e22e724e0e8

2025-01-24 19:48 UTC, NB28VT commented on src/applications/disability-benefits/all-claims/tests/pages/form0781/workflowChoicePage.unit.spec.js
> +  it('should prevent continuing if a selection is not made', () => {
Yeah this is a good call, figured this out in https://github.com/department-of-veterans-affairs/vets-website/pull/33655/commits/5475dff3a6c59f00f7e8606a7ecef76ee44439a9

2025-01-27 17:07 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/config/form0781/index.js
> +    path:
Probably only need the subpath, `additional-forms/mental-health-statement/upload`, and not the full path here, when this page is fully implemented.

2025-01-27 17:17 UTC, freeheeling approved these changes

2025-01-27 17:30 UTC, merged