[WIP] DBEX 0781 consent page
department-of-veterans-affairs/vets-website pull request #33804
Opened 2024-12-30 20:15 UTC by ajones446

**Note**: Delete the description statements, complete each step. **None are optional**, but can be justified as to why they cannot be completed as written. Provide known gaps to testing that may raise the risk of merging to production.

## Are you removing, renaming or moving a folder in this PR?
- [ ] No, I'm not changing any folders (skip to TeamSites and delete the rest of this section)
- [ ] Yes, I'm removing, renaming or moving a folder

If the folder you changed contains a `manifest.json`, search for its `entryName` in the content-build [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) (the `entryName` there will match).

If an entry for this folder exists in content-build and you are:
1. **Deleting a folder**:
   1. First search `vets-website` for _all_ instances of the `entryName` in your `manifest.json` and remove them in a separate PR. Look particularly for references in `src/applications/static-pages/static-pages-entry.js` and `src/platform/forms/constants.js`. _**If you do not do this, other applications will break!**_
      - _Add the link to your merged vets-website PR here_
   2. Then, Delete the application entry in [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) and merge that PR **before** this one
      - _Add the link to your merged content-build PR here_

2. **Renaming or moving a folder**: Update the entry in the [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json), but do not merge it until your vets-website changes here are merged. The content-build PR must be merged immediately after your vets-website change is merged in to avoid CI errors with content-build (and Tugboat).

### :warning: TeamSites :warning:
Examples of a TeamSite: https://va.gov/health and https://benefits.va.gov/benefits/. This scenario is also referred to as the "injected" header and footer. You can reach out in the `#sitewide-public-websites` Slack channel for questions.

Did you change site-wide styles, platform utilities or other infrastructure?
- [ ] No
- [ ] Yes, and I used the [proxy-rewrite steps](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite#that-sounds-normal-so-whats-the-proxy-all-about) to test the injected header scenario

## Summary

- _(Summarize the changes that have been made to the platform)_
- _(If bug, how to reproduce)_
- _(What is the solution, why is this the solution)_
- _(Which team do you work for, does your team own the maintenance of this component?)_
- _(If using a flipper, what is the end date of the flipper being required/success criteria being targeted)_

## Related issue(s)

- _Link to ticket created in va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000
- _Link to previous change of the code/bug (if applicable)_
department-of-veterans-affairs/vets-website#0000
- _Link to epic if not included in ticket_
department-of-veterans-affairs/va.gov-team#0000

## Testing done

- _Describe what the old behavior was prior to the change_
- _Describe the steps required to verify your changes are working as expected_
- _Describe the tests completed and the results_
- _Exclusively stating 'Specs and automated tests passing' is NOT acceptable as appropriate testing
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_

## Screenshots

_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

|         | Before | After |
| ------- | ------ | ----- |
| Mobile  |        |       |
| Desktop |        |       |

## What areas of the site does it impact?

*(Describe what parts of the site are impacted **if** code touched other areas)*

## Acceptance criteria

### Quality Assurance & Testing

- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
- [ ] Linting warnings have been addressed
- [ ] Documentation has been updated ([link to documentation](#) \*if necessary)
- [ ] Screenshot of the developed feature is added
- [ ] [Accessibility testing](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) has been performed

### Error Handling

- [ ] Browser console contains no warnings or errors.
- [ ] Events are being sent to the appropriate logging solution
- [ ] Feature/bug has a monitor built into Datadog or Grafana (if applicable)

### Authentication

- [ ] Did you login to a local build and verify all authenticated routes work as expected with a test user

## Requested Feedback

(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any concerns with this PR, why?_

2024-12-31 18:37 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/content/form0781/consentPage.jsx
> +  notEnrolled: "I'm not enrolled or registered in VA health care.",
use [curly apostrophe](https://design.va.gov/content-style-guide/punctuation#apostrophes)

```suggestion
  notEnrolled: 'I’m not enrolled or registered in VA health care.',
```

2024-12-31 18:39 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/content/form0781/consentPage.jsx
> +export const consentPageFormTitle =
May more accurately be named a 'question', rather than a 'title'.

2024-12-31 18:43 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/content/form0781/consentPage.jsx
> +      may know that your claim is related to MST.{' '}
Is the empty string literal necessary?

2024-12-31 18:50 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/pages/form0781/consentPage.js
> +export const uiSchema = {
This page will also eventually need the shared [heading tag](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9442-72051&t=z8iO1AbxK4gCM22i-4) and [mental health support alert component](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9250-96482&t=7cOgvcqLHTDovLbx-4) (incorporated in https://github.com/department-of-veterans-affairs/vets-website/pull/33811)

2024-12-31 19:03 UTC, freeheeling requested changes
Some minor suggestions to consider, otherwise looks great.

2025-01-02 22:38 UTC, ajones446 commented on src/applications/disability-benefits/all-claims/content/form0781/consentPage.jsx
> +      may know that your claim is related to MST.{' '}
Good catch! Not sure why it's there, might have been a copy pasta or linter weirdness. I'll remove it.

2025-01-02 22:47 UTC, ajones446 commented on src/applications/disability-benefits/all-claims/pages/form0781/consentPage.js
> +export const uiSchema = {
Great! Thanks for adding those. I made a note in the ticket to add them in later.

2025-01-03 00:28 UTC, freeheeling commented on src/applications/disability-benefits/all-claims/utils/form0781.js
> +    formData.mentalHealth.eventTypes.mst === true
Previously overlooked that optional chaining should be added here to avoid throwing a TypeError, in the event a property is null or undefined.

2025-01-03 18:45 UTC, freeheeling approved these changes

2025-01-06 19:31 UTC, Andrew565 approved these changes

2025-01-06 20:14 UTC, merged