Switch from phantomjs to electron
department-of-veterans-affairs/vets-website pull request #4740
Opened 2017-01-24 20:33 UTC by alexose

This is a big PR with a lot of changes:

* Added electron and chromedriver dependencies
* Pulled out a lot of the Selenium and PhantomJS dependencies and installation scripts
* Upgraded nightwatch
* Added dependencies that PhantomJS somehow was able to ignore
* Added some extra magic to our .travis.yml that will make electron work headlessly
* Introduced a way to disable smooth scrolling on a per-page basis (at some point, this needs to have much less code repetition.)
* Added a `selectDropdown` helper that sidesteps the problems with clicking on large `select` lists
* Fixed a gaggle of tests so that they pass consistently

Futurevision:
I tried not to impose my view on the existing test suite, although I would like to consider drastically reducing the amount of individual assertions.

Even without reducing the workload, there should be plenty of room for speed improvements.  These will be showing up in future PRs, I think.

While working on this PR, I created a docker image that mimics our Travis environment.  This is so we can avoid that annoying thing where tests pass locally and fail in CI.  I [published it over at Docker hub](https://hub.docker.com/r/alexose/vets-gov-e2e/), but it needs documentation.

2017-01-25 12:40 UTC, jcmeloni-usds commented
This is so exciting!

2017-01-31 18:16 UTC, robbiethegeek commented
@alexose can you fix the conflicts then @crwallace @aub @robbiethegeek-usds will all review

2017-01-31 18:17 UTC, robbiethegeek-usds commented
@alexose can you please resolve the conflicts and then @aub @crwallace and I can jump in and do a review.

2017-01-31 18:18 UTC, alexose commented
On it

2017-02-02 15:05 UTC, crwallace commented on package.json
> +    "jquery": "^3.1.1",
@alexose -- Do we need jquery? I know we are trying to pull it out of the codebase if we can.

2017-02-02 19:48 UTC, alexose-gov commented on package.json
> +    "jquery": "^3.1.1",
I don't think we need jQuery anymore.  Will test and find out

2017-02-02 20:30 UTC, jcmeloni-usds commented on package.json
> +    "jquery": "^3.1.1",
It's ALMOST out, pending a PR that @aub has, I believe.

2017-02-02 22:10 UTC, crwallace commented
I feel like you taking the time to work on tests to make sure that they pass consistently, alothough might not speed up tests, will contribute to developer happiness and I feel like that is important to note. 

One other question I have is if we are okay with the popup that opens while these tests are running. I was unable to run these tests locally in the background as the popup kept...well...popping up. 

Would love others thoughts on this.

2017-02-02 22:10 UTC, crwallace commented
sorry that was an accidental close.

2017-02-02 22:12 UTC, alexose-gov commented
It's definitely annoying that the electron window pops up frequently and switches focus-- I plan to fix that by wrapping the call to the binary in another file (which is exactly how spectron does it).

2017-02-13 19:07 UTC, aub requested changes
This looks good to me with a couple of small comments below.

2017-02-13 19:07 UTC, aub commented on test/util/e2e-helpers.js
> +}
Funky spacing here.

2017-02-14 15:51 UTC, merged