content/wip/links-to-EDU-form
department-of-veterans-affairs/vets-website pull request #5608
Opened 2017-05-23 21:57 UTC by peggygannon

2017-05-24 00:00 UTC, peggygannon commented
@J-Quag @iantopper EDU link PR ready for your review.

2017-05-24 03:17 UTC, bethpotts approved these changes
Looks great! I made a couple little edits. Thanks for getting this done so fast, Peggy.

2017-05-24 12:09 UTC, rroueche commented
@J-Quag technically the changes look good to me, but I have a few comments for you -- if you like these, then we can update and re-review:

1) On the [Fry Scholarship page](https://vetsgov-pr-5608.herokuapp.com/education/gi-bill/survivors-dependent-assistance/fry-scholarship/), I think we can go directly to the form intro page itself (instead of the generic apply page) because the form intro page lists out the steps for how to prepare and check eligibility etc: https://www.vets.gov/education/apply-for-education-benefits/application/5490/introduction

2) On the [Transfer page](https://vetsgov-pr-5608.herokuapp.com/education/gi-bill/transfer/), I think we can also link directly to the form into page: https://www.vets.gov/education/apply-for-education-benefits/application/1990e/introduction

3) On the Montgomery Pages (https://vetsgov-pr-5608.herokuapp.com/education/gi-bill/montgomery-active-duty/) and (https://vetsgov-pr-5608.herokuapp.com/education/gi-bill/montgomery-selected-reserve/), can we also go directly to the form form intro? https://www.vets.gov/education/apply-for-education-benefits/application/1990e/introduction

4) On the [Dependents Page](https://vetsgov-pr-5608.herokuapp.com/education/gi-bill/survivors-dependent-assistance/dependents-education/) can we also go directly to the form intro: https://www.vets.gov/education/apply-for-education-benefits/application/5490/introduction

2017-05-24 16:31 UTC, bethpotts commented
@J-Quag @iantopper I see a couple more tweaks from the editorial side. Letting you know that I'm going back in to make a few more commits.

2017-05-25 16:05 UTC, bethpotts commented
@J-Quag If you agree with @rroueche that the above pages she lists should point directly to the form intro rather than the general application process page, the content team can implement. Let me know! I like the idea of fewer steps for the Veteran to take, so I'll throw in a vote for directing users to the form itself.

2017-05-25 17:00 UTC, J-Quag commented
So part of what we're creating for Education is the wizard that will allow users to go through a flow that indicates what form they should fill out. The thought is that users can go through that if they are not definitely sure of the form they should fill out. 
Though if they are in the discovery pages, I would suppose that is being worked out. @goldenmeanie  do you have thoughts on this? 
If they are in pages for discovery and that is the form they want, we could just direct them to that form instead of the apply page w/wizard?

2017-05-25 18:28 UTC, rroueche commented
@J-Quag i still think a forms wizard could be a valuable tool -- probably in addition to the eligibility/discovery static content. I think we can link directly to the forms from the discovery content, but that shouldn't detract from the wizard work. Maybe part of the wizard discovery could be testing out how people react to reading to find the right tool for them, vs using a wizard to be directed to the right one.

2017-05-25 21:42 UTC, goldenmeanie commented
Some of those pages would need to link to multiple forms, right? For example, GI Bill is either 1990, 1990E, or 1995.

2017-05-26 16:47 UTC, rroueche commented
@goldenmeanie @J-Quag there are only a few places where I recommend linking directly, see recs 1-4 in my comment above and let me know what ya think!

2017-05-30 13:45 UTC, rroueche commented
Related to: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2934

2017-05-30 15:53 UTC, goldenmeanie commented
I am totally on-board with the ability to apply from these pages! 

On the general apply page we have an "option button" that gives a little help in choosing the right form. We could embed that button on the benefit pages and I think it would cover the cases where there are multiple forms you might need. Does that make sense?

2017-05-30 16:39 UTC, rroueche commented
@goldenmeanie i think that is a fabulous idea! @bethpotts or @amybehrens sound good to you? If so, then we can move fwd w/that plan -- @goldenmeanie may need your help in terms of the show/hide options thing you mentioned on the phone.

2017-05-30 19:55 UTC, bethpotts commented
@goldenmeanie @rroueche @peggygannon Sounds like a great idea! Peggy has already updated the links on the pages you listed earlier in this string where there's no need for the option button. The links go directly to the appropriate intro page for the form itself.

2017-08-02 15:20 UTC, leannammiller commented
@peggygannon it seems like this is complete? if so please close!

2017-08-02 17:09 UTC, peggygannon commented
@leannammiller Closing this. Thanks!

2017-08-02 17:54 UTC, peggygannon commented
@leannammiller

2017-08-03 22:11 UTC, bethpotts commented on content/pages/education/other-educational-assistance-programs/call-to-service.md
> +Apply online with VA Form 22-1990N. [Find out how to apply](/education/apply/).
@goldenmeanie You're right! You found another one. I see this wasn't in Rachael's original list. Yes, please go ahead and think this one directly too. Thanks!!

2017-08-03 22:14 UTC, bethpotts commented on content/pages/education/other-educational-assistance-programs/call-to-service.md
> +Apply online with VA Form 22-1990N. [Find out how to apply](/education/apply/).
@goldenmeanie Forgot to say, please link the whole line as Rachael did above in her last couple of commits: [Apply online with VA Form 22-1990N]. Thanks!

2017-08-14 18:55 UTC, bethpotts commented
@goldenmeanie @J-Quag We're ready to get this merged and to production tomorrow or Wednesday if you want to take a last look. I'll ask Chris V. to review our markdown to make sure all's well if that sounds good to you. Then Sophia can merge for us. Thanks! It'll be great to wrap this one up.

2017-08-15 22:56 UTC, peggygannon commented
@cvalarida This pull request resolves this issue: department-of-veterans-affairs/vets.gov-team/issues/4331.

It's a long PR (sorry! it's been around a while) Can you review the code in the most recent commits?

2017-08-16 16:48 UTC, cvalarida requested changes
Still need to hook up the JS so the wizard actually works, so I'm blocking this from getting merged until I (or somebody) can get that fix in.

2017-08-16 22:08 UTC, cehsu commented on src/js/no-react-entry.js
> +const wizardPages = new Set(['/education/apply/', '/education/eligibility/']);
The wizard is now required on the eligibility page.

2017-08-17 17:55 UTC, peggygannon commented on src/js/no-react-entry.js
> +const wizardPages = new Set(['/education/apply/', '/education/eligibility/']);
@cehsu @cvalarida Hello! Looks like the wizard is enabled. Is this PR ready to be merged?

2017-08-17 22:38 UTC, cvalarida approved these changes
Tested locally and it works. I think we're golden!

2017-08-17 22:38 UTC, cvalarida commented on src/js/no-react-entry.js
> +if (wizardPages.has(location.pathname)) {
Ooh, this is much nicer!

2017-08-17 22:40 UTC, cvalarida commented
Ideally, we wouldn't duplicate all that html, but I this this is fine for now. We can circle back around to it and come up with a way to maybe provide a `div` with a specific ID that gets populated with the elements when the wizard javascript file is loaded. This would reduce duplication, though it's a little nasty. I'd rather use the templating engine, but... :man_shrugging:

2017-08-17 23:05 UTC, cehsu commented
Great idea @cvalarida, @peggygannon is there any reason to keep this as HTML? Would content/design ever want to be able to edit this directly or now that it's fairly done, is it ok to simply handle this using JavaScript?

2017-08-17 23:32 UTC, cvalarida commented
More specifically, is there a reason we'd need to have different content for this in the eligibility vs application process page?

2017-08-17 23:35 UTC, peggygannon commented
@cehsu @cvalarida Good question! The only reason I would encourage to keep this wizard in HTML is so content and design would still have the flexibility to edit the wizard questions if needed in the future. 
The content on the eligibility page should be the same as the apply page. 

 ccing @bethpotts  for her input as well. Beth, see Claire's question ^^ about Javascript.

2017-08-18 02:29 UTC, bethpotts commented
@cehsu @cvalarida @peggygannon  What's the benefit to switching to javascript? I guess I hesitate to do that if we wouldn't be able to edit the words further--if we did testing, for instance, and found that we wanted to reword some questions. But would love to understand why you'd like to move from html to javascript. I don't have any insight there... thanks!
Tagging @goldenmeanie in case he has any thoughts on this. I think this option button for the application process page started with you, Alex, right?

2017-08-18 03:00 UTC, goldenmeanie commented
My read on this is that the plan is to use Javascript to dynamically insert a snippet of HTML into all the places on vets.gov that it shows up. The idea being that if there are any edits you only make them in the one place and it ripples out from there. But maybe I am misinterpreting the intent?

I would generally prefer for stuff like this to remain editable by mere mortals. But I would love to hear more from the devs.

2017-08-18 17:03 UTC, cvalarida commented
@goldenmeanie @peggygannon @bethpotts

I'm not sure if the content team has any access restrictions or anything like that, but if we move it to javascript, you guys should still be able to edit it just fine. The main benefit for inserting the html via javascript is, like @goldenmeanie said, so we can edit the content in one file and have the changes cascade to everywhere it's used.

Also, if we found we wanted to add it somewhere else, we can just "plug it in" and have it just work.

I just talked to @cehsu and it sounds like she'll get started on that conversion. It shouldn't take long, and there _shouldn't_ (:crossed_fingers:) be a problem with editing the content the way we're looking at wiring this up.

More information to come!

2017-08-18 17:12 UTC, cvalarida commented
**Update:** We'll go ahead and merge this now, while @cehsu works on the unified, plug-n-play version.

2017-08-18 17:12 UTC, merged