Fix sidebar visibility issues for disability claims
department-of-veterans-affairs/vets-website pull request #5686
Opened 2017-06-05 18:13 UTC by bshyong

Resolves https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3076

2017-06-06 17:58 UTC, melwoodard reviewed
@bshyong this looks good. Is there an easy way to bring back the slide-out transition that used to happen when the menu is opened?

2017-06-07 00:10 UTC, U-DON approved these changes
LGTM. Might be a way to maintain the animated sliding effect, but not sure.

2017-06-07 00:39 UTC, bshyong commented
I'll add this in—we can't hide the element completely if we want to keep transitions; we have to make it invisible with a height/width of 0 instead.

2017-06-07 16:33 UTC, melwoodard requested changes
The scale effect still isn't really right. If it isn't easy to do the slide-in without visible scaling, I say let's just keep it simple and take out the transition effect.

2017-06-07 20:03 UTC, bshyong commented
@melwoodard updated—take a look at this and see what you think

http://recordit.co/d1dZ8pGOS2

2017-06-07 21:53 UTC, U-DON commented on src/sass/modules/_m-nav-sidebar.scss
> +      &+ div:before {
Super nitpick: usually I leave a space between the `&` and the operator.

2017-06-08 16:25 UTC, melwoodard reviewed
@bshyong better, but still seems funky with the scale effect stretching the menu out when it appears. I'm looking at this locally too and now the gray transparent overlay is on top of the menu, preventing me from interacting with it. I don't want to keep you spinning on this forever, so let's go back to the static transition for now and I can put in an issue to come back to the fine-tuning later.

2017-06-08 17:30 UTC, bshyong commented
Updated—no animation now and we can improve this later and add animations back in

2017-06-08 21:25 UTC, melwoodard approved these changes
Thank you! Looks great, and I'll add the animation issue for the future.

2017-06-08 21:29 UTC, merged