Add benefits pages to burials form
department-of-veterans-affairs/vets-website pull request #5771
Opened 2017-06-15 15:00 UTC by jbalboni

Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3148

Adds benefits selection pages:

![screen shot 2017-06-15 at 10 59 15 am](https://user-images.githubusercontent.com/634932/27187682-d2315148-51b9-11e7-9c51-e0642f80c3d1.png)
![screen shot 2017-06-15 at 10 59 27 am](https://user-images.githubusercontent.com/634932/27187683-d232323e-51b9-11e7-84c8-6453672a0ab2.png)
![screen shot 2017-06-15 at 10 59 21 am](https://user-images.githubusercontent.com/634932/27187681-d22d03a4-51b9-11e7-884d-c3ff6c3f3d81.png)

2017-06-15 15:00 UTC, jbalboni commented on package.json
> +    "vets-json-schema": "https://github.com/department-of-veterans-affairs/vets-json-schema.git#689259b3a3134ed044f7b9edadd5f77201287a4f"
This is not in master yet.

2017-06-15 15:01 UTC, jbalboni commented on package.json
> +    "vets-json-schema": "https://github.com/department-of-veterans-affairs/vets-json-schema.git#689259b3a3134ed044f7b9edadd5f77201287a4f"
This is not in master yet.

2017-06-15 15:44 UTC, jbalboni commented
I still need to check on the explanatory text that's in the outline, I'm not sure how that is supposed to work and may be a separate ticket.

2017-06-15 16:37 UTC, cehsu commented on src/js/burials/config/form.js
> +              'ui:title': 'Did you previously recieve a VA burial allowance?',
receive not receive

2017-06-15 16:38 UTC, cehsu commented on src/js/burials/config/form.js
> +              previouslyReceiveAllowance,
If changed in backend schema, this should be updated as well.

2017-06-15 16:49 UTC, cehsu commented
@jbalboni Good question about the explanatory text, is it intended to be a tooltip?

2017-06-15 17:08 UTC, cehsu commented
Could you please swap out the burial allowance screenshot for one in which VA MC Death is selected to reveal the actual burial cost field?

2017-06-15 17:19 UTC, jbalboni commented
@cehsu Yep, I asked and it's a link that opens a modal (the rx app does this). We would need to add support for that to our FieldTemplate component. I'm going to put that in a separate ticket.

2017-06-15 17:37 UTC, jbalboni commented
@cehsu Ticket is here: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3332. It's ready to go if you want to tackle it after the burials page you're working on.

2017-06-15 17:43 UTC, cehsu commented on test/burials/config/plotAllowance.unit.spec.jsx
> +    formDOM.fillData('#root_placeOfRemains', 'Cemetary');
I asked a question in the issue about whether any of the options here are mutually exclusive.

2017-06-15 17:45 UTC, cehsu commented on test/common/schemaform/validation.unit.spec.js
> +    it('should not add error if no props are true', () => {
should this be is prop is true?

2017-06-15 17:47 UTC, cehsu approved these changes
LGTM. Thanks for already answering my questions. Had minor questions/comments.

2017-06-15 21:16 UTC, cehsu requested changes
It looks like some updates are required due to this new information from @stacyhlinn (copying from issue):
@cehsu

Let's update to:

Was the Veteran buried in a national cemetery, or one owned by the federal government?* [Y/N]

{If previous answer is N} Was the Veteran buried in a state Veteran's cemetery?* [Y/N]

cc'ing @J-Quag for transparency.

2017-06-15 21:45 UTC, cvalarida approved these changes

2017-06-15 21:45 UTC, cvalarida commented on test/burials/config/burialAllowance.unit.spec.jsx
> +    expect(Array.from(formDOM.querySelectorAll('.usa-input-error')).length).to.equal(1);
In the next test, you get the length of a `.querySelectorAll()` without doing `Array.from()`. Is it necessary?

2017-06-15 21:45 UTC, cvalarida commented on test/burials/config/burialAllowance.unit.spec.jsx
> +    expect(Array.from(formDOM.querySelectorAll('.usa-input-error')).length).to.equal(0);
Here too.

2017-06-15 21:45 UTC, cvalarida commented on test/burials/config/plotAllowance.unit.spec.jsx
> +    expect(Array.from(formDOM.querySelectorAll('.usa-input-error')).length).to.equal(4);
Flagging this one too for visibility...

2017-06-15 21:45 UTC, cvalarida commented on test/burials/config/plotAllowance.unit.spec.jsx
> +    expect(Array.from(formDOM.querySelectorAll('.usa-input-error')).length).to.equal(0);
Please forgive the [spam](https://www.youtube.com/watch?v=anwy2MPT5RE).

2017-06-15 22:57 UTC, cehsu commented on test/burials/config/burialAllowance.unit.spec.jsx
> +    expect(Array.from(formDOM.querySelectorAll('.usa-input-error')).length).to.equal(1);
The NodeList should have a length property already? [source](https://www.w3schools.com/jsref/met_document_queryselectorall.asp)

2017-06-16 00:09 UTC, cehsu commented on src/js/burials/config/form.js
> +              'ui:title': 'Was the Veteran buried in a state Veteran’s cemetery?',
`Veterans` not `Veteran's`, courtesy of @peggygannon

2017-06-16 01:19 UTC, jbalboni commented on test/burials/config/burialAllowance.unit.spec.jsx
> +    expect(Array.from(formDOM.querySelectorAll('.usa-input-error')).length).to.equal(1);
I think we did that to use it with `filter`, but yeah, not necessary here.

2017-06-16 01:29 UTC, jbalboni commented
@cehsu Should be all fixed now.

I did realize I spelled cemetery wrong for the property names, so I'll make an issue to go back and fix that.

2017-06-16 01:30 UTC, cehsu approved these changes

2017-06-16 01:48 UTC, merged