wip - draft static copy burials for pre need integration
department-of-veterans-affairs/vets-website pull request #5870
Opened 2017-06-26 17:31 UTC by DanielleSoCompany

Draft copy created for discussion.

2017-09-22 19:25 UTC, ghost approved these changes

2017-09-22 21:38 UTC, bethpotts commented
@phiden Would you kindly review and merge? Thanks!

2017-09-25 13:56 UTC, phiden requested changes
@bethpotts would you mind fixing the merge conflicts please?

2017-09-25 17:59 UTC, phiden approved these changes

2017-09-25 21:31 UTC, bethpotts commented
@phiden Ready to merge! Thanks.

2017-09-26 13:45 UTC, merged