New FAQ page
department-of-veterans-affairs/vets-website pull request #6270
Opened 2017-08-23 19:34 UTC by bshyong

Connects to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/3504

![screen shot 2017-08-23 at 12 20 55 pm](https://user-images.githubusercontent.com/303289/29634646-5dde5b7a-87ff-11e7-97eb-360d8d376757.png)

![screen shot 2017-08-23 at 12 34 23 pm](https://user-images.githubusercontent.com/303289/29634663-6ae1a6f6-87ff-11e7-8667-8b33e966567b.png)

2017-08-23 21:19 UTC, U-DON approved these changes
LGTM.

2017-08-23 21:19 UTC, U-DON commented on src/js/common/components/authentication/LoginPrompt.jsx
> +            <h5>Having trouble signing in?</h5>
I wonder why we're changing the language from "Sign In" to "Log In" but using "signing in" here.

2017-08-23 21:21 UTC, U-DON commented on src/js/common/components/authentication/LoginPrompt.jsx
> +            <h5>Having trouble signing in?</h5>
@melwoodard: ^

2017-08-24 17:21 UTC, melwoodard requested changes
A couple things:

- All phone numbers in the "What if I can't verify my identity online?" and "Need help?" accordions should be `tel` links
- In the "How do I verify" accordion, the two links to id.me aren't loading. @amybehrens do you know why?

2017-08-24 17:22 UTC, melwoodard requested changes

2017-08-24 17:22 UTC, melwoodard commented on src/js/common/components/authentication/LoginPrompt.jsx
> +            <h5>Having trouble signing in?</h5>
Let's revert this to "sign in"

2017-08-24 17:22 UTC, melwoodard commented on src/js/common/schemaform/SaveInProgressErrorPage.jsx
> +                  onUpdateLoginUrl={this.props.updateLogInUrl}>Log in</SignInLink>
Let's revert this to "sign in"

2017-08-24 17:22 UTC, melwoodard commented on src/js/login/components/SearchHelpSignIn.jsx
> +        <a href="#" onClick={this.props.onUserLogin}>Log In</a><span className="signin-spacer">|</span><a href="#" onClick={this.props.onUserSignup}>Sign up</a>
Let's revert this to "sign in"

2017-08-24 17:22 UTC, melwoodard commented on test/common/schemaform/SaveInProgressErrorPage.unit.spec.jsx
> +    expect(findDOM.querySelector('.usa-button-primary').textContent).to.contain('Log in');
Let's revert this to "sign in"

2017-08-24 17:58 UTC, bshyong commented
Changes made! The "how do I verify" links belong to ID.me but they are not loading for me either. This is the URL that is in the FAQ page:

https://vetsgov.id.me/hc/en-us/articles/229334788-How-do-I-complete-the-LOA3-identity-proofing-process-

2017-08-24 19:21 UTC, melwoodard commented
Thanks Ben! Turns out id.me moved their FAQ. This should be the correct page: https://support.id.me/hc/en-us/articles/229334788-How-do-I-complete-the-LOA3-identity-proofing-process-

2017-08-25 15:30 UTC, bshyong commented
Links are updated; if all looks good we can get this page launched today

2017-08-25 15:47 UTC, melwoodard requested changes
One more thing! I overlooked the "need help" box - can you make the phone numbers tel links there too? Other than that looks good!

2017-08-25 16:15 UTC, melwoodard approved these changes
Thanks, looks great!

2017-08-25 16:27 UTC, merged