Change apostrophes
department-of-veterans-affairs/vets-website pull request #6376
Opened 2017-09-08 22:03 UTC by cvalarida

We've been trying to keep the apostrophes consistently curly, so this just updates a few that I saw while going through the letters code.

2017-09-08 22:23 UTC, markgreenburg requested changes
Good eye! I know of a couple more that you can roll in:
https://github.com/department-of-veterans-affairs/vets-website/blob/f0c50fab58e43168ee98d491fed6481f57da044f/src/js/letters/components/DownloadLetterLink.jsx#L59

2017-09-09 02:36 UTC, raquelromano-gov approved these changes
I like the "consistently curly"--easy to remember

2017-09-11 16:52 UTC, cvalarida commented
@markgreenburg Cool! Just added a couple more. 👍

2017-09-11 17:32 UTC, markgreenburg approved these changes

2017-09-12 21:53 UTC, merged