Update supporting documents description text, hook up attachments
department-of-veterans-affairs/vets-website pull request #6770
Opened 2017-11-13 16:02 UTC by jbalboni

Updates description. Also connects the file upload fields based on @lihanli's branch. I'm going to set up the attachment type in a separate PR.

Veteran:
![screen shot 2017-11-10 at 10 44 01 am](https://user-images.githubusercontent.com/634932/32735049-baaa2fb2-c861-11e7-98bb-f62dc0fe0182.png)

Sponsor/other:
![screen shot 2017-11-10 at 10 43 36 am](https://user-images.githubusercontent.com/634932/32735050-bab7f43a-c861-11e7-8133-1a42fde021ad.png)

Unmarried child:
![screen shot 2017-11-10 at 10 42 38 am](https://user-images.githubusercontent.com/634932/32735051-bac3d174-c861-11e7-8ab5-5583d4a3398a.png)

2017-11-15 17:22 UTC, lihanli approved these changes
api call lgtm

2017-11-15 20:43 UTC, cehsu approved these changes
LGTM. Some minor questions, including one that might be good to check in with @peggygannon about.

2017-11-15 20:43 UTC, cehsu commented on src/js/pre-need/components/SupportingDocumentsDescription.jsx
> +        <p>You’ll also need to provide supporting documents, such as :</p>
Is there supposed to be an space before the colon?

2017-11-15 20:43 UTC, cehsu commented on src/js/pre-need/components/SupportingDocumentsDescription.jsx
> +          <li>The manager or principal officer of an institution in which the applicant is being care for</li>
Should this be "cared for" (with a "d")? Also, it ends with a preposition, not sure if that's something we want to try to avoid.

2017-11-15 20:43 UTC, cehsu commented on test/pre-needs/config/documents.unit.spec.jsx
> +    expect(formDOM.querySelectorAll('.usa-input-error').length).to.equal(0);
Could we use `empty` here instead?

2017-11-15 21:05 UTC, peggygannon requested changes
@jbalboni Please see my edits below. I've only listed my changes below (some of the text looked fine as is). Can I see a screenshot when the updates are in? Tx!

If you have supporting documents, you can upload them here. This will help us make a determination more quickly. 

for Veteran
[What kinds of documents should I provide?]
To apply, you'll need a copy of your DD214 or other separation papers. This will help us figure out if you qualify for burial in a VA national cemetery based on your military status and service history. If you don’t have these documents, you can still apply--and we’ll request the documents for you. 

--please bold the "or"s in the bulleted list 
--update this bullet point to: The manager or principal officer of an institution in which the applicant is being cared for

Sponsor/other
To apply, you'll need a copy of your sponsor's DD214 or other separation papers. This will help us figure out if you qualify for burial in a VA national cemetery based on your sponsor's military status and service history. If you don’t have these documents, you can still apply--and we'll request the documents for you. 

--please bold the "or"s in the bulleted list
--update this bullet point to: The manager or principal officer of an institution in which the applicant is being cared for 

Unmarried child
[What kinds of documents should I provide?]
To apply, you'll need a copy of your sponsor's DD214 or other separation papers. This will help us figure out if you qualify for burial in a VA national cemetery based on your sponsor's military status and service history. If you don’t have these documents, you can still apply--and we'll request the documents for you. 

You’ll need to upload supporting documents showing:
Medical evidence of a disability
Start date of a disability
Age when diagnosed with a disability

--please bold the "or"s in the bulleted list
--update this bullet point to: The manager or principal officer of an institution in which the applicant is being cared for

2017-11-15 23:56 UTC, peggygannon commented
@jbalboni Just one small tweak. Under unmarried adult child, Can we change this sentence: 
You'll need to upload supporting documents showing:

To
You'll need to also provide supporting documenting showing: 

I realized we should probably take out the word "upload" as some people might actually mail or fax the documentation.

2017-11-16 03:44 UTC, jbalboni commented
@peggygannon Screenshot's updated.

2017-11-16 14:11 UTC, peggygannon approved these changes

2017-11-16 14:12 UTC, peggygannon commented
@jbalboni LGTM!

2017-11-16 14:24 UTC, merged