Set up FDC page
department-of-veterans-affairs/vets-website pull request #7592
Opened 2018-04-13 22:36 UTC by cehsu

These changes set up the FDC page.

TODO:
- [ ] move helpers and remove React import from form.js
- [ ] write tests

([Additional ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9109))

![screen shot 2018-04-13 at 3 32 45 pm](https://user-images.githubusercontent.com/16051172/38760441-1d1a1ece-3f30-11e8-930c-64b14d9118da.png)
![screen shot 2018-04-13 at 3 32 37 pm](https://user-images.githubusercontent.com/16051172/38760445-22c278ee-3f30-11e8-9f6a-21f99687f7b6.png)

2018-04-13 23:25 UTC, peggygannon requested changes
@cehsu Hi, Claire, this is not the content I provide for the claims increase FDC page. Please see this ticket for the correct copy: 
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/9950

2018-04-13 23:35 UTC, cehsu commented
Thanks @peggygannon, updated.
![screen shot 2018-04-13 at 4 33 38 pm](https://user-images.githubusercontent.com/16051172/38761534-93a244b0-3f38-11e8-9101-b99b5d1e34b1.png)
![screen shot 2018-04-13 at 4 34 55 pm](https://user-images.githubusercontent.com/16051172/38761558-b0351d32-3f38-11e8-9d22-b7c5cfcdef40.png)
![screen shot 2018-04-13 at 4 35 13 pm](https://user-images.githubusercontent.com/16051172/38761561-b3557228-3f38-11e8-945d-5464d1e217fb.png)

2018-04-14 00:01 UTC, peggygannon approved these changes

2018-04-18 00:07 UTC, cvalarida reviewed
Looks like this is still a WIP, but once you bring back the other chapters, it looks good--just a couple of nits.

2018-04-18 00:07 UTC, cvalarida commented on src/js/disability-benefits/526EZ/config/form.js
> +      'Please sign in again to resume your application for disability claims increase.'
Can we move this back up to the line on which the property is defined?

2018-04-18 00:07 UTC, cvalarida commented on src/js/disability-benefits/526EZ/config/form.js
> -    chapterTwo: {
Um...I'm guessing you didn't intend to nuke all the other chapters?

2018-04-18 00:07 UTC, cvalarida commented on src/js/disability-benefits/526EZ/config/form.js
> +                    'No, I have some extra information that I will submit to VA later.'
Is it a VS Code setting to move long strings down to their own line? It only moves the whole string one character to the left, so it's not actually saving much horizontal space.

2018-04-18 00:07 UTC, cvalarida commented on src/js/disability-benefits/526EZ/config/form.js
> +                yesNoReverse: true,
Oh interesting. What does this do?

2018-04-18 01:27 UTC, cehsu commented
UPDATE: These changes are blocked as we may not need this page per @goldenmeanie's insights.

2018-04-18 20:58 UTC, cvalarida approved these changes
This may not need to be merging as you said, but in case it is still necessary, I'll go ahead and approve it. I anticipate it'll be a fun merge conflict to resolve, though. :grimacing:

2018-04-19 07:40 UTC, merged