9117 686 intro page
department-of-veterans-affairs/vets-website pull request #7621
Opened 2018-04-19 16:48 UTC by lbai001

#### Recording
http://recordit.co/kk48Arvjzy

2018-04-19 16:48 UTC, lbai001 commented
please advise for any additional test needed @jbalboni

2018-04-19 20:55 UTC, jbalboni commented on src/js/common/schemaform/components/AskVAQuestions.jsx
> +          <p className="help-talk">
Adding this here will affect other forms. You can make a component for this content and use the `getHelp` property in the form config to pass this in and render it in line 9.

2018-04-19 20:55 UTC, jbalboni commented on src/js/disability-benefits/686/containers/IntroductionPage.jsx
> +              <SaveInProgressIntro
I don't think you need to use SaveInProgressIntro for this. You can use the info version of our AlertBox: https://department-of-veterans-affairs.github.io/design-system/components/detail/alertbox.html

2018-04-23 17:24 UTC, jbalboni commented on src/js/common/schemaform/save-in-progress/SaveInProgressIntro.jsx
> +    const prefillAvailable = !!(profile && profile.prefillsAvailable.includes(this.props.formId));
Where did this change come from?

2018-04-23 23:53 UTC, lbai001 commented on src/js/common/schemaform/save-in-progress/SaveInProgressIntro.jsx
> +    const prefillAvailable = !!(profile && profile.prefillsAvailable.includes(this.props.formId));
after pulling master

2018-04-24 01:30 UTC, jbalboni commented
@lbai001 Can you include a screenshot of the page, too? It's easier for the content folks to review.

2018-04-24 01:31 UTC, jbalboni approved these changes
This looks good to me. I would like to have @peggygannon look at it too, if possible.

2018-04-24 01:31 UTC, jbalboni commented on src/js/disability-benefits/686/config/form.js
> +    noAuth: 'Please sign in again to continue your application for declaration of status of dependents.',
We can get rid of this comma

2018-04-24 05:53 UTC, lbai001 commented
@jbalboni 
<img width="850" alt="screen shot 2018-04-23 at 10 51 47 pm" src="https://user-images.githubusercontent.com/15193547/39168527-0ef8d814-4749-11e8-89cd-dc526b2f05a2.png">
<img width="764" alt="screen shot 2018-04-23 at 10 51 53 pm" src="https://user-images.githubusercontent.com/15193547/39168528-0f125cee-4749-11e8-9df5-fe6d1db79258.png">
<img width="732" alt="screen shot 2018-04-23 at 10 52 05 pm" src="https://user-images.githubusercontent.com/15193547/39168529-0f2b6bbc-4749-11e8-925d-adb689ce552d.png">
<img width="849" alt="screen shot 2018-04-23 at 10 52 18 pm" src="https://user-images.githubusercontent.com/15193547/39168530-0f4800d8-4749-11e8-8841-7c1772fc408f.png">

2018-05-01 22:34 UTC, peggygannon requested changes
@jbalboni @lbai001 
Please see my edits below. Some of the content on this page does not reflect the latest content in the prototype. Let me know if you have any questions. Thx!
1. header: please change head to: 
Apply to add a dependent to your VA benefits
2. please update the head before the subway map to: 
Follow the steps below to add a dependent to your VA benefits.
3. Under "Prepare" please add a space btw "be" and "sure"
4. Please update the bullets under "Prepare" to match the prototype. 
5. Please update the sentence about a dependent who goes to school   "If you're claiming a dependent" to match the prototype.
6. Please update the text in blue box to match the prototype. 
7. Please move "What if I need help filing out my application..." to below blue text box to match prototype. 
8. Please delete the duplicate 4 step in the subway map.

2018-05-03 19:19 UTC, peggygannon approved these changes

2018-05-04 22:12 UTC, merged

2018-05-04 22:13 UTC, lbai001 commented
@rtluu please verify and close

2018-05-07 16:50 UTC, rtluu commented
@lbai001 is the save in progress message at the top something that should be changed on the page itself or is that handled in a separate module?

![Screen Shot 2018-05-07 at 12.48.52 PM.png](https://images.zenhubusercontent.com/59975d8b8f62dc7798c35199/f8d16956-0da4-467b-a7b5-166c75877e2b)