9824 686 chapter 4
department-of-veterans-affairs/vets-website pull request #7723
Opened 2018-05-14 13:15 UTC by lbai001

![screencapture-localhost-3001-disability-benefits-686-dependent-status-unmarried-children-2018-05-14-06_03_48](https://user-images.githubusercontent.com/15193547/39999539-246e34b4-573e-11e8-970b-7011f58a7c6d.png)
![screencapture-localhost-3001-disability-benefits-686-dependent-status-unmarried-children-2018-05-14-06_04_02](https://user-images.githubusercontent.com/15193547/39999540-248973e6-573e-11e8-95a6-63c03f474e06.png)
![screencapture-localhost-3001-disability-benefits-686-dependent-status-unmarried-children-address-0-2018-05-14-06_03_13](https://user-images.githubusercontent.com/15193547/39999541-24a8cd36-573e-11e8-940b-b405b538c00c.png)
![screencapture-localhost-3001-disability-benefits-686-dependent-status-unmarried-children-information-0-2018-05-14-06_03_29](https://user-images.githubusercontent.com/15193547/39999542-24c28686-573e-11e8-8233-d50975a11c60.png)

2018-05-14 17:08 UTC, jbalboni approved these changes
I have a couple of minor comments, but it looks good overall.

2018-05-14 17:08 UTC, jbalboni commented on src/applications/disability-benefits/686/config/form.js
> +      title: 'Veteran\'s Unmarried Children',
We try to use `’` for all apostrophes.

2018-05-14 17:08 UTC, jbalboni commented on src/applications/disability-benefits/686/config/form.js
> +                        personChildLiveWith: {
I think this is called `personWhoLivesWithChild` in the schema.

2018-05-14 17:40 UTC, peggygannon requested changes
@lbai001 Hi, Annie, these screens don't entirely match Judy's Invision Prototype: https://projects.invisionapp.com/share/M4H8VL3TY36#/screens/291249508

Some examples,
-- we changed Name fields to say: Child's first name, Child's last name, etc.. 
--Add Another Dependent button was changed to say Add Another Child
--the Child status labels are also slightly different. I edited them in the prototype to be more user friendly and plain language

cc @jbalboni

2018-05-15 16:15 UTC, lbai001 commented
@peggygannon 
![screencapture-localhost-3001-disability-benefits-686-dependent-status-unmarried-children-2018-05-15-09_14_26](https://user-images.githubusercontent.com/15193547/40069527-806b1754-5820-11e8-9901-e842f6c5ef29.png)
![screencapture-localhost-3001-disability-benefits-686-dependent-status-unmarried-children-address-0-2018-05-15-09_15_08](https://user-images.githubusercontent.com/15193547/40069528-80872746-5820-11e8-9ea3-b53b89b4aba8.png)
![screencapture-localhost-3001-disability-benefits-686-dependent-status-unmarried-children-information-0-2018-05-15-09_14_38](https://user-images.githubusercontent.com/15193547/40069529-80a21510-5820-11e8-8735-55980761e85d.png)

2018-05-15 17:30 UTC, peggygannon reviewed
Thanks @lbai001 001 Screens look good. 
It looks like the updated screen is missing the label for:
--Child is 18 to 23 years old and in school
I wanted to make sure that that label is in there? 
Could you let me know? thanks..

2018-05-15 17:53 UTC, lbai001 commented
@peggygannon the child inputed is not 18 -23 years old, birthday inputed is 2013.

here's a case for a 18 year old child:

<img width="798" alt="screen shot 2018-05-15 at 10 52 52 am" src="https://user-images.githubusercontent.com/15193547/40074317-27e60f68-582e-11e8-94b6-4060a6850b24.png">

2018-05-15 20:18 UTC, peggygannon approved these changes

2018-05-15 20:18 UTC, peggygannon commented
@lbai001 Ok, thanks. Looks good.

2018-05-15 22:13 UTC, merged