add static page content to opt out form
department-of-veterans-affairs/vets-website pull request #7975
Opened 2018-07-09 17:40 UTC by rianfowler

2018-07-09 17:46 UTC, rianfowler commented on content/pages/education/opt-out.md
> -<div itemscope itemtype ="http://schema.org/HowTo">
I dunno what this div is for but I removed it.

2018-07-09 18:25 UTC, cehsu approved these changes
LGTM once the schema tags are replaced (as we probably want these for search engine result pages) and @peggygannon and @emilywaggoner approve.

2018-07-09 19:13 UTC, peggygannon requested changes
@rianfowler Please see below for my edits: 
1. the title of the page in the heroku link is: 
Opt Out of Sharing VA Education Benefits Information
Was there a decision to shorten the header? 

2. Please remove the Ready to apply? question above the green button.

3. Green button languages needs to say Opt Out

4. Please remove "the" before VA in this header: 
What kind of information does VA share with schools?

5. Per feedback from Mikki, this page should not appear in Education left nav. We are still discussing entry points for this page. 

6. the URL for this is changing to: vets.gov/education/opt-out-information-sharing

2018-07-09 21:17 UTC, rianfowler commented on content/pages/education/opt-out.md
> -<div itemscope itemtype ="http://schema.org/HowTo">
Cool I'll add this back.

2018-07-10 15:44 UTC, rianfowler commented
@peggygannon Updated the screenshot with the changes.

2018-07-10 22:12 UTC, peggygannon commented
@rianfowler Thank you!

It looks like we lost the green Opt Out button. It should go below: 
**How do I tell VA I don’t want my information shared?**
You’ll need to fill out a short form to tell us you want to opt out of sharing this information. You can get started right now.

also, I realize in my earlier comment that I didn't give you the URL to the form. I'm not sure if you have it, but here are the URLs for both the landing page and the form (green button)
The URL for the landing page is: vets.gov/education/opt-out-information-sharing
the URL for the form (green button) is: vets.gov/education/opt-out-information-sharing/opt-out-form-0993

2018-07-10 22:42 UTC, rianfowler commented
@peggygannon sorry I uploaded the wrong screen shot.

2018-07-10 22:47 UTC, rianfowler commented
@peggygannon Currently I have it set up to show the modal when the opt out button is clicked and the form link on "Yes, I Want to Opt Out" mentioned on this ticket: https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets.gov-team/issues/11291

@cehsu we'll need to update the app url to this per the comment above: vets.gov/education/opt-out-information-sharing/opt-out-form-0993

2018-07-12 03:50 UTC, emilywaggoner requested changes
Thanks @rianfowler! I have one request:

Would you mind swapping the positions of the first and last questions?

Specifically, move the following, including the green button, to the last position:

### How do I tell VA I don't want my information shared?
You'll need to fill out a short form...
[ opt out call to action ]

And then move this to the first position:

### What's the Colmery Act?
The Harry W. Colmery Veterans Educational... 
[Learn more ...]

Edited to loop in @peggygannon and provide more context. I think we should move the CTA to the bottom so that we don't encourage someone to begin the opt out process before they've read through the page content.

2018-07-12 13:29 UTC, emilywaggoner commented
@peggygannon That sounds great to me. @rianfowler let's do what Peggy described.

2018-07-12 15:42 UTC, rianfowler commented
@peggygannon @emilywaggoner There a little repetition with the header content under the title. 

@peggygannon Regarding this: 

>  but typically for forms, we don't create a FE file for static content pages. 

When we set up this page we assumed that it would need to be part of the education collection and have the side nav- was easier for us to treat it as a static content page. Now that we know we're not doing this, we could move this into an introduction page like we do with our other forms. @cehsu let's discuss this in stand up- I know we made some changes to remove the introduction page and to treat the opt out as a single page form. 

![download-4](https://user-images.githubusercontent.com/4998130/42643817-5196ab86-85b7-11e8-8ae8-b7656f823121.png)

2018-07-12 16:36 UTC, closed without merging

2018-07-12 17:17 UTC, cehsu commented
@peggygannon indicated that we may want to add an amended note under the button recommending that the user log in to be able to save their form, and verify their account to enable prefill (similar to how the form start buttons on the form introduction pages are framed -- using the SIPIntro component). Is there another ticket this should be captured on for discussion @peggygannon?