Complaint tool issue info
department-of-veterans-affairs/vets-website pull request #8046
Opened 2018-07-24 19:22 UTC by rrmatthews

These changes set up the applicant information page for the complaint tool as described by this [ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11575

## TODO:
- [x] Write schema / uiSchema
- [x] Write unit tests
- [ ] Verify content

## Notes: 

## Screenshots: 
![localhost_3001_education_complaint-tool_form_feedback-information](https://user-images.githubusercontent.com/15916054/43161145-45606ca6-8f55-11e8-9a5f-8085140eb2f6.png)

2018-07-26 00:08 UTC, peggygannon requested changes
@cehsu Thanks.. Please see below for a couple of changes from me: 

We need to replace "Complaint" with "Feedback" in the  breadcrumb

Please fix the misspelling of Feedback in the header Feedback Information

per the prototype the question should read:
Which topic best describes your feedback? (Select all that apply) (*Required)

We need to add two more issues to the list: 
--Transfer of credits
--Refund issues

it looks like the character count info is missing from the two questions at the bottom. Do we no longer have a limit? 

Please rewrite the first question at the bottom TO:
Please write your feedback and any details about your issue in the space below. 

--for the bullet list, we are still waiting on copy/examples  of each topic from the stakeholders.

2018-07-26 20:52 UTC, rrmatthews commented
I noted that the issue description character limit is set a 32000 on the backend, do we want to mention this to the user (instead of the current 1000 character limit)? @lihanli

2018-07-26 20:53 UTC, rrmatthews commented
Thanks @peggygannon , made the changes requested and updated the screenshot

2018-07-27 02:24 UTC, cehsu approved these changes
LGTM, pending @peggygannon's approval. We will want to merge this after the applicant information page PR, since this PR includes those changes (I have updated the applicant information changes to be in sync with the latest version of that PR). I removed the contact information changes, so that the contact information PR would not block this one.

2018-07-27 15:54 UTC, rianfowler approved these changes

2018-07-27 17:41 UTC, peggygannon commented
@cehsu @rrmatthews I don't see the updated screenshot above with the changes..

2018-07-27 17:45 UTC, rrmatthews commented
@peggygannon this should be the screenshot

![43284678-971e4504-90ea-11e8-910f-79070a10f86e](https://user-images.githubusercontent.com/15916054/43337999-419bc200-91a3-11e8-8beb-081918410baa.png)

2018-07-27 17:47 UTC, lihanli commented
@rrmatthews yea the limit description should match the limit on the schema

2018-07-27 18:14 UTC, rrmatthews commented
@lihanli okay thank you, made that change. @peggygannon screenshot has been updated, but please note that the issue description character limit says 32,000 to match the backend limit as well

2018-07-27 20:55 UTC, peggygannon commented
@cehsu @rrmatthews The following changes aren't reflected in the updated screenshot: 

We need to replace "Complaint" with "Feedback" in the breadcrumb

Please fix the misspelling of Feedback in the header "Feedback Information"

per the prototype the question should read:
Which topic best describes your feedback? (Select all that apply) (*Required)

Please fix misspelling of "characters" in both instances. 

Please rewrite the first question at the bottom TO:
"Please write your feedback and any details about your issue in the space below."

2018-07-27 21:53 UTC, cehsu commented
Thanks @peggygannon, kindly refer to the updated screenshot below.
![localhost_3001_education_complaint-tool_form_feedback-information 1](https://user-images.githubusercontent.com/16051172/43347902-3e02bf46-91ac-11e8-8b65-1e552fcd5d14.png)

2018-07-27 22:03 UTC, cehsu commented on package.json
> +    "vets-json-schema": "https://github.com/department-of-veterans-affairs/vets-json-schema.git#223ad037ab294b946079e351a5356c9d678b12a0",
The latest version is now: 444e3aba11ac1ce27e869d24bbee20160bfa3ea6, let's make sure when we merge this that the diff indicates that we are updating the version from 4e5d6a1082e8268b79cb3c433ba379ce97343bc0 and not switching it back from 444e3aba11ac1ce27e869d24bbee20160bfa3ea6 if it has already been updated by another PR.

2018-07-27 22:29 UTC, peggygannon approved these changes
@cehsu Complaint still needs to be removed from breadcrumb.

Should the second text box also all for 32,000 characters? If so, we need to replace 1,000 with 32,000..

2018-07-28 00:40 UTC, cehsu commented
Thanks again @peggygannon, updated screenshot provided below. The two fields have different word limits, that is why the limit provided to the user is different.
![localhost_3001_education_complaint-tool_form_applicant-information 3](https://user-images.githubusercontent.com/16051172/43351256-2f775186-91c4-11e8-8b08-3e9a3e1d2ff6.png)

2018-07-28 00:55 UTC, merged

2018-07-30 13:18 UTC, saintsoup52 commented
FWIW There is a missing category of complaints in the screen shots above... "Other"