[WIP] All claims 2dot1 mg
department-of-veterans-affairs/vets-website pull request #8285
Opened 2018-08-30 22:45 UTC by markgreenburg

## Description

## Testing done

## Testing Plan

## Screenshots

## Acceptance Criteria (Definition of Done)

#### Unique to this PR

- [ ] _Replace this line with individual tasks unique to your PR_

#### Applies to all PRs

- [ ] Appropriate logging
- [ ] Documentation has been updated, if applicable
- [ ] Provide link to originating GitHub issue, or connected to it via ZenHub
- [ ] Does not contain any sensitive information (i.e. PII/credentials/internal URLs/etc., in logging, hardcoded, or in specs)
- [ ] Provide which alerts would indicate a problem with this functionality (if applicable)

2018-08-31 18:59 UTC, jbalboni approved these changes
LGTM

2018-08-31 19:49 UTC, cvalarida approved these changes

2018-08-31 23:05 UTC, peggygannon requested changes
@markgreenburg Hi, there. Please see my content updates below: 
1. for intro screen, please update to: 
On the next few screens, we’ll ask you about the disabilities you’re claiming in two parts.
-	Your rated service-connected disabilities, if you have any. (Please note, if you don’t have any rated disabilities, you won’t see this screen.)
-	Your new service-connected disabilities or conditions
 Once we have your list of disabilities, we’ll ask you more specific questions about each of them.

2. Rated disabilities screen, please update first sentence to: 
Below are your rated disabilities. If you’ll be filing for increased compensation because one of them has gotten worse, please choose the disability here. 


I would like to see updated screenshots, so I can review the content again to make sure my edits work with the flow! thx.

2018-09-04 16:16 UTC, markgreenburg commented
@peggygannon here're some new screenshots for you!

![screen shot 2018-09-04 at 10 47 06 am](https://user-images.githubusercontent.com/24251447/45043811-de0cc680-b033-11e8-98c1-a0b82cde7d4d.png)

![screen shot 2018-09-04 at 10 47 18 am](https://user-images.githubusercontent.com/24251447/45043823-e5cc6b00-b033-11e8-858d-869c887fe94b.png)

2018-09-04 17:56 UTC, peggygannon approved these changes

2018-09-04 20:35 UTC, merged