[WIP] All claims 32 mg
department-of-veterans-affairs/vets-website pull request #8447
Opened 2018-09-18 14:42 UTC by markgreenburg

## Description
- Adds claim exams info page to 526 All Claims Form
- Updates Formation dependency to pull in changes that address bug with form continuing when collapsible panels toggled

## Testing done
- Tested locally

## Screenshots

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-09-18 20:57 UTC, cvalarida approved these changes

2018-09-18 21:12 UTC, markgreenburg commented
Confirmed with Alex that the intended UI here is the accordion.

2018-09-19 15:16 UTC, markgreenburg commented on src/applications/disability-benefits/all-claims/content/claimExamsInfo.jsx
> +        your first call within XX days.
Discussing with Peggy

2018-09-19 15:16 UTC, markgreenburg commented on src/applications/disability-benefits/all-claims/content/claimExamsInfo.jsx
> +        NNN-NNN-XXXX<br/>
Checking with Peggy to see if this is correct.

2018-09-19 19:17 UTC, peggygannon requested changes
@markgreenburg Please see below for some updates to the outline. It was helpful to see this content laid out and see where I need to adjust, esp with the accordions.
I removed the toggle answer from the first question, as this question/answer is important and works better untoggled. (not everyone will need an exam). 

Please let me know if you have any question about my updates below. Thank you!

After we review your disability claim and supporting evidence, we may ask you to have a claim exam (also known as a C&P exam) if we need more information to decide your claim. 
We’ll use the results of this exam, in addition to your evidence, to rate your disability and make a decision on your claim. 

**Does everyone who files a disability claim need to have a claim exam?** 
No. We’ll ask you to have a claim exam only if we need more information to decide your claim. If you've provided enough supporting evidence for your claimed disability, we won’t ask you to have a claim exam. 

**How will you contact me if I need to have an exam?**
{Toggle answer}
The staff at your local VA medical center will contact you to schedule your exam. They’ll either send you a letter by mail with the date and time of your exam, or call you to find a time that works for you. 

**What if I need to reschedule my exam appointment?**
{Toggle answer}
If you can’t make it your scheduled exam, let us know right away. You can most likely reschedule, but this may delay a decision on your claim. If you need to reschedule your exam, please call 1-800-827-1000.

[ Back | Continue ] { buttons }
Save and finish this application later.

2018-09-20 19:28 UTC, markgreenburg commented
@peggygannon please see new screenshots per our convo 🙂

2018-09-20 19:38 UTC, peggygannon approved these changes

2018-09-20 19:38 UTC, peggygannon commented
thanks, @markgreenburg Updated screenshots look good.

2018-09-25 18:07 UTC, merged