4142 limited consent
department-of-veterans-affairs/vets-website pull request #8481
Opened 2018-09-20 16:12 UTC by hopelam

## Description
https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets.gov-team/issues/12552

Move limited consent to aggregate level; add text box for description if limited consent checkbox is checked; content of text box is sent to api

## Testing done

local developer testing done

## Screenshots
<img width="675" alt="nothing expanded" src="https://user-images.githubusercontent.com/41018009/45831899-79f22f80-bcce-11e8-8746-674898e7b13a.png">
<img width="636" alt="all_expanded" src="https://user-images.githubusercontent.com/41018009/45831900-79f22f80-bcce-11e8-84ad-17b1bad41078.png">

## Acceptance criteria
- [ ]  Limited Consent check box is presented at aggregate level and not for every individual provider that is entered
- [ ] The text for the Limited Consent checkbox should be updated to state "I want to limit my consent for the VA to retrieve only specific information from my private medical provider(s)"
- [ ]  Upon the user selecting the Limited Consent check box, then a free text field is presented in the UI 
- [ ] The free text field should have display the following brief instructional text:  "Describe the limitation below (Treatment dates, Disability type, etc.) (*Required)"
- [ ] allow up to 83 characters of free text to be entered in the UI because that is the character limit allowed within the pdf for this field
- [ ] if Limited Consent check box is unchecked, then free text field will remain hidden in UI
- [ ] whatever is entered in the free text field should appear in field 12 of the 4142a pdf that is generated
- [ ] "what does this mean" text should be updated to: "If you choose to limit consent, your doctor will abide by the limitation you specify.  Limiting consent could add to the time it takes to get your private medical records."

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-09-21 13:02 UTC, robfelder requested changes
Overall everything looks great, just a few minor things here and there. I noticed that the payload that's being sent is sending like this:
```
"form4142":{  
      "limitedConsent":"[object Object] [object Object]",
      "providerFacility":[  
        {  
          "providerFacilityName":"Another Provider",
          "treatmentDateRange":[  
            {  
              "from":"2010-01-03",
              "to":"2012-05-08"
            }
          ],
          "providerFacilityAddress":{  
            "street":"1234 test rd",
            "city":"Testville",
            "postalCode":"12345",
            "country":"USA",
            "state":"AZ"
          }
        },
        {  
          "providerFacilityName":"Another Provider",
          "treatmentDateRange":[  
            {  
              "from":"2003-01-05",
              "to":"2005-10-04"
            }
          ],
          "providerFacilityAddress":{  
            "street":"1234 test rd",
            "city":"Testville",
            "postalCode":"12345",
            "country":"USA",
            "state":"AZ"
          }
        }
      ]
    }
```
Where the limited consent is just [object object], is that intended behavior?
Also, noticed there aren't any unit tests. Were they not needed? At least to validate the payload?

I'm also getting an error submitting the application. It works fine against the `bah-sprint3` branch, but not against the `4141-limited-consent` branch:

![screen shot 2018-09-21 at 11 45 15 am](https://user-images.githubusercontent.com/11091836/45891721-4da0e680-bd94-11e8-809f-94e287513239.png)
![screen shot 2018-09-21 at 11 45 50 am](https://user-images.githubusercontent.com/11091836/45891741-55f92180-bd94-11e8-83bb-5a9a48b4bab3.png)

2018-09-21 14:38 UTC, igreulich commented on src/applications/disability-benefits/4142/helpers.jsx
> +const transformDateRange = treatmentDateRange => {
This is probably better written utilizing the es6 implicit `return`ing.

`const transformDateRange = treatmentDateRange => ([treatmentDateRange]);`

2018-09-21 14:38 UTC, igreulich commented on src/applications/disability-benefits/526EZ/helpers.jsx
> -/**
There is no need, this stopped being a function.

2018-09-21 14:42 UTC, igreulich requested changes
I just have the one tweak.

2018-09-24 11:57 UTC, imeecuison commented on src/applications/disability-benefits/4142/helpers.jsx
> -export const limitedConsentDescription = (
@robfelder: I have moved everything we are using out of 4142 directory and deleted the 4142 directory. This warning should no longer be there. Thank you!

2018-09-24 12:00 UTC, imeecuison commented
@robfelder , @igreulich , & @JBarbour2 : I have made the requested changes, please review again. Thank you!

2018-09-24 13:44 UTC, imeecuison commented
Just realized something... Unit tests still need to be written. Should I write them before you review again? @robfelder @igreulich

2018-09-24 15:31 UTC, igreulich commented on src/applications/disability-benefits/526EZ/helpers.jsx
> +  <p>Describe the limitation here. (Treatment dates, Disability type, etc.)</p>
@robfelder Are you referring to the lack of (*Required), or the addition of the . after the word below?

2018-09-24 15:33 UTC, igreulich approved these changes

2018-09-24 17:36 UTC, igreulich commented
@imeecuison I gave you some merge conflicts. I also might fix them, in #8487

2018-09-25 16:14 UTC, robfelder commented on src/applications/disability-benefits/526EZ/helpers.jsx
> +  <p>Describe the limitation here. (Treatment dates, Disability type, etc.)</p>
No, it says `Describe the limitation here`, but the acceptance criteria says `Describe the limitation below`

2018-09-25 17:16 UTC, igreulich commented on src/applications/disability-benefits/526EZ/helpers.jsx
> +  <p>Describe the limitation here. (Treatment dates, Disability type, etc.)</p>
I totally missed that one.

@imeecuison are you working on these fixes?

2018-09-25 17:18 UTC, imeecuison commented on src/applications/disability-benefits/526EZ/helpers.jsx
> +  <p>Describe the limitation here. (Treatment dates, Disability type, etc.)</p>
This has been changed to Describe the limitation below.

2018-09-25 17:58 UTC, robfelder approved these changes

2018-09-25 18:20 UTC, merged