781 Intro Page
department-of-veterans-affairs/vets-website pull request #8487
Opened 2018-09-20 19:23 UTC by igreulich

## Description
As a Veteran submitting a claim for the contention of PTSD on the Vets.gov platform, I need to be properly oriented so that I can easily transition into the guided flow for the Form0781/0781a from the 526EZ flow.

## Testing done
N/A

## Screenshots
See the initial page here - 
https://bahdigital.invisionapp.com/share/F6IA8LNDMXG#/screens

## Acceptance criteria
- [ ] The Veteran will be shown an explanation screen that introduces him/her to this workflow, per the prototype (https://bahdigital.invisionapp.com/share/F6IA8LNDMXG#/screens/295996741)
- [ ] The Veterans Crisis Line telephone number should be hyperlinked for the user and clicking on it opens a link to dial from your computer/mobile device
- [ ] The Veterans Crisis Line confidential online chat should be hyperlinked for the user and clicking on it opens a link to chat from your computer/mobile device
- [ ] The Veterans Crisis Line text message option should be hyperlinked for the user and clicking on it opens a link to text from your computer/mobile device

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-09-21 15:29 UTC, robfelder requested changes
Outside of the misspelling and the one page in question, the code LGTM! The linter errors and unit tests have to be resolved before merging though.

2018-09-21 15:29 UTC, robfelder commented on src/applications/disability-benefits/781/definitions/toursOfDuty.js
> +import dateRangeUI from 'us-forms-system/lib/js/definitions/dateRange';
Is this file necessary?

2018-09-21 15:29 UTC, robfelder commented on src/applications/disability-benefits/781/helpers.js
> +      We'll now ask you questions about the stressful event or events related to your PTSD. We understand that some of the questions maybe difficult to answer. The information you provide here will h
There's a misspelling here. "...help us understand you situation..." should be "...help us understand your situation..."

2018-09-21 17:28 UTC, igreulich commented
@robfelder Need a recheck, please.

2018-09-24 12:43 UTC, robfelder commented
Looks like there are still some linter errors @igreulich

2018-09-24 15:49 UTC, igreulich commented
@robfelder , I will resolve these conflicts, after I have gotten the Ack-spelling stuff pushed through.

2018-09-24 17:35 UTC, igreulich commented
@robfelder You are up, again!

2018-09-24 17:50 UTC, robfelder commented
@igreulich there are still some linter errors, but I'm building on top of this PR and have resolved them already. Unit test error is just like before. Imee's unit test should resolve that.

2018-09-24 17:50 UTC, merged