All claims 31 2 mg
department-of-veterans-affairs/vets-website pull request #8531
Opened 2018-09-24 20:55 UTC by markgreenburg

## Description
Adds VA Medical Records supporting evidence type to the All Claims form.
- Allows addition of multiple facilities
- Allows association of disabilities to each VA evidence entry

## Testing done
- Tested locally
- Added unit tests around validations and required fields

## Screenshots
Empty form:
![screen shot 2018-09-24 at 3 08 20 pm](https://user-images.githubusercontent.com/24251447/45978328-b2b54000-c011-11e8-9552-e7ff7eb47d22.png)

-----
More empty form:
![screen shot 2018-09-24 at 3 08 50 pm](https://user-images.githubusercontent.com/24251447/45978346-bd6fd500-c011-11e8-8315-ef2598f105b9.png)

-----
And some more:
![screen shot 2018-09-24 at 3 09 06 pm](https://user-images.githubusercontent.com/24251447/45978357-c5c81000-c011-11e8-8b48-0ba3cc03d639.png)

-----

State field goes away when country is not USA (per EVSS requirements):
![screen shot 2018-09-24 at 3 09 29 pm](https://user-images.githubusercontent.com/24251447/45978361-ccef1e00-c011-11e8-8a79-4fabe0954661.png)

-----

Users can select multiple disabilities to associate with each piece of evidence:
![screen shot 2018-09-24 at 3 09 36 pm](https://user-images.githubusercontent.com/24251447/45978398-e7c19280-c011-11e8-9d78-a8c32742c978.png)

-----

Users can add multiple VA facilities on this page:
![screen shot 2018-09-24 at 3 12 53 pm](https://user-images.githubusercontent.com/24251447/45978425-fad46280-c011-11e8-8f78-a8f6f8795735.png)

## Acceptance criteria
- [x] Add VA facility evidence - one or many per mocks
- [x] Able to associate existing rated, new disabilities, or both with each VA facility

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-09-24 22:08 UTC, cvalarida approved these changes
Just had a few comments and questions. The biggest one is whether we can uncomment that `depends` line.

2018-09-24 22:08 UTC, cvalarida commented on src/applications/disability-benefits/all-claims/utils.jsx
> +    return accumCopy;
What do you think about using `set` instead of `cloneDeep`?

2018-09-25 18:39 UTC, markgreenburg commented on src/applications/disability-benefits/all-claims/config/form.js
> +          // depends: (formData) => formData['view:something'] === true,
This depends (🥁 ) on the 3.1 PR, which contains the actual data that this page will gate on.

2018-09-25 20:17 UTC, peggygannon requested changes
@markgreenburg Hi, Mark, please see below for a few content tweaks for this screen. 

the date question is a bit awkward, so let's rewrite it to: 
First date you received treatment for these conditions at this facility (this doesn't have to be exact).

Last date you received treatment for these conditions at this facility (this doesn't have to be exact).

Also, the conditions list from EVSS has all the condition names lowercased.. Is there something we can do make the first word of the condition capitalized when it's pulled in? Or would I need to go through the conditions list and edit and capitalize all first words?

2018-09-25 21:49 UTC, markgreenburg commented
@peggygannon I actually already made the change to capitalize the conditions but neglected to update the screenshot for that section. Also, I've updated the wording on those date questions. Here's a new screenshot:

![screen shot 2018-09-25 at 4 48 14 pm](https://user-images.githubusercontent.com/24251447/46045317-f5931880-c0e2-11e8-8492-bce06b0e8e60.png)

2018-09-25 22:13 UTC, peggygannon approved these changes

2018-09-26 15:59 UTC, markgreenburg commented on src/applications/disability-benefits/all-claims/pages/vaMedicalRecords.js
> +              false
Yes...yes we do. And besides, `false` isn't a great country choice 🤦‍♂️

2018-09-26 16:25 UTC, merged