All claims 31 3 mg
department-of-veterans-affairs/vets-website pull request #8579
Opened 2018-09-27 19:38 UTC by markgreenburg

## Description
Adds Private Medical Records Uploads to All Claims 526 form.
Note: does not add anything 4142-related, as that will be added later

## Testing done
- Tested locally
- Added unit tests

## Screenshots
Base screen:
![screen shot 2018-09-27 at 2 29 36 pm](https://user-images.githubusercontent.com/24251447/46169959-1635ac80-c262-11e8-92de-817a77b417f9.png)

If user needs help they can click on the additional info tip:
![screen shot 2018-09-27 at 2 29 46 pm](https://user-images.githubusercontent.com/24251447/46169990-2c436d00-c262-11e8-83d6-bf4dcb2a3183.png)

If user selects 'no', they can just continue (since 4142 integration is not yet done):
![screen shot 2018-09-27 at 2 30 10 pm](https://user-images.githubusercontent.com/24251447/46170060-5eed6580-c262-11e8-8909-477d283cffcf.png)

If user selects 'yes', they can upload one or more documents:
![screen shot 2018-09-27 at 2 30 17 pm](https://user-images.githubusercontent.com/24251447/46170111-85130580-c262-11e8-9e25-04188cc2dad6.png)

They can edit the document name and type for each:
![screen shot 2018-09-27 at 2 35 17 pm](https://user-images.githubusercontent.com/24251447/46170152-a5db5b00-c262-11e8-914a-fe6822e5ce37.png)

## Acceptance criteria
- [x] Veteran can upload private medical records
- [x] Veteran can upload multiple private medical records
- [x] Veteran can choose to not upload private medical records

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-09-27 21:53 UTC, peggygannon requested changes
@markgreenburg Looks good.. just a few content tweaks from me: 

1. Please add a period after this sentence:
Large files can take longer to upload with a slow Internet connection.

2. Please update the following buttons: 
--Upload >> Upload Document
--Add another record >> Add Another Document (with initial caps)

2018-10-01 16:56 UTC, cvalarida approved these changes
Looks great!

2018-10-01 16:56 UTC, cvalarida commented on src/applications/disability-benefits/all-claims/constants.js
> +    'view:hasEvidenceFollowUp.view:selectableEvidenceTypes.view:hasVAMedicalRecords',
Oh hey, I didn't notice this before. Clever!

2018-10-01 16:56 UTC, cvalarida commented on src/applications/disability-benefits/all-claims/pages/privateMedicalRecords.js
> +        fileUploadUrl: `${environment.API_URL}/v0/upload_supporting_evidence`,
@kreek Is this the right endpoint for uploading private medical records for all claims?

2018-10-02 15:09 UTC, markgreenburg commented
@peggygannon here's a new screenshot with those 2 changes. Please take a look when you get a chance. Thanks!

![screen shot 2018-10-02 at 10 08 59 am](https://user-images.githubusercontent.com/24251447/46357812-48ad2400-c62b-11e8-9957-8cca8f5949b4.png)

2018-10-02 18:04 UTC, peggygannon approved these changes

2018-10-02 19:09 UTC, merged