BAH Stressful Incident Description Page
department-of-veterans-affairs/vets-website pull request #8632
Opened 2018-10-03 14:39 UTC by robfelder

## Description
This PR covers the Stressful Incident description page of the 781 flow.

## Testing done
Manual testing
Unit test written

## Screenshots
![screen shot 2018-10-03 at 10 37 31 am](https://user-images.githubusercontent.com/11091836/46417790-685e4e00-c6f8-11e8-827a-6efd27824062.png)

## Acceptance criteria
- [x] The user should be presented with guidance text per the Content Document
- [x] The user is able to input the incident description via free form text 
- [x] Special characters should be allowed
- [x] There is no limit on how much text the user can enter in the Description of the incident text box
- [ ] The PTSD type that the user previously selected (either Personal Assault or Military Sexual Trauma) should be populated as the _$PTSDclassification_ on this page, per the Content Document
- [ ] If the user selected **more than one** PTSD Type for 0781a (Personal assault and Military sexual trauma) then the following is expected:
                - then 'Personal assault & Military sexual trauma' replaces $PTSDclassification in header of 
                781 workflow
               - then 'Personal assault and Military sexual trauma' replaces $PTSDclassification in body of 
                781 workflow

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-10-04 14:42 UTC, robfelder commented
@imeecuison @aaronjlech, when you get a moment, could you review please.

**Note:** I still need to implement the PTSD Classification though.

2018-10-04 14:56 UTC, aaronjlech requested changes
A couple of spots stressful has an extra L, other than that looks good.

2018-10-04 14:56 UTC, aaronjlech commented on src/applications/disability-benefits/781/helpers.js
> +export const stressfullIncidentDescriptionTitle = () => (
`stressfull` should be `stressful`

2018-10-04 14:56 UTC, aaronjlech commented on src/applications/disability-benefits/781/pages/stressfulIncSecDesc.js
> +import { ptsdNameTitle, stressfullIncidentDescriptionTitle } from '../helpers';
+1

2018-10-04 14:56 UTC, aaronjlech commented on src/applications/disability-benefits/781/pages/stressfulIncSecDesc.js
> +  'ui:description': stressfullIncidentDescriptionTitle,
+1

2018-10-04 15:00 UTC, imeecuison approved these changes
Awesome!

2018-10-05 14:38 UTC, robfelder commented
@aaronjlech spelling mistakes updated. Thanks for pointing that out.

2018-10-05 19:17 UTC, aaronjlech approved these changes
@robfelder LGTM!!

2018-10-05 19:34 UTC, merged