Content and test updates
department-of-veterans-affairs/vets-website pull request #8648
Opened 2018-10-04 19:05 UTC by markgreenburg

## Description
Updates content across several 526 Increase pages.

## Testing done
- Tested locally
- Updated unit tests as needed

## Screenshots
![screen shot 2018-10-04 at 1 38 41 pm](https://user-images.githubusercontent.com/24251447/46496673-4212de00-c7de-11e8-8ef3-f5556e44eb2f.png)
-----
![screen shot 2018-10-04 at 1 38 14 pm](https://user-images.githubusercontent.com/24251447/46496674-4212de00-c7de-11e8-96dd-264c887ccef2.png)
-----
![screen shot 2018-10-04 at 1 37 49 pm](https://user-images.githubusercontent.com/24251447/46496675-4212de00-c7de-11e8-95c5-577c6a6874c5.png)
-----
![screen shot 2018-10-04 at 1 37 38 pm](https://user-images.githubusercontent.com/24251447/46496677-4212de00-c7de-11e8-9d37-c7c65d5a8007.png)
-----
![screen shot 2018-10-04 at 1 37 32 pm](https://user-images.githubusercontent.com/24251447/46496679-42ab7480-c7de-11e8-96db-8a08ded73f9e.png)
-----
![screen shot 2018-10-04 at 1 37 24 pm](https://user-images.githubusercontent.com/24251447/46496682-42ab7480-c7de-11e8-9571-5bbc1e6dad9d.png)
-----
![screen shot 2018-10-04 at 1 37 17 pm](https://user-images.githubusercontent.com/24251447/46496684-42ab7480-c7de-11e8-9a42-7a3882046149.png)
-----
![screen shot 2018-10-04 at 1 36 48 pm](https://user-images.githubusercontent.com/24251447/46496686-42ab7480-c7de-11e8-8d28-8aa1f7519aff.png)
-----
![screen shot 2018-10-04 at 12 37 35 pm](https://user-images.githubusercontent.com/24251447/46496687-42ab7480-c7de-11e8-9f1b-b528b38236a9.png)
-----
![screen shot 2018-10-04 at 12 37 24 pm](https://user-images.githubusercontent.com/24251447/46496688-42ab7480-c7de-11e8-8283-9616920b380e.png)

## Acceptance criteria
- [x] Content matches latest copy

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-10-05 19:31 UTC, peggygannon requested changes
@markgreenburg Hi, Mark. Thanks for making these changes. I didn't see screenshots for the below updates.. Are you able to post these screenshots? 

**disability-benefits/apply/form-526-disability-claim/introduction**
- [ ] In sign-in blue box (at top and bottom of page), please change "To apply for a disability increase, you’ll need to sign in and verify your account." TO:

To apply for a disability increase, you'll need to sign in and verify your identity."

- [ ] Please update ITF message under top blue button to TO:

Note: By clicking the button to start the disability application, you’ll declare your intent to file. This will reserve a potential effective date for when you could start getting benefits. 


- [ ] Please delete the extra "Learn" in this link: 
[Learn what additional forms you may need to file with your disability claim].

**form-526-disability-claim/supporting-evidence/0/private-medical-records-choice/** 
- [ ] Under "Which should I choose?" please remove this:
"If you tell us which VA medical center treated you for your condition, we can get your medical records for you."
Replace it with this sentence
If you tell us the name of the private doctor or hospital that treated you for your condition, we can get your medical records for you.

2018-10-08 15:43 UTC, markgreenburg commented
Hey @peggygannon - please see screenshots below

![screen shot 2018-10-08 at 10 41 23 am](https://user-images.githubusercontent.com/24251447/46619070-c7500880-cae6-11e8-89cb-99ff0ab06368.png)

-----

![screen shot 2018-10-08 at 10 38 30 am](https://user-images.githubusercontent.com/24251447/46619130-f0709900-cae6-11e8-99da-741022518852.png)

-----

![screen shot 2018-10-08 at 10 34 21 am](https://user-images.githubusercontent.com/24251447/46619072-c7500880-cae6-11e8-855a-dbbbb1fd077a.png)

2018-10-08 18:14 UTC, cvalarida approved these changes
Once Peggy gives the go-ahead, it's good. :+1:

2018-10-08 19:09 UTC, peggygannon approved these changes

2018-10-08 19:34 UTC, merged