Update homelessness PoC content
department-of-veterans-affairs/vets-website pull request #8962
Opened 2018-11-01 00:05 UTC by cvalarida

## Description
Changed the content for the homelessness PoC.

## Testing done
Manually tested.

## Screenshots
![image](https://user-images.githubusercontent.com/12970166/47825405-fdbc2480-dd2e-11e8-8694-0a3c594c7b5f.png)
**Note:** This screenshot doesn't contain the requirement update from https://github.com/department-of-veterans-affairs/vets-website/pull/8961.

## Acceptance criteria
- [x] The content is updated

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-11-01 18:00 UTC, markgreenburg reviewed
I think the `name` and `phone number` fields also need their names changed per Peggy's content in the ticket

2018-11-01 18:01 UTC, peggygannon requested changes
@cvalarida The screenshot doesn't show the updated content for this screen, per https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/14627

This is the updated content:

Please provide the name of a person or place we can call if we need to get in touch with you.
Name {text box}
Phone number {text box}

2018-11-01 18:55 UTC, cvalarida commented
:man_facepalming: Missed that the name field rename.

Updated screenshot:
![image](https://user-images.githubusercontent.com/12970166/47872808-cc923180-ddcc-11e8-92cb-341646b9313f.png)

How's that look, @peggygannon?

2018-11-01 20:24 UTC, markgreenburg approved these changes
🚀

2018-11-07 20:47 UTC, peggygannon approved these changes

2018-11-12 17:14 UTC, merged