[WIP] Ep add connected acct
department-of-veterans-affairs/vets-website pull request #8973
Opened 2018-11-01 18:56 UTC by edpaget

Adding in actions and refactoring into components, to the connected accounts PR. Separating it out so changes are easier to see.

2018-11-02 22:12 UTC, juliasolorzano requested changes
Looks good. Added a few small comments.

Also, the current route is set to `/connected-accounts/` instead of `/account/connected-accounts/`. I am wondering if it's possible to remove the routing from vagov-content completely at that is how we get this work properly 🤔 I've seen this done a few ways in apps around this repo. Open to ideas here!

2018-11-02 22:12 UTC, juliaelman commented on src/applications/personalization/connected-accounts/components/NoConnectedApps.jsx
> +    title = <h3>Something went wrong loading your connected Accounts.</h3>;
Change to "Sorry — we can’t seem to find any connected accounts."

2018-11-02 22:12 UTC, juliaelman commented on src/applications/personalization/connected-accounts/containers/ConnectedAcctApp.jsx
> +        <LoadingIndicator message="Loading your account information..." />
s account information/connected accounts

2018-11-05 19:17 UTC, edpaget commented
This this just all be set now.

2018-11-05 20:48 UTC, juliasolorzano approved these changes
🚀

2018-11-05 20:49 UTC, merged