Remove a sentence from the disability wizard
department-of-veterans-affairs/vets-website pull request #9036
Opened 2018-11-06 00:32 UTC by cvalarida

## Description
Changes the content in the disability compensation wizard per the connected ticket.

## Testing done
Manually tested.

## Screenshots
![image](https://user-images.githubusercontent.com/12970166/48035284-3174c100-e118-11e8-8b4b-db052b2e4fe6.png)

## Acceptance criteria
- [x] The sentence in question is removed

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-11-06 16:19 UTC, markgreenburg approved these changes
lgtm

2018-11-06 16:47 UTC, cvalarida commented
@peggygannon Can you take a quick look at this one? I meant to add you as a reviewer when I made the PR. :man_facepalming:

2018-11-06 17:23 UTC, peggygannon requested changes
@cvalarida per the issue for this, the sentence should now read. Can we make that update?

To file your first disability claim, please go to our eBenefits website.

2018-11-06 21:28 UTC, cvalarida commented
Updated button text:
![image](https://user-images.githubusercontent.com/12970166/48094772-e3b79180-e1c7-11e8-9faf-53996bd3ccd1.png)

2018-11-06 21:31 UTC, cvalarida commented
Updated content:
![image](https://user-images.githubusercontent.com/12970166/48094897-3002d180-e1c8-11e8-87ea-cbb76cca3e8e.png)

2018-11-06 21:37 UTC, markgreenburg commented on src/applications/disability-benefits/526EZ/components/ButtonContainer.jsx
> +        !isLoggedIn && (
Oh that's nice

2018-11-07 17:52 UTC, peggygannon approved these changes

2018-11-09 20:39 UTC, merged