turn on online only and distance learning
department-of-veterans-affairs/vets-website pull request #9090
Opened 2018-11-09 16:40 UTC by rianfowler

## Description

## Testing done
verified locally 

## Screenshots
![screen shot 2018-11-09 at 09 35 44](https://user-images.githubusercontent.com/4998130/48275750-86a81f80-e403-11e8-962f-acac86675be9.png)

## Acceptance criteria
- [ ]

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-11-09 16:41 UTC, rianfowler commented on src/applications/gi/components/profile/Programs.jsx
> +      onlineOnly: {
these properties are tied to the api response. e.g. onlineOnly maps to online_only

2018-11-09 17:06 UTC, rianfowler commented
delaying until we have content for the modal

2018-11-09 19:20 UTC, erikphansen approved these changes

2018-11-16 17:05 UTC, rianfowler commented
@peggygannon I added some screenshots @peggygannon

2018-11-16 17:45 UTC, cehsu approved these changes

2018-11-16 18:00 UTC, peggygannon requested changes
@rianfowler Hi, Rian, seeing this laid out in a modal, I think we should delete these two lines below.  I think we want to focus on the housing allowance in the modal copy. 

Please delete: 
"With online learning, students have access to a teacher and student resources, such as recorded lessons or online forums. With distance learning, the student and teacher are in separate locations and there is little interaction with fellow students."

2018-11-16 20:14 UTC, rianfowler commented
@peggygannon I've updated the copy and screen shots in the description.

2018-11-16 20:31 UTC, peggygannon commented
@rianfowler Hi.. Can I see the updated screenshot, so i can check/sign off? Thanks!

2018-11-16 20:32 UTC, rianfowler commented
@peggygannon 
![screen shot 2018-11-16 at 13 12 35](https://user-images.githubusercontent.com/4998130/48645816-fa1dd400-e9a3-11e8-8ad3-3c8c8974831a.png)

![screen shot 2018-11-16 at 13 10 59](https://user-images.githubusercontent.com/4998130/48645817-fa1dd400-e9a3-11e8-9c7b-dc20d0a77e51.png)

2018-11-16 20:34 UTC, peggygannon approved these changes

2018-11-16 20:47 UTC, merged