All claims retirement content mg
department-of-veterans-affairs/vets-website pull request #9103
Opened 2018-11-13 19:39 UTC by markgreenburg

## Description
- Updates military retired pay question / answer content
- Updates 'waive retirement pay' description / question / answer content

## Testing done
- Tested locally

## Screenshots
Military retired pay questionnaire:
<img width="614" alt="screen shot 2018-11-13 at 12 46 51 pm" src="https://user-images.githubusercontent.com/24251447/48437805-f68e1100-e747-11e8-9ab4-7cc42bce93a2.png">

-----
Waive Retirement Pay page:
<img width="614" alt="screen shot 2018-11-13 at 12 53 24 pm" src="https://user-images.githubusercontent.com/24251447/48438361-72d52400-e749-11e8-8174-24c7d056b0a6.png">

## Acceptance criteria
- [x] Content updated per latest copy in ticket

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-11-14 23:19 UTC, peggygannon requested changes
thanks, @markgreenburg Please see below for some additional tweaks: 

for table, can we swap the order of columns and fix the headers to have them match the guidance in the copy (see below)? 
Also, I think we're missing the strike-through in the table. 

 | Retirement            | Compensation           | Take home   |
| :-------------------- | :--------------------- | :---------- |
| $700/mo (minus taxes) | ~~$700/mo~~            | $630/mo     |
| **~~$700/mo~~**       | **$700/mo (tax-free)** | **$700/mo** |

2.  The footnote below the table should be styled as italics, no bold. 

cc @goldenmeanie for his fyi on the retirement table

2018-11-15 19:36 UTC, goldenmeanie commented
Agree about the strikethrough, but I looking at it this way, I think the comp column first makes it read a little better. It puts the minus taxes right next to the lowered amount. I think this will be more clear.

2018-11-16 01:40 UTC, cvalarida approved these changes
When it's good by @peggygannon and @goldenmeanie, it's good by me. :+1:

2018-11-16 01:40 UTC, cvalarida commented on src/applications/disability-benefits/all-claims/content/waiveRetirementPay.jsx
> +          <td>$700/month</td>
Looks like a case for the [`<del>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/del)!

2018-11-19 16:58 UTC, markgreenburg commented
@peggygannon @goldenmeanie thanks for the review, I was a little unsure of some of the specifics. How's this? Do the header names need to change?

<img width="492" alt="screen shot 2018-11-19 at 10 58 25 am" src="https://user-images.githubusercontent.com/24251447/48722627-1612b700-ebea-11e8-8c1a-4cf237a4b073.png">

2018-11-19 17:17 UTC, goldenmeanie commented
Is it practical to force the parenthetical to the second line? I vote for this column order.

I am wondering if the strikethrough is legible enough? Is there a practical way to do something like this?
![screen shot 2018-11-19 at 12 16 21 pm](https://user-images.githubusercontent.com/1969/48723576-faf97480-ebf4-11e8-9f49-90dab1cb45bb.png)

2018-11-19 18:40 UTC, peggygannon commented
@markgreenburg @goldenmeanie Hi, there. 

per, my latest edit, can we make the columns headers the below? 
 | Compensation           | Retirement          | Take home  pay |

2018-11-19 18:48 UTC, markgreenburg commented
@goldenmeanie would it help to add row headers? E.g., something like:

|               | VA Compensation | Military Retired Pay |
|---------------|-----------------|----------------------|
| Compensation  | $700/month      | $700/month           |
| Taxes         | $0/month        | $70/month            |
| **Take Home Pay** | **$700/month**      | **$630/month**           |

2018-11-19 18:55 UTC, markgreenburg commented
@peggygannon updated the headers:
<img width="596" alt="screen shot 2018-11-19 at 12 53 09 pm" src="https://user-images.githubusercontent.com/24251447/48728283-292d8300-ebfa-11e8-8416-e1094cc4cb62.png">

2018-11-26 16:54 UTC, peggygannon approved these changes

2018-11-26 18:01 UTC, merged