Additional remarks - Mental health changes 781a
department-of-veterans-affairs/vets-website pull request #9128
Opened 2018-11-15 22:30 UTC by imeecuison

## Description
Option to enter additional remarks in behavior - particularly mental health.
These questions are asked after Additional Event screen and physical health additional remarks.
```bah-781a-additionalRemarks-mental```
http://localhost:3001/disability-benefits/apply/form-526-all-claims/new-disabilities/ptsd-781a-mental-changes

## Testing done
tests/pages/mentalHealthChanges.unit.spec.jsx

## Screenshots
<img width="629" alt="screen shot 2018-11-15 at 5 12 21 pm" src="https://user-images.githubusercontent.com/41440372/48585131-b3739f80-e8f9-11e8-8bf7-6b50a3d99995.png">
<img width="629" alt="screen shot 2018-11-15 at 5 12 09 pm" src="https://user-images.githubusercontent.com/41440372/48585132-b40c3600-e8f9-11e8-919e-3543e2b9fe39.png">

## Acceptance criteria
- [ ] The PTSD type classification is correctly populated on page header based on the user's selection at the beginning of the workflow
- [ ] User is able to indicate changes to mental health/substance abuse as a result of the stressful incident per the Content Document
**Noted: No fields are required.**

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-11-16 15:34 UTC, devin-mccurdy approved these changes
LGTM!

2018-11-16 15:42 UTC, imeecuison commented
@dmccurdybah : isAnsweringPtsdForm is on line 367 in utils. Is it not showing up for you?

2018-11-16 15:44 UTC, imeecuison commented
@department-of-veterans-affairs/code-reviewers-for-external-teams-group Could I get a code review on this at your earliest convenience. Thank you!

2018-11-30 12:08 UTC, imeecuison commented
@rianfowler : When you have a moment, can you give me a second review on this PR. Thank you!

2018-11-30 18:02 UTC, rianfowler requested changes
just a couple of minor issues besides the conflicts

2018-11-30 18:02 UTC, rianfowler commented on src/applications/disability-benefits/all-claims/pages/mentalHealthChanges.js
> +        hypervigillance: {
hypervigilance is misspelled

2018-11-30 18:02 UTC, rianfowler commented on src/applications/disability-benefits/all-claims/utils.jsx
> +  _.get('view:uploadPtsdChoice', formData, '') === 'answerQuestions';
Not familiar enough with this form to comment on this but please respond to this.

2018-12-02 10:03 UTC, imeecuison commented
@rianfowler : I've made changes. Please review again. Thank you!

2018-12-03 15:20 UTC, rianfowler approved these changes

2018-12-03 15:24 UTC, jbalboni approved these changes

2018-12-03 15:26 UTC, merged