Additional remarks 781 form
department-of-veterans-affairs/vets-website pull request #9158
Opened 2018-11-23 18:33 UTC by imeecuison

## Description
Textarea box for user to input additional remarks.

## Testing done
tests/pages/additionalRemarks781.unit.spec.jsx

## Screenshots
<img width="651" alt="screen shot 2018-11-23 at 1 06 50 pm" src="https://user-images.githubusercontent.com/41440372/48956984-f5b56600-ef23-11e8-9e8a-3c5bb4073be5.png">

## Acceptance criteria
- [ ] User is able to answer “If there is anything else you would like to tell us about the stressful events that contributed to your PTSD, you can provide that information below. If you have any supporting documents or buddy statements to support your claim, you’ll have a chance to upload those later in the application.”
- [ ] User is able to continue to the next step in the process
**Note: Field is not required.**

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-11-26 15:20 UTC, aaronjlech reviewed
This looks good, just the 1 minor comment on the depends function. Will there be an additional remarks for 781a? If so we can probably make this 1 branch?

2018-11-26 17:16 UTC, imeecuison commented on src/applications/disability-benefits/all-claims/config/form.js
> +            needsToEnter781(formData) && isAnsweringPtsdForm(formData),
Removed 'needsToEnter781'. For 781a: the additional remarks equivalent has already been done: additional remarks - physical, emotional, work, etc. Thanks!

2018-12-03 16:45 UTC, imeecuison commented
@aaronjlech : Can you check this one again? Thank you!

2018-12-04 16:40 UTC, aaronjlech requested changes
Just a few small tweaks.

2018-12-04 16:40 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/config/781/index.js
> -        title: `${numberToWords[index]} PTSD assault incident date`,
Can we put this title back on the one that is in the file?

2018-12-04 16:40 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/config/781/index.js
> -        title: `${numberToWords[index]} PTSD incident date`,
Same with this one, put this title on the incidentDate page that is in the file.

2018-12-04 16:40 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/config/form.js
> +export default createFormConfig;
change this back to `formConfig`.

2018-12-04 16:40 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/config/form.js
> +const createFormConfig = {
change this back to `formConfig`

2018-12-04 16:40 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/pages/additionalRemarks781.js
> +import { PtsdNameTitle } from '../content/ptsdClassification';
use the new helper content `ptsd781NameTitle`

2018-12-04 16:40 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/pages/additionalRemarks781.js
> +  'ui:title': ({ formData }) => (
If you use `ptsd781NameTitle` you can just do 
```'ui:title': pstd781NameTitle,```

2018-12-04 16:40 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/pages/additionalRemarks781.js
> +import React from 'react';
Can we make this file extension a `.jsx` since it's using react.

2018-12-04 16:41 UTC, aaronjlech requested changes

2018-12-04 16:41 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/tests/config/schema.js
> +// This file to be moved to vets-json-schema repo before form hits production
Is there a reason this file is in `src/applications/disability-benefits/all-claims/tests/config/schema.js`

2018-12-05 15:52 UTC, zurbergram commented
Closing this PR.  New PR for https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/9158 is https://github.com/department-of-veterans-affairs/vets-website/pull/9206

2018-12-05 15:52 UTC, closed without merging