526 Supporting Evidence Content Updates
department-of-veterans-affairs/vets-website pull request #9161
Opened 2018-11-26 21:50 UTC by markgreenburg

## Description
- Updates content for several supporting evidence screens
- Updates content for all file uploaders in the All Claims flow

## Testing done
- Tested locally

## Screenshots
![screen shot 2018-11-26 at 3 49 18 pm](https://user-images.githubusercontent.com/24251447/49044318-fef83a00-f192-11e8-9f1b-21e61690800d.png)

![screen shot 2018-11-26 at 3 49 46 pm](https://user-images.githubusercontent.com/24251447/49044323-04558480-f193-11e8-901b-35ae7005b2e2.png)

## Acceptance criteria
- [x] Content updates per attached ticket

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-11-26 22:06 UTC, peggygannon requested changes
@markgreenburg Hi, Mark, please see my content tweaks below: 

Under private medical records upload:
I think we should remove this line from the body text, as it's now part of the footnote. 
"Please note that large files can take longer to upload with a slow Internet connection."

2018-11-28 16:53 UTC, markgreenburg commented
Thanks @peggygannon; here's a new screenshot:

![screen shot 2018-11-28 at 10 51 56 am](https://user-images.githubusercontent.com/24251447/49167821-d50e5700-f2fb-11e8-9075-37145d416040.png)

2018-11-28 17:11 UTC, peggygannon approved these changes

2018-11-28 19:20 UTC, cvalarida approved these changes

2018-11-28 19:20 UTC, cvalarida commented on src/applications/disability-benefits/all-claims/content/fileUploadDescriptions.jsx
> +      You can upload your document in a pdf, .jpeg, or .png file format. You’ll
`.pdf` or `PDF`?

2018-11-29 17:48 UTC, merged