4142 e2e all claims
department-of-veterans-affairs/vets-website pull request #9177
Opened 2018-11-29 18:49 UTC by zurbergram

## Description

As a MVP development team, I need to write e2e tests so that we have full test coverage.
End to end testing documentation is located in GitHub.

Zenhub issue is [Form 4142/4142a: Write e2e tests for all functionality in the launched product#14892](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/14892)

## Testing done
- [x] local testing
- [x] unit tests

## Screenshots

## Acceptance criteria
- [x] Automated e2e tests exist for all functionality in for 4142 & 4142a
- [x] All automated 4142 and 4142a e2e tests run successfully

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-11-29 19:54 UTC, zurbergram commented on src/applications/disability-benefits/all-claims/utils.jsx
> +    if (clonedData.newDisabilities) {
Adding an undefined check since `clonedData.newDisabilities` is not always set in the `transform` function

2018-12-05 17:42 UTC, zurbergram commented on src/applications/disability-benefits/all-claims/tests/00-all-fields.e2e.spec.js
> +  // ****
All tests below are commented out as the flow of all-claims is currently in flux. They worked for the page/form they are for before the flow before them was changed.

2018-12-05 17:45 UTC, zurbergram commented
This is for PR https://github.com/department-of-veterans-affairs/vets-website/pull/9177

2018-12-06 21:13 UTC, devin-mccurdy requested changes

2018-12-06 21:13 UTC, dmccurdybah commented on package.json
> +    "test:unit:db": "BABEL_ENV=test mocha --opts src/platform/testing/unit/mocha.opts --recursive 'src/applications/disability-benefits/**/tests/*.unit.spec.js?(x)' ",
I know these links aren't working but I don't think they're going to be used.

2018-12-06 21:13 UTC, dmccurdybah commented on src/applications/disability-benefits/all-claims/tests/schema/maximal-test.json
> +    "view:hasMilitaryRetiredPay": false,
I think we need to leave these as true so that the test of the form data transform will transform the data for these pages.

2018-12-07 16:19 UTC, zurbergram commented
@department-of-veterans-affairs/code-reviewers-for-external-teams-group - Could I get a code review on this at your earliest convenience? Thanks!

2018-12-07 16:21 UTC, devin-mccurdy approved these changes

2018-12-17 19:27 UTC, cvalarida approved these changes
This looks fine for now. I'm guessing it'll need some work when we go to enable it, but it looks like this has the bulk of the work for now.

I'm dreaming up some grand scheme whereby we can pass test data files into an e2e test generator so we don't have to manually write out a new test for each form flow. We've got plenty of other work ahead of that, though. :stuck_out_tongue:

2018-12-17 20:38 UTC, merged