Form 21-8940: Ability to populate Impact on recent job applications questions
department-of-veterans-affairs/vets-website pull request #9199
Opened 2018-12-04 19:52 UTC by zurbergram

## Description

As a Veteran submitting a claim for Individual Unemployability on the Vets.gov platform, I need the ability to populate the recent job applications, so that I can provide additional evidence associated to my Individual Unemployability while completing the Form 21-8940 application interview.

## Testing done
- [x] manually tested
- [x] Unit tests

## Screenshots
![screen shot 2018-12-04 at 2 50 51 pm](https://user-images.githubusercontent.com/1094999/49468875-0a231980-f7d4-11e8-80b2-6dd0abfaddb9.png)
![screen shot 2018-12-04 at 2 51 02 pm](https://user-images.githubusercontent.com/1094999/49468878-0b544680-f7d4-11e8-9e06-529b9498dbe6.png)

## Acceptance criteria
- [x] The user is able to populate the following: 
- [x] Have you tried to find a steady job since you became too disabled to work? { radio }
Yes
No
- [x] { If yes }
- [x] Employer’s name { text field }
- [x] Address {address pattern}
- [x] Type of work { text field }
- [x] Date you applied { date picker }
- [x] The user is able to select the help text
- [x] The user is able to add another
- [x] The user is able to move to the next step in the process, Story#14539: Form 21-8940: Ability to populate Past Education and Training questions
- [x] Field validations (if applicable per the linked document for Validations above) are enforced in the UI
- [x] Error messages (if applicable per the linked document for Validations above) are displayed in the UI

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-12-04 20:54 UTC, aaronjlech requested changes
Looks good for the most part. Just 2 little semantic/organization things.

2018-12-04 20:54 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/pages/recentJobApplications.js
> +  substantiallyGainfulEmploymentInfo: {
can we change this to `'view: substantiallyGainfulEmploymentInfo'`. Or something with `view:` in it. We use that to symbolize UI related data fields/content fields(things not in the form Schema).

2018-12-04 20:54 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/pages/recentJobApplications.js
> +import { validateZIP } from '../validations';
Should we move all of the imports above the `const` ? That way they are all relatively in the same location?

2018-12-04 21:09 UTC, aaronjlech approved these changes
Looks good!

2018-12-04 21:18 UTC, zurbergram commented
@department-of-veterans-affairs/code-reviewers-for-external-teams-group - Could I get a code review on this at your earliest convenience? Thanks!

2018-12-07 16:11 UTC, rianfowler approved these changes
LGTM

2018-12-28 18:12 UTC, merged