Form 21-8940: Ability to populate Impact on military duty interview questions#14537
department-of-veterans-affairs/vets-website pull request #9222
Opened 2018-12-07 20:33 UTC by zurbergram

## Description

Form 21-8940: Ability to populate Impact on military duty interview questions

As a Veteran submitting a claim for Individual Unemployability on the Vets.gov platform, I need the ability to populate the military duty interview, so that I can provide additional evidence associated to my Individual Unemployability while completing the Form 21-8940 application interview.

## Testing done
- [x] local testing
- [x] e2e tests

## Screenshots
![screen shot 2018-12-07 at 3 32 04 pm](https://user-images.githubusercontent.com/1094999/49671276-51f4ab80-fa35-11e8-87c9-3c8fd5ef178d.png)
![screen shot 2018-12-07 at 3 32 16 pm](https://user-images.githubusercontent.com/1094999/49671288-5caf4080-fa35-11e8-9358-364278a9b549.png)

## Acceptance criteria
- [x] The user is able to populate the following: 
- [x] If you’re currently serving in the Reserves or the National Guard, does your service-connected disability prevent you from performing your military duties? { radio }
Yes
No
I’m not serving in the Reserves or the National Guard.
- [x] The user is able to move to the next step in the process, Story#14538: Form 21-8940: Ability to populate Impact on recent job applications questions
- [x] Field validations (if applicable per the linked document for Validations above) are enforced in the UI
- [x] Error messages (if applicable per the linked document for Validations above) are displayed in the UI

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-12-12 20:15 UTC, aaronjlech requested changes
Looks good, just a few suggestions/new linter changes

2018-12-12 20:15 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/pages/militaryDutyImpact.js
> +          alsoNo: 'I’m not serving in the Reserves or the National Guard.',
😂 Maybe we can put something like `reservesNo` ?

2018-12-12 20:15 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/tests/pages/militaryDutyImpact.unit.spec.jsx
> +    const form = mount(
going to need to update the tests to add `form.unmount()` at the very end due to new linter issues.

2018-12-12 20:15 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/tests/pages/militaryDutyImpact.unit.spec.jsx
> +    const form = mount(
this test too `form.unmount()`

2018-12-12 20:15 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/tests/pages/militaryDutyImpact.unit.spec.jsx
> +    const form = mount(
this test too `form.unmount()`

2018-12-27 18:54 UTC, aaronjlech approved these changes
lgtm

2018-12-28 18:49 UTC, zurbergram commented
@department-of-veterans-affairs/code-reviewers-for-external-teams-group - Could I get a code review on this at your earliest convenience? Thanks!

2018-12-28 19:09 UTC, rianfowler approved these changes

2018-12-28 19:11 UTC, rianfowler commented
Failing unit test: 
```
Error: Method “simulate” is only meant to be run on a single node. 0 found instead.
at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1532:17)
at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:867:14)
at selectRadio (src/platform/testing/unit/schemaform-utils.jsx:308:6)
at Context.<anonymous> (src/applications/disability-benefits/all-claims/tests/pages/militaryDutyImpact.unit.spec.jsx:41:5)
```

2018-12-31 14:06 UTC, merged