Bah 8940 supplemental benefits
department-of-veterans-affairs/vets-website pull request #9228
Opened 2018-12-10 15:32 UTC by imeecuison

## Description
Supplemental benefits form

## Testing done
tests/pages/supplementalBenefits.unit.spec.jsx

## Screenshots
![screen shot 2018-12-10 at 9 44 19 am](https://user-images.githubusercontent.com/41440372/49742445-9024e180-fc66-11e8-926d-e6be34755502.png)

## Acceptance criteria
- [ ] The user is able to populate the following:
Are you receiving, or do you expect to receive, disability retirement benefits? {radio}

Yes

No
- [ ] Are you receiving, or do you expect to receive, workers’ compensation benefits? {radio}

Yes

No 
- [ ] The user is able to select help text
- [ ] The user is able to move to the next step in the process, Story#14537: Form 21-8940: Ability to populate Impact on military duty interview questions
- [ ] Field validations (if applicable per the linked document for Validations above) are enforced in the UI
- [ ] Error messages (if applicable per the linked document for Validations above) are displayed in the UI
**NOTE: No fields are required as per document.**

## Definition of done
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2018-12-11 16:38 UTC, desireeturner commented
This PR is related to the following issue: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/14536

2018-12-12 20:01 UTC, aaronjlech requested changes
@imeecuison Looks good, just some minor little things!

2018-12-13 15:20 UTC, imeecuison commented on src/applications/disability-benefits/all-claims/pages/supplementalBenefits.js
> +import React from 'react';
changed!

2018-12-13 15:20 UTC, imeecuison commented on src/applications/disability-benefits/all-claims/pages/supplementalBenefits.js
> +    'ui:options': {},
removed

2018-12-13 15:20 UTC, imeecuison commented on src/applications/disability-benefits/all-claims/pages/supplementalBenefits.js
> +    'ui:options': {},
removed

2018-12-13 15:22 UTC, imeecuison commented on src/applications/disability-benefits/all-claims/tests/pages/supplementalBenefits.unit.spec.jsx
> +    expect(form.find('.usa-input-error-message').length).to.equal(0);
changed

2018-12-14 20:26 UTC, aaronjlech approved these changes

2018-12-14 20:35 UTC, imeecuison commented
@department-of-veterans-affairs/code-reviewers-for-external-teams-group Could I get a code review on this at your earliest convenience. Thank you!

2018-12-16 18:09 UTC, rianfowler approved these changes
LGTM

2018-12-17 13:49 UTC, aaronjlech requested changes

2018-12-17 13:49 UTC, aaronjlech commented on src/applications/disability-benefits/all-claims/pages/supplementalBenefits.jsx
> +      'ui:options': {},
This looks like it's still in the file, can we remove this empty `ui:options`?

2018-12-17 14:12 UTC, imeecuison commented on src/applications/disability-benefits/all-claims/pages/supplementalBenefits.js
> +    'ui:options': {},
sorry about that! i thought I did it.

2018-12-17 15:01 UTC, aaronjlech approved these changes

2018-12-17 15:01 UTC, merged