All claims ptsd content update mg
department-of-veterans-affairs/vets-website pull request #9505
Opened 2019-02-01 18:54 UTC by markgreenburg

## Description
Updates all of the PTSD 781 & 781a pages per the linked content ticket

## Testing done
- Tested each page locally
- Unit tests pass

## Screenshots
Woo boy...

PTSD Intro
![screen shot 2019-01-29 at 4 51 04 pm](https://user-images.githubusercontent.com/24251447/52140953-d587de80-2619-11e9-99dc-1dbe43bb1b54.png)

-----

walkthrough-781-choice
![screen shot 2019-01-30 at 2 12 59 pm](https://user-images.githubusercontent.com/24251447/52140986-f6e8ca80-2619-11e9-99c3-082c1ca66eaf.png)

-----

ptsd-intro-to-questions
![screen shot 2019-01-30 at 2 14 47 pm](https://user-images.githubusercontent.com/24251447/52141013-1122a880-261a-11e9-9fdc-f8d9e11dccff.png)

-----

ptsd-incident-date-0
![screen shot 2019-01-30 at 2 20 19 pm](https://user-images.githubusercontent.com/24251447/52141049-2697d280-261a-11e9-8300-6a94219f92fd.png)

-----

ptsd-incident-unit-assignment
![screen shot 2019-01-30 at 2 23 07 pm](https://user-images.githubusercontent.com/24251447/52141078-3d3e2980-261a-11e9-852b-a26bc9ef1923.png)

-----

ptsd-individuals-involved-0
![screen shot 2019-01-30 at 2 28 42 pm](https://user-images.githubusercontent.com/24251447/52141095-4a5b1880-261a-11e9-8a43-806ebb0c0ea5.png)

-----

ptsd-incident-support-0
![screen shot 2019-01-30 at 2 39 12 pm](https://user-images.githubusercontent.com/24251447/52141180-80000180-261a-11e9-8dc3-a4f27ae61efa.png)

-----

ptsd-individuals-involved-questions-0
![screen shot 2019-01-31 at 10 30 14 am](https://user-images.githubusercontent.com/24251447/52141249-c2c1d980-261a-11e9-8455-4129a3d952e6.png)
-----
![screen shot 2019-01-30 at 3 26 35 pm](https://user-images.githubusercontent.com/24251447/52141250-c2c1d980-261a-11e9-8b00-a00cb73087b9.png)
-----
![screen shot 2019-01-30 at 3 26 29 pm](https://user-images.githubusercontent.com/24251447/52141251-c2c1d980-261a-11e9-8256-b18c77dcfdc5.png)
-----
![screen shot 2019-01-30 at 3 26 19 pm](https://user-images.githubusercontent.com/24251447/52141252-c2c1d980-261a-11e9-8e96-ed592fd7d612.png)

-----

ptsd-incident-support-additional-break-0
![screen shot 2019-01-31 at 10 35 44 am](https://user-images.githubusercontent.com/24251447/52141307-e422c580-261a-11e9-9224-7119c532745f.png)

-----

ptsd-incident-description-0
![screen shot 2019-01-31 at 10 50 25 am](https://user-images.githubusercontent.com/24251447/52141335-074d7500-261b-11e9-8364-2b6223404ec3.png)

-----

walkthrough-781a-choice
![screen shot 2019-01-31 at 11 13 20 am](https://user-images.githubusercontent.com/24251447/52141374-221fe980-261b-11e9-89cc-c5352c905e19.png)

-----

ptsd-secondary-incident-date-0
<img width="609" alt="screen shot 2019-02-01 at 10 13 36 am" src="https://user-images.githubusercontent.com/24251447/52141437-5e534a00-261b-11e9-8dda-836fb558aa8c.png">

-----

ptsd-secondary-incident-unit-assignment-0
<img width="677" alt="screen shot 2019-02-01 at 10 13 55 am" src="https://user-images.githubusercontent.com/24251447/52141464-732fdd80-261b-11e9-8813-6fa6d40e9317.png">

-----

ptsd-secondary-incident-support-0
<img width="864" alt="screen shot 2019-02-01 at 10 17 24 am" src="https://user-images.githubusercontent.com/24251447/52141509-90fd4280-261b-11e9-86c3-bbccd1cbbc42.png">

-----

ptsd-secondary-incident-description-0
<img width="876" alt="screen shot 2019-02-01 at 10 19 46 am" src="https://user-images.githubusercontent.com/24251447/52141536-ad00e400-261b-11e9-84aa-d0f50b9bee11.png">

-----

ptsd-secondary-other-sources-0
<img width="861" alt="screen shot 2019-02-01 at 10 27 43 am" src="https://user-images.githubusercontent.com/24251447/52141570-c1dd7780-261b-11e9-9f52-6056778cfc48.png">

-----

ptsd-secondary-other-sources-help-0
<img width="874" alt="screen shot 2019-02-01 at 10 46 56 am" src="https://user-images.githubusercontent.com/24251447/52141604-dcafec00-261b-11e9-8a72-c33492044762.png">

-----

ptsd-secondary-authorities-0
<img width="877" alt="screen shot 2019-02-01 at 11 00 18 am" src="https://user-images.githubusercontent.com/24251447/52141631-ef2a2580-261b-11e9-96d2-01bdceffc685.png">

-----

ptsd-secondary-upload-supporting-sources-choice-0
<img width="967" alt="screen shot 2019-02-01 at 11 03 51 am" src="https://user-images.githubusercontent.com/24251447/52141666-09640380-261c-11e9-8d8b-9478f313b0dc.png">

-----

ptsd-secondary-upload-supporting-sources-0
<img width="932" alt="screen shot 2019-02-01 at 11 24 06 am" src="https://user-images.githubusercontent.com/24251447/52141678-154fc580-261c-11e9-818c-c1adc1f05a6e.png">

-----

new screen: ptsd-781a-changes-intro
<img width="970" alt="screen shot 2019-02-01 at 12 45 17 pm" src="https://user-images.githubusercontent.com/24251447/52142799-539ab400-261f-11e9-8c5c-ef17af1f81cd.png">

-----

ptsd-781a-physical-changes
<img width="835" alt="screen shot 2019-02-01 at 11 28 13 am" src="https://user-images.githubusercontent.com/24251447/52141697-27316880-261c-11e9-87e8-fbc28c9c2ed9.png">

-----

ptsd-781a-mental-changes
<img width="864" alt="screen shot 2019-02-01 at 11 31 38 am" src="https://user-images.githubusercontent.com/24251447/52142950-db80be00-261f-11e9-9f08-b02b42244439.png">

-----

ptsd-781a-work-changes
<img width="885" alt="screen shot 2019-02-01 at 11 42 52 am" src="https://user-images.githubusercontent.com/24251447/52142965-e9ceda00-261f-11e9-93dd-818f4eb1a993.png">

-----

ptsd-781a-social-changes
<img width="828" alt="screen shot 2019-02-01 at 11 43 02 am" src="https://user-images.githubusercontent.com/24251447/52142982-f6533280-261f-11e9-9acf-22b2fe82604f.png">

-----

ptsd-781a-additional-changes
<img width="848" alt="screen shot 2019-02-01 at 11 43 08 am" src="https://user-images.githubusercontent.com/24251447/52142998-03702180-2620-11e9-92e2-2311103b94f1.png">

## Acceptance criteria
- [x] Content updated per ticket
- [x] Tests pass

## Definition of done
- [x] Events are logged appropriately
- [x] Documentation has been updated, if applicable
- [x] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)
- [x] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

2019-02-01 19:28 UTC, bshyong approved these changes

2019-02-04 20:28 UTC, peggygannon requested changes
@markgreenburg here's my feedback on the PTSD questions. Please let me know if you have any questions or if anything is unclear! thx. 

ptsd-incident-date-0
--remove "or situation" from first sentence. 
Sentence should read: Please tell us when this event happened.

ptsd-incident-unit-assignment
--can we unbold this parenthetical content?  (If you don’t know the exact date you can give us an estimate.)

ptsd-individuals-involved-0
Please update question to: 
"Was anyone else injured or killed during this event?"

ptsd-incident-description-0
Update paragraph to this:
Please tell us what happened during the event. You don‘t have to repeat any information that you‘ve already shared in this form. You only need to provide the level of detail that you‘re comfortable sharing.

walkthrough-781a-choice
it looks like we lost sexual trauma in the header and text Please reinstate header to: 
--Header: PTSD: Personal assault & sexual trauma  
--lowercase personal sexual in text it should read: 
Now we're going to ask you questions about your personal assault and sexual trauma-related PTSD.

please add period after this sentence:
--I want to continue online and answer questions about my PTSD.

please update radio button TO: 
--I’ve already filled out VA Form 21-0781a and want to upload it.

ptsd-secondary-incident-date-0
--Header should read: PTSD: Personal assault & sexual trauma  

ptsd-secondary-incident-unit-assignment-0
--header should be: PTSD: Personal assault & sexual trauma 
--can we unbold this parenthetical content?  (If you don’t know the exact date you can give us an estimate.)

ptsd-secondary-incident-description-0
Please update intro sentence to: 
Please tell us what happened during the event. You don‘t have to repeat any information that you‘ve already shared in this form. You only need to provide the level of detail that you‘re comfortable sharing.

ptsd-781a-additional-changes
Delete "Enter other behavior changes" above text box.

2019-02-05 18:20 UTC, markgreenburg commented
@peggygannon Sorry, I think I might've included some old screenshots, most of the changes you referenced were already up to date. In any case, here's a new round:

ptsd-incident-date-0
--remove "or situation" from first sentence.
Sentence should read: Please tell us when this event happened.
![screen shot 2019-02-05 at 10 42 58 am](https://user-images.githubusercontent.com/24251447/52294455-04b28e80-293f-11e9-83af-2a270cff0d03.png)


ptsd-incident-unit-assignment
--can we unbold this parenthetical content? (If you don’t know the exact date you can give us an estimate.)
![screen shot 2019-02-05 at 10 50 07 am](https://user-images.githubusercontent.com/24251447/52294464-0ed48d00-293f-11e9-848b-fbe3aa2760b7.png)


ptsd-individuals-involved-0
Please update question to:
"Was anyone else injured or killed during this event?"
![screen shot 2019-02-05 at 11 01 44 am](https://user-images.githubusercontent.com/24251447/52294476-15630480-293f-11e9-80fe-7e174a671c96.png)


ptsd-incident-description-0
Update paragraph to this:
Please tell us what happened during the event. You don‘t have to repeat any information that you‘ve already shared in this form. You only need to provide the level of detail that you‘re comfortable sharing.
![screen shot 2019-02-05 at 11 12 24 am](https://user-images.githubusercontent.com/24251447/52294493-201d9980-293f-11e9-8903-dbac8b6d3b8b.png)


walkthrough-781a-choice
it looks like we lost sexual trauma in the header and text Please reinstate header to:
--Header: PTSD: Personal assault & sexual trauma
--lowercase personal sexual in text it should read:
Now we're going to ask you questions about your personal assault and sexual trauma-related PTSD.

*NB: what shows up in the header on this and other pages is determined by which exact options are selected for ptsd type. Possible combinations are:*
Personal assault
Sexual trauma
Personal assault & sexual trauma
Combat
Non-combat
Combat & non-combat

These should all be capitalized as above in the headers, and sentence-cased in the actual content (so lowercased in most cases).

please add period after this sentence:
--I want to continue online and answer questions about my PTSD.

please update radio button TO:
--I’ve already filled out VA Form 21-0781a and want to upload it.

![screen shot 2019-02-05 at 11 22 11 am](https://user-images.githubusercontent.com/24251447/52294729-a508b300-293f-11e9-8f8d-d37590bd872e.png)

ptsd-secondary-incident-date-0
--Header should read: PTSD: Personal assault & sexual trauma
![screen shot 2019-02-05 at 12 16 53 pm](https://user-images.githubusercontent.com/24251447/52294846-f5801080-293f-11e9-9b76-a68532d7ada5.png)


ptsd-secondary-incident-unit-assignment-0
--header should be: PTSD: Personal assault & sexual trauma
--can we unbold this parenthetical content? (If you don’t know the exact date you can give us an estimate.)
![screen shot 2019-02-05 at 11 23 15 am](https://user-images.githubusercontent.com/24251447/52294862-fe70e200-293f-11e9-8933-04462de7214f.png)


ptsd-secondary-incident-description-0
Please update intro sentence to:
Please tell us what happened during the event. You don‘t have to repeat any information that you‘ve already shared in this form. You only need to provide the level of detail that you‘re comfortable sharing.
![screen shot 2019-02-05 at 11 12 24 am](https://user-images.githubusercontent.com/24251447/52294439-f95f6300-293e-11e9-8b65-871783ddde8e.png)


ptsd-781a-additional-changes
Delete "Enter other behavior changes" above text box.
![screen shot 2019-02-05 at 11 58 46 am](https://user-images.githubusercontent.com/24251447/52294905-13e60c00-2940-11e9-9a67-7c84dc991cf6.png)

2019-02-06 00:36 UTC, peggygannon approved these changes

2019-02-06 00:37 UTC, peggygannon commented
@markgreenburg Screenshots look good. thank you for explaining about the headers and how they appear depending on what the user selects!

2019-02-07 17:44 UTC, merged