VET TEC: Veteran Name, DOB, SSN not displaying for some users#16799
department-of-veterans-affairs/vets-website pull request #9540
Opened 2019-02-06 21:07 UTC by zurbergram

**Specs:**
- User account: Users 15, 150

**Steps to Reproduce**
url: https://staging.va.gov/education/apply-for-education-benefits/application/0994/applicant/information
user: 15, 150

**What happened:**
1. Veteran name, DOB, SSN are not displayed as expected on the first screen of the application for this user. 
![Screen Shot 2019-02-06 at 2.44.30 PM.png](https://images.zenhubusercontent.com/5b645f6fe2255460d8f0b032/c2fcd336-887b-4e1f-9dfe-e4d58a273f80)

**Desired behavior:**
Veteran name, DOB, SSN should be displayed as they are below: 
![Screen Shot 2019-02-06 at 2.48.19 PM.png](https://images.zenhubusercontent.com/5b645f6fe2255460d8f0b032/7377f050-3ab1-41f7-bb12-a044b64fb3e4)

2019-02-06 21:11 UTC, devin-mccurdy approved these changes

2019-02-07 14:19 UTC, robfelder requested changes
Maybe I'm missing something, but none of these changes seem to change the fact that the Vet name, DOB & SSN are not displaying.

2019-02-07 15:17 UTC, robfelder approved these changes

2019-02-07 15:20 UTC, zurbergram commented
@department-of-veterans-affairs/frontend-review-group Could I get a code review on this at your earliest convenience. Thank you!

2019-02-07 17:08 UTC, rianfowler approved these changes

2019-02-07 17:29 UTC, merged